### ISSUE TITLE
"There is no enougth sending queue can be used"

### ISSUE THREAD

**Issue by sakopov** [kerryjiang/SuperSocket#100]
Hi,

We're running SuperSocket 1.6.4 and recently started receiving "There is no enougth sending queue can be used". This seems to be happening after running the service several days which is about 200/300 connections from 1 client. The server is running inside SuperSocket.SocketService.exe as a window service.

Here is our supersocket config section.
```
  <superSocket isolation="AppDomain" disablePerformanceDataCollector="true">
    <servers>
      <server name="MyServer" serverTypeName="MyServer" maxConnectionNumber="1000">
        <listeners>
          <add ip="Any" port="19000" />
        </listeners>
      </server>
    </servers>
    <serverTypes>
      <add name="MyServer" type="MyProject.MyServer, MyProject" />
    </serverTypes>
    <logFactories>
      <add name="ConsoleLogFactory" type="SuperSocket.SocketBase.Logging.ConsoleLogFactory, SuperSocket.SocketBase" />
    </logFactories>
  </superSocket>
```

One of the recent changes we'd done was configuring Dependency Injection in SuperSocket. I don't know if this is relevant at all, but I thought i'd point it out.

I had to implement a command loader that works with our DI container.

```
    public class SimpleInjectorCommandLoader<TCommand> : CommandLoaderBase<TCommand> where TCommand : class, ICommand
    {
        private readonly Container _container;

        public SimpleInjectorCommandLoader(Container container)
        {
            _container = container;
        }

        public override bool Initialize(IRootConfig rootConfig, IAppServer appServer)
        {
            return true;
        }

        public override bool TryLoadCommands(out IEnumerable<TCommand> commands)
        {
            commands = (IEnumerable<TCommand>) _container.GetAllInstances<CommandBase<MyProtocolSession, BinaryRequestInfo>>();

            return true;
        }
    }
```

And then modified our server to configure dependencies

```
    public sealed class MyServer : AppServer<MyProtocolSession, BinaryRequestInfo>
    {
        private Container _container;

        public MyServer()
            : base(new DefaultReceiveFilterFactory<MyReceiveFilter, BinaryRequestInfo>())
        {
            ConfigureContainer();
        }

        protected override bool SetupCommandLoaders(List<ICommandLoader<ICommand<MyProtocolSession, BinaryRequestInfo>>> commandLoaders)
        {
            commandLoaders.Add(new SimpleInjectorCommandLoader<ICommand<MyProtocolSession, BinaryRequestInfo>>(_container));

            return true;
        }

        private void ConfigureContainer()
        {
            _container.Register<IBlah, Blah>();
            ...
       }
```

Any ideas on what could be causing this or if its by any chance DI changes?

Thanks!

**Comment by sakopov** [comment]
Bump.

Spent some time looking through SuperSocket code. The only thing i can think of is that the the connection is getting closed somewhere. Does this sound about right? Why would the sending queue fill up?

**Comment by sakopov** [comment]
It appears the issue was introduced when I overrode the `CreateAppSession` method in `MyServer` to get `MyProtocolSession` instance from the DI container (SimpleInjector).

```
        protected override MyProtocolSession CreateAppSession(ISocketSession socketSession)
        {
            var sessionFactory = new SimpleInjectorAppSessionFactory<MyProtocolSession>(_container);

            var appSession = sessionFactory.Create();

            appSession.Initialize(this, socketSession);

            return appSession;
        }
```

As shown in the code above, I was calling `Initialize()` on the session object which internally allocates a receiver to the session. However, SuperSocket [makes the same call internally](https://github.com/kerryjiang/SuperSocket/blob/v1.6/SocketBase/AppServerBase.cs#L1382) after calling `CreateAppSession()`. This caused 2 receivers being allocated to the same session, which would eventually drain the receiver pool and result in the original error. 

The fix is obviously to remove session initialization.

```
        protected override MyProtocolSession CreateAppSession(ISocketSession socketSession)
        {
            var sessionFactory = new SimpleInjectorAppSessionFactory<MyProtocolSession>(_container);

            var appSession = sessionFactory.Create();

            return appSession;
        }
```

While the issue's resolved, I think it would have been nice to mark a session as *initialized* and put a check in place to make sure it doesn't get initialized more than once.

**Comment by kerryjiang** [comment]
OK, I'll check the code.

**Comment by sakopov** [comment]
I could do a pull request for this. Let me know if you'd like me to.
