### ISSUE TITLE
能否热更换接收过滤器?

### ISSUE THREAD

**Issue by TMily** [kerryjiang/SuperSocket#102]
在我的应用中,由于历史遗留问题,需要为已经建立的会话更换其他类型的接收过滤器.更换的类型和时机都由程序直接控制.我查看文档似没有找到相关的方式方法.还请指教.

**Comment by TMily** [comment]
不好意思,之前只看了文档站没注意到QuickStart里面似乎有相关范例,先行关闭.

**Comment by TMily** [comment]
初步尝试看QuickStart的实例基本能满足我的需求,但是为何内置的过滤器中FixedHeaderReceiveFilter的NextReceiveFilter属性只有get而没有set? 在我的应用中需要切换的两种过滤器是FixedHeaderReceiveFilter和BeginEndMarkReceiveFilter

**Comment by kerryjiang** [comment]
你可以overwrite属性NextReceiveFilter

**Comment by TMily** [comment]
哦抱歉 昨晚一时脑抽没想起来开issue打扰了~
