### ISSUE TITLE
单次请求超过250879个字节会发生协议错误

### ISSUE THREAD

**Issue by fish0413** [kerryjiang/SuperSocket#105]
使用FixedHeaderReceiveFilter，Header大小为12个字节，发送的Body一但超过250867个字节，在ResolveRequestInfo方法执行成功并返回正确内容后就会发生ProtocolError，链接会被断开。

**Comment by kerryjiang** [comment]
Could you check the error logs?

You better create a test case to demonstrate this issue.

**Comment by fish0413** [comment]
我写了一个测试项目，请帮我看看是什么问题。

[Test_SuperSocket_250879.zip](https://github.com/kerryjiang/SuperSocket/files/980632/Test_SuperSocket_250879.zip)

**Comment by fish0413** [comment]
我写了一个测试项目，请帮我看看是什么问题。

[Test_SuperSocket_250879.zip](https://github.com/kerryjiang/SuperSocket/files/980646/Test_SuperSocket_250879.zip)

**Comment by fish0413** [comment]
发现maxRequestLength这个参数可以影响这个问题，默认值1024，改大以后可以接收更大的数据，改成2048后可以支持100M的数据

**Comment by kerryjiang** [comment]
不可能，maxRequestLength是指最大请求长度，如果请求长度超过这个数，服务器将断开连接。

**Comment by fish0413** [comment]
目前的情况是，将maxRequestLength设置为2048以后，单次发送100M也不会出错，如果采用默认值1024，单次发送达到250880个字节就会断开连接。

**Comment by fish0413** [comment]
我搞不懂它到底是怎么工作的
