### ISSUE TITLE
关于发送命令到客户端的问题

### ISSUE THREAD

**Issue by happy5217744** [kerryjiang/SuperSocket#110]
现在业务层需要发送命令给客户端，并得到客户端的响应，应该怎么做，有没有成熟的模式，通过SocketServerManager可行吗？谢谢

**Comment by kerryjiang** [comment]
No, 直接向客户端发送阿，在Commandl里面把回复和请求关联起来就行了。

**Comment by happy5217744** [comment]
请问下业务层怎么去调Supersocket的command 发送命令，如何把对客户端的请求和客户端的回复关联起来，能不能详细说下，谢谢

**Comment by kerryjiang** [comment]
看文档和源代码中的QuickStart示例项目:
http://docs.supersocket.net/
