### ISSUE TITLE
关于发送命令到控制台后从控制台返回的数据中的中文乱码问题

### ISSUE THREAD

**Issue by csharpweb** [kerryjiang/SuperSocket#111]
渔大，问题如题，已经试过各种方法，设置了utf8 使用了default，都还是 不行，都是乱码的，数据是从命令执行端返回的执行结果。

**Comment by kerryjiang** [comment]
你先弄清楚客户端用的什么编码，服务器端和客户端一致就行了。

**Comment by csharpweb** [comment]
我看到了，好像是我控制端没有指定textencoding参数的问题。。
