### ISSUE TITLE
Bootstrap启动的SuperSocket Server如何获取其中AppSession

### ISSUE THREAD

**Issue by venlentine** [kerryjiang/SuperSocket#117]
取得IBootstrap的服务后，只有SessionCount属性
var server = bootstrap.AppServers.FirstOrDefault(s => s.Name.Equals(name, StringComparison.OrdinalIgnoreCase));
如何在这个server中获取到具体的AppServer和AppSession

**Comment by benjious** [comment]
你解决了吗？我至今也没解决，我建议作者可以在文档中说明一下

**Comment by xiaobochen111** [comment]
var server= ( YourServer )bootstrap.GetServerByName( "你在配置中的服务名称" );
            var allSession = server.GetAllSessions().ToList();
allSession就是当前所有的客户端

**Comment by traceless0929** [comment]
可以使用server.GetAllSessions()取出所有Session，特定的某个Session通过linq where出来就行了
