### ISSUE TITLE
Xamarin Version of SuperSocket

### ISSUE THREAD

**Issue by Danielku15** [kerryjiang/SuperSocket#119]
Hi Kerry. 

It seems that SuperSocket (unlike SuperSocket.ClientEngine) is not yet available for Xamarin. I was able to compile an own version by basically removing all configuration based code. It would be nice if you would provide Xamarin and/or .net Standard 2.0 versions of this library to consume it via nuget.

**Comment by kerryjiang** [comment]
There is already one.
