### ISSUE TITLE
这个开源出来的代码好少啊

### ISSUE THREAD

**Issue by zwffff2015** [kerryjiang/SuperSocket#121]
这个开源的东西，和反编译出来的东西相差也太大了吧，这属于伪开源吗？

**Comment by kerryjiang** [comment]
恩，伪开源。
你如果是用的1.6.*的版本的话，请查看1.6分支的代码。
当前分支是基于.NET Core重新设计的版本。

**Comment by rujianwang** [comment]
v1.6的 分支貌似编译失败

**Comment by chucklu** [comment]
@zwffff2015  You should read the following documentation first
https://github.com/kerryjiang/SuperSocket/blob/master/README.md

> This branch is under developing and unstable. If you want a stable version which can be used in your production system, please switch to branch v1.6.
