### ISSUE TITLE
请问，大概什么时候发布NET Core版本

### ISSUE THREAD

**Issue by leehavin** [kerryjiang/SuperSocket#123]
请问，大概什么时候发布NET Core版本

**Comment by kerryjiang** [comment]
May be later than .NET Core 2.1.

**Comment by chucklu** [comment]
https://github.com/dotnet/core/blob/master/roadmap.md
.NET Core 2.0 shipped on August 14th, 2017.

Milestone | Release Date
-- | --
.NET Core 2.1 Preview    | Q4 2017
.NET Core 2.1                 | Q1 2018

**Comment by mrtylerzhou** [comment]
looking forward to the core version

**Comment by alex-ling** [comment]
cccore
csupersocket

**Comment by beefsteak** [comment]
the release of .NET Core 2.1 now, when will the supersocket of net core be released?

**Comment by linchenrr** [comment]
I'm waiting for it, too

**Comment by debin168** [comment]
great work ，您真的很棒。

**Comment by kerryjiang** [comment]
I don’t have an estimate yet. I am working on some adjustments to use the libraries in Kestrel.

**Comment by kerryjiang** [comment]
The road map has been updated in the readme.
