### ISSUE TITLE
Built-in gzip support

### ISSUE THREAD

**Issue by xenon200x** [kerryjiang/SuperSocket#128]
Dear Kerry,
    Thanks for the good work. I want to know what is the best practice for enabling gzip compression support in supersocket framework? I mean, should I implement requested functionality in custom receive filters using gzipstream, or there is a built-in and more efficient way for this purpose?

Kind regards,
Behnam

**Comment by kerryjiang** [comment]
Hello Behnam, do you mean the whole communication is compressed by gzip?

I prefer to message level compression which can be done by yourself.

**Comment by xenon200x** [comment]
Hi Kerry,
    Thanks for your clarification. IMHO compressing the whole communication is a daunting task and out of scope of this conversation. Message level compression is what I meant. And it appears that I'm gonna implement it myself. So thanks again for your time.

Regards,
