### ISSUE TITLE
http://www.supersocket.net/ 无法访问了

### ISSUE THREAD

**Issue by liugt34** [kerryjiang/SuperSocket#134]
![image](https://user-images.githubusercontent.com/8056013/35318942-a573bb3c-0118-11e8-922c-58aeda38184d.png)

**Comment by chucklu** [comment]
The website is working.
Maybe something wrong with your network service or proxy.
You can also check the firewall as the browser already suggested.

**Comment by liugt34** [comment]
@chucklu   i can access other website  except this website,，How odd!
