### ISSUE TITLE
the client can connect to the server,but the server can't receive any message from the client!

### ISSUE THREAD

**Issue by liugt34** [kerryjiang/SuperSocket#135]
when i use the telenet , the code work well,, but when i use a software of《debugger helper》 ，it can not receive any message. i don't know why?

appServer.NewRequestReceived += new RequestHandler<RobotSession, StringRequestInfo>(appServer_NewRequestReceived);

the software download link
[http://www.usr.cn/Down/Software/USR-TCP232-Test-V1.3.exe](http://www.usr.cn/Down/Software/USR-TCP232-Test-V1.3.exe)

**Comment by liugt34** [comment]
![image](https://user-images.githubusercontent.com/8056013/35323502-b0cc234c-0128-11e8-8e50-4c0e91915722.png)

**Comment by liugt34** [comment]
i  got it , it must use the protocol defined myself

**Comment by chucklu** [comment]
The default protocol is command line protocol, every message should end with a new line.
When you send message by the tools, the tool will not add a new line for everymessage
