### ISSUE TITLE
CSuperSocket?

### ISSUE THREAD

**Issue by stefan2410** [kerryjiang/SuperSocket#137]
Hello, thanks for your excellent project.
I've found in Nuget,  CSuperSocket libraries from Kerry Jiang, I tested and they are suitable for our project.
What is the relation with SuperSocket?  It seems  refactored. 
thanks

**Comment by chucklu** [comment]
@stefan2410  I tried to search CSuperSocket on nuget, and I find the author is huajunsoft.
Could paste the nuget link here?

**Comment by stefan2410** [comment]
@chucklu  Here is one of the 4  packages https://www.nuget.org/packages/CSuperSocket.SocketEngine/2.1.2.1 
It mentions 
Owners huajunsoft
Authors 
Kerry Jiang, Sarco, DynamicBlue

**Comment by chucklu** [comment]
@stefan2410  I think those libraries are developed based on the kerryjiang's version.
The owner add kerryjiang as the author cause this repository is under 
License: http://www.apache.org/licenses/LICENSE-2.0

**Comment by stefan2410** [comment]
@chucklu  understood, I should remove them, then. thank you They create confusion because they use the name of  kerryjiang
