### ISSUE TITLE
How can I link to the SuperSocket server running on Microsoft Azure by socket?

### ISSUE THREAD

**Issue by hanzz0502** [kerryjiang/SuperSocket#141]
I have written a server using SurperSocket and deploy it to Microsoft Azure through workRole.Now I want to use the custom client on PC to link to the server by socket to transmit message,but I don't know how to link to it.Using the IP Address of the server?Or using URL to link to the server?

**Comment by nomadfighter** [comment]
IP address and URL all ok.
but first, u must set the INBOUND PORT RULES on the Azure.
