### ISSUE TITLE
客户端接收大数据量时分包了

### ISSUE THREAD

**Issue by csharpweb** [kerryjiang/SuperSocket#142]
嗨 江大！
请问下客户端接收数据量比较大的时候发现数据分包了，请问下要怎么来接收完整的数据？
EasyClient client = new EasyClient();
                ExecuteResponse<TDATA> response = null;
                TaskCompletionSource<NBCloudCommandResponsePackageInfo> taskCompleteSrc = new TaskCompletionSource<NBCloudCommandResponsePackageInfo>();
                client.Initialize(new NBCloudCommandResponseReceiveFilter(), (package) =>
                {
                    //Logger.Debug(package.Response);
                    taskCompleteSrc.TrySetResult(package);
                });
                client.Error +=  (s, e) =>
                {
                    taskCompleteSrc.TrySetException(e.Exception);
                };
                var flag = await client.ConnectAsync(new DnsEndPoint(request.IpAddress, request.Port));
                if (flag)
                {
                    client.Send(Encoding.UTF8.GetBytes(request.Command));
                }
                else
                {
                    response = new ExecuteResponse<TDATA>() { ExecuteSuccess = false, Message = "终端连接失败！", ErrorMessage = "终端连接失败！" };
                }
                var data = await taskCompleteSrc.Task;
                response = JsonConvert.DeserializeObject<ExecuteResponse<TDATA>>(data.Response);
                return response;

这是我目前接收数据的代码，当数据量大了的时候，taskCompleteSrc.TrySetResult(package);会被多次调用（应该是分包发送了），会导致错误，请问下这种情况怎么来解决呢？

期待您的恢复！

**Comment by chucklu** [comment]
Please copy the detail of your error message, such as stack trace

**Comment by winnyrain** [comment]
应根据协议处理粘包，重新组成完整包
