### ISSUE TITLE
如何按顺序处理消息包？

### ISSUE THREAD

**Issue by JiekeZhu** [kerryjiang/SuperSocket#143]
你好，
SuperSocket IOCP异步模型中收到的网络请求都是异步处理的，
socketSession.AsyncRun(() => socketSession.ProcessReceive(e));
这没有疑问。
问题是，按照我的认识：游戏中，房间内的消息都需要按顺序处理，需要将解析出来的消息报放到队列中，逐个按顺序处理。这样就需要一个消息(队列)处理线程，同样的也需要一个发送(队列)处理线程。然后我没能再SuperSocket中知道的这样的功能模块，就很好奇了。

谢谢~
---
很早以前就听过到SuperSocket的大名了，不过那时候对服务端开发涉及较少，也不深入，这两年才做的多一点。两个星期之前我还在用C++处理服务端的事情，服务接口、数据库操作、网络通信的。然后我就再回顾了一下C#线路，过了一遍Asp.net Core MVC！！！发现用C++累个半死的事情，C#几行代码就搞定。C++累个半死打出来的框架，C#几个Filter就搞定了。一堆Sql代码，C#(EF)还是几行代码就搞定了，而且可维护性高很多。阿西吧~ 然后我就顺道来看一下C#网络库了。Asp.net core的SignalR要到v2.1，这个季度末才能出来，具体怎样还不知道。
按照自己的能力表层的看了一下SuperSocket，第一感受是牛掰~给力啊，整体框架都很完善。网络内核、配置、日志、性能监视等等。666~ 感谢大婶们的辛苦力作~

**Comment by chucklu** [comment]
please check [Implement Your Own Communication Protocol with IRequestInfo, IReceiveFilter and etc](http://docs.supersocket.net/v1-6/en-US/Implement-Your-Own-Communication-Protocol-with-IRequestInfo,-IReceiveFilter-and-etc)

You need design your own protocol, maybe you can add an order1 to check the order of different messages, guid for message,and add an order2 for message(if you split one message into several blocks) in it.

I suggest  you to use [FixedHeaderReceiveFilter ](https://github.com/kerryjiang/SuperSocket.ProtoBase/blob/4eacfc60ad0b4b1527bc634a1822bc60ea3e9ff0/src/ReceiveFilters/FixedHeaderReceiveFilter.cs), then design your own protocol
Here is a [demo](https://github.com/kerryjiang/SuperSocket/blob/v1.6/QuickStart/CustomProtocol/MyReceiveFilter.cs) in v1.6 branch

**Comment by JiekeZhu** [comment]
Ok. Got it.
I'm gonna implement my own ReceiveFilter.
It's gonna use Protocol Buffers  and put every packet into a queue which will be processed by a thread, the main packet receiving thread, including socket-connected socket-closed packet processing.
At the same time, I will also use a sending thread to process socket writing/closing operations.
With these two logic controling mechanism, I call make sure my game messages are processed sequentially while the IO operations are asynchronous.

Thanks,
Br.
