### ISSUE TITLE
EasyClient发送20条json数据对象造成服务端异常

### ISSUE THREAD

**Issue by flyingfive** [kerryjiang/SuperSocket#144]
你好，最近在做服务端主动调取客户数据（建立连接后）时碰到一个问题：当客户端收到服务端请求消息后返回超过20个对象的json数据时服务端出错：打开日志后发现如下堆栈信息：
2018-05-11 18:12:13,433 [6] ERROR ProtobufAppServer-33476626 - Session: f454bbe9-1968-432d-adf0-6c04be9dab31/173.31.15.53:52554
Unexpected error
System.ArgumentException: Illigal offsetDelta: 4096
参数名: offsetDelta
   在 SuperSocket.SocketEngine.AsyncSocketSession.StartReceive(SocketAsyncEventArgs e, Int32 offsetDelta)

尝试过启动服务时的参数配置，问题依旧。客户端EasyClient里找不到相关的配置接口。请问可能的原因会有哪些，还是自定义的ProtobufReceiveFilter有问题没有注意到？感谢~

**Comment by chucklu** [comment]
I think  it's a bug of your custom filter, just code logic bug.
You can try to output the detail of your logic(record the offset and total length) to log file, and check it.

**Comment by flyingfive** [comment]
感谢回复，我再试试。
