### ISSUE TITLE
Session Closed Event, CloseReason value = 4 (ApplicationError), so what has caused "Application Error"? 

### ISSUE THREAD

**Issue by ldahual** [kerryjiang/SuperSocket#145]
What on earth does "ApplicationError" mean？

**Comment by chucklu** [comment]
It  means an error happened in your Application level, your custom code.
The source code is in file SuperSocket\SocketBase\AppSession.cs
```csharp
        /// <summary>
        /// Handles the exceptional error, it only handles application error.
        /// </summary>
        /// <param name="e">The exception.</param>
        protected virtual void HandleException(Exception e)
        {
            Logger.Error(this, e);
            this.Close(CloseReason.ApplicationError);
        }

/// <summary>
        /// Gets the logger.
        /// </summary>
        public ILog Logger
        {
            get { return AppServer.Logger; }
        }
```

SuperSocket\SocketBase\AppServerBase.cs
```xml
 /// <summary>
        /// Gets the logger assosiated with this object.
        /// </summary>
        public ILog Logger { get; private set; }

 bool IWorkItem.Setup(IBootstrap bootstrap, IServerConfig config, ProviderFactoryInfo[] factories)
{
 Logger = CreateLogger(this.Name);
}

 /// <summary>
        /// Creates the logger for the AppServer.
        /// </summary>
        /// <param name="loggerName">Name of the logger.</param>
        /// <returns></returns>
        protected virtual ILog CreateLogger(string loggerName)
        {
            return LogFactory.GetLog(loggerName);
        }
```

You can configure the log factory section in config file, then the detail error will be recorded.
Please read this document [SuperSocket Basic Configuration](http://docs.supersocket.net/v1-6/en-US/SuperSocket-Basic-Configuration
) to learn knowledge about "Log Factories Configuration". Then you can check the detail in log file.

**Comment by ldahual** [comment]
@chucklu Thank you for your reply ~
After reading the document [SuperSocket Basic Configuration](http://docs.supersocket.net/v1-6/en-US/SuperSocket-Basic-Configuration)  I have more questions about log factory.
I have used SuperSocket in a Visual Studio C# project by  Nuget packets. I have configured the RootConfig like this:
```
var rootConfig = new RootConfig();
rootConfig.MinCompletionPortThreads = 8;
rootConfig.MinWorkingThreads = 8;
rootConfig.LogFactory = "ServerLog";
...
appTcpServer.Setup(rootConfig, serverConfig);
```
And I can't find any log file. 
So how to config the log factory and export error details?

**Comment by chucklu** [comment]
@ldahual  I think you might miss the configuration file for log4net.
Please read this document [Logging in SuperSocket](http://docs.supersocket.net/v1-6/en-US/Logging-in-SuperSocket).

> SuperSocket also provides the basic log4net configuration files log4net.config/log4net.unix.config, **you should put the log configuration file into the sub directory "Config" of the root of the running application**. The log4net config define the loggers and appenders to category all logs into the 4 rolling files in the folder named "Logs":
> 
> info.log
> debug.log
> err.log
> perf.log
> You also can customize the config according your logging requirements.
> 
> Because of the loose couple with the log4net, you need to reference the file log4net.dll manually by yourself (please use the one provided by SuperSocket).

You can get the basic config file from this repository‘s v1.6 branch, under “[Solution Items](https://github.com/kerryjiang/SuperSocket/tree/v1.6/Solution%20Items)” folder.

**Comment by ldahual** [comment]
@chucklu Thank you. I have gotten the 4 log files and located the exception.
