### ISSUE TITLE
服务端自定义的AppSession的OnSessionClosed无法触发

### ISSUE THREAD

**Issue by AWNUXCVBN** [kerryjiang/SuperSocket#147]
客户端是单独写的Scoket Tcp，我写了如下代码，也无法触发自定义的AppSession的OnSessionClosed，请问是否必须用SuperSocket写客户端才会触发？
`socket.Shutdown(SocketShutdown.Both);`
`socket.Close();`

**Comment by AWNUXCVBN** [comment]
我试着做了，尝试了try catch和各种关闭方法，还是不会触发，我再找找原因

**Comment by QDPudge** [comment]
我也试了，无论怎么样都无法触发断开时间，我捕捉的session 连接状态connected状态也是true，可是close，Dispose都试了都不行，有办法吗。我客户端就是用的原生的socket

**Comment by chucklu** [comment]
@QDPudge  show me the code

**Comment by QDPudge** [comment]
我使用的C# .NET4.6 原生socket
private static Socket tcpSocket;
  tcpSocket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
  tcpSocket.Connect(ip, System_info.port_login);
断开时 我使用一下方法 均无法触发

            socket.Close();
            socket.Dispose();

            socket.Shutdown(SocketShutdown.Both);

而且 SuperSocket的session集合中，链接状态Connected 扔为true
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Chuck Lu <notifications@github.com>
发送时间: Thursday, June 21, 2018 10:14:28 AM
收件人: kerryjiang/SuperSocket
抄送: QDPudge; Mention
主题: Re: [kerryjiang/SuperSocket] 服务端自定义的AppSession的OnSessionClosed无法触发 (#147)


@QDPudge<https://github.com/QDPudge> show me the code

―

**Comment by AWNUXCVBN** [comment]
@chucklu @QDPudge 
My client code is here  

https://gitee.com/awnuxcvbn/Ganghood/blob/master/Client/Assets/Scripts/Core/Manager/NetMgr.cs

My server code is here

https://gitee.com/awnuxcvbn/Ganghood/blob/master/Server/Server/Net/PlayerSession.cs

Not fixed yet

**Comment by QDPudge** [comment]
I find  Method OnSessionClosed in my code has two param
(AppSession app, CloseReason reason)

But your code just have one ;

Sad ☹
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Chuck Lu <notifications@github.com>
发送时间: Friday, June 22, 2018 5:01:46 PM
收件人: kerryjiang/SuperSocket
抄送: QDPudge; Mention
主题: Re: [kerryjiang/SuperSocket] 服务端自定义的AppSession的OnSessionClosed无法触发 (#147)


@QDPudge<https://github.com/QDPudge> @AWNUXCVBN<https://github.com/AWNUXCVBN>
I have test the code, and there is no problem. I believe maybe you make mistake when create the socket server based on SuperSocket.

I suggest you check your server code carefully to find out the problem. Maybe you can check the demo code TelnetServer_AppSession<https://github.com/kerryjiang/SuperSocket/tree/v1.6/QuickStart/Basic/TelnetServer_AppSession>

You can modify the OnSessionClosed method in TelnetSession class like this:

 protected override void OnSessionClosed(CloseReason reason)
        {
            //add you logics which will be executed after the session is closed
            Console.WriteLine($"{nameof(SessionID)} = {SessionID}, {nameof(Connected)} = {Connected}");
            base.OnSessionClosed(reason);
        }

[image]<https://user-images.githubusercontent.com/3004057/41767875-5c12cd8a-763d-11e8-8f5c-204688206d2e.png>

Here is my client test code

 [Test]
        public void SocketClientTest()
        {
            var host = "127.0.0.1";
            int port = 2012;
            IPAddress[] IPs = Dns.GetHostAddresses(host);
            Socket tcpSocket;
            tcpSocket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
            tcpSocket.Connect(IPs[0], port);
            Thread.Sleep(3 * 1000);
            try
            {
                tcpSocket.Shutdown(SocketShutdown.Both);
            }
            catch
            {

            }
            finally
            {
                try
                {
                    tcpSocket.Close();
                }
                catch
                {

                }
            }
        }

**Comment by AWNUXCVBN** [comment]
My serverconfig error,fixed.
`var serverConfig = new ServerConfig
            {
                Port = 6650, //set the listening port
                Ip = "Any",
                Name = "GameServer",
                //Other configuration options
                Mode = SocketMode.Tcp,
                MaxConnectionNumber = 2000,
                IdleSessionTimeOut = 600,
                TextEncoding = "UTF-8",
                //参数为false时，客户端断开服务器无法触发SessionClosed，额暂时未了解配置说明
                SyncSend = false,
                SendBufferSize = 1024,
                ReceiveBufferSize = 1024,
                LogBasicSessionActivity = true,
                LogAllSocketException = true,
                KeepAliveTime = 300,
            };`

**Comment by AWNUXCVBN** [comment]
@QDPudge 
//syncSend: 是否启用同步发送模式, 默认值: false;
                SyncSend = false,

**Comment by QDPudge** [comment]
谢谢你的耐心帮助！

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: XUEFEI <notifications@github.com>
发送时间: Saturday, June 23, 2018 4:56:58 PM
收件人: kerryjiang/SuperSocket
抄送: QDPudge; Mention
主题: Re: [kerryjiang/SuperSocket] 服务端自定义的AppSession的OnSessionClosed无法触发 (#147)


@QDPudge<https://github.com/QDPudge>
//syncSend: 是否启用同步发送模式, 默认值: false;
SyncSend = false,

―
