### ISSUE TITLE
System.InvalidOperationException: "现在已经正在使用此 SocketAsyncEventArgs 实例进行异步套接字操作。";

### ISSUE THREAD

**Issue by tupunco** [kerryjiang/SuperSocket#15]
Win2008R2-x64-企业版 服务器
Framework 版本: v4.0.30319

这个问题经常发生, 只能重启服务来解决.
异常如下:
Unexpected error
System.InvalidOperationException: "现在已经正在使用此 SocketAsyncEventArgs 实例进行异步套接字操作。";
   在 System.Net.Sockets.SocketAsyncEventArgs.StartOperationCommon(Socket socket)
   在 System.Net.Sockets.Socket.ReceiveAsync(SocketAsyncEventArgs e)
   在 SuperSocket.SocketEngine.AsyncSocketSession.StartReceive(SocketAsyncEventArgs e, Int32 offsetDelta) 位置 e:\Workshop\SuperSocket\v1.6\SocketEngine\AsyncSocketSession.cs:行号 148

**Comment by alanyuen** [comment]
新版已有這個問題

**Comment by kerryjiang** [comment]
貌似当前很少有用户报这个问题，如果真的有问题，可能和socket实例关闭状态的检测有关。

**Comment by kerryjiang** [comment]
This issue might have been fixed by the latest commits in branch 1.6, could you have a try and then tell me your test result?

**Comment by tupunco** [comment]
目前不再做这块儿内容, 看看别的用户的反馈吧.

**Comment by kerryjiang** [comment]
From the other user's feedback, this issue has been fixed in the latest code of SuperSocket branch v1.6.
