### ISSUE TITLE
创建多个ReceiveFilter，以方便扩展支持多种协议

### ISSUE THREAD

**Issue by xiaobochen111** [kerryjiang/SuperSocket#150]
我的目的：写一个通讯框架，能支持不同的协议，在扩展协议的时候新增处理方法即可，比如新加了A设备，那么我只需要写A设备的协议解析方法即可。看了文档，按以下写法能让消息进入不同的filter（消息分发），但是我这种写法是通过指定端口来实现消息分发的，请问有其他的方法能实现消息分发吗？
创建多个ReceiveFilter，目前我只找到这种
public IReceiveFilter<TRequestInfo> CreateFilter( IAppServer appServer , IAppSession appSession , IPEndPoint remoteEndPoint )
        {

            IReceiveFilter<TRequestInfo> i;
            if( appSession.RemoteEndPoint.Port != 4001 )
            {
                i = ( IReceiveFilter<TRequestInfo> )new DTUReceiveFilter();
            }
            else
            {
               i = ( IReceiveFilter<TRequestInfo> )new AAARecieveFilter();
            }
            return i;
        }
请教一下这里怎么根据会话去创建不同的filter呢。

**Comment by chucklu** [comment]
Please check this demo project [SwitchReceiveFilter](https://github.com/kerryjiang/SuperSocket/tree/v1.6/QuickStart/SwitchReceiveFilter) on branch v1.6 .

**Comment by xiaobochen111** [comment]
@chucklu 我看了SwitchReceiveFilter的例子，他的思路是通过包头来进行消息分发到不同的Filter中去处理，但是这样也会遇到一个问题，不同设备发送过来的包头有可能相同。而且对于有分包或者粘包的数据，获取包头是不是一定准确呢？我再想想有没有办法解决这些问题，谢谢您的回复。

**Comment by chucklu** [comment]
@xiaobochen111  You can design your customized protocol, like  embeding your device mac after the header. Then you can check the device mac to decide switch to which filter, it's up to you.

**Comment by kerryjiang** [comment]
The protocol analyzing need start right after the connection establish. So you only can use the information you can get at that point to decide which receive filter should be picked.
