### ISSUE TITLE
The sending attempt timed out

### ISSUE THREAD

**Issue by darkinghb** [kerryjiang/SuperSocket#151]
Hi, i'm trying to send one message to various clients but i'm getting timed out error some time

Log:
```
   in SuperSocket.SocketBase.AppSession`2.InternalSend(ArraySegment`1 segment)
   in SuperSocket.SocketBase.AppSession`2.Send(ArraySegment`1 segment)
   in Oblivion.Connection.SuperSocket.Session`1.Send(Byte[] data) on C:\Users\User\Documents\GitHub\Oblivion\Oblivion\Oblivion.Emulator\Connection\SuperSocket\Session.cs:linha 35
```
Line 35 is the send() in this method:
```
public void Send(byte[] data)
        {
            if (_disposed) return;
            try
            {
                Send(new ArraySegment<byte>(data));
            }
            catch (Exception e)
            {
                Logging.HandleException(e, "Send");
            }
        }

```
Here is my server config:
```
var config = new ServerConfig
            {
                Port = port,
                ReceiveBufferSize = 4096,
                SendBufferSize = 4096,
                ListenBacklog = 150,
                SendTimeOut = 25000,
                SyncSend = false,
                MaxConnectionNumber = maxConn
            };
```

**Comment by kerryjiang** [comment]
Do you have situation that server sends data to client very frequently?

**Comment by darkinghb** [comment]
Yes, it's a web game...

**Comment by kerryjiang** [comment]
Do you have an estimate about how many messages would be sent over each connection?

**Comment by darkinghb** [comment]
I can't estimate, cos each action is an message.
It's a game like habbo, imvu, or the sims...
The client send packet to server, the server process the data then the client send again, maybe 1 message per 0.1 sec

**Comment by darkinghb** [comment]
Another info: i have 400 clients (users)

**Comment by darkinghb** [comment]
Update: this is related to client ping/packet loss.
I'm running some test, maybe if i increase sending queue size to a high value can solve the problem.

**Comment by darkinghb** [comment]
Found the problem!
Just increase SendingQueueSize and disconnect connections with high ping.
In my case, i'm disconnecting the connection who generate exceptions
 ```
        public void Send(byte[] data)
        {
            if (_disposed) return;
            try
            {
                Send(data, 0, data.Length);
            }
            catch (Exception e)
            {
                HandleException(e);
            }
        }
```

**Comment by SunningPig** [comment]
同样碰到这样的问题 @darkinghb

**Comment by SunningPig** [comment]
Encountered the same problem,What is the final solution? @darkinghb

**Comment by chucklu** [comment]
@SunningPig 

>  increase SendingQueueSize and disconnect connections with high ping
