### ISSUE TITLE
如何从一个客户端向另一个客户端发送消息

### ISSUE THREAD

**Issue by debin168** [kerryjiang/SuperSocket#152]
public class ECHO : CommandBase<TelnetSession, StringRequestInfo>
    {
        public override void ExecuteCommand(TelnetSession sessionA, StringRequestInfo requestInfo)
        {
             //body 中解析出另外一个sessionB中的companyId 
             //如何利用该companyId 获取相关联的sessionB  我知道有GesseionsId()这个方法，但
           //是这个方法是由appserver 主动发起的，如何在command的执行里面发起？
            sessionA.Send(requestInfo.Body);
        }
    }
感谢赐教！

己经解决了，仔细查看了下 ，session里有这个  session.AppServer.GetSessionByID()
方法，那就可以调用appserver获取另一个session了。

**Comment by chucklu** [comment]
Since you have the solution, please close this issue.
