### ISSUE TITLE
文档页面打不开

### ISSUE THREAD

**Issue by linchenrr** [kerryjiang/SuperSocket#153]
As title, the web page http://docs.supersocket.net/  can not open with err:"ERR_CONNECTION_REFUSED".
mengxin sese shaking...

![2](https://user-images.githubusercontent.com/11712968/42144245-aafcba3a-7dec-11e8-9fd1-b258f6aee497.png)

**Comment by chucklu** [comment]
You can get the documentation here 
https://github.com/kerryjiang/SuperSocket.Document/tree/v1.6
https://github.com/kerryjiang/SuperSocket.Document/tree/v1.6(zh-CN)

**Comment by kerryjiang** [comment]
Thanks for the reminder!
The docker containers didn't start after the server restarted.
I just started them manually, so the website should be ok right now.
