### ISSUE TITLE
TLS 1.2 issue

### ISSUE THREAD

**Issue by AmitaKhatri** [kerryjiang/SuperSocket#159]
Hi,

We disabled some of the cipher suites and TLS 1.0, 1.1 from our server but after that, the super socket stopped working. It kept on giving an error like "The client and server cannot communicate, because they do not possess a common algorithm".

Here is the list of cipher suites that we had disabled:
TLS_RSA_WITH_RC4_128_MD5
TLS_RSA_WITH_RC4_128_SHA
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA

Can you please let me know if there is any solution for this?

**Comment by chucklu** [comment]
What's the version of .net you are using for SuperSocket?
You can google the exception and find some solution on stackoverflow.
https://stackoverflow.com/a/42124951

You can also check the following documentation
https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls

**Comment by AmitaKhatri** [comment]
I am using 1.6.6.1 version.

I have already tried these options but they ain't working for me.

**Comment by chucklu** [comment]
I am not asking the version of SuperSocket, I want to know the .net verison.
Which solution are you using?
> E:\GitHub\KerryJiang\SuperSocket-v1.6 [v1.6 ↓2 +5 ~1 -0 !]> ls *.sln
> 
> 
>     Directory: E:\GitHub\KerryJiang\SuperSocket-v1.6
> 
> 
> Mode                LastWriteTime         Length Name
> ----                -------------         ------ ----
> -a----       10/23/2017   4:39 PM           5692 SuperSocket.2008.sln
> -a----       10/23/2017   4:39 PM           6863 SuperSocket.2010.NET35.sln
> -a----       10/23/2017   4:39 PM           6863 SuperSocket.2010.sln
> -a----       10/23/2017   4:39 PM           6942 SuperSocket.2013.NET40.sln
> -a----       10/23/2017   4:39 PM           6942 SuperSocket.2013.sln
>

**Comment by AmitaKhatri** [comment]
I am using the .net version 4.5. The library is referenced by the nuget package.

**Comment by chucklu** [comment]
Do you have the full stack trace of the exception?

**Comment by AmitaKhatri** [comment]
Hi chucklu,

Here is the stack trace:

Unexpected error
Caller: OnBeginInitStream, file path: d:\WorkShop\SuperSocket\v1.6\SocketEngine\AsyncStreamSocketSession.cs, line number: 255
System.ComponentModel.Win32Exception (0x80004005): The client and server cannot communicate, because they do not possess a common algorithm
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at SuperSocket.SocketEngine.AsyncStreamSocketSession.OnBeginInitStream(IAsyncResult result, Boolean connect)

**Comment by Danielku15** [comment]
We also lately discovered this issue and were able to solve it after reading on SuperSocket internals: 

The tricky part is to correctly configure the TLS versions that should be used. Internally the `Security` property is parsed from string into the `System.Security.Authentication.SslProtocols` enum.  If you set the property to `tls` you will only enable [TLS 1.0](https://docs.microsoft.com/en-us/dotnet/api/system.security.authentication.sslprotocols?view=netframework-4.7.2). To have other versions enabled you need to use something like: `config.Security = (SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12).ToString()`

I made this small helper function to load the actually enabled SCHANNEL protocols: 

```csharp
// config.Security = GetEnabledTlsVersions();

public static string GetEnabledTlsVersions()
{
    var enabledProtocols = SslProtocols.None;

    try
    {
        var protocols = new[]
        {
            (key: @"SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Server", protocol: SslProtocols.Ssl2),
            (key: @"SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Server", protocol: SslProtocols.Ssl3),
            (key: @"SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server", protocol: SslProtocols.Tls),
            (key: @"SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server", protocol: SslProtocols.Tls11),
            (key: @"SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server", protocol: SslProtocols.Tls12)
        };

        using (var baseKey = RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, RegistryView.Registry64))
        {
            foreach (var protocol in protocols)
            {
                using (var key = baseKey.OpenSubKey(protocol.key, false))
                {
                    var value = key?.GetValue("DisabledByDefault") ?? 0;
                    if (value is int disabled && disabled != 0)
                    {
                        continue;
                    }

                    value = key?.GetValue("Enabled") ?? 1;
                    if (value is int enabled && enabled != 0)
                    {
                        enabledProtocols |= protocol.protocol;
                    }
                }
            }
        }
    }
    catch (Exception e)
    {
        // Log Error: "Failed to load enabled SSL protocols"
    }

    if (enabledProtocols == SslProtocols.None)
    {
        enabledProtocols = SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12;
    }

    return enabledProtocols.ToString();
}
```

**Comment by AmitaKhatri** [comment]
This worked. Thanks!
