### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by rujianwang** [kerryjiang/SuperSocket#160]
https://supersocket.codeplex.com/releases/view/620564
这个链接下载的代码，编译失败啊。
疑问一：
nuget上的包版本是1.6.6 
git上稳定分支版本是1.6.4的
codeplex 上提供的zip包 是编译不通过的，而且里面的大版本号写的是 1.7.0.5 感觉和1.6.* 版本 有很大差异。

我就想问下 nuget上的1.6.6的版本  的源代码 是不是 不能提供啊？

谢谢

**Comment by chucklu** [comment]
Please check the git history of this file https://github.com/kerryjiang/SuperSocket/blob/v1.6/Solution%20Items/GlobalAssemblyInfo.cs

> commit 9beaf9b5b42129f95cbd16ae97987bd4411d0ba1
> Author: Kerry Jiang <kerry-jiang@hotmail.com>
> Date:   Wed Apr 6 22:59:24 2016 +0800

You can create a branch based the released commit:
![image](https://user-images.githubusercontent.com/3004057/43698766-43549378-997e-11e8-99db-d0f4625e6758.png)

**But I suggest  you compile the latest source code on branch v1.6.**

**Comment by chucklu** [comment]
There are some bug fix between the latest source code and version 1.6.6.1, I think you might need it.
![image](https://user-images.githubusercontent.com/3004057/43699154-244861d8-9980-11e8-9bc3-3f07e59a8eff.png)

**Comment by rujianwang** [comment]
Thanks a lot!

**Comment by chucklu** [comment]
Hi @rujianwang ,
      You'd better clone this repository instead of downloading the zip file of specified commit.

**Comment by rujianwang** [comment]
@chucklu I've got version 1.6.6.1 from branch v1.6. Thanks.
