### ISSUE TITLE
superwebsocket在高并发压测时，服务器连接数到达1000左右出现连接超时.服务器负载并不大，是否有配置可以提升这个阈值让服务器尽可能满负荷运行

### ISSUE THREAD

**Issue by traceless0929** [kerryjiang/SuperSocket#161]
配置文件如下
```
<superSocket>
    <servers>
      <server name="MatchingServer" maxConnectionNumber="50000" serverType="ChessCardHall.MatchingService.testServer, ChessCardHall.testService" ip="Any" port="2013">
      </server>
    </servers>
  </superSocket>
```

查看文档发现有maxWorkingThreads、maxCompletionPortThreads发现配置无效，源码看来是直接使用系统api调取的值，并不能配置

**Comment by chucklu** [comment]
You can check the perf.log, something like this:

> 2018-04-02 15:34:29,019 Performance - ---------------------------------------------------
> CPU Usage: 0.00%, Physical Memory Usage: 67,907,584.00, Total Thread Count: 26
> AvailableWorkingThreads: 2046, AvailableCompletionPortThreads: 1000
> MaxWorkingThreads: 2047, MaxCompletionPortThreads: 1000
> YourAppServer ----------------------------------
> Started Time: 2018/4/2 15:34:28
> Is Running: True
> Total Connections: 0
> Maximum Allowed Connection Number: 3000
> Total Handled Requests: 0
> Request Handling Speed (#/second): 0
> Avialable Sending Queue Items: 500
> Total Sending Queue Items: 500

The perf.log is generated by SuperSocket automatically if you have configured the log setting.

**Comment by traceless0929** [comment]
@chucklu  
```
2018-08-08 13:47:05,721 Performance - ---------------------------------------------------
CPU Usage: 0.00%, Physical Memory Usage: 52,596,736.00, Total Thread Count: 19
AvailableWorkingThreads: 2045, AvailableCompletionPortThreads: 1000
MaxWorkingThreads: 2047, MaxCompletionPortThreads: 1000
MatchingServer ----------------------------------
Started Time: 2018/8/8 13:47:05
Is Running: True
Total Connections: 8009
Maximum Allowed Connection Number: 50000
Total Handled Requests: 0
Request Handling Speed (#/second): 81
Avialable Sending Queue Items: 8,333
Total Sending Queue Items: 8,333
```

I looked at  this log .but 
```
AvailableWorkingThreads: 2045, AvailableWorkingThreads: 1000
MaxWorkingThreads: 2047, MaxCompletionPortThreads: 1000
```
AvailableWorkingThreads\AvailableWorkingThreads always like this.

**Comment by mmaohq** [comment]
May I ask how this problem was finally solved?
