### ISSUE TITLE
Session data acceess from ReceiveFilter

### ISSUE THREAD

**Issue by Alexandertlt** [kerryjiang/SuperSocket#170]
Hello! I use FixedHeaderReceiveFilter. I need to get the stored information from the Session object in ReceiveFilter. How can I get saved data from Session object when I am in ReceiveFilter?

**Comment by kerryjiang** [comment]
Let your filter implement this interface:

`public interface IReceiveFilterInitializer
    {
        /// <summary>
        /// Initializes the ReceiveFilter with the specified appServer and appSession
        /// </summary>
        /// <param name="appServer">The app server.</param>
        /// <param name="session">The session.</param>
        void Initialize(IAppServer appServer, IAppSession session);
    }`

**Comment by kerryjiang** [comment]
`
public interface IReceiveFilterInitializer
    {
        /// <summary>
        /// Initializes the ReceiveFilter with the specified appServer and appSession
        /// </summary>
        /// <param name="appServer">The app server.</param>
        /// <param name="session">The session.</param>
        void Initialize(IAppServer appServer, IAppSession session);
    }
`

**Comment by kerryjiang** [comment]
public interface IReceiveFilterInitializer
    {
        /// <summary>
        /// Initializes the ReceiveFilter with the specified appServer and appSession
        /// </summary>
        /// <param name="appServer">The app server.</param>
        /// <param name="session">The session.</param>
        void Initialize(IAppServer appServer, IAppSession session);
    }

**Comment by kerryjiang** [comment]
Let your filter implement this interface:

IReceiveFilterInitializer
