### ISSUE TITLE
请问supersocket如何处理拆包粘包的问题呀？ 

### ISSUE THREAD

**Issue by loveyeguo** [kerryjiang/SuperSocket#172]
如提问，我搜遍了百度谷歌都没有一篇文章讲这个的 ，求大神解答！！！

**Comment by chucklu** [comment]
You can define your custom protocol to solve it.
There is a sample https://github.com/kerryjiang/SuperSocket/tree/v1.6/QuickStart/CustomProtocol

**Comment by loveyeguo** [comment]
> You can define your custom protocol to solve it.
> There is a sample https://github.com/kerryjiang/SuperSocket/tree/v1.6/QuickStart/CustomProtocol

谢谢你，我下载看看

**Comment by loveyeguo** [comment]
> You can define your custom protocol to solve it.
> There is a sample https://github.com/kerryjiang/SuperSocket/tree/v1.6/QuickStart/CustomProtocol

能否加您的qq?  我仍然有一些疑问

**Comment by loveyeguo** [comment]
我已经知道了，在supersocket的自定义协议里面，其实已经处理了封包和拆包的问题，只需要继承协议，然后重写自己处理数据，转换成自己的实体类即可。 但是同时又生出一个问题，如果遇到一些错误的数据，或者说毫无意义的数据，然后接下来又是正确的数据，那么对于 FixedHeaderReceiveFilter  协议，我应该如何处理呢？    是否可以捕获异常，然后直接关闭session连接？ 正确的做法及示例代码是什么？

**Comment by chucklu** [comment]
You can test it first, I remember the wrong data will be skipped automatically.

**Comment by startewho** [comment]
对于TCP来讲，像流水一样。你根据约定取约定的长度或者分隔符来取，取到了就是适合的包，这个包就是你的业务包。没取到，就返回空，等着循环下次再来取。如果取到之后，要更新buffer的起始位置。相当于这一段已经读取了。没用了，组件就可以dispose这一部分其实。
