### ISSUE TITLE
不停的记录日志 The session will be closed for 。。。

### ISSUE THREAD

**Issue by pj3743** [kerryjiang/SuperSocket#176]
我设置了 ，空闲session超时时间
clearIdleSession="true"
clearIdleSessionInterval ="10"
idleSessionTimeOut="20"

之后如果有空闲的session，就会不断的记录如下的日志，就算这个session被close，也会一直记录
The session will be closed for 38.4553704 timeout, the session start time: 2018/12/27 17:31:56, last active time: 2018/12/27 17:31:56!

![image](https://user-images.githubusercontent.com/8121964/50475476-ef714880-09ff-11e9-9607-6dd140b29c4f.png)

**Comment by chucklu** [comment]
I  have tried the same configuration as you did, but can not reproduce it.

> 2018-12-27 18:55:16,701 [1000] INFO  TelnetServer - The server instance TelnetServer has been started!
> 2018-12-27 18:56:12,597 [28628] INFO  TelnetServer - Session: ab1a8481-d73c-4ac6-b68a-f4ac135c4a2b/127.0.0.1:65456
> A new session connected!
> 2018-12-27 18:56:36,797 [15676] INFO  TelnetServer - Session: ab1a8481-d73c-4ac6-b68a-f4ac135c4a2b/127.0.0.1:65456
> The session will be closed for 24.1915826 timeout, the session start time: 12/27/2018 6:56:12 PM, last active time: 12/27/2018 6:56:12 PM!
> 2018-12-27 18:56:36,797 [15676] INFO  TelnetServer - Session: ab1a8481-d73c-4ac6-b68a-f4ac135c4a2b/127.0.0.1:65456
> This session was closed for TimeOut!
> 2018-12-27 19:00:08,363 [22232] INFO  TelnetServer - Session: 4294ceea-6966-41b4-8dc3-7b319ddbe5b4/127.0.0.1:49568
> A new session connected!
> 2018-12-27 19:00:37,030 [15676] INFO  TelnetServer - Session: 4294ceea-6966-41b4-8dc3-7b319ddbe5b4/127.0.0.1:49568
> The session will be closed for 28.666269 timeout, the session start time: 12/27/2018 7:00:08 PM, last active time: 12/27/2018 7:00:08 PM!
> 2018-12-27 19:00:37,030 [12752] INFO  TelnetServer - Session: 4294ceea-6966-41b4-8dc3-7b319ddbe5b4/127.0.0.1:49568
> This session was closed for TimeOut!
> 2018-12-27 19:02:38,734 [4560] INFO  TelnetServer - Session: 1b7e63f2-b5ec-4555-991a-efdee4df5146/127.0.0.1:49958
> A new session connected!
> 2018-12-27 19:02:42,220 [4560] INFO  TelnetServer - Session: c41e9df1-5268-4a37-9ac4-b3b7360bec4a/127.0.0.1:49964
> A new session connected!
> 2018-12-27 19:03:07,175 [15676] INFO  TelnetServer - Session: 1b7e63f2-b5ec-4555-991a-efdee4df5146/127.0.0.1:49958
> The session will be closed for 28.4417275 timeout, the session start time: 12/27/2018 7:02:38 PM, last active time: 12/27/2018 7:02:38 PM!
> 2018-12-27 19:03:07,176 [15676] INFO  TelnetServer - Session: c41e9df1-5268-4a37-9ac4-b3b7360bec4a/127.0.0.1:49964
> The session will be closed for 24.9552739 timeout, the session start time: 12/27/2018 7:02:42 PM, last active time: 12/27/2018 7:02:42 PM!
> 2018-12-27 19:03:07,181 [24592] INFO  TelnetServer - Session: 1b7e63f2-b5ec-4555-991a-efdee4df5146/127.0.0.1:49958
> This session was closed for TimeOut!
> 2018-12-27 19:03:07,203 [15676] INFO  TelnetServer - Session: c41e9df1-5268-4a37-9ac4-b3b7360bec4a/127.0.0.1:49964
> This session was closed for TimeOut!
>

**Comment by pj3743** [comment]
Thanks. I have found the problem. I override 'OnSessionClosed' method, but missed 'base.OnSessionClosed(session, reason);'

![image](https://user-images.githubusercontent.com/8121964/50501742-702e5400-0a95-11e9-86fb-97978e6f6c37.png)

**Comment by kerryjiang** [comment]
Yes, you found the problem.

I will improve the API in the next version to avoid this kind problem.
