### ISSUE TITLE
server receive data delay a long time

### ISSUE THREAD

**Issue by bighamx** [kerryjiang/SuperSocket#177]
I use EasyClient as client and  supersocker as a server. after connection done, client send data to server successfully. but after this success sent,the follow sent will be received by server for a very long time delay.
it's about 10 seconds. i use wireshark to check tcp data and find client will send a TCP WINDOW UPDATE 526000 to server.,and the data trans is normal. but server will invoke GetBodyLengthFromHeader with  delay, could anyone give me some tips?
i have deleted all config about receive buffer and send buffer from sever side code.the client side code has no config about buffer.

**Comment by chucklu** [comment]
Did you test the server with only one client?

**Comment by bighamx** [comment]
> Did you test the server with only one client?

i've found the problem. i uninstall all the network driver related software ,such as oray VPN\ hyperV \oray ddns. after reboot my pc it's all normal.
