### ISSUE TITLE
SuperSocket如何同时作为客户端和服务端？

### ISSUE THREAD

**Issue by doterme** [kerryjiang/SuperSocket#178]
我的场景：
两个使用SuperSocket开发的上位机A和B，一个PLC开发的下位机C。C会发送数据给B，B收到数据后需要转发给A。C到B我已经做好了，B如何转发收到的数据给A呢？

**Comment by chucklu** [comment]
You can just build a socket connection between Server B and Server A, then transfer the data.
You might need have a data cache on Server B and a thread to transfer the data in cache to Server A， the thread might be a timer, read the data from cache every n seconds.
The data cache could have a key for every client, when you transfer the data from Server B to Server A, you will need the key to identity the client.
