### ISSUE TITLE
服务端如何推送命令，怎么处理客户端的发送的命令和客户端回复服务端的推送命令

### ISSUE THREAD

**Issue by lhxidian** [kerryjiang/SuperSocket#179]
服务端如何推送命令，怎么处理客户端的发送的命令和客户端回复服务端的推送命令

**Comment by chucklu** [comment]
It's up to the design of your protocol.
I suggest you to use fixed header protocol.
https://github.com/kerryjiang/SuperSocket/blob/v1.6/Facility/Protocol/FixedHeaderReceiveFilter.cs
https://github.com/kerryjiang/SuperSocket/blob/v1.6/Test/Protocol/FixedHeaderProtocolTest.cs

**Comment by lhxidian** [comment]
tks
i will try
