### ISSUE TITLE
限定log4net的版本了吗？

### ISSUE THREAD

**Issue by lhxidian** [kerryjiang/SuperSocket#181]
应用程序要求的log4net的版本是：log4net.2.0.3 如果我使用：log4net.2.0.8 就会抛出异常

“System.IO.FileLoadException”类型的异常在 SuperSocket.SocketBase.dll 中发生，但未在用户代码中进行处理

其他信息: 未能加载文件或程序集“log4net, Version=1.2.13.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)

**Comment by chucklu** [comment]
Please provide a MCVE for your question
https://meta.stackoverflow.com/questions/366988/what-does-mcve-mean

How could I reproduce it on my computer? 
Did you download the dll from Nuget, then which version are you using? 
Maybe you are running the source code? then which commit you are working with?

**Comment by lhxidian** [comment]
My project use .NET Framework 4 and supersocket version is v1.6.6.1.
download the supersocket dll from Nuget.

when i download the newest log4net dll which version is v2.0.8, but the supersocket's dependency is v2.0.3. when i run the codes below and throw FileLoadException.

            IBootstrap bootstrap = BootstrapFactory.CreateBootstrap();
            if (!bootstrap.Initialize())
            {
                string info = "Socket初始化失败";
                throw new Exception(info);
            }

then i clone from https://github.com/kerryjiang/SuperSocket.git, and change the brach to v1.4 and open the SuperSocket.2013.NET40.sln with Visual Studio 2015. I found SuperSocket.SocketBase.Net40's reference log4net's version is 1.2.13.0. I change it to v2.0.8. build it.
then i can use v2.0.8 in my project.

i suggest supersocket use log4net's new  version in SuperSocket.SocketBase.Net40.

**Comment by lhxidian** [comment]
ok

**Comment by robertlagrant** [comment]
@chucklu is the 1.6 version likely to be on NuGet?

**Comment by chucklu** [comment]
https://www.nuget.org/packages/SuperSocket
@robertlagrant  Currently, the version on NuGet is 1.6.6.1, and map to commit  9beaf9b5b42129f95cbd16ae97987bd4411d0ba1 on branch v1.6
However, the latest source code on branch v1.6 is f0b85082764bb1307d9dfb9bc6bda4a38ac53c78
