### ISSUE TITLE
我有一个MesReceiveFilter : FixedHeaderReceiveFilter<BinaryRequestInfo>，怎么增加到AppServer

### ISSUE THREAD

**Issue by lhxidian** [kerryjiang/SuperSocket#182]
class MesReceiveFilter : FixedHeaderReceiveFilter<BinaryRequestInfo>
    {
        public MesReceiveFilter() : base(6)
        {
        }

        protected override int GetBodyLengthFromHeader(byte[] header, int offset, int length)
        {
            return (int)header[offset + 4] * 256 + (int)header[offset + 5];
        }

        protected override BinaryRequestInfo ResolveRequestInfo(ArraySegment<byte> header, byte[] bodyBuffer, int offset, int length)
        {
            return new BinaryRequestInfo(Encoding.UTF8.GetString(header.Array, header.Offset, 4), bodyBuffer.CloneRange(offset, length));
        }
    }

**Comment by chucklu** [comment]
Please refer to the documentation http://docs.supersocket.net/v1-6/en-US/Implement-Your-Own-Communication-Protocol-with-IRequestInfo,-IReceiveFilter-and-etc
The section **Work together with AppSession and AppServer**
