### ISSUE TITLE
Diagnosing bootstrap.Initialize() returning false

### ISSUE THREAD

**Issue by robertlagrant** [kerryjiang/SuperSocket#186]
On the latest NuGet SuperSocket (1.6.6.1). Trying this on Windows and MacOS.

I'm switching from an appserver defined purely in code to using a config file to define it. Here's the config (App.config in the config/ folder):

```xml
<?xml version="1.0"?>
<configuration>
    <configSections>
        <section name="superSocket"
                 type="SuperSocket.SocketEngine.Configuration.SocketServiceConfig, SuperSocket.SocketEngine" />
    </configSections>
    <appSettings>
        <add key="ServiceName" value="My Windows Service" />
    </appSettings>
    <superSocket>
        <servers>
            <server name="MyAppServer1"
                    serverTypeName="MyCustomAppServer"
                    ip="Any"
                    port="2012"
                    maxRequestLength="2048">
            </server>
        </servers>
        <serverTypes>
            <add name="MyCustomAppServer"
                 type="MyCustomNamespace.MyCustomAppServer, MyCustomNamespace"/>
        </serverTypes>
    </superSocket>
    <startup>
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0" />
    </startup>
</configuration>
```
I have the usual code at the top of my Main method:
```c#
IBootstrap bootstrap = BootstrapFactory.CreateBootstrap();
bool res = bootstrap.Initialize();

if (!res)
{
    Console.WriteLine("Failed to initialize!");
    Console.ReadKey();
    return;
}
```
This is printing the _Failed to initialize!_ but it's very hard to figure out why this is, as it's just a boolean returned. Is there likely to be something wrong with this config? Or somewhere else?

Update: running this on Visual Studio in Windows has an extra clue:

```Exception thrown: 'System.Configuration.ConfigurationErrorsException' in SuperSocket.SocketEngine.dll
An unhandled exception of type 'System.Configuration.ConfigurationErrorsException' occurred in SuperSocket.SocketEngine.dll
Missing 'superSocket' or 'socketServer' configuration section.
```

**Comment by chucklu** [comment]
Please upload your sample to github, you can create a new repository under your account.
Then I can clone and test it for you

**Comment by robertlagrant** [comment]
Sure! https://github.com/robertlagrant/my-socket-server

**Comment by chucklu** [comment]
@robertlagrant  Please make sure the log4net works first, then you can check the logs folder.

**Comment by chucklu** [comment]
http://docs.supersocket.net/v1-6/en-US/Logging-in-SuperSocket

> The logging system in SuperSocket
> The logging system is enabled automatically when the SuperSocket boostrap is starting, so you needn't create your own logging tool by yourself. You'd better to use the logging function in SuperSocket.
> 
> By default, the SuperSocket uses log4net as it's logging framework. So if you are familiar with log4net, it will be very easy for you to use and customize the logging function in SuperSocket.
> 
> SuperSocket also provides the basic log4net configuration files log4net.config/log4net.unix.config, you should put the log configuration file into the sub directory "Config" of the root of the running application. The log4net config define the loggers and appenders to category all logs into the 4 rolling files in the folder named "Logs":
> 
> info.log
> debug.log
> err.log
> perf.log
> You also can customize the config according your logging requirements.
> 
> Because of the loose couple with the log4net, you need to reference the file log4net.dll manually by yourself (please use the one provided by SuperSocket).

You can find the the error message in log file.

**Comment by robertlagrant** [comment]
Thanks.

That project I made is also a useful sample of how logging is broken when using the App.config way of initialising things, as it's all what comes as default when I install supersocket from nuget :-)

**Comment by chucklu** [comment]
I found you have copied the log4net.config to the Config folder of your project, but you forgot to set "Copy to Output Directory " property of that file.

**Comment by robertlagrant** [comment]
I've figured out the problem! It's the line `type="MyCustomNamespace.MyCustomAppServer, MyCustomNamespace"`in the config. The second MyCustomNamespace should actually be the assembly name, specified in the .sln file. In the example's case, it was `my-socket-server`.

Best to copy the example in https://raw.githubusercontent.com/kerryjiang/SuperSocket/v1.6/Solution%20Items/Net45/App.config, in lieu of the documentation explaining this.
