### ISSUE TITLE
Suggestions about newline

### ISSUE THREAD

**Issue by chucklu** [kerryjiang/SuperSocket#193]
Currently, I find the source on master branch, keeps using "\r\n" as a newline.
I suggest you to use [Environment.NewLine](https://docs.microsoft.com/en-us/dotnet/api/system.environment.newline?view=netcore-3.0).

Gets the newline string defined for this environment.
A string containing "\r\n" for non-Unix platforms, or a string containing "\n" for Unix platforms.

[Difference between “\n” and Environment.NewLine](
https://stackoverflow.com/questions/1015766/difference-between-n-and-environment-newline)

**Comment by chucklu** [comment]
If you would like it, I can replace "\r\n" with Environment.NewLine in source code and send you a new pull request.

**Comment by kerryjiang** [comment]
As communication protocol, the terminator should be fixed as '\r\n' or '\n'?

What if the server is linux but the client is windows?

**Comment by chucklu** [comment]
It makes sense now, newline should be platform independent.
