### ISSUE TITLE
关于传输大量数据接收过滤器的编写问题

### ISSUE THREAD

**Issue by cnxy** [kerryjiang/SuperSocket#194]
你好，

如何优雅地在继承自“IReceiveFilter<TRequestInfo>”的类中编写接收大量数据（超过缓冲区大小）的接收过滤器代码？目前，使用的是自己定义的接收缓冲区，每接收到一块字节，就存起来，直到数据完整就返回指定的已实现IReceiveFilter接口的接收过滤器。

**Comment by chucklu** [comment]
show me the code

**Comment by cnxy** [comment]
public class MessageSession : AppSession<MessageSession,MessageRequestInfo>
    {
        protected override void HandleException(Exception e)
        {
            Console.WriteLine(e.Message);
            base.HandleException(e);
        }
    }

    public class MessageServer : AppServer<MessageSession,MessageRequestInfo>
    {
        public MessageServer() : base(new MessageReceiveFilterFactory())
        { }

        protected override void OnNewSessionConnected(MessageSession session)
        {
            session.Charset = Encoding.UTF8;
            base.OnNewSessionConnected(session);
        }
    }

    public class Add : CommandBase<MessageSession, MessageRequestInfo>
    {
        public override void ExecuteCommand(MessageSession session, MessageRequestInfo requestInfo)
        {
            Console.WriteLine(requestInfo.Key);
        }
    }

    public class Minus : CommandBase<MessageSession, MessageRequestInfo>
    {
        public override void ExecuteCommand(MessageSession session, MessageRequestInfo requestInfo)
        {
            Console.WriteLine(requestInfo.Key);
        }
    }

    public class MessageReceiveFilter : ReceiveFilterBase<MessageRequestInfo>
    {
        IAppSession appSession;
        public MessageReceiveFilter(IAppSession appSession)
        {
            this.appSession = appSession;
        }

        public override MessageRequestInfo Filter(byte[] readBuffer, int offset, int length, bool toBeCopied, out int rest)
        {
            if (appSession.Items.Count == 0)
            {
                appSession.Items.Add("PreviousTime", new DateTime());
            }
            else
            {
                if ((DateTime.Now - ((DateTime)appSession.Items["PreviousTime"])).TotalMilliseconds > 3000)
                {
                    BufferPool.Clear(appSession.SessionID);
                    appSession.Items.Clear();
                }
            }

            int receiveBufferSize = appSession.Config.ReceiveBufferSize;
            rest = 0;
            byte[] buffer = readBuffer.CloneRange(offset, length);
            byte[] poolBuffer = BufferPool.Get(appSession.SessionID);

            if (poolBuffer == null)
            {
                if (length >= 4)
                {
                    int commandLength = BitConverter.ToInt32(buffer, 0);
                    if (length >= commandLength + 4)
                    {
                        string commmand = Encoding.UTF8.GetString(buffer.CloneRange(4, commandLength));

                        if (length >= commandLength + 8)
                        {
                            int parameterLength = BitConverter.ToInt32(buffer, 4 + commandLength);
                            if (length >= parameterLength + commandLength + 8)
                            {
                                string content = Encoding.UTF8.GetString(buffer.CloneRange(commandLength + 8, parameterLength));
                                if (length > parameterLength + commandLength + 8)
                                    rest = length - (parameterLength + commandLength + 8);
                                return new MessageRequestInfo(new Message { Command = commmand, Content = content });
                            }
                            else
                            {
                                if (length == receiveBufferSize)
                                {
                                    BufferPool.Update(appSession.SessionID, buffer.CloneRange(0, length));
                                    appSession.Items["PreviousTime"] =  DateTime.Now;
                                }
                            }
                        }
                    }
                }
            }
            else
            {
                int commandLength = BitConverter.ToInt32(poolBuffer, 0);
                int parameterLength = BitConverter.ToInt32(poolBuffer, 4 + commandLength);
                poolBuffer = BufferPool.Update(appSession.SessionID, buffer);
                appSession.Items["PreviousTime"] = DateTime.Now;
                if (poolBuffer.Length == commandLength+ parameterLength+8)
                {
                    poolBuffer = BufferPool.Get(appSession.SessionID);
                    string commmand = Encoding.UTF8.GetString(poolBuffer.CloneRange(4, commandLength));
                    string content = Encoding.UTF8.GetString(poolBuffer.CloneRange(commandLength + 8, parameterLength));
                    BufferPool.Clear(appSession.SessionID);
                    return new MessageRequestInfo(new Message { Command = commmand, Content = content });
                }
            }

            return null;
        }
    }

    public class MessageReceiveFilterFactory : IReceiveFilterFactory<MessageRequestInfo>
    {
        public IReceiveFilter<MessageRequestInfo> CreateFilter(IAppServer appServer, IAppSession appSession, IPEndPoint remoteEndPoint)
        {
            return new MessageReceiveFilter(appSession);
        }
    }

    public class Message
    {
        public string Command { set; get; }
        public string Content { set; get; }
    }

    public class MessageRequestInfo : RequestInfo<Message>
    {
        public MessageRequestInfo(Message message)
        {
            Initialize(message.Command, message);
        }
    }

    public class BufferPool
    {
        static ConcurrentDictionary<string, List<byte>> pool;

        static BufferPool()
        {
            pool = new ConcurrentDictionary<string, List<byte>>();
        }

        public static byte[] Update(string id,byte[] buffer)
        {
            pool.AddOrUpdate(id, new List<byte>(buffer), (x, y) =>
            {
                y.AddRange(buffer);
                return y;
            });
            return pool[id].ToArray();
        }

        public static byte[] Get(string id)
        {
            if (pool.ContainsKey(id)) return pool[id]?.ToArray();
            else return null;
        }

        public static void Clear(string id)
        {
            pool.TryRemove(id, out List<byte> value);
        }

    }

**Comment by chucklu** [comment]
You'd better use the provided protocol, I suggest you to use [FixedHeaderReceiveFilter](https://github.com/kerryjiang/SuperSocket/blob/v1.6/Facility/Protocol/FixedHeaderReceiveFilter.cs)
You can check the other protocol in
https://github.com/kerryjiang/SuperSocket/tree/v1.6/Facility/Protocol

**Comment by cnxy** [comment]
我的协议是这样子的：
**命令长度(int) + 命令名称(string,UTF8) + 内容长度(int) + 内容长度(UTF8)**，
虽然可以用`FixedHeaderReceiveFilter`，格式为：
**命令长度(int) + 内容长度(int) + 命令名称(string,UTF8) + 内容长度(UTF8)**，
前面两个长度是固定的，但想使用自己的自定义协议实现，关于大量数据传输的，有没有什么好的办法处理？

**Comment by chucklu** [comment]
You can check the sample first https://github.com/kerryjiang/SuperSocket/tree/v1.6/QuickStart/CustomProtocol
And come back here when you encounter problems.

I don't understand your question about mass data transfer. What's wrong with it?
You'd better implement a sample using FixedHeaderReceiveFilter first, then check if you need ask question here.

**Comment by cnxy** [comment]
按照你建议的使用`FixedHeaderReceiveFilter`：服务器代码如下：

    public class MessageSession : AppSession<MessageSession,MessageRequestInfo>
    {
        protected override void HandleException(Exception e)
        {
            Console.WriteLine(e.Message);
            base.HandleException(e);
        }
    }

    public class MessageServer : AppServer<MessageSession,MessageRequestInfo>
    {
        public MessageServer() : base(new MessageReceiveFilterFactory())
        { }

        protected override void OnNewSessionConnected(MessageSession session)
        {
            session.Charset = Encoding.UTF8;
            base.OnNewSessionConnected(session);
        }
    }

    public class Send8_1000Times : CommandBase<MessageSession, MessageRequestInfo>
    {
        public override void ExecuteCommand(MessageSession session, MessageRequestInfo requestInfo)
        {
            Console.WriteLine(requestInfo.Key);
        }
    }

    public class Send9_10240Times : CommandBase<MessageSession, MessageRequestInfo>
    {
        public override void ExecuteCommand(MessageSession session, MessageRequestInfo requestInfo)
        {
            Console.WriteLine(requestInfo.Key);
        }
    }

    public class MessageReceiveFilter : FixedHeaderReceiveFilter<MessageRequestInfo>
    {
        public MessageReceiveFilter() : base(8) { }
        protected override int GetBodyLengthFromHeader(byte[] header, int offset, int length)
        {
            return BitConverter.ToInt32(header, offset) + BitConverter.ToInt32(header, offset+4);
        }

        protected override MessageRequestInfo ResolveRequestInfo(ArraySegment<byte> header, byte[] bodyBuffer, int offset, int length)
        {
            byte[] headerBytes = header.ToArray();
            int commandLength = BitConverter.ToInt32(headerBytes, 0);
            int contentLength = BitConverter.ToInt32(headerBytes, 4);
            Message message = new Message
            {
                CommandLength = commandLength,
                Command = Encoding.UTF8.GetString(bodyBuffer.CloneRange(offset, commandLength)),
                ContentLength = contentLength,
                Content = Encoding.UTF8.GetString(bodyBuffer.CloneRange(offset + commandLength, contentLength))
            };
            return new MessageRequestInfo(message);
        }
    }

    public class MessageReceiveFilterFactory : IReceiveFilterFactory<MessageRequestInfo>
    {
        public IReceiveFilter<MessageRequestInfo> CreateFilter(IAppServer appServer, IAppSession appSession, IPEndPoint remoteEndPoint)
        {
            return new MessageReceiveFilter();
        }
    }

    public class Message
    {
        public int CommandLength { set; get; }
        public string Command { set; get; }
        public int ContentLength { set; get; }
        public string Content { set; get; }
    }

    public class MessageRequestInfo : RequestInfo<Message>
    {
        public MessageRequestInfo(Message message)
        {
            Initialize(message.Command, message);
        }
    }

客户端代码如下：

            Socket socket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
            socket.Connect("192.168.93.208", 3000);
            string command = "Send8_1000Times";
            byte[] contents = new byte[1000];
            for(int i=0;i<contents.Length;i++)
            {
                contents[i] = 0x38;
            }
            List<byte> list = new List<byte>();
            list.AddRange(BitConverter.GetBytes(command.Length));
            list.AddRange(BitConverter.GetBytes(contents.Length));
            list.AddRange(Encoding.UTF8.GetBytes(command));
            list.AddRange(contents);
            command = "Send9_10240";
            contents = new byte[10240];
            for (int i = 0; i < contents.Length; i++)
            {
                contents[i] = 0x39;
            }
            list.AddRange(BitConverter.GetBytes(command.Length));
            list.AddRange(BitConverter.GetBytes(contents.Length));
            list.AddRange(Encoding.UTF8.GetBytes(command));
            list.AddRange(contents);
            socket.Send(list.ToArray());
            socket.Close();

第一个`Send8_1000Times`命令类被调用了，而第二个`Send9_10240`却不会，这是怎么回事？已经更改了App.Config中的server属性`maxRequestLength`为102400000，但还是不起作用。

**Comment by chucklu** [comment]
```C#
string command = "Send8_1000Times";
command = "Send9_10240";
```
The second command did not contains Times

**Comment by cnxy** [comment]
Thanks a lot. It is my fault.

Hi, here is what I do : 
I removed `maxRequestLength` from `server` section, and I found it didn't work when I changed the length of `contents` from 1000 to 1024. Is it  associated with  `maxRequestLength`? And How to set it up?

**Comment by chucklu** [comment]
You can check the documentation [SuperSocket Basic Configuration](http://docs.supersocket.net/v1-6/en-US/SuperSocket-Basic-Configuration).

> maxRequestLength: The maximum allowed request length, default value is 1024;

It can be configured in config file or by code.


Another suggestion is, you'd better make the log works first.
When you encounter problems, please check the log first.
http://docs.supersocket.net/v1-6/en-US/Logging-in-SuperSocket

> By default, the SuperSocket uses log4net as it's logging framework. So if you are familiar with log4net, it will be very easy for you to use and customize the logging function in SuperSocket.
> 
> SuperSocket also provides the basic log4net configuration files log4net.config/log4net.unix.config, you should put the log configuration file into the sub directory "Config" of the root of the running application. The log4net config define the loggers and appenders to category all logs into the 4 rolling files in the folder named "Logs":

You can get the config file for log4net in https://github.com/kerryjiang/SuperSocket/tree/v1.6/QuickStart/Basic/TelnetServer/Config

**Comment by cnxy** [comment]
@chucklu  _Thanks._ :smiley:

**Comment by kerryjiang** [comment]
I suggest you try SuperSocket 2.0 preview. That will simplify your work a lot.
