### ISSUE TITLE
[初级认知问题] 有没有各个分支的介绍？

### ISSUE THREAD

**Issue by feipinxiang** [kerryjiang/SuperSocket#199]
NuGet上搜“SuperSocket”可以搜到下面这些列表，但有的介绍是一模一样的，有点分不清各个都是干什么的。比如“SuperSocket”和“SuperSocket.Engine”

SuperSocket
SuperSocket.Engine
SuperSocket.Facility

SuperSocket.ClientEngine
SuperSocket.ClientEngine.Core

SuperSocket.WebSocket
SuperSocket.Autofac
SuperSocket.ProtoBase

**Comment by chucklu** [comment]
The owner of the official release packages should be KerryJiang
https://www.nuget.org/profiles/kerryjiang

Only the description for the  following two packages are same.
SuperSocket
SuperSocket.Engine

Some other packages such as SuperSocket.Facility and SuperSocket.Autofac, someone else made it. You should ask the owner of it.

**Comment by feipinxiang** [comment]
> The owner of the official release packages should be KerryJiang
> https://www.nuget.org/profiles/kerryjiang
> 
> Only the description for the following two packages are same.
> SuperSocket
> SuperSocket.Engine
> 
> Some other packages such as SuperSocket.Facility and SuperSocket.Autofac, someone else made it. You should ask the owner of it.

What is the difference between SuperSocket.Engine and SuperSocket?

**Comment by chucklu** [comment]
SuperSocket.Engine contains SuperSocket, and provide the scripts which can be used to install SuperSocket as service on Windows or Linux.
You'd better try it first and ask question later.

**Comment by feipinxiang** [comment]
SuperSocket.ClientEngine 不能注册为服务吧？为什么不叫 SuperSocket.Client ？
