### ISSUE TITLE
IWorkItem接口的继承问题

### ISSUE THREAD

**Issue by chucklu** [kerryjiang/SuperSocket#20]
interface IWorkItemBase : IStatusInfoSource, ISystemEndPoint{}
interface IWorkItem : IStatusInfoSource, IWorkItemBase{}
IWorkItemBase 已经继承了IStatusInfoSource
IWorkItem 继承了IWorkItemBase的时候，不会把之前的继承关系继承过来吗?
看了类图，感觉很奇怪，形成了一个环，接口是这样用的吗？

貌似网络不好，我上传不了类图

**Comment by chucklu** [comment]
好吧，类图关系的截图，我发到你的qq上了。

**Comment by chucklu** [comment]
忘记说接口在什么位置了
\supersocket\SocketBase\IWorkItem.cs

**Comment by chucklu** [comment]
interface IWorkItem : IStatusInfoSource, IWorkItemBase{}
这个可以下面这个吧
interface IWorkItem : IWorkItemBase{}

**Comment by chucklu** [comment]
以msdn上的List<T> 为例，为了让读者方便，所以把所有接口继承的都写满了
实际的源代码中只写了2个接口public class List<T> : IList<T>, System.Collections.IList

这个问题有人专门写了文章来解释的，共享一下
http://blogs.msdn.com/b/ericlippert/archive/2011/04/04/so-many-interfaces.aspx

**Comment by kerryjiang** [comment]
Nice share
