### ISSUE TITLE
我下载源代码运行AppTest，然后连接一个tcp客户端，就报下面的错

### ISSUE THREAD

**Issue by Expre** [kerryjiang/SuperSocket#202]
The server is started.
info: SuperSocket[0]
      A new session connected: 85ed1b62-ef12-41b2-a287-d9fc64192c5f
fail: IChannel[0]
      Exception happened in ReceiveAsync
System.IO.FileLoadException: Could not load file or assembly 'System.Memory, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Memory, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at SuperSocket.Channel.PipeChannel`1.GetArrayByMemory[T](ReadOnlyMemory`1 memory)
   at SuperSocket.Channel.TcpPipeChannel`1.ReceiveAsync(Socket socket, Memory`1 memory, SocketFlags socketFlags) in D:\LandIC\SuperSocket-master\src\SuperSocket.Channel\TcpPipeChannel.cs:line 74
   at SuperSocket.Channel.TcpPipeChannel`1.FillPipeAsync(Socket socket, PipeWriter writer) in D:\LandIC\SuperSocket-master\src\SuperSocket.Channel\TcpPipeChannel.cs:line 42

fail: SuperSocket[0]
      Failed to handle the session 85ed1b62-ef12-41b2-a287-d9fc64192c5f.

**Comment by chucklu** [comment]
This master branch is under developing and unstable. If you want a stable version which can be used in your production system, please switch to branch v1.6.

**Comment by chucklu** [comment]
You'd better use git clone to get the source code, then you can fetch the latest code and merge it to local repository by git later.

**Comment by chucklu** [comment]
The source code on branch master is based on .net core 3.0 preview.
You can download the package from https://dotnet.microsoft.com/download/dotnet-core/3.0 and install it .

**Comment by Expre** [comment]
![image](https://user-images.githubusercontent.com/35752873/54823086-ba645180-4ce1-11e9-8f35-871ab1aaef07.png)
环境是3.0预览版

**Comment by Expre** [comment]
运行结果：
![image](https://user-images.githubusercontent.com/35752873/54823190-057e6480-4ce2-11e9-8838-3374c36edc04.png)
报错详情：
![image](https://user-images.githubusercontent.com/35752873/54823248-3bbbe400-4ce2-11e9-8881-4085394121f9.png)

**Comment by chucklu** [comment]
How did you build the TestApp project?
It works fine on my computer. 

You'd better clone this repository and make sure you are on latest commit of branch master.

**Comment by Expre** [comment]
好的，谢谢。我重新下载一份看看

**Comment by Expre** [comment]
> How did you build the TestApp project?
> It works fine on my computer.
> 
> You'd better clone this repository and make sure you are on latest commit of branch master.

难道是我电脑环境的问题？还是同样的错误。项目急用，暂时用socket.core代替，等有时间再来看这个问题。

**Comment by lishiming0308** [comment]
将tools文件夹下的Dependencies.props 文件中的RuntimeFrameworkVersion 改成你当前.netCore3.0的版本就可以解决这个问题。
![image](https://user-images.githubusercontent.com/25046226/56778876-1bb0a080-680b-11e9-911b-e71730239bc4.png)

**Comment by Expre** [comment]
谢谢大渔，搞定啦。



------------------ 原始邮件 ------------------
发件人: "lishiming"<notifications@github.com>; 
发送时间: 2019年4月26日(星期五) 上午10:07
收件人: "kerryjiang/SuperSocket"<SuperSocket@noreply.github.com>; 
抄送: "孙治民"<891424065@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [kerryjiang/SuperSocket] 我下载源代码运行AppTest，然后连接一个tcp客户端，就报下面的错 (#202)




将tools文件夹下的Dependencies.props 文件中的RuntimeFrameworkVersion 改成你当前.netCore3.0的版本就可以解决这个问题。

**Comment by Expre** [comment]
> 将tools文件夹下的Dependencies.props 文件中的RuntimeFrameworkVersion 改成你当前.netCore3.0的版本就可以解决这个问题。
> ![image](https://user-images.githubusercontent.com/25046226/56778876-1bb0a080-680b-11e9-911b-e71730239bc4.png)

搞定啦，谢谢

**Comment by kerryjiang** [comment]
I fixed the wrong version number.
