### ISSUE TITLE
Move SuperSocket to .NET Generic Host

### ISSUE THREAD

**Issue by robertlagrant** [kerryjiang/SuperSocket#206]
.NET will start moving more and more functionality on to its [Generic Host](https://docs.microsoft.com/en-gb/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.2) concept; this ticket is to suggest moving SuperSocket on to the same base.

This could allow the retirement of certain aspects of the SuperSocket codebase, e.g. logging configuration and other generic server duties.

**Comment by kerryjiang** [comment]
Yes, I think I should take this advice!
Thank you!

**Comment by kerryjiang** [comment]
https://github.com/kerryjiang/SuperSocket/commit/00562ce3f27e5b8c9be4cad08e0d6bc5357ca163
I am working on it right now. It is really brilliant suggestion.
Thanks!
