### ISSUE TITLE
Retrieving the current appserver from unrelated code

### ISSUE THREAD

**Issue by robertlagrant** [kerryjiang/SuperSocket#207]
I'm running a SuperSocket server and a self-hosted HTTP server from the same codebase. One thing I'd like to do is on receipt of an HTTP POST, create and send a message down the pipe of the active TCP session (the number of connected clients is constrained at the architectural level to 1).

I'm not sure how to do this. I'm currently using bootstrap configuration to create the server, and I can get the server instance out of the bootstrap object, but I seem to need to then pass the bootstrap object through each method call in my HTTP server startup code, until it reaches a place where it can reside.

This seems a bit cumbersome. Is there a way to simply look up all running app servers, and their sessions from anywhere in my codebase?

**Comment by kerryjiang** [comment]
I think you just need pass in your AppServer instance to the place where you need access the sessions.

**Comment by robertlagrant** [comment]
@kerryjiang indeed; my problem is that the HTTP server startup code is hidden behind indirection as well. Perhaps a singleton can help.
