### ISSUE TITLE
IActiveConnector.ActiveConnect for SuperSocket 2

### ISSUE THREAD

**Issue by overing** [kerryjiang/SuperSocket#208]
由于 SuperSocket 对同时大量 Socket 连线的优秀附载能力
除了伺服器他甚至被我们团队用来当作对伺服器压力测试的工具
请问 SuperSocket 2 会提供如 v1.6 的 IActiveConnector.ActiveConnect 功能吗？
以及未来对 WebSocket 的支援版本是否也能提供此功能？

**Comment by kerryjiang** [comment]
I almost forget this feature. I think it should be in SuperSocket 2.0!
