### ISSUE TITLE
ReceiveBufferSize,MaxRequestLength,SendBufferSize 问题.

### ISSUE THREAD

**Issue by qtxCoding** [kerryjiang/SuperSocket#209]
江大神,卢大神好~有个很初级的问题想问下:在config中如何配置ReceiveBufferSize,MaxRequestLength,SendBufferSize,这三个属性如何配置能达到最大性能?或者还有其他配置?
ReceiveBufferSize有没有最大值限制呢?

**Comment by qtxCoding** [comment]
MaxConnectionNumber和ReceiveBufferSize这俩之间的关系我从源码中看到了:bufferSize * AppServer.Config.MaxConnectionNumber  这样计算出来的结果的单位是什么呢?

**Comment by qtxCoding** [comment]
我怎么根据当前服务器的硬件配置来设置这几个属性呢?假如服务器有8G内存的话

**Comment by kerryjiang** [comment]
MaxRequestLength 这个设置成满足应用需求的最小值
ReceiveBufferSize/SendBufferSize 这两个根据客户端与服务器端所处的网络环境决定吧。网速快，稳定，buffer设置大一些。再根据实际测试情况调整；
MaxConnectionNumber 这个设置成满足应用需求的最小值

**Comment by qtxCoding** [comment]
江神,感谢您的回答!这个我试了试..ReceiveBufferSize设置了409600 然后MaxConnectionNumber 设置了10000,启动失败
但是设置了512000和10000,然后启动成功了,但是客户端连接不上,连上就断了........不知道是不是哪个设置或者限制我没弄好..那天群里也有人讨论这个问题.还不是很明确...

**Comment by kerryjiang** [comment]
Check logs.

**Comment by qtxCoding** [comment]
好滴江神..要学的还很多啊...谢谢指点啊!
