### ISSUE TITLE
发送超时

### ISSUE THREAD

**Issue by fangzz** [kerryjiang/SuperSocket#21]
服务器用SuperSocket,客户端使用Cocos在手机上使用wifi连接发送数据,会出现如下错误:
2015-01-14 13:25:14,179 [5896] ERROR WSGatewaySvr - Session: 8c62d585-349b-4e1a-ac06-0544ecca2421/123.123.123.123:50022
Unexpected socket error: 10060
System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

看了代码,貌似是timeout了.
不过我服务器只有一个连接发送数据也会出现这种情况.
这跟wifi环境有很大关系?
麻烦能提供查问题或解决的办法,源代码看了,不知从何下手.

**Comment by fangzz** [comment]
服务器监听参数如下,其他均默认:
{
    c.Name = name;
    c.Port = port;
    c.Ip = ip;
    c.MaxConnectionNumber = 1000;
    c.Mode = SuperSocket.SocketBase.SocketMode.Tcp;
    c.ReceiveBufferSize = 64 * 1024;
    c.SendBufferSize = 64 * 1024;
    c.SendingQueueSize = 128;
    c.SyncSend = false;
    c.Security = false;
    c.Certificate = cert;
    c.SendTimeOut = 25000; // 25s
}

**Comment by kerryjiang** [comment]
Which version are you using? I have many suggestions:
1) you client should not receive data and process the data in the same thread, receive data non-stop and put the received data into a queue. Let the business code process the received data in another thread;
2) Use TrySend than Send, if it returns false, close the connection directly;

**Comment by fangzz** [comment]
Thanks, I will try.
I use V1.5.3, but when I update to V1.6.4, client sometimes cannot receive/send data also.
But there is no timeout at server-side.

**Comment by kerryjiang** [comment]
The unstable network will cause the problem.
