### ISSUE TITLE
请问使用的 NET Core 是哪个版本的？

### ISSUE THREAD

**Issue by ProDog** [kerryjiang/SuperSocket#215]
当前 .NET SDK 不支持将 .NET Core 3.0 设置为目标。请将 .NET Core 2.2 或更低版本设置为目标，或使用支持 .NET Core 3.0 的 .NET SDK 版本。

**Comment by chucklu** [comment]
Please check this article https://www.cnblogs.com/chucklu/p/10405977.html
You could use vs 2019 or switch to use vs code

**Comment by kerryjiang** [comment]
I prefer VSCode, :)

**Comment by kerryjiang** [comment]
Right library project of SuperSocket target to .netstandard 2.1 and the executable project target to .netcoreapp3.0.
