### ISSUE TITLE
1.6日志问题

### ISSUE THREAD

**Issue by JHeLiu** [kerryjiang/SuperSocket#220]
哦，问下，1.6X版本 我必须要使用Log4 库嘛？ 我不太想使用它。我找到更好的 NLog代替它。
这个库是否允许自己重写日志这一块，
我觉得日志这一块应该可以让使用者更灵活的选择日志库，不知道这样行不行的同

**Comment by chucklu** [comment]
Please refer to http://docs.supersocket.net/v1-6/en-US/Logging-in-SuperSocket
The section "Use other logging framework than log4net"

**Comment by kerryjiang** [comment]
Probably you don't have a good way to do it for now. But it is easy for SuperSocket 2.0.

![image](https://user-images.githubusercontent.com/456060/58267729-0dd23a80-7d39-11e9-803a-55d7722d5197.png)
