### ISSUE TITLE
你好，异常情况突然收不到消息问题

### ISSUE THREAD

**Issue by dingjianwan** [kerryjiang/SuperSocket#223]
你好，我用supersocket做server接收plc的消息。正常情况下，要求他们心跳和交互信息分开发，但是偶尔他们一起发，然后就收不到消息了，断开重新连接收得到。
我自己写个tcp server begin receive 也收不到消息，没有异常（参考这篇博文写的https://www.cnblogs.com/chenxizhang/archive/2011/09/10/2172994.html）。 
但是我用网络调试助手却可以收到。

我想问问.net tcp有没有什么要注意的。哪些情况会导致收不到消息。您是tcp通信的专家就来这里题问了，谢谢。

**Comment by kerryjiang** [comment]
请问你指的心跳是指什么？

**Comment by dingjianwan** [comment]
> 请问你指的心跳是指什么？

就是一串无意义的信号，用来保持连接的。

**Comment by dingjianwan** [comment]
> > 请问你指的心跳是指什么？
> 
> 就是一串无意义的信号，用来保持连接的。

有时候是设备的状态信息，我之前和一个电梯对接，他需要定频率把门的状态发给我，我这边根据业务给它指令让他开门或者关门，需要他这边接收到请求指令时原样返回，这样我就停止发请求，然后监听它的状态信息。   问题就在于这里，他返回确认信号和状态信号一起过来，几乎同一毫秒，我这边就收不到了。但是我用网络调试助手监听，交互过程都是正常。

**Comment by dingjianwan** [comment]
> > > 请问你指的心跳是指什么？
> > 
> > 
> > 就是一串无意义的信号，用来保持连接的。
> 
> 有时候是设备的状态信息，我之前和一个电梯对接，他需要定频率把门的状态发给我，我这边根据业务给它指令让他开门或者关门，需要他这边接收到请求指令时原样返回，这样我就停止发请求，然后监听它的状态信息。 问题就在于这里，他返回确认信号和状态信号一起过来，几乎同一毫秒，我这边就收不到了。但是我用网络调试助手监听，交互过程都是正常。

而且是后面这个链接的全部消息都收不到了。

**Comment by kerryjiang** [comment]
如果是指应用层心跳，那心跳的消息包也应和其它类型的包一样遵循你应用层的通信协议。

**Comment by dingjianwan** [comment]
> 如果是指应用层心跳，那心跳的消息包也应和其它类型的包一样遵循你应用层的通信协议。

协议是一样的，我的意思是plc那边两条消息同一毫秒过来，就收不到了，好像哪里堵塞了，后面也收不到消息（用tcp server 监听也没有），但是网络调试助手一直都能收到。

**Comment by kerryjiang** [comment]
TCP是串行的，同时发送也一定会有先后，请检查你们的协议解析实现。

**Comment by dingjianwan** [comment]
> TCP是串行的，同时发送也一定会有先后，请检查你们的协议解析实现。

好的，谢谢了。

**Comment by shizhengzl** [comment]
楼主找到问题了吗？
