### ISSUE TITLE
走TCP时，client的端口一直变化。

### ISSUE THREAD

**Issue by chimisu** [kerryjiang/SuperSocket#225]
如题，用网络助手观察，client连过来的端口不会变化，但是用supersocket就会变化，想知道下解决方案。谢谢。

**Comment by chucklu** [comment]
It's correct that the client port automatically changed.

If you want to bind the port for the client, you can refer to https://stackoverflow.com/questions/38427835/connect-tcpclient-to-a-remote-tcp-server-binding-to-a-specific-local-port
However, it's not suggested. What would you do if the port was occupied?

**Comment by doterme** [comment]
@chucklu 我用supersocket是作为一个TCP Server来用，client连过来之后，我想通过这个连接的session发送数据给client，监测到remoteEndPoint的端口一直在变化，但是用网络助手监测，端口就不会变化，除非client断开跟TCP Server的连接，否则这个通信因该使用同一个socket。

**Comment by kerryjiang** [comment]
在连接/Session的生命周期内，连接的RemoteEndPoint是不会变化的。不知你从何得知它是会变化的。

**Comment by chucklu** [comment]
@doterme  The client port will not change in one session life scope.

**Comment by doterme** [comment]
@kerryjiang 大佬，我订阅的是NewRequestReceived事件，这个事件拿到的Session中的RemoteEndPoint中的端口在变化。我也不知道什么原因。我是自定义的Session，继承自AppSession。自定义的RequestInfo继承自RequestInfo。自定义的ReceiveFileter，继承自BeginEndMarkReceiveFilte。自定义的FilterFactory，实现IReceiveFilterFactory。

**Comment by kerryjiang** [comment]
Could you show your client code?

**Comment by doterme** [comment]
client代码是别人写的，用c写的，嵌入式设备。我现在只能通过网络助手监测到端口不变化。实际我在用的过程中发现，session连接和session断开事件一直在循环执行。

**Comment by kerryjiang** [comment]
可能的原因是，协议解析出错，连接断开，然后客户端重复连接。
请检查log或者debug查看是否协议解析出错。

**Comment by doterme** [comment]
协议应该是解析正常的，我能解析到我要的数据。还有其他原因吗？

**Comment by kerryjiang** [comment]
看log，寻找连接关闭原因。
