### ISSUE TITLE
Configuring Supersocket in code using Setup does not work

### ISSUE THREAD

**Issue by sreejith-mq** [kerryjiang/SuperSocket#23]
I subclassed `WebSocketServer<WebSocketSession>`.  Trying to configure the server using

`this.Setup(new RootConfig(), new ServerConfig() { MaxRequestLength = 4096 , Port=8000});`

does not work.  `this.Config` is null and the server throws an error when calling the `Start()` function.

**Comment by sreejith-mq** [comment]
I got round this problem by not subclassing `WebSocketServer` and using it as a mix in.  Then the following works

```
WebSocketServer<WebSocketSession> server = new WebSocketServer();
server.Setup(new RootConfig(), new ServerConfig() { Port=9000, MaxRequestLength=4096});
```

**Comment by kerryjiang** [comment]
Did you check the log or exception details.

Sent from my Windows Phone
________________________________

**Comment by sreejith-mq** [comment]
There was not exception.  Call to `Setup()` returned `true`.  But when I tried starting the server, I got an error which said that server cannot be started before configuring.
As I commented above, I got around this by avoiding sub-classing and using a `WebSocketSever` object in my class

**Comment by kerryjiang** [comment]
Get the log working and then check detail error in the log.
