### ISSUE TITLE
2.0版本是用的VS多少？

### ISSUE THREAD

**Issue by DamonDBT** [kerryjiang/SuperSocket#230]
我用VS2015打不开，能给一个2015的sln吗，谢谢。

**Comment by chucklu** [comment]
The source code of 2.0 is based on .net core 3.0 preview currently.
It's not possible open it by vs 2015, so there is no solution file for vs 2015.  

https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x#prerequisites-for-net-core-30-preview-3
> Prerequisites for .NET Core 3.0 Preview 3
> 
> .NET Core 3.0 Preview 3 has the same prerequisites as other versions of .NET Core. However, if you want to use Visual Studio to create .NET Core 3.0 projects, you must use the Visual Studio 2019. Visual Studio 2019 can be installed side-by-side with other versions of Visual Studio without conflict.

You could try with[ vs code](https://code.visualstudio.com/) or [vs 2019](https://visualstudio.microsoft.com/vs/).

**Comment by ishowfun** [comment]
9012年了，就别用VS2015了，用VS2019

**Comment by kerryjiang** [comment]
I prefer Visual Studio Code.
