### ISSUE TITLE
http://docs.supersocket.net   无法访问

### ISSUE THREAD

**Issue by loveyeguo** [kerryjiang/SuperSocket#231]

**Comment by chucklu** [comment]
You'd better send an email to @kerryjiang  directly, you can get the email address from https://github.com/kerryjiang

**Comment by chucklu** [comment]
There is a repository for the documentation
https://github.com/kerryjiang/SuperSocket.Document/tree/v1.6
https://github.com/kerryjiang/SuperSocket.Document/tree/v1.6(zh-CN)

**Comment by ashyEmmm** [comment]
2019.7.26依旧无法访问
