### ISSUE TITLE
關於在 CommandBase 中想執行 AppServer 中的 delegate callback

### ISSUE THREAD

**Issue by getoutnow2013** [kerryjiang/SuperSocket#236]
SuperSocket Server 接收到內容後，交給 CommandBase 進行 ExecuteCommand
若在這個 ExecuteCommand 之中，若想呼叫 Server 上的 delegate function 時，將 Information 傳送到 AppServer  之外，要如何進行？

舉例來說：
1. AppServer 有 OnAddCommand delegate function
2. AppServer 有 Class Add : CommandBase<AppSession, StringRequestInfo>
3. 如何在 Add Class 中，將內容透過 OnAddCommand delegate 傳遞出去？

目前只有想到用 AppServer.NewRequestReceived 來處理
但是這個缺點就是要利用 switch ，並且把 Command 的處理行為寫在這裡。

請問有更好的方式嗎？

**Comment by kerryjiang** [comment]
You can access AppServer through AppSession.
