### ISSUE TITLE
Initialize MyAppSession - How to connect to MyAppServer?

### ISSUE THREAD

**Issue by Boeckle** [kerryjiang/SuperSocket#237]
I try to set up a server-client connection. Till now I used AsynTcpSession as clients but I want to connect an MyAppSession to MyAppServer, but I don't know how to initialize the session:
```
public virtual void Initialize(IAppServer<TAppSession, TRequestInfo> appServer, ISocketSession socketSession)
{
}
```

The sessions know the ip and port from the server. I used the example from [the documentation](http://docs.supersocket.net/v1-6/en-US/Implement-your-AppServer-and-AppSession).

Thanks in advance!

**Comment by kerryjiang** [comment]
Just overwrite it, and it will be executed automatically.

**Comment by Boeckle** [comment]
I don't think I explained my problem properly. 
I don't know which parameters to pass to the function: appServer and socketSession.
Is the socketSession the own session? (The create MyAppSession, which I try to connect?)
And for the appServer do I need to set up a new MyAppServer in the MyAppSession-part?

Thanks for the reply!

**Comment by chucklu** [comment]
Please check the [demo](https://github.com/kerryjiang/SuperSocket/blob/v1.6/QuickStart/Basic/TelnetServer_AppSession/TelnetSession.cs) here, you don't need to implement Initialize method. It's virtual method not abstract.

**Comment by Boeckle** [comment]
But how do I call the Initialize method from a session?

`public virtual void Initialize(IAppServer<TAppSession, TRequestInfo> appServer, ISocketSession socketSession)
    {}`

The session doesn't know the `appServer`-properties, how should I call the Initialize methode?

**Comment by kerryjiang** [comment]
It is automatically. You don't need write any code to call it.

**Comment by Boeckle** [comment]
Well, I think I don't use the `RequestInfo` properly to pass parameters to the server.

I tried to have some additionally parameters in `MyAppSession`-class...
