### ISSUE TITLE
Client無法得知是否已連上Server

### ISSUE THREAD

**Issue by zongu** [kerryjiang/SuperSocket#239]
專案版本: .Net Framework 4.6.1
Server: SuperSocket實作
Client: WebSocket4Net實作

Server我參考[SuperSocket](http://docs.supersocket.net/v1-6/zh-CN/Implement-your-AppServer-and-AppSession)實作，並自定義協議ReceiveFilter繼承FixedHeaderReceiveFilter；問題發生於當Client連上Server後，Server有收到該Client的連線並建立出Session連線，但Client卻沒觸發Opened事件，我查了其他人的做法似乎都沒有跟我類似的情況，所以在這邊提出

附上我[Git專案](https://github.com/zongu/SuperSocket)

**Comment by chucklu** [comment]
Where is your client code?  You can try with https://github.com/kerryjiang/SuperSocket.ClientEngine
```C#
// Connect to the server
var connected = await client.ConnectAsync(new IPEndPoint(IPAddress.Parse("192.168.10.11"), 25));

if (connected)
{
	// Send data to the server
	client.Send(Encoding.ASCII.GetBytes("LOGIN kerry"));
}
```

**Comment by zongu** [comment]
> Where is your client code? You can try with https://github.com/kerryjiang/SuperSocket.ClientEngine
> 
> ```cs
> // Connect to the server
> var connected = await client.ConnectAsync(new IPEndPoint(IPAddress.Parse("192.168.10.11"), 25));
> 
> if (connected)
> {
> 	// Send data to the server
> 	client.Send(Encoding.ASCII.GetBytes("LOGIN kerry"));
> }
> ```

Thank you for your reply, [here](https://github.com/zongu/SuperSocket/blob/master/SuperSocket/Compoment/ClientProcessCompoment.cs) is my client code.
I will try your solution

**Comment by chucklu** [comment]
I did not have enough time to review your code, you'd better use the official client implementation.
I have an advice for you, do not name class start with `I`, it's the name convention for interface.

**Comment by zongu** [comment]
Ok, I will check my code. Thanks
