### ISSUE TITLE
2.0版本 服务端如何主动踢掉连接？

### ISSUE THREAD

**Issue by XuLinFei** [kerryjiang/SuperSocket#242]
2.0版本 服务端如何主动踢掉连接？

**Comment by chucklu** [comment]
https://github.com/kerryjiang/SuperSocket/blob/master/src/SuperSocket.Channel/ChannelBase.cs#L42

**Comment by XuLinFei** [comment]
> https://github.com/kerryjiang/SuperSocket/blob/master/src/SuperSocket.Channel/ChannelBase.cs#L42

如何访问到这个属性 我在session里访问不到这个channel

**Comment by chucklu** [comment]
https://github.com/kerryjiang/SuperSocket/blob/master/src/SuperSocket.Server/AppSession.cs#L28

@kerryjiang  Maybe you can provide a close method in AppSession?

**Comment by XuLinFei** [comment]
> https://github.com/kerryjiang/SuperSocket/blob/master/src/SuperSocket.Server/AppSession.cs#L28
> 
> @kerryjiang Maybe you can provide a close method in AppSession?

I have customized a class that inherits AppSession, but this property (IAppSession. Channel) is not public. I can't access it in subclasses. I wonder if I can implement it without modifying the framework source code. After all, I want to follow the version, and I don't want to change the source code.

**Comment by XuLinFei** [comment]
Can we solve this problem only through the interface provided by the framework instead of modifying the framework source code?

**Comment by chucklu** [comment]
You need learn some advanced knowledge in C#.
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation
Do not use session variable with `AppSession`, you can try session variable with type `IAppSession`.

**Comment by XuLinFei** [comment]
Do you mean to implement IAppSession directly instead of inheriting AppSession?

**Comment by chucklu** [comment]
It seems that you have poor knowledge about inheritance and interface. 
https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/inheritance
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/

What I am talking about is
```C#
 IAppSession session = new CustomAPPSession();
 session.Channel.Close();
```

**Comment by XuLinFei** [comment]
o~ thanks

**Comment by chucklu** [comment]
The above knowledge I mentioned is the basic knowledge for a junior developer, you'd better master them before you writing code as a programmer.

**Comment by XuLinFei** [comment]
OK~
