### ISSUE TITLE
Many server configurations can not be found in 2.0. Where can I set them up?

### ISSUE THREAD

**Issue by XuLinFei** [kerryjiang/SuperSocket#243]
Similar to configuration
<server name="OnlineServer" serverTypeName="OnlineServer" ip="Any" port="1121" maxConnectionNumber="200" clearIdleSession="true" maxRequestLength="10485760" receiveBufferSize="10485760" clearIdleSessionInterval="120" idleSessionTimeOut="300" keepAliveTime="600" keepAliveInterval="60" logAllSocketException="true" autoStartAfterUnexpectedShutdown="true">

**Comment by XuLinFei** [comment]
<server name="OnlineServer" serverTypeName="OnlineServer" ip="Any" port="1121" maxConnectionNumber="200" clearIdleSession="true" maxRequestLength="10485760" receiveBufferSize="10485760" clearIdleSessionInterval="120" idleSessionTimeOut="300" keepAliveTime="600" keepAliveInterval="60" logAllSocketException="true" autoStartAfterUnexpectedShutdown="true">

**Comment by XuLinFei** [comment]
serverTypeName="OnlineServer" ip="Any" port="1121" maxConnectionNumber="200" clearIdleSession="true" maxRequestLength="10485760" receiveBufferSize="10485760" clearIdleSessionInterval="120" idleSessionTimeOut="300" keepAliveTime="600" keepAliveInterval="60" logAllSocketException="true" autoStartAfterUnexpectedShutdown="true"

**Comment by kerryjiang** [comment]
Yes, it is still in preview. Not ready for production yet.

**Comment by kerryjiang** [comment]
We still miss the options for clearIdleSession and keepAlive.

**Comment by kerryjiang** [comment]
Take a look at this doc,
https://docs.supersocket.net/v2-0/en-US/Start-SuperSocket-by-Configuration
