### ISSUE TITLE
发起TCP数据超过1024字节，连接就自动断开了，设置了缓存区大小好像还是没有效果。

### ISSUE THREAD

**Issue by KangLeo** [kerryjiang/SuperSocket#245]
服务端程序是这么设置的
 var serverConfig = new ServerConfig()
            {
                Port = _receivePort,
                MaxConnectionNumber = 10000,
                ClearIdleSession = true,
                IdleSessionTimeOut = 200,
                LogAllSocketException = true,
                ReceiveBufferSize = 40 * 1024,
                SendBufferSize = 40 * 1024,
                SendingQueueSize = 40 * 1024
            };

**Comment by KangLeo** [comment]
serverConfig还需要设置MaxRequestLength的大小，默认是1024

**Comment by chucklu** [comment]
For troubleshooting, you 'd better enable log first http://docs.supersocket.net/v1-6/en-US/Logging-in-SuperSocket. When you encounter problem, check log file first.
