### ISSUE TITLE
最新的代码对Package的处理似乎有问题

### ISSUE THREAD

**Issue by chukaif** [kerryjiang/SuperSocket#246]
因为作者没有在nuget上更新最新版本，我直接将最近代码放到项目里面去跑了，但是程序只会处理第一批接收到的数据包，处理完成后，后续接收的数据不会处理。
我监控了断点之后发现在PipeChannel类中的ProcessPackages方法只会处理第一批数据，后续不会再进入ProcessPackages方法。
不知道是supersocket尚未完善还是我的做法有问题？

**Comment by kerryjiang** [comment]
It is still in preview. Please don’t use it for production for now. There will be more changes coming on these days.

**Comment by chukaif** [comment]
OK, I  see, Thanks!
