### ISSUE TITLE
Disable Nagle's algorithm (NoDelay) in WebSocketServer v1.6

### ISSUE THREAD

**Issue by darxis** [kerryjiang/SuperSocket#247]
How to disable Nagle's algorithm (`NoDelay`) in `WebSocketServer` v1.6? I can't find this option in `ServerConfig`

**Comment by chucklu** [comment]
Did you mean this? 
https://github.com/kerryjiang/SuperSocket/blob/v1.6/SocketEngine/TcpSocketServerBase.cs#L60

**Comment by darxis** [comment]
I can't find how `TcpSocketServerBase` is related to the `WebSocketServer` but I think you are right, `NoDelay` is set to `true` for each socket.
