### ISSUE TITLE
WebSocketServer slow performance compared to NetGain WebSocketServer v1.6

### ISSUE THREAD

**Issue by darxis** [kerryjiang/SuperSocket#248]
I am using the v1.6 `SuperSocket.WebSocket.WebSocketServer` server and I am experiencing random slow performance.
At random times all clients are receiving delayed messages and the delay is increasing in time, until it achieve 15 seconds delay and my client logic disconnects when this delay is achieved.

I am trying to figure out why this happens and I have written a simple test scenario including an echo WebSocketServer and a client, that sends messages and wait the echo response in a loop.

I have compared the performance of `SuperSocket.WebSocket.WebSocketServer` and the `NetGain` (https://github.com/StackExchange/NetGain) WebSocketServer, and it appears that the `NetGain` server is performing 2x times better, I mean that it have processed 2x more echo messages that the `SuperSocket.WebSocket.WebSocketServer`.

**Comment by chucklu** [comment]
WebSocketServer ?
I did not find this class in https://github.com/kerryjiang/SuperSocket/tree/v1.6.
I can only find https://github.com/kerryjiang/SuperSocket/tree/master/src/SuperSocket.WebSocket.Server
However the master branch is for SuperSocket 2.0.

Or maybe you are talking about [WebSocketServer](https://github.com/kerryjiang/SuperWebSocket/blob/master/SuperWebSocket/WebSocketServer.cs) in another repository.
I read https://github.com/kerryjiang/SuperWebSocket/blob/master/README.md

> SuperWebSocket is being merged into SuperSocket as an additional module SuperSocket.WebSocket. You can use SuperSocket.WebSocket in the same way with SuperWebSocket but with a different namespace.

Not sure why I can not find WebSocketServer on branch v1.6 . @kerryjiang

**Comment by chucklu** [comment]
If you are using SuperSocket v1.6, you could configure the [log component](Logging in SuperSocket) first.
Then you can check the generated perf.log(you could search this file by [everything](https://www.voidtools.com/)).
You will get something like this:

> 2019-06-06 18:44:43,169 Performance - ---------------------------------------------------
> CPU Usage: 0.00%, Physical Memory Usage: 62,345,216.00, Total Thread Count: 27
> AvailableWorkingThreads: 2046, AvailableCompletionPortThreads: 1000
> MaxWorkingThreads: 2047, MaxCompletionPortThreads: 1000
> YourAppServer ----------------------------------
> Started Time: 6/6/2019 6:44:43 PM
> Is Running: True
> Total Connections: 0
> Maximum Allowed Connection Number: 3000
> Total Handled Requests: 0
> Request Handling Speed (#/second): 0
> Avialable Sending Queue Items: 500
> Total Sending Queue Items: 500
> 
> 2019-06-06 18:45:43,173 Performance - ---------------------------------------------------
> CPU Usage: 0.04%, Physical Memory Usage: 64,589,824.00, Total Thread Count: 27
> AvailableWorkingThreads: 2044, AvailableCompletionPortThreads: 1000
> MaxWorkingThreads: 2047, MaxCompletionPortThreads: 1000
> YourAppServer ----------------------------------
> Started Time: 6/6/2019 6:44:43 PM
> Is Running: True
> Total Connections: 0
> Maximum Allowed Connection Number: 3000
> Total Handled Requests: 0
> Request Handling Speed (#/second): 0
> Avialable Sending Queue Items: 500
> Total Sending Queue Items: 500

**Comment by darxis** [comment]
@chucklu Thanks for this logging tip, I will surely use it in the near future! Its nice that the Request Handling Speed is logged.

Coming back to my issur, I have found why it is slower. NetGain server does not support WSS protocol and I was comparing its performance to WebSocketServer with WSS enabled. It turned out that using secured WSS vs. using unsecured WS is more than 2 times slower...

**Comment by chucklu** [comment]
I did not find the webscoketserver through solution, from your pr, I find it https://github.com/kerryjiang/SuperSocket/pull/250/files.
And I can search it with everything on my local computer.
![image](https://user-images.githubusercontent.com/3004057/65810092-6d08f580-e1d8-11e9-9f43-4c60f038ecc2.png)
