### ISSUE TITLE
v1.6分支下的QuickStart下的BroadcastService逻辑问题

### ISSUE THREAD

**Issue by chucklu** [kerryjiang/SuperSocket#25]
private Dictionary<string, List<string>> broadcastDict = new Dictionary<string, List<string>>(StringComparer.OrdinalIgnoreCase);
 public BroadcastServer()
        {
            lock (broadcastSyncRoot)
            {
                //It means that device V001 will receive broadcast messages from C001 and C002,
                //device V002  will receive broadcast messages from C002 and C003
                broadcastDict["C001"] = new List<string> { "V001" };
                broadcastDict["C002"] = new List<string> { "V001", "V002" };
                broadcastDict["C003"] = new List<string> { "V002" };
            }
        }
internal void BroadcastMessage(BroadcastSession session, string message)
{
  lock (broadcastSyncRoot)
            {
                if(!broadcastDict.TryGetValue(session.DeviceNumber, out targetDeviceNumbers))
                    return;
            }
}
上面这段代码，broadcastDict存放的是CXXX,以及将要发送给消息的设备集合。
然后broadcastDict.TryGetValue(session.DeviceNumber, out targetDeviceNumbers)这个获取判断是把设备号码作为key传递进去的。这样操作的话，targetDeviceNumbers恒等于null了。

不过，我尝试把C001作为设备号码来进行传递的时候，就可以。不过这样的话，逻辑上就是有问题的了。

**Comment by kerryjiang** [comment]
targetDeviceNumbers恒等于null? 是啥意思？

**Comment by chucklu** [comment]
正常来说，注册新的会话，是用RegisterNewSession函数的吧
 internal void RegisterNewSession(BroadcastSession session)
        {
            if (string.IsNullOrEmpty(session.DeviceNumber))
                return;

            lock (syncRoot)
            {
                broadcastSessionDict[session.DeviceNumber] = session;
            }
        }
这个函数是用session.DeviceNumber作为broadcastSessionDict的Key的吧。

但是后面取值的时候，是从broadcastDict取的，这个的key是c001,c002,c003;
所以从broadcastDict取key为V001,V002的话，返回的value不都是null吗？


ps:C001这个应该不是用来注册会话的吧？这个就是程序里面默认的吧

**Comment by chucklu** [comment]
最后总结，
if(!broadcastDict.TryGetValue(session.DeviceNumber, out targetDeviceNumbers))
return;
就是这个函数的执行，每次都会return的。
因为broadcastDict的key不是DeviceNumber，是C001这种，【C001是Channel吗？】

**Comment by kerryjiang** [comment]
broadcastDict["C001"] = new List { "V001" };
broadcastDict["C002"] = new List { "V001", "V002" };
broadcastDict["C003"] = new List { "V002" };

不太懂你的意思，你用“C001”作为Key去取值，你会取不到？

**Comment by chucklu** [comment]
取值的时候，不是用session.DeviceNumber去取值的吗？
RegisterNewSession的时候不是用设备号去注册的吗？
 lock (broadcastSyncRoot)
            {
                //It means that device V001 will receive broadcast messages from C001 and C002,
                //device V002  will receive broadcast messages from C002 and C003
                broadcastDict["C001"] = new List<string> { "V001" };
                broadcastDict["C002"] = new List<string> { "V001", "V002" };
                broadcastDict["C003"] = new List<string> { "V002" };
            }
按照你的注释的话，只有V开头的才是设备号吧？
conn命令，不是只能注册V开头的吗？逻辑上的话

难不成C001这种也是设备号？用conn 注册C001?

**Comment by kerryjiang** [comment]
session.DeviceNumber 不是你自己设的吗？那是你自己的逻辑。
示例项目仅仅提示你类似的需求如何解决。

**Comment by chucklu** [comment]
按照代码示例的话，C开头的V开头的是不一样吧

**Comment by kerryjiang** [comment]
你管他一样不一样干嘛？
C001, C002, V001, V002 都是设备号，可为一种或多种不同的设备。
本示例展示如何使用SuperSocket做消息转发，仅此而已。

**Comment by chucklu** [comment]
我又仔细看了下，CXXX和VXXX都可以注册，但是只有CXXX可以对外广播，CXXX存储在broadcastDict的Key里面。目前只有三个，没有动态加的
而广播的对象存储在broadcastDict的Value里面

**Comment by kerryjiang** [comment]
示例项目仅仅提示你类似的需求如何解决，仅仅起示例作用, 不是能够支持现实应用的程序！
基本逻辑看明白就行了！
