### ISSUE TITLE
1.6版本BeginEndMarkReceiveFilter过滤器问题

### ISSUE THREAD

**Issue by yedajiang44** [kerryjiang/SuperSocket#251]
假如一个完整的包数据是：a123456879a
第一次发送a12345，第二次发送6789a
如何在用BeginEndMarkReceiveFilter时将这两次数据作为一个数据包处理？
我在Filter中返回NullRequestInfo第二次的时候readBuffer里就没有第一次发的数据了
想知道如何使第二次进Filter方法时第一次发送的数据也在readBuffer里？？？

**Comment by kerryjiang** [comment]
What are your begin and end mark?

**Comment by yedajiang44** [comment]
看了下源码其实`BeginEndMarkReceiveFilter`已经处理了
只要是第一次接收的数据是起始字符就行，如果第一次接收的不是起始字符就直接设置过滤器的`State`为`FilterState.Error`

还有就是`wireshark`抓包的时候发现很多时候出现一条数据被分成两次接收到，不知道是不是抓包工具问题
由于我用`SwitchReceiveFilter`实现多个`IReceiveFilter`来回切换
而且有多个`IReceiveFilter`都是起止字符不同的`BeginEndMarkReceiveFilter`
所以我丢包的原因不知道是因为过滤器切换问题还是`Filter`问题
