### ISSUE TITLE
supersocket.net doesn't support TLS

### ISSUE THREAD

**Issue by dylanh724** [kerryjiang/SuperSocket#253]
While not technically a direct issue, is it just me thinking that a WebSocket repo's main site doesn't have TLS is a bit funny? I'd arguably call this an issue that should be resolved by the host.

**Comment by kerryjiang** [comment]
:) Just because I don't want to spend time on getting a SSL certificate from somewhere (I am too lazy...).

**Comment by robertlagrant** [comment]
@kerryjiang I think if you use Cloudflare they can do your SSL for you, all for free.

**Comment by kerryjiang** [comment]
Get it done just now.
https://www.supersocket.net/

**Comment by kerryjiang** [comment]
Add http to https redirection soon...

**Comment by kerryjiang** [comment]
Https redirection has been setup.
