### ISSUE TITLE
PipeChannel.ProcessPackages()循环

### ISSUE THREAD

**Issue by yedajiang44** [kerryjiang/SuperSocket#254]
https://github.com/kerryjiang/SuperSocket/blob/ce4c16b0b4680d16459d1ddd4341b1c2d709b1d9/src/SuperSocket.Channel/PipeChannel.cs#L75

在过滤器收到一条包后，debug后发现这里似乎一直不为null，导致多次回调，我是直接启动示例中的EchoServer，当我发送1回车后，终端不停的接受到服务器发送的数据1

**Comment by kerryjiang** [comment]
Fixed it just now, could you have one more try?

**Comment by yedajiang44** [comment]
nice！it's fixed!
