### ISSUE TITLE
1.6.6 FixedHeaderReceiveFilter implement IReceiveFilterInitializer causes an exception

### ISSUE THREAD

**Issue by yedajiang44** [kerryjiang/SuperSocket#255]
我没看具体代码，也没查找具体原因，相同的代码，只要实现IReceiveFilterInitializer就会出现解析异常

**Comment by kerryjiang** [comment]
你有办法绕过去吗？我原则上不再维护1.6版本了。

**Comment by yedajiang44** [comment]
> 你有办法绕过去吗？我原则上不再维护1.6版本了。

唯一的办法就是不实现`IReceiveFilterInitializer`或者重新定义一个接口实现，`Session`初始化的时候调用这个接口

**Comment by kerryjiang** [comment]
Does this fix work for you?

`
void IReceiveFilterInitializer.Initialize(IAppServer appServer, IAppSession session)
        {
            Initialize(appServer, session);
        }
        
        protected void Initialize(IAppServer appServer, IAppSession session)
        {
            m_OrigOffset = session.SocketSession.OrigReceiveOffset;
        }`

**Comment by kerryjiang** [comment]
那子类怎么重设m_OrigOffset？

**Comment by yedajiang44** [comment]
> 那子类怎么重设m_OrigOffset？
字类不需要重设`m_OrigOffset`了，重写`Initialize`只是为了拿到`appServer`和`session`，所以不需要关心父类`m_OrigOffset`

**Comment by yedajiang44** [comment]
会的，因为在AppSession里显式调用了`IReceiveFilterInitializer.Initialize`了
https://github.com/kerryjiang/SuperSocket/blob/f0b85082764bb1307d9dfb9bc6bda4a38ac53c78/SocketBase/AppSession.cs#L195
所以`m_OrigOffset`肯定是会被赋值的

**Comment by kerryjiang** [comment]
但是在使用了SwitchReceiveFilter的情况下呢？

**Comment by yedajiang44** [comment]
> 但是在使用了SwitchReceiveFilter的情况下呢？


这个时候就需要实现`IReceiveFilterInitializer`了，然后手动调用`IReceiveFilterInitializer.Initialize`，这也是我目前的解决方案

**Comment by kerryjiang** [comment]
不准备再发布1.6.*的nuget包了。如果你无法自己绕过去，那就直接修改源代码，然后使用你自己编译的版本。
