### ISSUE TITLE
希望在 nuget 发布一下 预览版2

### ISSUE THREAD

**Issue by HaoZhiYing** [kerryjiang/SuperSocket#256]
希望在 nuget 发布一下 预览版2

**Comment by kerryjiang** [comment]
正在修复一些，bug。再等websocket初步成型之后就发布第二个预览版。

Yes, I am fixing some quality issues. And 2.0 preview 2 will be shipped soon after websocket can generally work.

**Comment by kerryjiang** [comment]
Released:
https://www.nuget.org/packages/SuperSocket.Server/2.0.0-preview2-00
