### ISSUE TITLE
2.0 数据接收不到

### ISSUE THREAD

**Issue by XuLinFei** [kerryjiang/SuperSocket#259]
我们现在用2.0作为服务接收硬件数据，但是出现了，一开始几个通信时正常的，后面就一直接收不到数据，断开重连后又可以了。自定义的过滤器协议如下：
public class CollectReceiveFilter : TerminatorPipelineFilter<BytesPackageInfo>
    {

        public CollectReceiveFilter()
            : base(new byte[] { 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF})
        {

        }
        protected override BytesPackageInfo DecodePackage(ReadOnlySequence<byte> buffer)
        {
            var data = buffer.ToArray();
            int offset = 0;
            CollectHead _CollectHead = default;
            string Key = "G" + GetHeader(data, offset + 1, 2);
            CollectServer.Instinstance.Logger.LogWarning(Key);
            try
            {
                _CollectHead = new CollectHead(data.CloneRange(offset, 50));
                byte[] _Body = data.CloneRange(offset + 50, _CollectHead.BodyLength);
                BytesPackageInfo result = new BytesPackageInfo
                {
                    Header = _CollectHead,
                    Body = _Body,
                    Key = Key,
                    AllData = data.ToList()
                };
                return result;
            }
            catch (Exception e)
            {
                CollectServer.Instinstance.Logger.LogError(e.Message);
                //todo 
            }
            return base.DecodePackage(buffer);
        }
}

**Comment by XuLinFei** [comment]
并且可以看到应用的内存在不断的增加

**Comment by kerryjiang** [comment]
你这是啥通信协议？

**Comment by XuLinFei** [comment]
TCP 数据解析用的我们公司自定义的协议

**Comment by XuLinFei** [comment]
我使用模拟器发送 频率搞得情况下的几乎必出现这个问题

**Comment by kerryjiang** [comment]
你们公司的协议是每个包12个0xff结尾？

**Comment by XuLinFei** [comment]
是的

**Comment by kerryjiang** [comment]
试试看这个版本：
https://www.nuget.org/packages/SuperSocket.Server/2.0.0-preview1-10

如果还不能解决，建议fork版本，参考现有的测试用例，增加一个你的协议的测试用例用于重现你的问题：
https://github.com/kerryjiang/SuperSocket/tree/master/test/Test

你这个协议解析性能有很大的提升空间。不要做任何ToArray()，Copy，CloneRange和ToList().
把包格式定义成你业务直接能处理的数据。

**Comment by kerryjiang** [comment]
另外，不要 return base.DecodePackage(buffer);

**Comment by XuLinFei** [comment]
OK 谢谢

**Comment by XuLinFei** [comment]
我fork了最新版本 并在测试里加了一个和我协议类似的测试。这个测试是没法通过的。

**Comment by XuLinFei** [comment]
通过调试，我定位到错误，是会卡在我标记的这行代码
![file](https://user-images.githubusercontent.com/16266462/68096996-50ef2700-feef-11e9-830a-44a91ad5a744.jpg)
。

**Comment by kerryjiang** [comment]
发送包的协议格式不对。

你服务器端协议解析是用 12个0xff做结束符，但是客户端用FixedHeader。客户端和服务器端使用的协议不同，当然跑不通。
https://github.com/XuLinFei/SuperSocket/blob/master/test/Test/XLCustomProtocalTest.cs

**Comment by XuLinFei** [comment]
没有，这个测试如果把发送长度降低是可以跑通的，而且 我这个应该用的是TerminatorPipelineFilter，您说我用的FixedHeader  我不太理解

**Comment by XuLinFei** [comment]
我用最新的版本，这个问题就不存在了，下面我用硬件测一下，试试看效果。

**Comment by kerryjiang** [comment]
你这个是客户端发送到服务器端的请求，前面4个字节是后面内容不分的长度啊，4个自己是固定的头部长度。并非你服务器端所支持的以12个0xff结尾的协议啊。
`
protected override string CreateRequest(string sourceLine)
        {
            return sourceLine.Length.ToString().PadLeft(4) + sourceLine;
        }
`

**Comment by XuLinFei** [comment]
这个问题 我修改了 测试时通过的

**Comment by XuLinFei** [comment]
然后我有发现了一个新的问题，就是在DecodePackage这个方法里，如果报错了，那么下一次请求过来，还是那个错误数据，这个数据不被推进，会一直存在，像是一个死循环

**Comment by kerryjiang** [comment]
那我看看，为什么会报错呢？

**Comment by XuLinFei** [comment]
下位机传输数据的时候，有时候数据采集不够，但是协议又有数据长度限制。

**Comment by kerryjiang** [comment]
为什么不补长呢？首先你协议设计的问题，协议解析出错，直接抛出异常，断开连接。

**Comment by XuLinFei** [comment]
我就是直接抛出，但是连接没有自动断开

**Comment by XuLinFei** [comment]
![1573027167](https://user-images.githubusercontent.com/16266462/68279469-724a4180-00ae-11ea-9a4a-e725c0dd12cd.jpg)
通过调试我发现会在图中，标记位置报错（End position was not reached during enumeration.）
然后下面请求进来都接收不到数据了

**Comment by XuLinFei** [comment]
我知道问题了，这应该是一个重大的bug。在这一行代码，如果我提供的协议是12个FF结尾的，但是这个片段最后一位刚好是FF（或者最后某几位但是不足十二位的时候，后面的数据藏在下一个片段下，不知道是否是结尾，也可能是正常编码数据），那么他就会报这个错。希望你们能尽快修复这个问题。

**Comment by kerryjiang** [comment]
https://github.com/kerryjiang/SuperSocket/blob/master/test/Test/TerminatorProtocolTest.cs
加个测试用例重现这个bug吧，我这边就可以调试了。

**Comment by kerryjiang** [comment]
另外nuget上最新的包，协议解析抛异常直接断掉连接。
