### ISSUE TITLE
2.0版客户端断开，服务端没响应断开事件？，服务端的连接session还存在

### ISSUE THREAD

**Issue by qqzhw** [kerryjiang/SuperSocket#262]

**Comment by kerryjiang** [comment]
How did the client disconnect?

There is a test case for it:
https://github.com/kerryjiang/SuperSocket/blob/master/test/Test/MainTest.cs

**Comment by qqzhw** [comment]
Thanks   
OnSessionClosed没有触发，SessionCount 数量没有减少，不会移除断开的连接Session。我的操作方式：1.使用TCP工具连接服务 2.tcp工具端断开 此时服务端没有触发SessionClose，SessionCount也没减少。

**Comment by kerryjiang** [comment]
OK, I can reproduce it with the mentioned test case.
Let me fix it.

**Comment by kerryjiang** [comment]
I did a fix just now.

**Comment by qqzhw** [comment]
OK thank you.
