### ISSUE TITLE
2.0 任意客户端关闭后服务端尝试发送数据都会使进程挂起，还有多线程异步发送数据时会出现Writing is not allowed after writer was completed错误导致进程挂起

### ISSUE THREAD

**Issue by kofhero** [kerryjiang/SuperSocket#263]
2.0 任意客户端关闭后服务端尝试发送数据都会使进程挂起，还有多线程异步发送数据时会出现Writing is not allowed after writer was completed错误导致进程挂起

**Comment by kerryjiang** [comment]
Ok, I will improve the code to handle these two cases better:
1) send data from the server when the session is closed;
2) concurrent sending;

**Comment by kerryjiang** [comment]
任意客户端关闭后服务端尝试发送数据时抛出异常应合理，业务代理有责任处理这样的一场，也可以在发送之前检查一下连接状态。
