### ISSUE TITLE
SuperWebSocket creating null.log in build folder

### ISSUE THREAD

**Issue by bedotnet** [kerryjiang/SuperSocket#265]
How can I customize SuperWebSocket or SuperSocket.WebSocket to use different log location. 
Currently logs are getting created in same executable folder as (null)-19.11.2019

The steps I have followed are 
**log4net.config**
```
<appender name="SuperWebSocketAppender" type="log4net.Appender.RollingFileAppender">
    <file type="log4net.Util.PatternString" value="C:\SupTest.log" />
    <datePattern value="'-'dd.MM.yyyy'.log'" />
    <rollingStyle value="Composite" />
    <maxSizeRollBackups value="120" />
    <maximumFileSize value="100MB" />
    <staticLogFileName value="false" />
    <appendToFile value="true" />
    <layout type="log4net.Layout.PatternLayout">
      <param name="ConversionPattern" value="%d [%t] %-5p %m%n" />
    </layout>
  </appender>
 <logger additivity="false" name="SuperWebSocketLogger">
    <level value="Info" />
    <appender-ref ref="SuperWebSocketAppender" />
  </logger>
```

And this in the code 
**DXMain**
`  var log =  this.Server.LogFactory.GetLog("SuperWebSocketLogger");`

After the following steps above. The logs are still getting created in build folder  as (null)-19.11.2019

**The Project Structure**
 -DXLogger (dll /Assembly only this project has log4net.config)
 -DXMain (exe)
 -DXCore (dll /Assembly)

DxMain and DXCore both references DXLogger which is implementation of log4net.
 The log4net.config resides in DxLogger project and is created in debug folder of main at runtime. 

Any suggestions ?
Or 
Is there a way where I can disable SuperWebSocket log completely ?

**Comment by kerryjiang** [comment]
I think you should leave the log4net.config in the same directory with the service application.

**Comment by kerryjiang** [comment]
You just need leave your log4net appender/logger in the log4net configuration file which is provided by SuperSocket/SuperWebSocket.

**Comment by bedotnet** [comment]
But the problem here is. Going ahead DxCore will become an Exe and we communicate between Core and Main. And both of these will refer to Dxlogger for logging. Any advice in this case, We would really like to have logs of SuperWebSocket in another folder. 

Also we cant see any log4net config defined by SuperWebSocket. We installed it through Nuget package.

**Comment by kerryjiang** [comment]
Everything should be exe centric.
If you just want to keep logs in a different folder, just update the appender in the log4net config file.
