### ISSUE TITLE
TLSV.12  Error Connecting with Client , Authentication Error

### ISSUE THREAD

**Issue by vishy007** [kerryjiang/SuperSocket#268]
Hi All,

I am getting error when I use TLSv1.2 with WSS, 
I am getting below error 

   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at SuperSocket.ClientEngine.SslStreamTcpSession.OnAuthenticated(IAsyncResult result)

I passed the certification also till same error.

What todo??

**Comment by vishy007** [comment]
Hi All.

Any update on the above issue, Please find below my code.

public class ServerSide
    {
        public WebSocketServer WebSocketServer { get; set; }
        RootConfig rConfig = new RootConfig();
        const SslProtocols protocolversionServer = SslProtocols.Tls12;
        const SecurityProtocolType securityProtocolTypeServer = SecurityProtocolType.Tls12;
        public void Connect()
        {


            int port = 7896;
            var appServer = new WebSocketServer();
            var serverConfig = new ServerConfig
            {
                Name = "SuperWebSocket",
                Ip = "127.0.0.1",
                ReceiveBufferSize = 5000000,
                SendBufferSize = 5000000,
                MaxRequestLength = 5000000,
                Port = port,
                Mode = SocketMode.Tcp,
                Security = securityProtocolTypeServer.ToString(),
                LogAllSocketException = true,
                Certificate = new CertificateConfig
                {
                    FilePath = @"C:\ProgramData\SupportAssist\Client\Agent\083ac84c-9d64-479b-b018-f350e0d5d1b3\e765916f-0356-415a-a774-f4efb5d941b1.pfx",
                    Password = "",

                },
                //Listeners = list,
            };

            var socketFactory = new SuperSocket.SocketEngine.SocketServerFactory();            //Setup the appServer
            bool startFlag = appServer.Setup(rConfig, config: serverConfig);



            Console.WriteLine(startFlag);
        }

But when I try to connect with CLine it fails.

   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at SuperSocket.ClientEngine.SslStreamTcpSession.OnAuthenticated(IAsyncResult result)


Both Tls1.1 and Tls1.2 not working just tls 1.0 works,  need help what todo??

@kerryjiang

**Comment by vishy007** [comment]
@kerryjiang : Just for info, I am using the latest version of SuperWebsocket 0.9.0.2 whatever is available in Nuget.

And my client is Websocket4net only.

public class ClientSide
    {
        private const string certDell = "CN=www.dell.com";
        private const string certFtpDell = "CN=ftp.dell.com";
        private const string certDownloadsDell = "CN=downloads.dell.com";
        private const string certStarDell = "CN=*.dell.com";

        const SslProtocols protocolversion = SslProtocols.Tls12;// | SslProtocols.Tls1211 | SslProtocols.Tls12;
        const SecurityProtocolType securityProtocolType = SecurityProtocolType.Tls12;// | SecurityProtocolType.Tls1211 | SecurityProtocolType.Tls12;
        public void Connect()
        {
            //ss.Add(this.CreateAuthorizationHeader(CredentialCache.DefaultNetworkCredentials));
            WebSocket4Net.WebSocket _websocketClient;
            System.Net.ServicePointManager.SecurityProtocol = securityProtocolType;
            _websocketClient = new WebSocket4Net.WebSocket("wss://127.0.0.1:7896", "Tls12", sslProtocols: protocolversion, version: WebSocketVersion.Rfc6455);




            _websocketClient.Security.EnabledSslProtocols = protocolversion;

            var cert = new System.Security.Cryptography.X509Certificates.X509Certificate();
            cert.Import(File.ReadAllBytes(@"C:\ProgramData\SupportAssist\Client\Agent\083ac84c-9d64-479b-b018-f350e0d5d1b3\e765916f-0356-415a-a774-f4efb5d941b1.pfx"));

            //_websocketClient.Security.Certificates.Add(cert);
            //_websocketClient.Security.AllowNameMismatchCertificate = true;
            ServicePointManager.ServerCertificateValidationCallback = RemoteCertificateValidate;
            _websocketClient.Error += _websocketClient_Error;
            _websocketClient.Opened += websocketClient_Opened;
            _websocketClient.Closed += websocketClient_Closed;
            _websocketClient.MessageReceived += websocketClient_MessageReceived;
            _websocketClient.Open();


            while (_websocketClient.State != WebSocket4Net.WebSocketState.Open)
            {
                Console.WriteLine(_websocketClient.State);
                //Thread.Sleep(2000);
            }

            _websocketClient.Send("sds");
            Console.WriteLine("Connected");
        }

        private bool RemoteCertificateValidate(object sender, X509Certificate cert, X509Chain chain, SslPolicyErrors sslPolError)
        {
            if (sslPolError == SslPolicyErrors.None && (cert.Subject.StartsWith(certDell) || cert.Subject.StartsWith(certFtpDell) || cert.Subject.StartsWith(certDownloadsDell) || cert.Subject.StartsWith(certStarDell)))
            {
                return true;
            }
            else
                return false;
        }

        private void _websocketClient_Error(object sender, SuperSocket.ClientEngine.ErrorEventArgs e)
        {

        }

        private void websocketClient_MessageReceived(object sender, MessageReceivedEventArgs e)
        {

        }

        private void websocketClient_Closed(object sender, EventArgs e)
        {

        }



        private void websocketClient_Opened(object sender, EventArgs e)
        {
            Console.WriteLine("Opened");
        }
    }

**Comment by chucklu** [comment]
@vishy007  Please read https://github.com/kerryjiang/SuperWebSocket/blob/master/README.md
SuperWebSocket is being merged into SuperSocket as an additional module SuperSocket.WebSocket. You can use SuperSocket.WebSocket in the same way with SuperWebSocket but with a different namespace.

**Comment by kerryjiang** [comment]
Where did you get the error? from your client or server side?

**Comment by vishy007** [comment]
I am getting this error at Client Side, when it try to call the Client. OPen method.

the exact point of error come when it calls the ssl.AuthenticateasClient function and hangs forever.

After some times it then says the above error

**Comment by vishy007** [comment]
> @vishy007 Please read https://github.com/kerryjiang/SuperWebSocket/blob/master/README.md
> SuperWebSocket is being merged into SuperSocket as an additional module SuperSocket.WebSocket. You can use SuperSocket.WebSocket in the same way with SuperWebSocket but with a different namespace.

 @chucklu : Will this support TLS1.0 and TLS1.2??

**Comment by vishy007** [comment]
Thanks All, it worked, I use the SuperSocket.Websocket and it supported.

Thanks All Great Tool

**Comment by vishy007** [comment]
Special thanks to @chucklu  and @kerryjiang
