### ISSUE TITLE
Attempting to get this working for the first time, instant disconnect, using SuperSocket.WebSocket.WebSocketServer

### ISSUE THREAD

**Issue by karezza** [kerryjiang/SuperSocket#269]
After viewing:  https://www.youtube.com/watch?v=JbXurSfeceY
Implemented the technique there (see its comment for the code) but using SuperSocket .WebSocket instead of SuperWebSocket.

Added to a pre-existing REST API using C# .net core 2.1, by adding to the Program.cs file.

I can see with my debug messages the server is starting & I am able to telnet to the port from a different computer.

I tried testing using websocket.org/echo.html from another pc.  I can see via wireshark a response "HTTP/1.1 101 Switching Protocols", however ... via the testing website it only says DISCONNECT & I'm unable to test sending a message.  I'm not getting any exceptions.

Packages installed via nuget with Visual Studio 2019.
SuperSocket.WebSocket (1.6.6.1)
SuperSocket.Engine (1.6.6.1)

1) Is there another package I need to install?
2) Does this work with .net core?
3) Is there an easy way to see if the websocketserver is functioning as expected?
4) How to increase debugging messages from SuperSocket?

**Comment by karezza** [comment]
I tried testing using websocket.org/echo.html from another pc.  This I can see via wireshark & I'm able to see a response "HTTP/1.1 101 Switching Protocols", however .. via the website it says DISCONNECT.  What's happening here?

**Comment by karezza** [comment]
Created a new console app with .net core 2.1 & used WebSocketServer.  Same result, able to connect but then there is an immediate disconnect.  Code is as follows:

`using SuperWebSocket;
using System;

namespace ConsoleApp1
{
    class Program
    {
        private static WebSocketServer wsServer;
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            wsServer = new WebSocketServer();
            int port = 8088;
            wsServer.Setup(port);
            wsServer.NewSessionConnected += WsServer_NewSessionConnected;
            wsServer.NewMessageReceived += WsServer_NewMessageReceived;
            wsServer.NewDataReceived += WsServer_NewDataReceived;
            wsServer.SessionClosed += WsServer_SessionClosed;
            wsServer.Start();
            Console.WriteLine("Server is running on port " + port + ". Press ENTER to exit....");
            Console.ReadKey();
        }

        private static void WsServer_SessionClosed(WebSocketSession session, SuperSocket.SocketBase.CloseReason value)
        {
            Console.WriteLine("SessionClosed");
        }

        private static void WsServer_NewDataReceived(WebSocketSession session, byte[] value)
        {
            Console.WriteLine("NewDataReceived");
        }

        private static void WsServer_NewMessageReceived(WebSocketSession session, string value)
        {
            Console.WriteLine("NewMessageReceived: " + value);
            if (value == "Hello server")
            {
                session.Send("Hello client");
            }
        }

        private static void WsServer_NewSessionConnected(WebSocketSession session)
        {
            Console.WriteLine("NewSessionConnected");
        }
    }
}
`

**Comment by karezza** [comment]
If I need to be using SuperSocket 2.0 in order to have it work with .net core, could you direct me to some documentation with an example?  I cloned the repository & built the code, yet to use it appears to be quite different from the previous method.  Looks like I need to be using WebSocketHostBuilder maybe?

**Comment by karezza** [comment]
Got this to compile, but obviously I don't know how this is supposed to work.  Could I get an assist:

```
static async Task Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            //var host = SuperSocketHostBuilder.Create<TextPackageInfo, LinePipelineFilter>()
            var wsServer = SuperSocket.WebSocket.Server.WebSocketHostBuilder.Create()
               .ConfigurePackageHandler(async (s, p) =>
               {
                   await s.SendAsync(Encoding.UTF8.GetBytes(p.Message + "\r\n"));
               })
               .UseSuperSocketWebSocket()
               .ConfigureLogging((hostCtx, loggingBuilder) =>
               {
                   loggingBuilder.AddConsole();
               })
               .ConfigureSuperSocket(options =>
               {
                   options.Name = "Echo Server";
                   options.Listeners = new[] {
                        new ListenOptions
                        {
                            Ip = "Any",
                            Port = 8088
                        }
                   };
               }).Build();

            await wsServer.RunAsync();
}
```

**Comment by karezza** [comment]
The code above results in the following:

```
Hello World!
fail: TcpChannelCreator[0]
      The listener failed to start.
System.Net.Sockets.SocketException (10048): Only one usage of each socket address (protocol/network address/port) is normally permitted.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at SuperSocket.Server.TcpChannelCreator.Start() in C:\Users\travis\source\repos\SuperSocket\src\SuperSocket.Server\TcpChannelCreator.cs:line 71
fail: SuperSocketService[0]
      Failed to listen Ip=Any, Port=8088, Security=None, Path=, BackLog=0, NoDelay=False.
fail: SuperSocketService[0]
      Failed to listen Ip=Any, Port=8088, Security=None, Path=, BackLog=0, NoDelay=False.
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
```

**Comment by kerryjiang** [comment]
Probably the previous process hasn't exit yet.
To test the server, you better write your test web pages to connect that websocket server or just write some test cases.

**Comment by karezza** [comment]
I don't see a previous process to shutdown.  Tried running again with a new port that I've never tried before 8090 (in this case) and the result was the same.  Is that a sufficient test to eliminate the problem as possibly being a previous process still running?

**Comment by kerryjiang** [comment]
Just check your process list, probably the port has been taken by another application.

**Comment by karezza** [comment]
I did a reboot and chose another new port that I've never used before, result is the same.  I'll try creating a new project with the same code.

**Comment by kerryjiang** [comment]
Could you run the test cases at first?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by karezza** [comment]
Seeing the same result.  Here is the process I used to create the project and test:

1. Create new C# .net core project (uses .net core 3.1 by default)
2. Add all assemblies, under SuperSocket.WebSocket.Server/bin/Debug/netstandard2.1
3. Install via NuGet:
Microsoft.Extensions.Hosting
Microsoft.Extensions.Logging
4. Add using statements:
using SuperSocket;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using System.Text;
5. Using the following code:
```
        static async Task Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            //var host = SuperSocketHostBuilder.Create<TextPackageInfo, LinePipelineFilter>()
            var wsServer = SuperSocket.WebSocket.Server.WebSocketHostBuilder.Create()
               .ConfigurePackageHandler(async (s, p) =>
               {
                   await s.SendAsync(Encoding.UTF8.GetBytes(p.Message + "\r\n"));
               })
               .UseSuperSocketWebSocket()
               .ConfigureLogging((hostCtx, loggingBuilder) =>
               {
                   loggingBuilder.AddConsole();
               })
               .ConfigureSuperSocket(options =>
               {
                   options.Name = "Echo Server";
                   options.Listeners = new[] {
                        new ListenOptions
                        {
                            Ip = "Any",
                            Port = 9000
                        }
                   };
               }).Build();

            await wsServer.RunAsync();

        }
```

**Comment by karezza** [comment]
When I run a test case to connect to the websocket I see the following exceptions appear:
Exception thrown: 'System.IO.FileNotFoundException' in SuperSocket.Channel.dll
Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll
Exception thrown: 'System.NullReferenceException' in SuperSocket.Server.dll

**Comment by karezza** [comment]
I added an output at the start of SuperSocket.Server.TcpChannelCreator.Start & when I run my program I can see that the method is being called twice ... though I don't know why.  This is probably what is causing the 'listener failed to start' error.

Being that I can connect to the ip/port and see new socket exceptions appear in the running program, this would indicate there is a port listening... though it doesn't function as expected.

**Comment by kerryjiang** [comment]
Could you just go to the tests/Test in the source code with Visual Studio Code and then run the command “dotnet test” in the terminal tab.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by karezza** [comment]
I right-clicked on Test & selected "Run Tests".  45 tests ran and Passed.

From the command window and the test/test directory, running "dotnet test" ran 45 tests and all passed.

**Comment by kerryjiang** [comment]
OK, just follow the usages in the unit tests.

**Comment by karezza** [comment]
I'll take a look and report back.

**Comment by jzabroski** [comment]
The advice to use a web browser to test a web socket server seems bad/klunky.  Perhaps something like websocket-mock could be helpful: https://github.com/davidkiss/websocket-mock

**Comment by jzabroski** [comment]
Or maybe just: https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.clientwebsocket?view=netframework-4.8

**Comment by karezza** [comment]
Will keep an eye out for documentation.

**Comment by karezza** [comment]
Not sure what to do.  Closing as the library has not been released yet so there is no expectation that it should be usable yet.
