### ISSUE TITLE
quickstart文件夹的ConnectionFilter的配置文件

### ISSUE THREAD

**Issue by chucklu** [kerryjiang/SuperSocket#27]
配置文件中有关于server以及serverTypes的配置，但是项目找不到相关的server
 <servers>
      <server name="EchoServer"
              serverTypeName="EchoService" ip="Any" port="2012"
              connectionFilter="IpRangeFilter" ipRange="127.0.1.0-127.0.1.255">
      </server>
    </servers>
    <serverTypes>
      <add name="EchoService"
           type="SuperSocket.QuickStart.EchoService.EchoServer, SuperSocket.QuickStart.EchoService" />
    </serverTypes>

2015-03-24 08:42:00,549 [3776] ERROR DefaultBootstrap - Failed to create server instance EchoServer!
System.IO.FileNotFoundException: 未能加载文件或程序集“SuperSocket.QuickStart.EchoService”或它的某一个依赖项。系统找不到指定的文件。

**Comment by chucklu** [comment]
自己随便写一个server就可以吗？还是这个项目漏掉了？

**Comment by chucklu** [comment]
<serverTypes>
      <add name="EchoService"
           type="SuperSocket.QuickStart.EchoService.EchoServer, SuperSocket.QuickStart.EchoService" />
    </serverTypes>

**Comment by kerryjiang** [comment]
Please read the QuickStart projects one by one to understand how SuperSocket works.
The document website is a very import learning resource:
http://docs.supersocket.net

**Comment by chucklu** [comment]
我看了其他项目的配置，server都是对应的项目里面的appserver，但这个ConnectionFilter是没有server的呀

**Comment by kerryjiang** [comment]
It is configuration sample.

**Comment by chucklu** [comment]
![qq 20150324110019](https://cloud.githubusercontent.com/assets/3004057/6795024/f9fcb63a-d214-11e4-94b8-6e75ed6e07f4.png)
额，配置里面，对应当前项目的是connectionFilters配置，但是server和serverTypes里面对应的东西是不存在的。

我的问题是：这2个缺少的是需要自己建立吗？
【ps：其他的类库项目只需要建立一个Text项目，直接调用类库就可以运行使用了，但是当前这个，因为缺少server以及serverTypes无法运行】

**Comment by chucklu** [comment]
其他的项目，比如BroadcastService类库，配置中的servers和serverTypes，是直接对应当前的项目的。
![qq 20150324110019](https://cloud.githubusercontent.com/assets/3004057/6795068/a1bb7b72-d215-11e4-87ad-d272433ecce1.png)
但是ConnectionFilter是项目本身是对应到了connectionFilters里面。

所以，我觉得，缺少了EchoService项目
quickstart文件夹下找不到这个项目

所以，我想知道的是如何让这个类库能正常运行起来？EchoService本身不存在的吗？
那么自己写一个就可以了吗？

**Comment by kerryjiang** [comment]
请阅读相关文档。
________________________________

**Comment by kerryjiang** [comment]
貌似你没弄懂示例项目和示例配置文件的意思。
该配置文件仅仅是告诉你connectionFilter如何配置，其它如如serverType的配置，请参考文档和示例项目！

**Comment by chucklu** [comment]
但是那么多的类库项目，只有这个是无法运行起来的。
其他的类库添加测试项目之后是可以直接运行起来的

**Comment by kerryjiang** [comment]
貌似你没看到我在另一个issue回复你的话：
示例项目仅仅提示你类似的需求如何解决，仅仅起示例作用, 不是能够支持现实应用的程序！
基本逻辑看明白就行了！

**Comment by chucklu** [comment]
看是看到了，但是我觉得demo的话，应该能运行起来才好测试呀。
所以，我在测试的时候遇到了问题。看样子还是需要自己写一个server来匹配这个connectionFilter

**Comment by kerryjiang** [comment]
connectionFilter可以与任何AppServer一起使用，随便加到另一个项目里面就行了。
