### ISSUE TITLE
2.0 版本的 IAppSession 能提供 Socket 的 RemoteEndPoint 吗？

### ISSUE THREAD

**Issue by SunriseChen** [kerryjiang/SuperSocket#270]
2.0 版本的 IAppSession 能提供 Socket 的 RemoteEndPoint 吗？
或者有什么途径可以得到客户端的 RemoteEndPoint 呢？
谢谢！

**Comment by kerryjiang** [comment]
I thought about this problem just last night. After I saw your question, I understand this feature is very necessary. So I added it back just now and it will be available in SuperSocket 2.0 Preview 2 on the following days.

**Comment by kerryjiang** [comment]
LocalEndPoint was added as well.

**Comment by SunriseChen** [comment]
非常感谢！
