### ISSUE TITLE
How to use it at .NEt Core MVC project 

### ISSUE THREAD

**Issue by SahadatHHredoy** [kerryjiang/SuperSocket#273]
Please give a sample how i use it at .NET core MVC Razor view Project

**Comment by kerryjiang** [comment]
It cannot be used in a razor view.

SuperSocket is a socket server framework.

Why do you want to use it in a view?

**Comment by h0730303779** [comment]
> It cannot be used in a razor view.
> 
> SuperSocket is a socket server framework.
> 
> Why do you want to use it in a view?

I have the same needs too;

我也有这个需求 我现在 netcore.31 MVC 中启用了   SocketServer 可以使用.
但我没办法 发消息  我无法注入我的 DeviceSessio;


---- 
   我的场景:
    MVC  直接获取树莓派连接的设备(姑且说是温度器)的当前信息  
   我需要同步返回  因为我是单体程序 不打算用别的解决方案
