### ISSUE TITLE
How to handle custom session for 2.0

### ISSUE THREAD

**Issue by mago-pablo** [kerryjiang/SuperSocket#274]
Hello Kerry, 

I have a working project for the new version 2.0, I have a previous project running on 1.6 and use custom session, I have reviewed the sample projects and tests for the 2.0, I see there is a InProcSessionContainerMiddleware, and a UseSession in the HostBuilder, but I cant manage to get a custom Session type running on the ExecuteAsync method from my  Commands. Am I missing something or is custom session to share state in a open socket session threw the commands not available yet. 

Thank you very much.

**Comment by mago-pablo** [comment]
I missed the following method: 
```
...
.UseSessionFactory<GenericSessionFactory<XSession>>()
```
in the hostbuilder, with this I was able to get the desired functionality running.

**Comment by kerryjiang** [comment]
UseSession should be enough:

`public static IHostBuilder UseSession<TSession>(this IHostBuilder hostBuilder)
            where TSession : AppSession, new()
        {
            return hostBuilder.UseSessionFactory<GenericSessionFactory<TSession>>();
        }`
