### ISSUE TITLE
建议将程序里使用的DateTime类型改为DateTimeOffset类型

### ISSUE THREAD

**Issue by liuguiyou** [kerryjiang/SuperSocket#275]
建议将程序里使用的DateTime类型改为DateTimeOffset类型,这样可以更好避免服务器时区不同导致的问题

**Comment by kerryjiang** [comment]
这个建议很奇怪，要么统一用UTC？
你说的哪个DateTime？

**Comment by chucklu** [comment]
@kerryjiang  https://docs.microsoft.com/en-us/dotnet/api/system.datetimeoffset?view=netframework-4.8

**Comment by kerryjiang** [comment]
现在只有session.StartTime是DateTime类型。

**Comment by overing** [comment]
Using DateTime.UtcNow is great, it's better than DateTime.Now.
https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/DateTime.cs#L1045

**Comment by kerryjiang** [comment]
I have changed session.StartTime to use type DateTimeOffset.
