### ISSUE TITLE
BootstrapFactory, SocketEngine

### ISSUE THREAD

**Issue by kinguru** [kerryjiang/SuperSocket#276]
Dear author,
please clarify what is BootstrapFactory found in the documentation (http://docs.supersocket.net/v1-6/en-US/Start-SuperSocket-by-Configuration).
Where to get source code of it?

What is SocketEngine? 
Should I use SocketEngine to implement WebSocket protocol on SuperSocket?

Thanks

**Comment by kerryjiang** [comment]
Sorry, it is in the branch v1.6:
https://github.com/kerryjiang/SuperSocket/tree/v1.6

SuperSocket already have websocket implementation.
Just use SuperSocket.WebSocket.
https://github.com/kerryjiang/SuperSocket/tree/v1.6/Protocols/WebSocket

**Comment by kerryjiang** [comment]
If you are new user, I recommend you to use SuperSocket 2.0. But right now, it is lack of documentation.
Anyway, you can play with it by following the samples and unit-tests.

**Comment by kinguru** [comment]
Thank you. Will SuperSocket work with .net 4.5? My application is not using dotnet core.

**Comment by kerryjiang** [comment]
Yes, try 1.6.

**Comment by kinguru** [comment]
Could you please share an example on how to cook WebScoketServer. I see no examples in the documentation or samples. Currently I'm using SocketEngine to create a server instance, but have no idea how to switch to WebSocketServer. Trying to figure out.

**Comment by kerryjiang** [comment]
Please refer to SuperWebSocket
https://github.com/kerryjiang/SuperWebSocket/tree/master/Samples

SuperWebSocket is just SuperSocket.WebSocket with different assembly name and namespace

**Comment by kinguru** [comment]
Hi again, 
do I need a Bootstrap from SocketEngine? I'm getting a lot of socket 995 errors in production (600+ sessions) in version without Bootstrap. 

My server start looks like:
`_server = new SuperSocket.WebSocket.WebSocketServer();
                _server.Setup(serverConfig);

                _server.NewSessionConnected += webSocketServer_NewSessionConnected;
                _server.SessionClosed += webSocketServer_SessionClosed;
                if (!_server.Start())
                {
                    throw new Exception("SuperWebSocket failed to start!");
                }`

**Comment by kerryjiang** [comment]
How did you test it? Which kind client did you use?

**Comment by kinguru** [comment]
I've figure out why I have so much 995 socket errors. It occurs when call session.Close(). 
In case of session.Close(reason) or session.CloseWithHandshake(...) - no 995 error code logged.

Another issue observed. Seems like session.TrySend and session.Send works different. I was used TrySend, but faced issues with hang connections. After switch to session.Send problem get resolved.
