### ISSUE TITLE
net core 用预览版2.0的问题

### ISSUE THREAD

**Issue by bbhxwl** [kerryjiang/SuperSocket#277]
代码是和1.6不一样么，文档很少，想按照1.6的代码写，好像很多代码也不一样，
很难入门预览版2.0，以前版本一直也没用过，刚听说过这个框架。想试试net core的

**Comment by chucklu** [comment]
You might have a glance at the sample code and test code
https://github.com/kerryjiang/SuperSocket/tree/master/samples
https://github.com/kerryjiang/SuperSocket/tree/master/test/Test

**Comment by kerryjiang** [comment]
More samples are coming...
