### ISSUE TITLE
把UDP还给我们

### ISSUE THREAD

**Issue by cglandy** [kerryjiang/SuperSocket#278]
渔总，我项目要升级.netcore ，原来是包含了UDP协议的，现在升级2.0发现没有UDP,玩不下去了。

**Comment by kerryjiang** [comment]
你以前是如何使用SuperSocket的UDP功能的？

**Comment by cglandy** [comment]
用法跟TCP的一样，就是config中的type不同

**Comment by kerryjiang** [comment]
Created a repository for it:
https://github.com/SuperSocket/SuperSocket.Udp

**Comment by kerryjiang** [comment]
It is on the way:
https://github.com/kerryjiang/SuperSocket/tree/master/src/SuperSocket.Udp
