### ISSUE TITLE
ValidateClientCertificate session doesn't include path.

### ISSUE THREAD

**Issue by rensing** [kerryjiang/SuperSocket#28]
I am using this override method to do additional cert checks. I am listening for websocket connections with different paths; the path portion of the connection url gives clues to the ValidateClientCertificate about whether not the cert validation is required, and if so, what to check. The path value IS available when the NewSessionConnected handler is triggered; would it be possible to have this value assigned earlier so it's available to the custom ValidateClientCertificate method?

**Comment by kerryjiang** [comment]
Do you mean SuperWebSocket? SuperSocket's session doesn't have a Path property.

**Comment by rensing** [comment]
Correct, I'm referring to the WebsocketSession passed into the overrideable ValidatClientCertificate method of WebsocketServer (which I've implemented in my custom WebsocketServer), when ClientCertificateRequired is set to true in the CertificateConfig.

**Comment by kerryjiang** [comment]
In my idea, ValidatClientCertificate works only for certificate. The Path is received after the connection is established which is later than ValidatClientCertificate.

**Comment by rensing** [comment]
Interesting... the WebsocketSession in ValidateClientCertificate does contain the remote socket address, so would it not be possible to also determine and include the other information about the connection; since your solution does not allow me to have a path as part of my listener, I need to be able to determine different clients based on the path. If I were able to include a path as part of defining the server configuration (in addition to ip and port), then I could create and run multiple servers, on the same ip and port... one that would validate the client, and one that wouldn't.

**Comment by kerryjiang** [comment]
It's okay to includes remote socket address within ValidateClientCertificate method, but you never access path in it because you haven't got anything when the connection has not been established yet.
And you cannot create two appservers to listen same ip/port and different path using SuperWebSocket,

**Comment by rensing** [comment]
Ok, that's unfortunate... was hoping Supersocket's server emulated C# 4.5 Websocket server where multiple prefixes (which include URLs with paths) are managed by any number of servers sharing the same ip and port; with Supersocket, ALL paths have to be handled by the same server and, optionally, the same client cert validator (without knowing which service is being requested). Will have to either migrate to C# 4.5 (whose websocket implementation requires either Win 8+ or WinServer 2012+) or find a way to run all services in the same server, sharing a cert validator...

**Comment by kerryjiang** [comment]
Sorry, that's quite different. They use system level listener instead of application level listener like SuperSocket.
