### ISSUE TITLE
.NET 4.8 support in Super Socket 2.0

### ISSUE THREAD

**Issue by kinguru** [kerryjiang/SuperSocket#282]
Dear Kerry Jiang,
does Super Socket 2.0 will run in .NET Framework 4.8 latest?

**Comment by kerryjiang** [comment]
Sorry, it cannot.
SuperSocket targets netstandard2.1 which is not compatible with any .net framework.

**Comment by lyling** [comment]
@kerryjiang when will 2.0 release? or will 1.6 support .net core 2.x/3.1 first ?

**Comment by kinguru** [comment]
> Sorry, it cannot.
> SuperSocket targets netstandard2.1 which is not compatible with any .net framework.

**Comment by kinguru** [comment]
Thank you

**Comment by kerryjiang** [comment]
> @kerryjiang when will 2.0 release? or will 1.6 support .net core 2.x/3.1 first ?

Sorry, no more SuperSocket 1.6.*.
