### ISSUE TITLE
RequestHandler not invoking method for non-localhost connections

### ISSUE THREAD

**Issue by JohnnyPixelz** [kerryjiang/SuperSocket#285]
Hello there,

I create an AppServer and add a RequestHandler to it. The thing is, the RequestHandler only handles the local connections and not external ones.

The session handler accepts the connection so it is not a firewall issue.

**Comment by kerryjiang** [comment]
Probably the problem is caused by protocol parsing. Which kind of protocol do you use?

**Comment by JohnnyPixelz** [comment]
I use tcp both on clients and server through the config.

**Comment by kerryjiang** [comment]
No, I meant the application protocol over TCP.

**Comment by JohnnyPixelz** [comment]
I'm sorry but I got into networking this week and it's hard for me to understand your question. I do not know which application protocol I use, I just receive and send strings. (At least that's my purpose) I can provide you with my code if needed.

**Comment by kerryjiang** [comment]
Protocol is the convention how to parse the stream data into meaningful packages.

**Comment by JohnnyPixelz** [comment]
Well localhost and external both send same requests with same program but only the localhost requests are processed. What could be the reason this happens and how can it be solved? Will changing the protocol solve it?

**Comment by kerryjiang** [comment]
They may come with different fragments.
That's reason we need application protocol over TCP.

**Comment by 491134648** [comment]
The following problem troubleshooting: 
1. Firewall problems, open related ports, 
2. Address issues of service program listening, changed to listen to all addresses of this machine
