### ISSUE TITLE
SuperSocket中samples下的WebSocketServer示例,为什么每次客户端连接1分钟,服务端就关闭客户端连接了?

### ISSUE THREAD

**Issue by fendou** [kerryjiang/SuperSocket#289]
WebSocketServer示例,为什么每次客户端连接1分钟服务端就自动关闭这个客户端的连接了?websocket server要如何保持一直和这个客户端连接?

**Comment by fendou** [comment]
每次连接一分钟,服务端就关闭了....

**Comment by kerryjiang** [comment]
服务端就关闭? 不是连接关闭？

**Comment by fendou** [comment]
服务端关闭了这个连接了,我测试了很多次了,是服务端关闭连接了,需要客户端断开再重新连接

**Comment by fendou** [comment]
> 服务端就关闭? 不是连接关闭？

服务端关闭了这个连接了,我测试了很多次了,是服务端关闭连接了,需要客户端断开再重新连接

**Comment by kerryjiang** [comment]
我专门写了个测试用例来验证这个问题，你说的问题没有出现。

你把下面的代码贴到 https://github.com/kerryjiang/SuperSocket/blob/master/test/Test/WebSocket/WebSocketBasicTest.cs 里面跑一下。


`[Theory]
        [InlineData(typeof(RegularHostConfigurator))]
        //[InlineData(typeof(SecureHostConfigurator))]
        public async Task TestLongLastingSession(Type hostConfiguratorType) 
        {
            var hostConfigurator = CreateObject<IHostConfigurator>(hostConfiguratorType);

            using (var server = CreateWebSocketServerBuilder(builder =>
            {
                return builder.ConfigureWebSocketMessageHandler(async (session, message) =>
                {
                    await session.SendAsync(message.Message);
                });
            }, hostConfigurator: hostConfigurator)
                .BuildAsServer())
            {
                Assert.True(await server.StartAsync());
                OutputHelper.WriteLine("Server started.");

                var websocket = new ClientWebSocket();

                websocket.Options.RemoteCertificateValidationCallback = (sender, certificate, chain, sslPolicyErrors) => true;

                await websocket.ConnectAsync(new Uri($"{hostConfigurator.WebSocketSchema}://localhost:4040"), CancellationToken.None);

                Assert.Equal(WebSocketState.Open, websocket.State);

                await Task.Delay(1000 * 60 * 2);

                var receiveBuffer = new byte[256];

                var msg = Guid.NewGuid().ToString();

                Assert.Equal(msg, await GetWebSocketReply(websocket, receiveBuffer, msg));  

                await websocket.CloseAsync(WebSocketCloseStatus.NormalClosure, string.Empty, CancellationToken.None);
                await Task.Delay(1 * 1000);

                Assert.Equal(WebSocketState.Closed, websocket.State);

                await server.StopAsync();
            }
        }`

**Comment by fendou** [comment]
> 我专门写了个测试用例来验证这个问题，你说的问题没有出现。
> 
> 你把下面的代码贴到 https://github.com/kerryjiang/SuperSocket/blob/master/test/Test/WebSocket/WebSocketBasicTest.cs 里面跑一下。
> 
> ```
>     [Theory]
>     [InlineData(typeof(RegularHostConfigurator))]
>     //[InlineData(typeof(SecureHostConfigurator))]
>     public async Task TestLongLastingSession(Type hostConfiguratorType) 
>     {
>         var hostConfigurator = CreateObject<IHostConfigurator>(hostConfiguratorType);
> 
>         using (var server = CreateWebSocketServerBuilder(builder =>
>         {
>             return builder.ConfigureWebSocketMessageHandler(async (session, message) =>
>             {
>                 await session.SendAsync(message.Message);
>             });
>         }, hostConfigurator: hostConfigurator)
>             .BuildAsServer())
>         {
>             Assert.True(await server.StartAsync());
>             OutputHelper.WriteLine("Server started.");
> 
>             var websocket = new ClientWebSocket();
> 
>             websocket.Options.RemoteCertificateValidationCallback = (sender, certificate, chain, sslPolicyErrors) => true;
> 
>             await websocket.ConnectAsync(new Uri($"{hostConfigurator.WebSocketSchema}://localhost:4040"), CancellationToken.None);
> 
>             Assert.Equal(WebSocketState.Open, websocket.State);
> 
>             await Task.Delay(1000 * 60 * 2);
> 
>             var receiveBuffer = new byte[256];
> 
>             var msg = Guid.NewGuid().ToString();
> 
>             Assert.Equal(msg, await GetWebSocketReply(websocket, receiveBuffer, msg));  
> 
>             await websocket.CloseAsync(WebSocketCloseStatus.NormalClosure, string.Empty, CancellationToken.None);
>             await Task.Delay(1 * 1000);
> 
>             Assert.Equal(WebSocketState.Closed, websocket.State);
> 
>             await server.StopAsync();
>         }
>     }
> ```

但是我真的遇到了60秒自动关闭客户端连接.我又查看了supersocket源码发现了以下有关60秒关闭,你看一下了,要如何修改呢?
namespace SuperSocket.WebSocket.Server
{
    public class HandshakeOptions
    {
        /// <summary>
        /// Handshake queue checking interval, in seconds
        /// </summary>
        /// <value>default: 60</value>
        public int CheckingInterval { get; set; } = 60;

        /// <summary>
        /// Open handshake timeout, in seconds
        /// </summary>
        /// <value>default: 120</value>
        public int OpenHandshakeTimeOut { get; set; } = 120;
        
        /// <summary>
        /// Close handshake timeout, in seconds
        /// </summary>
        /// <value>default: 120</value>
        public int CloseHandshakeTimeOut { get; set; } = 120;
    }
}

**Comment by fendou** [comment]
这里的源码有关60秒关闭的,你看一下 https://github.com/kerryjiang/SuperSocket/blob/master/src/SuperSocket.WebSocket.Server/HandshakeOptions.cs

**Comment by fendou** [comment]
请问一下,我现在要如何把60秒修改成一直连接?

**Comment by kerryjiang** [comment]
WebSocket服务器需要用websocket客户端去连接。非websocket客户端连上去之后，在一定时间内不能完成握手的话，服务器端就会把连接断开。

**Comment by fendou** [comment]
> WebSocket服务器需要用websocket客户端去连接。非websocket客户端连上去之后，在一定时间内不能完成握手的话，服务器端就会把连接断开。

哦,这样.是用websocket客户端连接的.是连接成功,发消息可以返回消息, 连接成功,不等于握手吗?我再研究一下.
