### ISSUE TITLE
Listener on the Server shutting down.

### ISSUE THREAD

**Issue by Shane8th** [kerryjiang/SuperSocket#293]
in the method "private async Task KeepAccept(Socket listenSocket)"

If an exception of "An existing connection was forcibly closed by the remote host." gets thrown it leaves the method, and stops accepting new clients due to the break.

This is probably unintended behavior, and stops the server from working.

Cheers!

**Comment by kerryjiang** [comment]
@Shane8th, do you have stack trace of this exception?

**Comment by Shane8th** [comment]
I added catch (Exception ex) into this function, so I could catch it.
here is the stack trace.


  | Name | Value | Type
-- | -- | -- | --
  | StackTrace | "   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at SuperSocket.Server.TcpChannelCreator.<KeepAccept>d__15.MoveNext() in C:\\Users\\Shane\\Downloads\\SuperSocket-master (1)\\SuperSocket-master\\src\\SuperSocket.Server\\TcpChannelCreator.cs:line 94" | string

**Comment by kerryjiang** [comment]
It could be thrown directly from "await listenSocket.AcceptAsync();".

Thanks for your finding! I will try to fix it tonight.

**Comment by kerryjiang** [comment]
Did a fix just now:
https://github.com/kerryjiang/SuperSocket/commit/894d1b9b09c71841c9135f4fa86859560bc6ef71

**Comment by Shane8th** [comment]
looks good, thank you :)
