### ISSUE TITLE
官方文档自定义SuperService未找到如何使用的方法

### ISSUE THREAD

**Issue by jiwenbu** [kerryjiang/SuperSocket#297]
文档：https://docs.supersocket.net/v2-0/zh-CN/Extend-your-AppSession-and-SuperSocketService
怎么使用自定义Service，
SuperSocketHostBuilder.Create<StringPackageInfo, GameService<StringPackageInfo>, CommandLinePipelineFilter>(); 没有这个三个参数 相应的重载方法

**Comment by chucklu** [comment]
https://github.com/kerryjiang/SuperSocket/blob/master/src/SuperSocket.Server/SuperSocketHostBuilder.cs#L114

**Comment by kerryjiang** [comment]
Sorry, probably the latest package in nuget doesn't have this change.

I am pushing a new package to nuget on these days.

**Comment by kerryjiang** [comment]
Anyway, you can use the packages in myget:
https://www.myget.org/feed/Packages/supersocket

**Comment by kerryjiang** [comment]
Just pushed the packages.

**Comment by jiwenbu** [comment]
thanks. and i want to know whether the stable release 2.0 is ready?

**Comment by chucklu** [comment]
https://github.com/kerryjiang/SuperSocket/issues/296#issuecomment-601920773
