### ISSUE TITLE
HandleSocketEventComplete + NullRefernceException

### ISSUE THREAD

**Issue by alanyuen** [kerryjiang/SuperSocket#30]
SaePoolResource.cs:

if(config.Mode != SocketMode.Udp)
{
    state.Sae.Completed += socketEventComplete.HandleSocketEventComplete; 
}

AsyncSocketSession.cs:
if (result.State == ProcessState.Cached)
{
    e.UserToken = null;
    var newState = m_SaePoolForReceive.Get();
    e = newState.Sae;
    e.UserToken = newState;
    newState.SocketSession = this;
}

HandleSocketEventComplete 有可能在UserToken,SocketSession未附值前已被調用

**Comment by kerryjiang** [comment]
OK, I'll check this issue again.

**Comment by kerryjiang** [comment]
It seems this issue is not same with the issue "现在已经正在使用此 SocketAsyncEventArgs 实例进行异步套接字操作。" in the v1.6 branch.

Could you share me the exception's stack trace?

I am sorry for my late response!

**Comment by kerryjiang** [comment]
This issue might have been fixed by the latest commits in branch 1.6, could you have a try and then tell me your test result?

**Comment by kerryjiang** [comment]
Suggest you upgrade to SuperSocket 2.0
