### ISSUE TITLE
SuperSocketService.cs 重复赋值

### ISSUE THREAD

**Issue by jason-shi** [kerryjiang/SuperSocket#301]
SuperSocketService.cs
Line-74 and Line-78 重复赋值了

74        _serverOptions = serverOptions;
75        Name = serverOptions.Value.Name;
76        _serviceProvider = serviceProvider;
77        _pipelineFilterFactory = GetPipelineFilterFactory();
78        _serverOptions = serverOptions;
79        _loggerFactory = loggerFactory;

**Comment by kerryjiang** [comment]
Thanks, I will fix it soon.

**Comment by kerryjiang** [comment]
Fixed it just now:
https://github.com/kerryjiang/SuperSocket/commit/eb6143a2bfedd6ecf288119172218808ae394330
