### ISSUE TITLE
2.0版本中哪个类是1.6.1版本中BinaryRequestInfo的对应类？

### ISSUE THREAD

**Issue by webmote** [kerryjiang/SuperSocket#303]
原先case中有用到固定头部字节的二进制协议，以下是相应代码片段：

```
 public class CommandFilter : FixedHeaderReceiveFilter<BinaryRequestInfo>
 {
        public CommandFilter ()
            : base(4)
        {
        }

        // something else
 }
```

**Comment by MaiKui** [comment]
可以使用IKeyedPackageInfo<TKey>这个接口来实现一个相似的类

**Comment by kerryjiang** [comment]
@webmote 建议直接解析成应用程序能理解的数据包结构而不是二进制数据。

@MaiKui Sorry, 文档里面讲得不清楚，应该是这个https://github.com/kerryjiang/SuperSocket/blob/master/src/SuperSocket.ProtoBase/IKeyedPackageInfo.cs

**Comment by webmote** [comment]
> @webmote 建议直接解析成应用程序能理解的数据包结构而不是二进制数据。
> 
> @MaiKui Sorry, 文档里面讲得不清楚，应该是这个https://github.com/kerryjiang/SuperSocket/blob/master/src/SuperSocket.ProtoBase/IKeyedPackageInfo.cs

明白，感谢 @kerryjiang . @MaiKui
