### ISSUE TITLE
EasyClient  cannot send data  to echo SuperServer 2.0 

### ISSUE THREAD

**Issue by zhangyuKyou** [kerryjiang/SuperSocket#304]
just like this  with   EchoTest 
 List<EasyClient<TextPackageInfo>> socketmap = new List<EasyClient<TextPackageInfo>>();
            for(int  j = 0; j < 2; ++j)
            {
                EasyClient<TextPackageInfo> client = new EasyClient<TextPackageInfo>(new LinePipelineFilter());
                var connected = await client.ConnectAsync(new IPEndPoint(IPAddress.Parse("127.0.0.1"), 4040));
                if (connected)
                {
                    Console.WriteLine("send data!!!");
                    await client.SendAsync(Encoding.ASCII.GetBytes("send data"));
                }
                socketmap.Add(client);

**Comment by kerryjiang** [comment]
The filter is LinePipelineFilter, so you should send a line as a full request which end with "\r\n".
