### ISSUE TITLE
似乎无法定时清空会话。

### ISSUE THREAD

**Issue by su3817806** [kerryjiang/SuperSocket#305]
.ConfigureServices((hostCxt, services) =>
                {
                    services.Configure<ServerOptions>((options) =>
                    {
                        options.ClearIdleSessionInterval = 5;
                        options.IdleSessionTimeOut = 5;
                    });
                })
                .UseClearIdleSession()
                .Build();

会提示ClearIdleSessionMiddleware needs a middleware of ISessionContainer
顺便请问下2.0如何从服务器端推送数据到客户端。
谢谢。

**Comment by kerryjiang** [comment]
`c#`
.UseInProcSessionContainer()
.UseClearIdleSession()

**Comment by kerryjiang** [comment]
There is a sample for server push:
https://github.com/kerryjiang/SuperSocket/tree/master/samples/WebSocketPushServer

**Comment by su3817806** [comment]
> There is a sample for server push:
> https://github.com/kerryjiang/SuperSocket/tree/master/samples/WebSocketPushServer

搞定，谢谢
