### ISSUE TITLE
ConfigureSessionHandler 关闭事件未及时触发

### ISSUE THREAD

**Issue by NHZF** [kerryjiang/SuperSocket#306]
当客户端主动调用close() 方法时，服务端关闭事件未及时触发，大约过了1分多钟才触发关闭事件，如果页面关闭或者刷新会及时触发关闭事件

**Comment by kerryjiang** [comment]
WebSocket服务器还是?普通的Socket服务器？

**Comment by kerryjiang** [comment]
Added a test case to cover this feature and it works as expected:
https://github.com/kerryjiang/SuperSocket/commit/95dddc9d5f326314f2e76838d818fa4fadf645db

**Comment by NHZF** [comment]
WebSocket服务器

**Comment by kerryjiang** [comment]
Adjusted one test case to cover it and it works:
https://github.com/kerryjiang/SuperSocket/commit/135bf59bcc356104bf477a3e1c0e3ef79d65bd3c

**Comment by NHZF** [comment]
![image](https://user-images.githubusercontent.com/33956303/78210393-a9e1dc00-74dc-11ea-94e1-87360789869a.png)

![image](https://user-images.githubusercontent.com/33956303/78210326-6be4b800-74dc-11ea-89be-7925cfde4200.png)
我这边还是不行，不过我提供一些更信息的信息给你

**Comment by kerryjiang** [comment]
你启动代码有点怪。
把echo的代码加进去
https://github.com/kerryjiang/SuperSocket/blob/master/samples/WebSocketServer/Program.cs
然后用这个来测
https://www.websocket.org/echo.html

**Comment by NHZF** [comment]
我重新按照你的流程新建了一个项目，测试结果还是一样
![image](https://user-images.githubusercontent.com/33956303/78219361-eec43d80-74f1-11ea-8560-714fef47cac0.png)
![image](https://user-images.githubusercontent.com/33956303/78219370-f683e200-74f1-11ea-8c17-0f99c7a2ee8d.png)

**Comment by kerryjiang** [comment]
Thanks for your finding!
I have fixed it just now. Could you try it again?

**Comment by NHZF** [comment]
现在关闭事件能及时响应了，到时候能否在NuGet包管理上也更新一下

**Comment by kerryjiang** [comment]
Yes, just released a new package.
