### ISSUE TITLE
Can you provide a decoder like the Netty LengthFieldLeadFrame Decoder

### ISSUE THREAD

**Issue by 491134648** [kerryjiang/SuperSocket#308]
Can you provide a decoder like the Netty LengthFieldLeadFrame Decoder, where packet length sits somewhere in the middle of the packet and can be quickly dropped back or stored in the buffer pool when a packet is broken or glued!

**Comment by kerryjiang** [comment]
I think this one is what you need:
https://github.com/kerryjiang/SuperSocket/blob/master/src/SuperSocket.ProtoBase/FixedHeaderPipelineFilter.cs
https://github.com/kerryjiang/SuperSocket/blob/master/test/Test/FixedHeaderProtocolTest.cs

Just pass in the header size to the constructor and return the body length from the method GetBodyLengthFromHeader(...).

**Comment by 491134648** [comment]
ok，thks！
