### ISSUE TITLE
Crash on simple websocketserver if string is empty.

### ISSUE THREAD

**Issue by imtrobin** [kerryjiang/SuperSocket#309]
Hi, I found a problem. If I send empty string from client, server will crash. I fix it with a check, and now another problem.

When I sent an empty string, the server don't respond until I send another message. it should respond with "empty" the first time.

e.g

client send "hello"
   server reply "hello"
client send ""
   no reply from server. It should reply here
client send ""
   reply  "empty"   

```
var host = WebSocketHostBuilder.Create ()

    .ConfigureWebSocketMessageHandler(async (session, message) =>
    {
        // echo message back to the client, fix to handle empty string or it crash
        await session.SendAsync (message?.Message??"empty")
                                                            .ConfigureAwait (false);
    })
    .ConfigureLogging ((hostCtx, loggingBuilder) =>
    {
        // register your logging library here
        loggingBuilder.AddConsole ();
    })
    .Build ();
await host.RunAsync ()
                    .ConfigureAwait (false);
```

**Comment by kerryjiang** [comment]
Thanks for your finding. Just fixed this problem y this commit:
https://github.com/kerryjiang/SuperSocket/commit/920421ab80df09954ebc760ba0b66b48c622f0a1

**Comment by imtrobin** [comment]
I updated, and it reply part is still not fixed.

**Comment by kerryjiang** [comment]
Did another fix. It should work right now.
