### ISSUE TITLE
下载后3.5的编译是4.0平台的

### ISSUE THREAD

**Issue by ningxiaoixao** [kerryjiang/SuperSocket#31]
是否可以增加对.net 3.5的支持!
谢谢

**Comment by kerryjiang** [comment]
1.6分支有3.5的支持，master分支的3.5支持已经被干掉了。

实在想不出保留.NET 3.5的兼容性的必要性。

**Comment by ningxiaoixao** [comment]
因为我现在用的这个mono 只支持到3.5,
