### ISSUE TITLE
WebSocket 向客户端发送一段比较长的文字时，会出现错误

### ISSUE THREAD

**Issue by NHZF** [kerryjiang/SuperSocket#312]
![image](https://user-images.githubusercontent.com/33956303/78652440-51ec1080-78f4-11ea-8992-da472fb22708.png)

**Comment by NHZF** [comment]
并不是所有的长文本都会报错，比如这一段文字肯定会报错：
这是一段长文本这是一段长文本这是一段长文本这是一段长文本这是一段长文本这是一段长文本

**Comment by kerryjiang** [comment]
I will check this problem today.

**Comment by kerryjiang** [comment]
Just fixed this bug, thanks for your finding!
Please get the latest package (2.0.0-preview3-03) from nuget or the latest source code from github.

**Comment by NHZF** [comment]
thanks
