### ISSUE TITLE
DefaultBootstrap - Failed to create server instance WeChatServer!

### ISSUE THREAD

**Issue by jonny-xhl** [kerryjiang/SuperSocket#314]
- 使用的版本是 1.6.6.1
- framework 版本3.5
以下是我的示例代码，当我调用`bootstrap.Initialize()`的时候就出现最下面那段日志了，着实没懂什么意思，能看出是什么问题吗？
```
private void Form1_Load(object sender, EventArgs e)
        {
            log4net.Config.XmlConfigurator.ConfigureAndWatch(new FileInfo("Config/log4net.config"));
            //声明bootStrap实例
            var bootstrap = BootstrapFactory.CreateBootstrap();
            //初始化
            if (!bootstrap.Initialize())
            {
                SetMessage("Failed to initialize!");
                return;
            }
            //开启服务
            var result = bootstrap.Start();
            if (result == StartResult.Failed)
            {
                SetMessage("Failed to start!");

                return;
            }
            else
            {
                SetMessage("服务器启动成功");
            }
            while (Console.ReadKey().Key==ConsoleKey.Q)
            {
                bootstrap.Stop();
            }
        }
```

>  2020-04-11 22:58:52,122 [1] ERROR DefaultBootstrap - Failed to create server instance WeChatServer!
System.IO.FileNotFoundException: 未能加载文件或程序集“System.Threading, Version=1.0.2787.102, Culture=neutral, PublicKeyToken=31bf3856ad364e35”或它的某一个依赖项。系统找不到指定的文件。
文件名:“System.Threading, Version=1.0.2787.102, Culture=neutral, PublicKeyToken=31bf3856ad364e35”
   在 System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   在 System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   在 System.Type.GetType(String typeName, Boolean throwOnError)
   在 SuperSocket.SocketEngine.DefaultBootstrap.CreateWorkItemInstance(String serviceTypeName, StatusInfoAttribute[] serverStatusMetadata)
   在 SuperSocket.SocketEngine.DefaultBootstrap.InitializeAndSetupWorkItem(WorkItemFactoryInfo factoryInfo)

**Comment by kerryjiang** [comment]
You should reference this assembly:
https://github.com/kerryjiang/SuperSocket/blob/v1.6/Reference/System.Threading.dll

**Comment by jonny-xhl** [comment]
为什么`System.Threading.dll` 需要单独关联引入？这是线程中**dll**吗，为什么没有自动生成呢？

**Comment by kerryjiang** [comment]
我不知道你咋引用的，如果是3.5的项目的话，应该自动引用这个assembly.
