### ISSUE TITLE
WebSocketHostBuilder.Create()是否可以增加一个重载, 传入自定义的WebSockSErvice,SebSocketSession类型

### ISSUE THREAD

**Issue by jason-shi** [kerryjiang/SuperSocket#315]
public static IWebSocketHostBuilder Create<TWebSocketService, TWebSocketSession>()
            where TWebSocketService : WebSocketService 
            where TWebSocketSession : WebSocketSession, new()
        {
            return new InternalWebSocketHostBuilder()
                .ConfigureDefaults()
                .UseSuperSocket<WebSocketPackage, WebSocketPipelineFilter, TWebSocketService>()
                .UseSession<TWebSocketSession>()
                .UseMiddleware<HandshakeCheckMiddleware>()
                .ConfigureServices((ctx, services) =>
                {
                    services.AddSingleton<IPackageHandler<WebSocketPackage>, WebSocketPackageHandler>();
                }) as IWebSocketHostBuilder;
        }

**Comment by kerryjiang** [comment]
Don't you think the host builder's extension method UseSession() is better?

**Comment by jason-shi** [comment]
UseSession() is better, but the WebSocketService can't custom myself.

**Comment by kerryjiang** [comment]
Made an enhancement about that.
https://github.com/kerryjiang/SuperSocket/commit/840d30b1763436115431a24dc20fb7682574b831

``C#
  WebSocketHostBuilder.Create<YourWebSocketService>();
``
