### ISSUE TITLE
2.0 版本 EasyClient 大量傳輸後接收的部分卡死 

### ISSUE THREAD

**Issue by muhman** [kerryjiang/SuperSocket#316]
版本: SuperSocket 2.0
來源: GitHub 直接下載原始碼
情境:
1. 建立 .NetCore 3.1 WinForm AP 1 (SuperSocket.Server 服務端)
2. 建立 .NetCore 3.1 WinForm AP 2 (EasyClient 客戶端+SuperSocket.WebSocket 服務端)
3. 建立多執行序壓測 AP 3

透過 AP3 與 AP2 建立 WebSocket 連線後，大量發送訊息到 AP2，AP2 與 AP1 建立 Socket 連線，當 AP2 收到 WS 訊息後再透過 EasyClient 傳送資料給 AP1，AP1 處理完畢後回送給 AP2再透過 WebSocket 轉發回 AP3。

當在這種情況下運行一陣子後，AP2的 EasyClient 突然無法再觸發 PackageHandler 事件。但是送出部分還是有再執行，用偵錯模式查 PipeChannel 類的 IAsyncEnumerable<TPackageInfo> RunAsync() 方法內的 await _packagePipe.ReadAsync(); 針對接收資料的情況沒有再被執行，但 Task ReadPipeAsync(PipeReader reader) 這段有執行。

是否可以協助確認下這個情況發生的原因，謝謝

**Comment by kerryjiang** [comment]
Which version do you use? Did you try pulling the latest source code?

**Comment by muhman** [comment]
> Which version do you use? Did you try pulling the latest source code?

Hi, I use the 2.0 latest source to build and use locally. But the same test process I use 1.6 version does not have this issue.

Thanks.

**Comment by kerryjiang** [comment]
Does it means:

1) AP1 was working correctly;
2) AP2 was working correctly with the client AP3, but the client in AP2 which communicates with AP1 didn't work correctly;
3) AP3 was working correctly;

**Comment by muhman** [comment]
> Does it mean?
> 
> 1. AP1 was working correctly;
> 2. AP2 was working correctly with the client AP3, but the client in AP2 which communicates with AP1 didn't work correctly;
> 3. AP3 was working correctly;

Yes, Only AP2 the EasyClient receives the AP1 message not working. but AP2 EasyClient sends to AP1 is working. and when I restart the AP2 EasyClient. EasyClient working again.

**Comment by muhman** [comment]
這邊看好像跟 thread  deadlock 有關，調整了一版目前看沒有 receive 卡住的情況了，感謝大神回應 謝謝
