### ISSUE TITLE
IServer中IServiceProvider获取不到已注册对象

### ISSUE THREAD

**Issue by ghost** [kerryjiang/SuperSocket#317]
在IServer中的ServiceProvider中不能获取到程序中其他位置中已注册的接口对象，但程序内Controller中是可以获取的，不知道IServer中的ServiceProvider是否是自己控制的程序域或自己管理的注册对象。

**Comment by SweetXylitol** [comment]
问题应该出现在我自己程序启动时使用了HostBuilder构建了Host，在Startup的ConfigureService中使用的 SuperSocketHostBuilder.Create<StringPackageInfo, CommandLinePipelineFilter>().ConfigurePackageHandler，这样应该是2个Host。如果直接提供在IServiceCollection中扩展的方法就好了。

**Comment by kerryjiang** [comment]
How does your code look like? If the instance of IServer doesn't have correct instance of ServiceProvider, how can the SuperSocketService start?

**Comment by kerryjiang** [comment]
I added a test case to cover this problem.
https://github.com/kerryjiang/SuperSocket/commit/1c3e02d4343d6bfab587e31aad662c050aa2d22e
But it works.

Could you add a test case to describe your problem?

**Comment by SweetXylitol** [comment]
感谢回复。
原因是我使用的方式与SuperSocket升级到2.0版本后提供的示例不一样导致的，代码将在下面粘贴。
因为我创建了2个Host实例导致的。
请问是否可以提供 IServiceCollection和IApplicationBuilder的扩展方法呢？而不只是 HostBuilder的，因为关于SuperSocket的代码是在单独的项目中的，不打算引用并使用HostBuilder。


在 Program.cs 文件， 我使用的是默认的HostBuilder
 Host.**CreateDefaultBuilder**(args)
            .ConfigureWebHostDefaults(action => action.UseStartup<Startup>());

在另外的项目A中，有 IApplicationBuilderExtensions.cs文件，并在Startup中调用了下面的扩展方法

       public static IApplicationBuilder UseServosServer(this IApplicationBuilder app)
        {
            if (app == null) throw new ArgumentNullException(nameof(app));

//**下面的代码是错误的调用，是引起这个问题的原因**
            var host = **SuperSocketHostBuilder.Create**<StringPackageInfo,MLLPService, MLLPFilter>()
    .ConfigurePackageHandler<StringPackageInfo>(async (session, package) =>
    {
        //自己的逻辑代码。
    },
    (s,pe)=> {

        return new ValueTask<bool>(Task.FromResult(true));
    })
    .ConfigureLogging((hostCtx, loggingBuilder) =>
    {
        //loggingBuilder.AddConsole();
    })
    .Build();

            host.RunAsync();
            return app;
        }

**Comment by kerryjiang** [comment]
两个Host实例应该不会互相影响啊？你是说你想在不同的host里面使用同一个ServiceProvider？

**Comment by SweetXylitol** [comment]
在默认Host实例中注册了IAbc接口，SuperSocket的Host中是访问不到的。而我希望访问到。
我创建了IServiceCollection的扩展类，并将HostBuilderExtensions.cs 中的方法移过去是可以的，已经测试。

**Comment by kerryjiang** [comment]
你能Fork一下然后提交你的改动吗？

**Comment by SweetXylitol** [comment]
好的

**Comment by WaldronYou8** [comment]
已提交 Pull Request #325。注：原Github帐号删除了。

**Comment by kerryjiang** [comment]
@WaldronYou8 这个改动好大了，好多东西依赖于Host。呢个否在SuperSocket的services里面再注册一下呢？

**Comment by WaldronYou8** [comment]
> @WaldronYou8 这个改动好大了，好多东西依赖于Host。**能否在SuperSocket的services里面再注册一下呢？**如果需要共享一些状态，难就注册个单例。

这个可以给下具体位置吗？需要在哪里加逻辑？
并且我觉得 ServiceCollectionExtensions 中的入口比较多，可以减少点。

**Comment by kerryjiang** [comment]
在各自的ServiceCollection里面注册单例不行吗？

**Comment by WaldronYou** [comment]
就以单例的方式注册的。与 SuperSocketHostBuilder.cs 中的注册方式一样，只是基于 IServiceCollection扩展。

**Comment by kerryjiang** [comment]
你两边注册的代码贴出来看看

**Comment by WaldronYou** [comment]
https://github.com/WaldronYou/SuperSocket/blob/master/src/SuperSocket.Server/ServiceCollectionExtensions.cs  
这个是从 ServiceCollectionExtensions.cs 中原样复制的逻辑。
只是把扩展方法的 this 修改为了 IServiceCollection

**Comment by WaldronYou** [comment]
使用时需要调用2个方法：
IServiceCollection.AddSuperSocketBase 方法用于加载配置信息。
IServiceCollection.AddSuperSocket（及其重载）用于配置服务。

**Comment by kerryjiang** [comment]
我的意思是，你为什么需要这个改动？就以单例的方式注册的，为什么不行呢？我暂时无法理解。

**Comment by kerryjiang** [comment]
How about this issue right now?

**Comment by kerryjiang** [comment]
Does it work now?

**Comment by loveksmy** [comment]
多年后的我遇到了同样的问题。
 SuperSocketHostBuilder.Create 创建后。

里面都不能调用原来系统容器中已经出入了的接口。
