### ISSUE TITLE
需求：多服务实例支持，并且可在运行中调整

### ISSUE THREAD

**Issue by ghost** [kerryjiang/SuperSocket#323]
2.0版本SuperSocket只能创建1个Server实例（是否有其他方法，但我没有从文档中学习到）。
记得原1.6版本的SuperSocket是支持多个实例配置的。2.0版本建议保留多实例支持。

虽然在程序运行过程中修改appsetting.json是可以实现服务的配置修改，还是希望增加可以在C#代码中获取服务实例并修改配置的代码。

**Comment by kerryjiang** [comment]
不准备支持这样的功能，建议用docker实现多实例。

**Comment by kerryjiang** [comment]
不过也可以考虑支持简化的多实例运行方式，就多个host嘛。

**Comment by kerryjiang** [comment]
主要是docker在应用程序容器这块可以做很多工作，SuperSocket自己做有点多余。

**Comment by kerryjiang** [comment]
这个话题值得讨论。

**Comment by SweetXylitol** [comment]
打算给使用用户提供界面管理功能，并且在1个应用中支持多个服务。
目前没有应用docker。
如果可以在程序中配置并支持多实体将方便很多。
我会考虑docker实现。

**Comment by jeffma** [comment]
建议你使用consul服务，SuperSocket 应该保持KISS原则。

**Comment by kerryjiang** [comment]
It is supported already.
