### ISSUE TITLE
关于sessionclosed回调

### ISSUE THREAD

**Issue by Helius-Sun** [kerryjiang/SuperSocket#324]
请问一下什么情况下会回调sessionclosed事件？我使用wireshark抓包，未检测到四次挥手过程，但是会走sessionclosed回调事件

**Comment by kerryjiang** [comment]
which version? 1.6 or 2.0? Client or server?

**Comment by Helius-Sun** [comment]
Version:1.6.6 
Server

**Comment by kerryjiang** [comment]
What about the CloseReason? It can be found in the logs.

**Comment by Helius-Sun** [comment]
It says socketerror

**Comment by kerryjiang** [comment]
That may means the connection dropped unintended.
