### ISSUE TITLE
使用 FixedHeaderReceiveFilter 來實做傳送檔案的 Socket Server 遇到隨機 Connection Close

### ISSUE THREAD

**Issue by getoutnow2013** [kerryjiang/SuperSocket#326]
實做一個 Client 傳送, Server 接收檔案的架構。
使用了預設的 FixedHeaderReceiveFilter < BinaryRequstInfo > 
Header 的部份為 4 bytes, 作為指令來通知 Server 對應的處理方式
1. PUT: 通知 Server 要開始傳送檔案，建立檔案的 WriteStream
2. DATA: 傳送每一次的 byte buffer，我是設定 length 為 4096
3. PUTE: 通知 Server 關閉檔案的 WriteStream

但是在 Client 傳送檔案內容的 bytes[] 時，總是會不定時遇到 Connection 已經關閉的問題
實在是不曉得到底是 Client 還是 Server 的什麼問題導致連線中斷？

下面為主要的程式碼...謝謝！

FileReceiveFilter class
```
public class FileReceiveFilter : FixedHeaderReceiveFilter<BinaryRequestInfo> {
        public FileReceiveFilter() : base(6) {
        }
        protected override int GetBodyLengthFromHeader(byte[] header, int offset, int length) {
            return (int)header[offset + 4] * 256 + (int)header[offset + 5];
        }
        protected override BinaryRequestInfo ResolveRequestInfo(ArraySegment<byte> header, byte[] bodyBuffer, int offset, int length) {
            return new BinaryRequestInfo(Encoding.ASCII.GetString(header.Array, header.Offset, 4), bodyBuffer.CloneRange(offset, length));
        }
}
```

SockSession class
```
public class SockSession : AppSession<SockSession, BinaryRequestInfo> {
        public string ClientID { get; set; } = "";
}
```

SockServer class
```
public class SockServer : AppServer<SockSession, BinaryRequestInfo> {
        public SockServer() : base(new DefaultReceiveFilterFactory<FileReceiveFilter, BinaryRequestInfo>()) {
            this.NewRequestReceived += OnNewRequestReceived;
        }
        private string _FileName = "";
        private FileStream _fs = null;
        private BinaryWriter _bw = null;
        private int _DataPackCnt = 0;
        private void OnNewRequestReceived(SockSession session, BinaryRequestInfo requestInfo) {
            string sCmd = requestInfo.Key.Trim();
            switch (sCmd) {
                case "PUT":
                    _FileName = Encoding.UTF8.GetString(requestInfo.Body) + ".bak";
                    PrintConsole("PUT FILE:", _FileName);
                    _fs = new FileStream(_FileName, FileMode.Create);
                    _bw = new BinaryWriter(_fs);
                    _DataPackCnt = 0;
                    break;
                case "DATA":
                    if (_bw != null) {
                        _DataPackCnt++;
                        PrintConsole("FILE DATA", _DataPackCnt.ToString(), ":", requestInfo.Body.Length.ToString());
                        _bw.Write(requestInfo.Body);
                    }
                    break;
                case "PUTE":
                    PrintConsole("PUT FILE END:", _FileName);
                    _bw.Flush();
                    _bw.Dispose();
                    _fs.Dispose();
                    break;
            }
    }
}
```

Client 我用 EasyClient 或單純的 Socket Client 結果都一樣
這邊用 Socket Client 作範例
NetClient class
```
public class NetClient {
        private Socket _client = null;
        public void PutFile(string FileName) {
            int buffersize = 4096;
            byte[] fname;
            byte[] buffer;
            FileInfo fi = new FileInfo(FileName);
            if (File.Exists(FileName)) {
                fname = Encoding.UTF8.GetBytes(FileName);
                SendData("PUT", 0, fname);
            } else {
                PrintConsole("PutFile", "File:", FileName, "is not exists.");
                return;
            }
            int iDataPackCnt = 0;
            using (var fs = new FileStream(FileName, FileMode.Open, FileAccess.Read)) {
                using (var br = new BinaryReader(fs)) {
                    buffer = br.ReadBytes(buffersize);
                    while (buffer.Length > 0) {
                        iDataPackCnt++;
                        SendData("DATA", iDataPackCnt, buffer);
                        buffer = br.ReadBytes(buffersize);
                    }
                }
            }
            SendData("PUTE", 0, fname);
        }

        private void SendData(string CmdKey, int DataPackCnt, byte[] Body) {
            CmdKey = CmdKey.PadRight(4);
            ushort iLen = (ushort)Body.Length;
            var baCmd = Encoding.ASCII.GetBytes(CmdKey);
            var baLen = BitConverter.GetBytes(iLen);
            byte[] baAll = baCmd.Concat(baLen).Concat(Body).ToArray();
            baAll[4] = baLen[1]; baAll[5] = baLen[0];
            PrintConsole("SendData", CmdKey, DataPackCnt.ToString(), "- BodyLen:", iLen.ToString(), ", AllLen:", baAll.Length.ToString());
            _client.Send(baAll);
        }
}
```

**Comment by getoutnow2013** [comment]
![TestSuperSocket](https://user-images.githubusercontent.com/24822811/79828458-4b20cb80-83d3-11ea-9c35-322cdf3168aa.png)

左方為 Client, 右方為 Server
測試的檔案是 737 KB，也就是最少需要 184 次 4KB + 1次 1KB 的傳送

可以看到 Client 讀取DATA到第63次(每次4096 bytes)時
Server端接收到57次，此時已發生中斷問題（每次中斷的次數不一定，也有完整送完的情況）

如果 client 在送每一次的 byte array 時，額外加上 Thread.Sleep(100)，則可以順利送完

**Comment by kerryjiang** [comment]
服务器端logs有什么异常吗？最有会有session关闭的log的，那个log里面CloseReason是什么。
另外，你这个文件操作有点吓人，感觉不安全, fileStream打开了，感觉很容出现重点出问题导致，fileStream没有关闭的情况。

**Comment by getoutnow2013** [comment]
![TestSuperSocket423](https://user-images.githubusercontent.com/24822811/80049435-77f4f000-8545-11ea-9ce7-4d7e23dc501d.png)

看 Client 這時送出的長度應該是 4102，但是 Server 顯示預計收的長度是 1024...?

err.log
> 2020-04-23 09:29:59,067 [7] ERROR SockServer-55909147 - Session: feff8bce-990c-4ab4-8578-61404be03780/127.0.0.1:61420
> Max request length: 1024, current processed length: 1026


info.log
> 2020-04-23 09:29:50,609 [1] INFO  SockServer-55909147 - The server instance SockServer-55909147 has been started!
> 2020-04-23 09:29:57,313 [3] INFO  SockServer-55909147 - Session: feff8bce-990c-4ab4-8578-61404be03780/127.0.0.1:61420
> A new session connected!
> 2020-04-23 09:29:59,070 [7] INFO  SockServer-55909147 - Session: feff8bce-990c-4ab4-8578-61404be03780/127.0.0.1:61420
> This session was closed for ProtocolError!

filestream 的確目前會有問題，要完善一點可能是在 SessionClose 時，也進行關閉 filestream 吧
因為設計上，同一個 Client 同時間僅能傳送一個檔案，所以當 Client 關閉時，也進行關閉 filestream 應該可以減少問題吧。

因為目的就是想透過 Socket 做個簡單的檔案傳輸(檔案可能從數KB~數GB不等)
所以如果有比較好的設計 pattern 也請分享一下
謝謝！

**Comment by getoutnow2013** [comment]
後續更新
我後來用 .Net 內建的 Socket Library 重新寫了一個 SocketServer 
用來接收上述 Client (.Net Client or SuperSocket.EasyClient)發送的 PUT/DATA/PUTE 以及發送的 byte array

結果，並不會發生傳送過程隨機 Connection 被中斷的問題，
檔案傳送完畢後，用comp比較結果也是完全相同的。

所以可以確定 SuperSocket v1.6.6 的 FixedHeaderReceiveFilter 是有問題的，
或者不是範例所介紹的 base(6) 及 override GetBodyLengthFromHeader, ResolveRequestInf 就能使用的。

**Comment by kerryjiang** [comment]
maxRequestLength 是 SuperSocket的内置功能，是防止收到超大包而导致更严重的问题。

**Comment by getoutnow2013** [comment]
謝謝！
