### ISSUE TITLE
WebSocket HandshakeValidator passing the Session

### ISSUE THREAD

**Issue by ArvinHsieh** [kerryjiang/SuperSocket#327]
Hi,  Can you consider passing the session in handshakeValidator(p)? because during the handshake phase, we need to use Socket URL the QueryString for verification. Then store some verified info in the session object.  DataContext field can be used to store custom objects?

**Comment by kerryjiang** [comment]
You can access the URL from package:
https://github.com/kerryjiang/SuperSocket/blob/master/src/SuperSocket.WebSocket/HttpHeader.cs
p.HttpHeader.Path


But you also want to assign state to session. Let me think about it.

**Comment by kerryjiang** [comment]
I made this enhancement, thanks for your suggestion.
https://github.com/kerryjiang/SuperSocket/commit/d4e4546beca79ebdacc02a279eee6b2692d315f9

**Comment by ArvinHsieh** [comment]
> I made this enhancement, thanks for your suggestion.
> [d4e4546](https://github.com/kerryjiang/SuperSocket/commit/d4e4546beca79ebdacc02a279eee6b2692d315f9)

Hi, It is very helpful to me. Thank you for considering.
