### ISSUE TITLE
Socket Server received the EasyClient message slow

### ISSUE THREAD

**Issue by muhman** [kerryjiang/SuperSocket#328]
大神您好

想請教使用從 github 下載最新版本的 SuperSocket 2.0，在大量資料連續傳送與接收的測試情況下會發生 EasyClient 傳送給 Server 的訊息延遲了好一段時間 Server 才收到。大致資訊如下。

1.主機A(SocketServer), B(EasyClient) 位於內部區網
2.資料流量約每秒 20mb
3.流程 B 傳送資料至 A，A 處理完成回傳至 B
4.協議使用 FixedHeader

這邊使用日志看到的情況是當 EasyClient 慢慢提升發送訊息的量至 Socket Server 時，一開始 Server 還都是很快就收到處理，當訊息量越大時，例如 EasyClient 呼叫 SendAsync 後記錄時間是 10:10:10，Server 的部分在命令接收處理 ValueTask ExecuteAsync 方法開頭就紀錄得到執行時間是 10:10:40，中間延遲了 30 秒。

想請教這種延遲的情況有可能是什麼原因影響呢? 謝謝

**Comment by 491134648** [comment]
可以做下相关压力测试，看服务端的吞吐量

**Comment by muhman** [comment]
嗯，這是壓測發生的，內網部分沒限制流量，查看CPU使用也蠻低約15~20%

**Comment by kerryjiang** [comment]
receiveBufferSize/sendBufferSize尝试调大看看。另外，能否把你的压测代码开源?

**Comment by muhman** [comment]
> receiveBufferSize/sendBufferSize尝试调大看看。另外，能否把你的压测代码开源?

您好，整理了壓測的檔案提供給您，再請您指導一下這種延遲情況怎麼優化好呢 謝謝
[https://easyupload.io/gem3j2](url)
使用方式
1.開啟 AP1, AP2
2.AP1啟動, AP2啟動
3.執行 LoadTest

目前我本機測試 LoadTest 開 8 thread 五個視窗就會開始延遲，如下
AP2: 2020-04-27 14:54:26.4921 | Trace | ea3399d5b1024141b65bf669d4b89e82 - 發送完成 | 
AP1: 2020-04-27 14:55:47.7567 | Trace | ea3399d5b1024141b65bf669d4b89e82 - 收到訊息 |  
AP1: 2020-04-27 14:55:47.7567 | Trace | ea3399d5b1024141b65bf669d4b89e82 - 處理完成回送 |  
AP2: 2020-04-27 14:56:01.0071 | Trace | 收到 EC 回應 ea3399d5b1024141b65bf669d4b89e82-NN1UDI6B4T1M6URWYAX....

**Comment by kerryjiang** [comment]
有直接Console输出的全部干掉，转用文件日志

**Comment by muhman** [comment]
> 有直接Console输出的全部干掉，转用文件日志

江大，請問 LoadTest 的 Console 日誌拿掉會跟 AP1 與 AP2 資料溝通會延遲是關連嗎? 這個測試傳輸的資料是故意比較大量，會不會就是瓶頸了? 只能將資料減量壓縮呢? 謝謝

**Comment by kerryjiang** [comment]
Console的高频调用会极大的拉低性能

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by muhman** [comment]
> Console的高频调用会极大的拉低性能 Get Outlook for iOS<https://aka.ms/o0ukef>

江大您好，我拿掉Console輸出之後還是會有一樣情況，我在深入追發現當 AP2 送出訊息的時候，其實 AP1 已經有收到 DecodePackage 的解包動作也執行完，但是在 DefaultObjectPipe 這個類裡面的 ValueTask<T> ReadAsync() 隔了一段時間才跑到然後找到對應命令去觸發 ValueTask ExecuteAsync。

追蹤流程如下:
AP2 => 50:00 訊息發送完成
AP1 => 50:01 收到訊息，執行了 DecodePackage(ReadOnlySequence<byte> buffer) 方法
AP1 => 50:01 執行了 DefaultObjectPipe 類的 int Write(T target) 方法
AP1 => 50:30 DefaultObjectPipe 類的 ReadAsync 循環中取得對應的訊息
AP1 => 50:30 執行了  ValueTask ExecuteAsync 方法
AP2 => 50:30 收到回應

DefaultObjectPipe 這個類裡面有使用到 lock，會跟 lock 有關嗎? 目前追到的情況就是實際送出的資料 server 已經有收到也寫入 BufferSegment _current 的 array 內，但是在 ReadAsync 讀取資料出來的時候延遲了，謝謝

**Comment by kerryjiang** [comment]
The server would not try to read the next package from the pipe until the previous page was handled by logic.

Could you log how long it took to send the data back to the client?

**Comment by kerryjiang** [comment]
You need adjust the buffer size for client and server.

**Comment by muhman** [comment]
> You need adjust the buffer size for client and server.

您好，我這邊重新針對 buffer size 去調整 send buffer 貼近每次傳送的資料量大小，然後加大 recevie buffer 後，發現延遲的情況舒緩了，所以目前判斷應該只要調整好適當的 buffer size 應該就可以，謝謝您
