### ISSUE TITLE
v2.0, how to get session by id or get all sessions

### ISSUE THREAD

**Issue by jason-shi** [kerryjiang/SuperSocket#329]
v2.0, i want to send a message an assigned session, but i can't get the session.
v1.6, i can get all sessions by AppServer.GetAllSessions or query session by AppServer.GetSession(id)

**Comment by kerryjiang** [comment]
SessionContainer:
``_serviceProvider.GetSessionContainer();

**Comment by jason-shi** [comment]
thank.
