### ISSUE TITLE
How to use it? - TRequestInfo Filter

### ISSUE THREAD

**Issue by kincjf** [kerryjiang/SuperSocket#33]
Hello!

It really helped to SuperSocket when i working!

We are making file transfer server which included image processing module,
and available with muitiple users at once.

Client : Send compressed file(image), Receive big image file
Server : Receive compressed file(image), Send big image file

So. we're plan to using BinaryRequestInfo and IReceiveFilter(Factory)

My Question is
1. TRequestInfo - readBuffer is shared by all connections in the same appServer instance. To get data what we want using filter(), Cut and get it in shared buffer using [offset, length] parameter?
2. filter(..., toBeCopied, ...) - Could you explain some cases? when using [toBeCopied]? I don't understand just read in documentation. 
3. Is there way to access network stream directly and best example to save file from binary stream?

Thanks to reply it. 
Best regards,

**Comment by kerryjiang** [comment]
Please read the document site at first and check out the samples in QuickStart,
Thanks!

**Comment by kerryjiang** [comment]
Please just use the built-in protocol templates at first:
http://docs.supersocket.net/v1-6/en-US/The-Built-in-Common-Format-Protocol-Implementation-Templates
