### ISSUE TITLE
centos 下跑websocket存在内存泄漏

### ISSUE THREAD

**Issue by xg117** [kerryjiang/SuperSocket#331]
一次200~400个客户端连接websocket，做高频数据分发，跑一段时间，然后关闭，再打开，内存缓慢涨上去，关闭连接内存不减，反复操作内存会一直缓慢涨上去。另外在linux下跑的性能比windows差，linux下cpu高，而且cpu峰值波动大，windows下就挺好的，我换了几个框架都存在这个问题。2.0.0-preview3-04   dotnet core 3.1

**Comment by kerryjiang** [comment]
Which version do you use?
1.6 or 2.0?

**Comment by kerryjiang** [comment]
Could you share the source code of your test projects?

**Comment by xg117** [comment]
是其它原因引起，已经找到。

**Comment by sunnuan** [comment]
> 是其它原因引起，已经找到。

可以说下是什么原因导致吗？现在也一样碰到这个问题呢
