### ISSUE TITLE
Session auth

### ISSUE THREAD

**Issue by kinguru** [kerryjiang/SuperSocket#332]
Hi @kerryjiang 
is it possible to authenticate session before it added to SessionContainer?
I need to check Headers first for tokens and allow or close a session.

**Comment by kinguru** [comment]
Solved. :)

**Comment by kerryjiang** [comment]
How did you do it?
You can use this feature HandshakeValidator:

https://github.com/kerryjiang/SuperSocket/blob/master/src/SuperSocket.WebSocket.Server/HandshakeOptions.cs

**Comment by kinguru** [comment]
Yes, I did use exactly HandshakeValidator :)
I was using previously a PackageHandler, but there is no HttpHeaders and OnConnect/Close is not called after PackageHandler. But with HabdshakeValidator all is fine. 
Thank you!
