### ISSUE TITLE
SuperSocket.WebSocket vs .NET WebSocket

### ISSUE THREAD

**Issue by kinguru** [kerryjiang/SuperSocket#333]
Hi Kerry!
I need your expertise as an expert in Web Sockets implementation in .NET. I know you are a great expert in this!
Is there a big difference between .NET WebSockets implementstion and your SuperSocket?
Which cases do you cover in your product, which is not covered in .NET?

Thanks a lot

**Comment by kerryjiang** [comment]
We develop base on the websocket standard rfc6455, so they may have different APIs, but they should share the same data protocol.

**Comment by kinguru** [comment]
Microsoft says, they are also had implemented rfc6455.
https://docs.microsoft.com/ru-ru/aspnet/core/fundamentals/websockets?view=aspnetcore-3.1
so trying to understand do i really need SuperSocket? hmmm
I see a lot of code written by you, so it should be better than MS?

**Comment by kerryjiang** [comment]
Just two options with different APIs.
