### ISSUE TITLE
使用BeginEndMarkPipeLineFilter，客户端发送消息的问题

### ISSUE THREAD

**Issue by WaldronYou** [kerryjiang/SuperSocket#335]
注：提交代码使用VS16（VS2019），使用VS15解决方案可能不兼容。
代码见：
提交：https://github.com/WaldronYou/SuperSocket/commit/7afe398a61687ab351f4eb2e2f991a00fe1ed431
sample 地址:https://github.com/WaldronYou/SuperSocket/tree/master/samples
-------------------
问题描述：
EasyClient，发送StringPackageInfo，使用 BeginEndMarkPipeLineFilter，
BeginMark 为 HEX 0B 并且 EndMark 为 HEX 1C 0D
client.SendAsync方法执行后，服务端收不到消息

-----使用client.ReceiveAsync情况------
在 client.ReceiveAsync方法执行时，时服务器才收到消息
服务器响应后，程序卡在client.ReceiveAsync方法。

-----使用client.StartReceive情况------
在 client.ReceiveAsync方法执行时，时服务器才收到消息
服务器响应后，Client_PackageHandler事件不能收到消息。

**Comment by WaldronYou** [comment]
补充：
1.使用 HL7Edit 作为接收服务测试的。
2.尝试在 SendAsync方法中增加   await writer.CompleteAsync(); 仍不起作用。
3.虽然这样增加将不支持多次消息发送。

SuperSocket.Channel.PipeChannel<TPackageInfo> 类中方法：
 public override async ValueTask SendAsync(ReadOnlyMemory<byte> buffer)
        {
            try
            {
                await _sendLock.WaitAsync();
                var writer = Out.Writer;
                WriteBuffer(writer, buffer);
                await writer.FlushAsync();

                await writer.CompleteAsync();//增加代码
            }
            finally
            {
                _sendLock.Release();
            }            
        }

**Comment by WaldronYou** [comment]
类似的，使用HL7Edit发送，服务端可以接收连接，但不会调用接收到包的Handler。
不使用HL7Edit，使用SuperSocket的EasyClient和Server也有同样的问题。
暂未知原因。请求帮助。

**Comment by kerryjiang** [comment]
你的BeginMark和EndMark用text encoding没问题？

**Comment by kerryjiang** [comment]
还真没有BeginEndMarkPipelineFilter的test case, 我先加上。
有没有包格式的文档？

**Comment by kerryjiang** [comment]
Added a test for BeginEndMarkPipelineFilter and it works.
I think the problem is at the client.

https://github.com/kerryjiang/SuperSocket/commit/b872f2f701c03d40bfcf88d48b6c4642f3922fb6

**Comment by kerryjiang** [comment]
You client sending code looks problematic and it may hide bugs.
Could you take a look at the piece of the code about sending in the new added test cases?
Just use Span<byte>, which is much more efficient.

**Comment by WaldronYou** [comment]
已解决。
