### ISSUE TITLE
Async

### ISSUE THREAD

**Issue by osmanm** [kerryjiang/SuperSocket#34]
should this change: 
 protected override void ExecuteJsonCommand(TWebSocketSession session, TJsonCommandInfo commandInfo)
        {
            m_AsyncJsonCommandAction.BeginInvoke(session, session.CurrentToken, commandInfo, null, session);
        }

to

 protected override void ExecuteJsonCommand(TWebSocketSession session, TJsonCommandInfo commandInfo)
        {
            m_AsyncJsonCommandAction.BeginInvoke(session, session.CurrentToken, commandInfo, OnAsyncJsonCommandExecuted, session);
        }

from null to OnAsyncJsonCommandExecuted.

**Comment by kerryjiang** [comment]
Suggest you upgrade to SuperSocket 2.0.
