### ISSUE TITLE
Include SuperSocket.Http project into solution

### ISSUE THREAD

**Issue by chucklu** [kerryjiang/SuperSocket#343]
Can not build the test project:
SuperSocket\test\Test\Test.csproj : error NU1105: Unable to find project information for 'D:\GitHub\KerryJiang\SuperSocket\src\SuperSocket.Http\SuperSocket.Http.csproj'. If you are using Visual Studio, this may be because the project is unloaded or not part of the current solution so run a restore from the command-line. Otherwise, the project file may be invalid or missing targets required for restore.

**Comment by kerryjiang** [comment]
But it is there:

https://github.com/kerryjiang/SuperSocket/blob/master/src/SuperSocket.Http/SuperSocket.Http.csproj
https://github.com/kerryjiang/SuperSocket/blob/master/test/Test/Test.csproj

**Comment by chucklu** [comment]
I am using the vs 2019, not vs code.
The project reference only works when you have included the project into solution.
You can check the solution file, https://github.com/kerryjiang/SuperSocket/blob/master/SuperSocket.sln

**Comment by kerryjiang** [comment]
Ok, got it. I just added it. Thank you!
