### ISSUE TITLE
Merge multiple TCP frames from device (PLC) automatically

### ISSUE THREAD

**Issue by Boeckle** [kerryjiang/SuperSocket#349]
I'm trying to send >2000 Bytes from an PLC to my TCP server. The PLC splits the message into multiple frames (max. byte length = 240). I receive all the data but with various results. Sometimes I see all the single frames coming in and the other time some frames are collected. I don't see a pattern why it would sometimes merge the frames and why it wouldn't. 

When sending from a computer client the frames get add together automatically and I do have the full message. Is there any parameter I need to set or should there be a minimum time between the incoming packages?

I'm using V1.6 and disabled the session snapshot. I checked the frames with Wireshark for variations but couldn't find any.

Thanks in advance.

**Comment by kerryjiang** [comment]
The application protocol (over TCP) the PLC uses to communicate with the tcp server should be understood. And you need implement the protocol base on SuperSocket.
