### ISSUE TITLE
Asyn break

### ISSUE THREAD

**Issue by osmanm** [kerryjiang/SuperSocket#35]
This code breaks... the async command is not done executing. the post filter are being called. maybe the filters should be in a command completed event.???

 if (!commandContext.Cancel)
            {
                ExecuteCommand(session, requestInfo);

```
            for (var i = 0; i < filters.Length; i++)
            {
                var filter = filters[i];
                filter.OnCommandExecuted(commandContext);
            }
        }
```

**Comment by kerryjiang** [comment]
Please upgrade to SuperSocket 2.0 to support async better.
