### ISSUE TITLE
core 单词写错了

### ISSUE THREAD

**Issue by Songxt** [kerryjiang/SuperSocket#351]
No **listner** was defined, so this server only can accept connections from the ActiveConnect.

===》listener

**Comment by chucklu** [comment]
You might fork this repository, and fix the typo then send a pull request.
https://github.com/kerryjiang/SuperSocket/blob/f129203ce1dfb04dda361a6e3ce85b48fbbf4897/src/SuperSocket.Server/SuperSocketService.cs#L180
