### ISSUE TITLE
PipelineFilter context null for first message

### ISSUE THREAD

**Issue by markgould** [kerryjiang/SuperSocket#355]
If a client sends a command immediately upon connection, the pipeline filter context is null. I have tracked it down and see why it happens, just not sure how you want to go about correcting it.
 
TcpPipeChannel calls StartTasks in the constructor, so immediately when the channel is created.

The context is set by SuperSockeService.InitializeSession which ends up tracing back to the IChannelCreator.NewClientAccepted event. When we receive this event, we already have the channel, and of course StartTasks has been called. So in this case the pipeline filter is run before it has truly been initialized.

It almost seems like it would be useful to have a Start method on IChannel and then change this code to look something like this:

```
       private async void OnNewClientAccept(Socket socket)
        {
            var handler = NewClientAccepted;

            if (handler == null)
                return;

            IChannel channel = null;

            try
            {
                channel = await _channelFactory(socket);
            }
            catch (Exception e)
            {
                _logger.LogError(e, $"Failed to create channel for {socket.RemoteEndPoint}.");
                return;
            }            

            handler.Invoke(this, channel);
            channel.Start();  //Added this line
        }
```

What do you think?

**Comment by kerryjiang** [comment]
Did a fix just now, could you have a try?

**Comment by markgould** [comment]
I can try it out - are any of these builds being published to your github packages? Or is the best way right now to pull down the latest source and reference?

**Comment by markgould** [comment]
I found the MyGet feed and tested, everything looks good! Thanks!
