### ISSUE TITLE
Where is ValidateClientCertificate method?

### ISSUE THREAD

**Issue by RCristiam** [kerryjiang/SuperSocket#356]
I'm using the beta version and trying to enable TLS/SSL with validation on the server side. According to the [previous](https://docs.supersocket.net/v1-6/en-US/Enable-TLS-SSL-trasnferring-layer-encryption-in-SuperSocket) documentation, It is needed to override **ValidateClientCertificate** method, but I cannot find the class which implements it.

I have cloned the project and seached and still cannot find it. 

May you tell me where is the ValidateClientCertificate method, please?

Thank you in advance,

**Comment by kerryjiang** [comment]
Could you try

`ListtenerOptions.CertificateOptions.RemoteCertificateValidationCallback`
