### ISSUE TITLE
websocket部分客户端掉线（拔网线形式），会影响推送给其它客户端怎么解决

### ISSUE THREAD

**Issue by xg117** [kerryjiang/SuperSocket#357]
Kerry你好，websocket部分客户端掉线（拔网线形式），会中断其他正常客户信息的接收。服务端部署在centos，客户机2台，每台创建256个websocket客户端连接链接服务端，然后其中一台的网线直接拔掉，就会出现有小部分连接在await s.SendAsync(line)发送时间很长，甚至二十几秒，影响了后面其它正常连接客户端接收信息。怎么解决这个问题？尝试用了 
                .UseClearIdleSession()    
                .ConfigureSuperSocket(so => { so.SendTimeout = 1000; })，都没能解决。谢谢！

我修改 SuperSocket-master\samples\WebSocketPushServer 让问题重现，
![image](https://user-images.githubusercontent.com/47174553/84370309-a7051500-ac0a-11ea-849c-271d5462fb8e.png)

**Comment by kerryjiang** [comment]
Did you figure out the problem?

**Comment by xg117** [comment]
首先说明下，我的运行环境不是windows，是linux。我修改了下源码，加了这个客户端心跳包时间，用来及时剔除掉线客户，好像正常了。原来的 LastActiveTime 好像不能很好的处理客户端超时问题。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Kerry Jiang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月16日(星期二) 下午3:36
收件人:&nbsp;"kerryjiang/SuperSocket"<SuperSocket@noreply.github.com&gt;;
抄送:&nbsp;"川"<ylwuchuan@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [kerryjiang/SuperSocket] websocket部分客户端掉线（拔网线形式），会影响推送给其它客户端怎么解决 (#357)





 
Did you figure out the problem?

**Comment by kerryjiang** [comment]
不太理解，你是说LastActiveTime一直在更新即使没有收到任何数据？

**Comment by xg117** [comment]
是的，客户端掉线了，LastActiveTime还一直在刷，而且是长时间在刷，远超超设置的clearIdleSessionInterval，idleSessionTimeOut时间都还在刷，我试过，拔掉网线后，几个小时被拔网线的客户端连接都没被移除。

**Comment by kerryjiang** [comment]
你这个说的有些奇怪，你是用的哪个版本？

**Comment by xg117** [comment]
就用最新版，在centos7.5下运行。

**Comment by kerryjiang** [comment]
你是如何模拟拔掉网线这种场景的？
