### ISSUE TITLE
是否可以将 SessionHandlers 修饰符修改为public？

### ISSUE THREAD

**Issue by WaldronYou** [kerryjiang/SuperSocket#358]
是否可以将 SuperSocket.Server. 修饰符修改为public？
需要在SuperSocket范围外访问该类。

**Comment by kerryjiang** [comment]
Why do you want this? I think SessionHandlers is only used within the server.

**Comment by WaldronYou** [comment]
没有用 SuperSocketHostBuilder 作为Host，使用IServiceCollection注册的服务，但需要处理Session逻辑时，不能访问到 SessionHandlers ，但内部的 Connected 和Closed  Func是注入的，建议开放 SessionHandlers 。

**Comment by kerryjiang** [comment]
Did it.
