### ISSUE TITLE
How to use it at .NEt Core MVC project 

### ISSUE THREAD

**Issue by h0730303779** [kerryjiang/SuperSocket#359]
> It cannot be used in a razor view.
> 
> SuperSocket is a socket server framework.
> 
> Why do you want to use it in a view?

I have the same needs too;

我也有这个需求 我现在 netcore.31 MVC 中启用了   SocketServer 可以使用.
但我没办法 在控制 发消息  我无法注入我的 DeviceSession;
 如果方便的话 能否给个 sample  或者指点几句也是十分感谢的

---- 
   我的场景:
    MVC  直接获取树莓派连接的设备(姑且说是温度器)的当前信息  
   我需要同步返回  因为我是单体程序 不打算用别的解决方案

_Originally posted by @h0730303779 in https://github.com/kerryjiang/SuperSocket/issues/273#issuecomment-645873517_

**Comment by kerryjiang** [comment]
不要考虑同步返回， 你在SuperSocket的Host加入ASPNET MVC就好了。
可以考虑前端用websocket接收服务器端推送消息。

**Comment by h0730303779** [comment]
> 不要考虑同步返回， 你在SuperSocket的Host加入ASPNET MVC就好了。
> 可以考虑前端用websocket接收服务器端推送消息。

不要推荐ws 如果用ws的话 我现在项目是完结状态用的 是signalr  
想优化换ss   server-to-client  等待返回
----
群里有朋友推荐了  不要注入直接用静态的 socket发送

**Comment by kerryjiang** [comment]
Check out this doc please:
https://docs.supersocket.net/v2-0/en-US/Integrate-With-AspNet-And-ABP
