### ISSUE TITLE
System.Exception: Failed to find a service

### ISSUE THREAD

**Issue by TunnelBlanket** [kerryjiang/SuperSocket#36]
Whenever I try to run **SuperSocket.SocketService.exe**, I get the following output:
*Failed to initialize SuperSocket ServiceEngine! Please check error log for more information!*

But I can't seem to find any logs!

I've stored my configuration in **SuperSocket.SocketService.exe.config**, and it looks like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<configSections>
        <section name="superSocket"
        	type="SuperSocket.SocketEngine.Configuration.SocketServiceConfig, SuperSocket.SocketEngine" />
    </configSections>

    <superSocket>
		<servers>
            <server name="LoginServer"
                    serverTypeName="Houdini.HoudiniServer"
                    ip="Any"
                    port="6112">
            </server>
        </servers>
  </superSocket>

</configuration>
```

I'm using Mono version 4.0.2 on OS X, and the NuGet package. All of the assemblies are in the same directory as the executable.

If I try running my program directly, I get the following
```
2015-08-04 04:33:40 ERROR DefaultBootstrap - System.Exception: Failed to find a service for server LoginServer!
  at SuperSocket.SocketEngine.WorkItemFactoryInfoLoader.LoadResult (System.Func`2 serverConfigResolver) [0x0018e] in <filename unknown>:0 
  at SuperSocket.SocketEngine.DefaultBootstrap.Initialize (System.Func`2 serverConfigResolver, ILogFactory logFactory) [0x0008e] in <filename unknown>:0 
2015-08-04 04:33:40 FATAL Houdini.MainClass - Failed to initialize!
```

**Comment by TunnelBlanket** [comment]
Okay, it's making logs now. I don't understand the error though. I've placed all the assemblies in the same directory as my .cs files (HoudiniServer.cs, etc), but I still get the error.

**Comment by kerryjiang** [comment]
The attribute serverTypeName is configured incorrectly.
Could you check out the document website?

**Comment by kerryjiang** [comment]
Configuration issue.
