### ISSUE TITLE
2.0版本中怎么停止和启动服务

### ISSUE THREAD

**Issue by ibcla** [kerryjiang/SuperSocket#360]
2.0版本中怎么停止和启动服务

**Comment by WaldronYou** [comment]
服务使用的是 IHostedService，这个是NetCore启动/停止时自动启动/停止的。
可以参考：
https://docs.microsoft.com/zh-cn/dotnet/architecture/microservices/multi-container-microservice-net-applications/background-tasks-with-ihostedservice

**Comment by kerryjiang** [comment]
Yes, just use Host.

**Comment by kerryjiang** [comment]
You can follow the code in the samples and test project.
