### ISSUE TITLE
1.6版本如何多帧处理

### ISSUE THREAD

**Issue by weiki516** [kerryjiang/SuperSocket#361]
这边出现一种情况:协议是下游终端定义的无法更新，需要同时支持多种协议，目前使用的是自定义协议，现在发现有多帧数据的情况出现，如何处理呢，则Command内处理时发现数据无法接受到第二帧，在过滤器中如何对这种不确定协议的数据进行组合呢，或者说怎样能一次接收一定大小的数据而不是按帧处理呢？官方案例都是针对一种单独协议的

**Comment by chucklu** [comment]
Please refer to https://github.com/kerryjiang/SuperSocket/tree/v1.6/QuickStart/SwitchReceiveFilter

**Comment by weiki516** [comment]
@chucklu 
感谢回复，我看到这个案例是针对多协议的，这个我已经实现，现在的主要问题是多帧如何处理，没有固定长度，部分协议有起始结束符，有的没有，现在只能收到一帧，出现多帧的时候其它帧就丢失了，如何让所有的帧都接收完再处理呢

**Comment by weiki516** [comment]
@kerryjiang  请教多帧如何处理？  一个帧的数据不完整需要多个帧合并处理

**Comment by chucklu** [comment]
@weiki516  https://www.cnblogs.com/yxh168/articles/9033311.html
It's up to your protocol, you'd better use Fixed Header protocol 
https://github.com/kerryjiang/SuperSocket/blob/v1.6/Facility/Protocol/FixedHeaderReceiveFilter.cs

**Comment by weiki516** [comment]
> @weiki516 https://www.cnblogs.com/yxh168/articles/9033311.html
> It's up to your protocol, you'd better use Fixed Header protocol
> https://github.com/kerryjiang/SuperSocket/blob/v1.6/Facility/Protocol/FixedHeaderReceiveFilter.cs

感谢回复，多协议目前无法修改，终端客户定义的，有没有什么办法不根据协议，延迟等待多个帧进入缓存,不论TCP包是否完整，只是多等待下让后面的帧进入缓存后再处理，

**Comment by cocosip** [comment]
内置的Filter是不能满足你的需求的，你需要自己定义。FixedHeaderReceiveFilter代码拷贝过来稍微改一改就应该差不多能用了

**Comment by kerryjiang** [comment]
"现在的主要问题是多帧如何处理，没有固定长度，部分协议有起始结束符，有的没有，现在只能收到一帧".
https://github.com/kerryjiang/SuperSocket/tree/v1.6/QuickStart/SwitchReceiveFilter
应该是PiplelineFilter的切换。

**Comment by kerryjiang** [comment]
无论你多少帧，都应该能正常通信，这就是我们需要应用层通信协议（并非指TCP）的原因。弄清楚你的通信协议，你才能够正确无歧义的通信。
