### ISSUE TITLE
Writing is not allowed after writer was completed

### ISSUE THREAD

**Issue by cocosip** [kerryjiang/SuperSocket#362]
最近在使用SuperSocket做FastDFS的客户端,遇到一点问题。文件下载这块已经解决。#295
现在在文件上传的时候，可能上传的文件比较大，为了避免暴内存。所以是将流文件分批循环写入的。
代码如下:
```c#
//写入文件的相关数据,比如存储 groupName等
 _client.SendAsync(newBuffer).AsTask().Wait();
//文件流写入
using (request.InputStream)
{
    byte[] buffers = new byte[1024 * 1024];
    int r = request.InputStream.Read(buffers, 0, buffers.Length);
    while (r > 0)
    {
         _client.SendAsync(buffers).AsTask().Wait();
         r = request.InputStream.Read(buffers, 0, buffers.Length);
     }
}
```
但是每次上传完一个文件返回了数据之后，当上传第二个文件的时候,就会提示 `Writing is not allowed after writer was completed` 该异常。
当我把写入方式修改掉，直接将整个文件的数据写入的时候,又是正常的。代码如下:
```c#
//buffer已经包含了相关参数,以及整个文件的数据
_client.SendAsync(buffer).AsTask().Wait();
```
大神帮忙看下代码是否有问题
https://github.com/cocosip/FastDFSCore/blob/dev/src/FastDFSCore.Transport.SuperSocket/Transport/SuperSocketConnection.cs#L101

**Comment by kerryjiang** [comment]
为啥这么多Wait()?
有这个错误的话，可能连接出了问题啊。

**Comment by kerryjiang** [comment]
这代码写得，本来就全程异步就好了，为什么弄这个多Wait。

**Comment by cocosip** [comment]
我发现了是我代码的问题。我这里使用了固定长度的byte[] 去读取数据,这样就导致读取到最后一组 byte[]的时候,末尾会被 0x00填充。导致接收的服务器端收到的数据有问题。从而客户端出现连接被关闭或者接收数据格式不正确抛异常的情况。
谢谢大神了！@kerryjiang

**Comment by kerryjiang** [comment]
It seems there are problems in your pipeline filter. I suggest you use the pipeline filter templates directly.
https://github.com/cocosip/FastDFSCore/blob/dev/src/FastDFSCore.Transport.SuperSocket/Transport/SuperSocket/ReceivedPackageFilter.cs

**Comment by cocosip** [comment]
昨晚经过调整已经能正常收发了。但是感觉不是一种最佳的实践方式。我看了SuperSocket的几种 Filter , 由于没有找到太多的示例代码，有些用法不是很明白。 感觉应该是使用 `FixedHeaderPipelineFilter` 结合 NextFilter 或者 是 `PackagePartsPipelineFilter` 。先尝试做做看

**Comment by kerryjiang** [comment]
有没有这个协议的文档? 我看一下协议就知道怎么弄了。

**Comment by cocosip** [comment]
fastdfs没有官方的协议说明， https://blog.csdn.net/qq_26462567/article/details/106877138     这是网友总结出来的,他的协议也比较简单，前面是10字节的头部,后面就是数据包了

**Comment by kerryjiang** [comment]
用FixedHeader就行，你折腾那么复杂干嘛？

**Comment by cocosip** [comment]
FixedHeader是等待整个包的长度全部都接收完成后，才做解包操作，否则数据都存储在缓存区。有超过4G以上的文件，内存不会溢出吗？

**Comment by kerryjiang** [comment]
哦，但你这代码应该还可以简化下。
