### ISSUE TITLE
建议 集成Abp Vnext模块

### ISSUE THREAD

**Issue by LostAsk** [kerryjiang/SuperSocket#363]
abp vnext中有很多很好的继承模块，现在想把supersocket集成到abp vnext，请问该如何集成
https://docs.abp.io/zh-Hans/abp/latest/Getting-Started-Console-Application#hello-world

**Comment by kerryjiang** [comment]
To access the service hosted by ABP or manage the server from ABP?

**Comment by bxjg1987** [comment]
abp vnext是asp.net core应用程序。 和 superSocket一样都是宿主在通用主机IHost上的，它们应该是共享 ServiceProvider的。所以理论上来说abp中可以通过依赖注入访问到 SuperSocketService，通过它可以拿到 superSocket的session的，拿到它应该可以做很多事情。

SuperSocketHostBuilder.Create.......创建并配置supperSocket，它返回一个ISuperSocketHostBuilder接口，它继承IHostBuilder的
asp.net core 创建默认HostBuilder的那几个步骤要手动复制过来，具体在微软官网Host.CreateDefault...里面有说。最后Build 然后Run

这样程序跑起来后 就有个Host实例运行起的，里面有两个IHostedServe，一个是SuperSocketService，另一个是asp.net core那个实现类，它们共享Host的ServiceProvider

因为SuperSocketService是可以继承的，所以在内部可以通过ServiceProvider访问到abp注册进来的服务。
反过来abp也可以通过ServiceProvider注册的各种服务。

理论哈，没实践过。其实abp或superSocket可以考虑互相集成下。两个都是非常优秀的框架。感谢作者的奉献~！

**Comment by bxjg1987** [comment]
如果superSoket是通过为扩展微软的IHostBuider来实现SuperSocketService和相关服务的注册，而不是提供ISuperSocketHostBuilder的方式，可能会更好一点。这样.net core所有东西都容易集成，包括asp.net core 。

**Comment by kerryjiang** [comment]
现在其实是可以的，或者还需要稍微封装一下。等我写个示例代码。

**Comment by bxjg1987** [comment]
ServerHostBuilderAdapter就是来实现这个的吗？ 等大佬的好消息哈！

**Comment by LostAsk** [comment]
等大号好消息 @kerryjiang

**Comment by LostAsk** [comment]
今天看完一整个HOST的启动流程，作者可以搞一个类似 GenericHostBuilderExtensions.ConfigureWebHostDefaults的扩展。。
然后生成socket的Ihost。run方法作者应该已经重写过了

**Comment by sagaii** [comment]
> 现在其实是可以的，或者还需要稍微封装一下。等我写个示例代码。

示例代码啥时候出呀？

**Comment by kerryjiang** [comment]
You can reuse the existing hostBuilder and initialize a SuperSocketHostBuilder using it. Then you can do whatever you want.
Try this new API within beta5.

```csharp
hostBuilder.AsSuperSocketHostBuiler()
```

**Comment by Akira3Chou** [comment]
> You can reuse the existing hostBuilder and initialize a SuperSocketHostBuilder using it. Then you can do whatever you want. Try this new API in beta5.
> 
> ```cs
> hostBuilder.AsSuperSocketHostBuiler()
> ```

Im trying to access abp's services in supersocket 2.0 command, but hostBuilder.AsSuperSocketHostBuiler() does not work it out for me...
Is there any way to share the abp's services to the supersocket built in the HostedSerice?
