### ISSUE TITLE
Is it possible to use dependency injection in AppSession?

### ISSUE THREAD

**Issue by ErikXu** [kerryjiang/SuperSocket#364]
I want to inject my services to my app seesion. but `UseSession<MySession>()` throw an execption:

```
'MySession' must be a non-abstract type with a public parameterless constructor in order to use it as parameter 'TSession' 
in the generic type or method 'HostBuilderExtensions.UseSession<TSession>(ISuperSocketHostBuilder)'
```

**Comment by kerryjiang** [comment]
Somebody else asked for the same feature. I will implement this change soon.
A PR is welcome.

**Comment by kerryjiang** [comment]
I just implemented it and release a new nuget package includes this enhancement.
Please take a look.

**Comment by ErikXu** [comment]
Greate news. I am going to check now, and give you feedback as soon as posibile.

**Comment by ErikXu** [comment]
Works well. Thanks!
