### ISSUE TITLE
多服务实例能同时支持SuperSocketService和WebSocketService吗

### ISSUE THREAD

**Issue by xxdotnet** [kerryjiang/SuperSocket#365]
MultipleServerHostBuilder同时构建SuperSocketService和WebSocketService

**Comment by kerryjiang** [comment]
Yes, of course. Did you find any problem about that?

**Comment by xxdotnet** [comment]
![image](https://user-images.githubusercontent.com/5773051/86720558-b899db00-c057-11ea-9e61-13a18a83000a.png)
   @kerryjiang 启用UseCommand就会报以下异常，求助大神帮忙看下
![image](https://user-images.githubusercontent.com/5773051/86720736-e54df280-c057-11ea-9dbf-4c36d07e7612.png)

**Comment by kerryjiang** [comment]
I found some problems. Probably can fix it in a couple days.

**Comment by xxdotnet** [comment]
@kerryjiang 好的，谢谢，等您更新哦
还有一个问题，关于WEBSOCKET
![image](https://user-images.githubusercontent.com/5773051/86722796-d5371280-c059-11ea-81dd-4d380681ea67.png)
单独实例运行是正常的。这个服务用的命令过滤器是基于IPackageMapper
![image](https://user-images.githubusercontent.com/5773051/86723160-39f26d00-c05a-11ea-9aa4-00190ab370b1.png)
如果不注入又会报错哦
![image](https://user-images.githubusercontent.com/5773051/86723373-6ad2a200-c05a-11ea-8c4c-4361f4a38d33.png)

**Comment by kerryjiang** [comment]
Added a test case for it:
        public async Task TestMultipleServerHost()

**Comment by xxdotnet** [comment]
非常感谢，这个版本近期会更新到NUGET吗

**Comment by kerryjiang** [comment]
已经更新beta3
