### ISSUE TITLE
2.0的文档会继续完善吗？

### ISSUE THREAD

**Issue by bxjg1987** [kerryjiang/SuperSocket#367]
我详细看了1.6和2.0的文档，发现2.0的文档不是很全，目前我准备使用1.6版，2.0的文档后续会写完整吗？

**Comment by kerryjiang** [comment]
当然，您需要哪方面的文档？

**Comment by bxjg1987** [comment]
嗯。我再看看 练练手~ 因为看到1.6的文档比2.0的丰富，有些概念换了名字。 我再研究下~ 非常感谢哈！
