### ISSUE TITLE
ConfigureSessionHandler extension not found

### ISSUE THREAD

**Issue by kinguru** [kerryjiang/SuperSocket#368]
Dear Kerry,
i was using SuperSocket from NuGet repository 2.0.0-preview3-05 and it has "ConfigureSessionHandler" extension.

Currently i start using your WebSocket Server in other project and can't find anymore this NuGet package version and "ConfigureSessionHandler" extension method in recent package 2.0.0-beta3

Also missing extensions: UseInProcSessionContainer, UseClearIdleSession

![image](https://user-images.githubusercontent.com/54497/87645651-77d84b00-c756-11ea-8026-9729d2272546.png)

**Comment by kerryjiang** [comment]
I think it had been changed to "UseSessionHandler(...)"

**Comment by kerryjiang** [comment]
Do you still have problem?

**Comment by kinguru** [comment]
Thank you, I've found it in other class, as you had mentioned21 июл. 2020 г. 20:16 пользователь Kerry Jiang <notifications@github.com> написал:
Do you still have problem?
