### ISSUE TITLE
 UseSession or th UseSessionFactory, won't activate my session type,

### ISSUE THREAD

**Issue by mago-pablo** [kerryjiang/SuperSocket#369]
Hello, I have updated to the latest nuget of the websocket server, and now the UseSession<T>() or th UseSessionFactory, won't activate my session type, I logged the IAppSession type and always get WebsocketSession. 

![image](https://user-images.githubusercontent.com/54640353/87748693-38444a00-c7bc-11ea-9171-311312898b22.png)

Could it be posible that the default GenericSessionFactory<WebSocketSession> is getting located instead of the type I am providing?

Best regards.

**Comment by kerryjiang** [comment]
It seems like a bug, let me check this problem.

**Comment by kerryjiang** [comment]
I just fixed this problem.
You can get the latest package from MyGet:
https://www.myget.org/feed/Packages/supersocket

**Comment by mago-pablo** [comment]
Thank you very much for such quick response, I have tested the fix, and now it is working as expected.
