### ISSUE TITLE
Async ExecuteJsonCommand

### ISSUE THREAD

**Issue by osmanm** [kerryjiang/SuperSocket#37]
instead of this: m_AsyncJsonCommandAction.BeginInvoke(session, session.CurrentToken, commandInfo, OnAsyncJsonCommandExecuted, session);

would this work? :  var t = Task.Factory.StartNew
                     (() =>
                     {
                         ExecuteAsyncJsonCommand(session, session.CurrentToken, commandInfo);
                     });
                t.Wait();
            }

you do not have access to  session.CurrentToken its in the main thread or seperate thead. this would ensure that this:
 for (var i = 0; i < filters.Length; i++)
            {
                var filter = filters[i];

```
            filter.OnCommandExecuting(commandContext);

            if (commandContext.Cancel)
                break;
        }
```

is called after the command is finished. please advise.

**Comment by kerryjiang** [comment]
Suggest you upgrade to SuperSocket 2.0.
