### ISSUE TITLE
EasyClient 'ConnectAsync' support bind client endpoint

### ISSUE THREAD

**Issue by cocosip** [kerryjiang/SuperSocket#371]
EasyClient ConnectAsync method now only support config remote endpoint , would support the binding client endpoint?

**Comment by kerryjiang** [comment]
Oh yes, somebody asked this feature before. It is in my todo list.

**Comment by kerryjiang** [comment]
This feature has been added. But it has not been released in any beta nuget package for now.
But you can use the nightly release build package in myget:
https://www.myget.org/feed/Packages/supersocket

https://github.com/kerryjiang/SuperSocket/blob/7f5cafa3bdf62493a1dae5806baa61733999bc80/test/SuperSocket.Tests/ClientTest.cs#L121-L124

**Comment by kerryjiang** [comment]
Close this issue for now. Reopen it if you find this feature doesn't work.
