### ISSUE TITLE
Address already in use on Linux (.NET Core)

### ISSUE THREAD

**Issue by kinguru** [kerryjiang/SuperSocket#374]
Dear Kerry,
I observing an issue with WebSocket 2.0.0-beta3 from NuGet on port binding.  
Steps to reproduce:
1. configure few ports to listen on: 80, 24080 for http and 443, 24443 for https in config file
2. run service in Linux

Actual result:
Service tries to bind to same port twice. First try is successfull, second throws an exception.
![image](https://user-images.githubusercontent.com/54497/88780738-1c657e80-d194-11ea-9ad1-0dbe7f2e5696.png)

Expected result:
Address/ports are binded without exceptions in log.

**Comment by kerryjiang** [comment]
Is it possible the ports have been taken by other applications already?

**Comment by kinguru** [comment]
Port is taken by your application :) it binds twice30 июл. 2020 г. 03:07 пользователь Kerry Jiang <notifications@github.com> написал:
Is it possible the ports have been taken by other applications already?

**Comment by kerryjiang** [comment]
Could you add a test case in SuperSocket's test project to reproduce it?

**Comment by kerryjiang** [comment]
Did a fix just now.
Could you get the nightly build version from the myget?
https://www.myget.org/feed/supersocket/
2.0.0-beta7-gb77c04d71a

**Comment by kerryjiang** [comment]
Reopen it if you still has this problem.
