### ISSUE TITLE
NuGet package for 1.6.7

### ISSUE THREAD

**Issue by Ch0senOne** [kerryjiang/SuperSocket#375]
@kerryjiang 
Could you please publish 1.6.7 version as a NuGet package? The latest published is 1.6.6.1 and it doesn't have the latest bug fix.

**Comment by kerryjiang** [comment]
Is it easy for you to upgrade SuperSocket 2.0 or just build from the source code by yourself?

**Comment by Ch0senOne** [comment]
Isn't 2.0 still in beta? And as far as I understand it targets .netstandard, but my project is using .NET framework 4.5.2
I could build it of course, but would like to avoid adding dlls to source control.

**Comment by kerryjiang** [comment]
Yes, it is still in beta. But it's the time to try it out. I wouldn't make another nuget package release for 1.6.
