### ISSUE TITLE
how to enable tls1.3?

### ISSUE THREAD

**Issue by zqhhn** [kerryjiang/SuperSocket#376]
ERR_SSL_OBSOLETE_VERSION

After chrome to upgrade to the 84 version, enabled by default Tls1.3 encryption protocol, abandoned Tls1.2 、1.1、1.0 agreement, because **the browser server (TIs1.2) do not agree with the client (Tls1.3) cryptographic protocol** leads to shake hands

**Comment by kerryjiang** [comment]
Which version of SuperSocket do you use?

**Comment by zqhhn** [comment]
1.6.6.0

**Comment by kerryjiang** [comment]
Check out this:
https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls

**Comment by kerryjiang** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.security.authentication.sslprotocols?view=netframework-4.8

Try this:

ServicePointManager.SecurityProtocol = ServicePointManager.SecurityProtocol | 12288;

**Comment by zqhhn** [comment]
It does't work. I am worried that TLS1.3 is not supported by 1.6.6.

**Comment by kerryjiang** [comment]
You need make change by yourself and upgrade the projects to .NET 4.8. It is the clear path to support TLS 1.3. One user already did it.

**Comment by kerryjiang** [comment]
Upgraded the projects to 4.8 and add a case for TLS1.3 over here
https://github.com/kerryjiang/SuperSocket/blob/f0b85082764bb1307d9dfb9bc6bda4a38ac53c78/SocketEngine/AsyncStreamSocketSession.cs#L208
