### ISSUE TITLE
BufferList不支持Add方法 为什么在UdpSocketServer.cs的89行调用Add方法呢

### ISSUE THREAD

**Issue by gemSender** [kerryjiang/SuperSocket#38]

**Comment by chucklu** [comment]
master分支上的代码吗？

**Comment by chucklu** [comment]
/// <summary>
        /// Adds an item to the <see cref="T:System.Collections.Generic.ICollection`1" />.
        /// </summary>
        /// <param name="item">The object to add to the <see cref="T:System.Collections.Generic.ICollection`1" />.</param>
        /// <exception cref="System.NotSupportedException"></exception>
        public void Add(ArraySegment<byte> item)
        {
            throw new NotSupportedException();
        }

貌似确实是这样

**Comment by gemSender** [comment]
master貌似还没开发完成， 先用1.6版本吧
