### ISSUE TITLE
该委托必须有一个目标(且仅有一个目标)

### ISSUE THREAD

**Issue by tangming579** [kerryjiang/SuperSocket#381]
SuperSocket作为服务端，与客户端采用TCP短连接，当客户端数量较多且同时发送消息给服务时，使用AppSession.TrySend方法发送消息回复报错，信息如下：

System.ArgumentException: 该委托必须有一个目标(且仅有一个目标)。
   在 SuperSocket.SocketBase.SessionHandler`2.BeginInvoke(TAppSession session, TParam value, AsyncCallback callback, Object object)
   在 SuperSocket.SocketBase.AppServerBase`2.OnSessionClosed(TAppSession session, CloseReason reason)
   在 SuperSocket.SocketBase.AppServer`2.OnSessionClosed(TAppSession session, CloseReason reason)
   在 SuperSocket.SocketBase.AppServerBase`2.OnSocketSessionClosed(ISocketSession session, CloseReason reason)
   在 System.Action`2.Invoke(T1 arg1, T2 arg2)
   在 SuperSocket.SocketEngine.SocketSession.OnClosed(CloseReason reason)
   在 SuperSocket.SocketEngine.AsyncSocketSession.OnClosed(CloseReason reason)
   在 SuperSocket.SocketEngine.SocketSession.FireCloseEvent()
   在 SuperSocket.SocketEngine.SocketSession.OnSendEnd(Boolean isInClosingOrClosed)
   在 SuperSocket.SocketEngine.SocketSession.StartSend(SendingQueue queue, Int32 sendingTrackID, Boolean initial)
   在 SuperSocket.SocketEngine.SocketSession.TrySend(ArraySegment`1 segment)
   在 SuperSocket.SocketBase.AppSession`2.InternalTrySend(ArraySegment`1 segment)
   在 SuperSocket.SocketBase.AppSession`2.TrySend(Byte[] data, Int32 offset, Int32 length)

**Comment by kerryjiang** [comment]
SessionClosed事件的处理是否声明了两次？

另外 SuperSocket 1.6 版本不在维护，建议升级 2.0.

**Comment by tangming579** [comment]
谢谢，确实是因为订阅了两次SessionClosed，2.0 您没有发布到NuGet吗

**Comment by kerryjiang** [comment]
已发布多个测试版，请选中包含预发布版本

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
