### ISSUE TITLE
2.0 websocket ping/pong

### ISSUE THREAD

**Issue by fengbozs** [kerryjiang/SuperSocket#383]
大渔，你好！
       我在使用2.0版本websocket时发现，当客户端发送ping包时，服务器回复的pong包值为139，调试下来发现是收到ping后直接修改ping包的code进行回复，但是OpCodeByte在进行  |  操作时，还是ping值的 OpCodeByte，导致回复了错误code。重新创建pack进行回复，运行正常。

**Comment by kerryjiang** [comment]
Thanks for your finding, I will fix it ASAP.

**Comment by kerryjiang** [comment]
This bug has been fixed in the beta 6.
