### ISSUE TITLE
SuperSocket.WebSocket.Server 2.0.0-Beta 5 UsePerMessageCompression Exception 

### ISSUE THREAD

**Issue by newonejoe** [kerryjiang/SuperSocket#384]
Exception:

> fail: IChannel[0]
>       Protocol error
> System.Exception: Problem happened when decode with the extension permessage-deflate.
>  ---> System.IO.InvalidDataException: The archive entry was compressed using an unsupported compression method.
>    at System.IO.Compression.Inflater.Inflate(FlushCode flushCode)
>    at System.IO.Compression.Inflater.ReadInflateOutput(Byte* bufPtr, Int32 length, FlushCode flushCode, Int32& bytesRead)
>    at System.IO.Compression.Inflater.ReadOutput(Byte* bufPtr, Int32 length, Int32& bytesRead)
>    at System.IO.Compression.Inflater.InflateVerified(Byte* bufPtr, Int32 length)
>    at System.IO.Compression.DeflateStream.ReadCore(Span`1 buffer)
>    at SuperSocket.WebSocket.Extensions.Compression.WebSocketPerMessageCompressionExtension.Decode(WebSocketPackage package)
>    at SuperSocket.WebSocket.FramePartReader.PayloadDataReader.Process(WebSocketPackage package, Object filterContext, SequenceReader`1& reader, IPackagePartReader`1& nextPartReader, Boolean& needMoreData)
>    --- End of inner exception stack trace ---
>    at SuperSocket.WebSocket.FramePartReader.PayloadDataReader.Process(WebSocketPackage package, Object filterContext, SequenceReader`1& reader, IPackagePartReader`1& nextPartReader, Boolean& needMoreData)
>    at SuperSocket.ProtoBase.PackagePartsPipelineFilter`1.Filter(SequenceReader`1& reader)
>    at SuperSocket.WebSocket.WebSocketDataPipelineFilter.Filter(SequenceReader`1& reader)
>    at SuperSocket.Channel.PipeChannel`1.ReaderBuffer(ReadOnlySequence`1& buffer, SequencePosition& consumed, SequencePosition& examined)
>    at SuperSocket.Channel.PipeChannel`1.ReadPipeAsync(PipeReader reader)

Server Code:

  ```
class Program
    {
        static async Task Main(string[] args)
        {
            var host = WebSocketHostBuilder.Create()
                     .UseCommand<StringPackageInfo, StringPackageConverter>(commandOptions =>
                     {
                     //Register commands one by one
                     commandOptions.AddCommand<ADD>();
                     })
                     // Message Compression
                     .UsePerMessageCompression()
                     .ConfigureAppConfiguration((hostCtx, configApp) =>
                     {
                         configApp.AddInMemoryCollection(new Dictionary<string, string>
                         {
                        { "serverOptions:name", "TestServer" },
                        { "serverOptions:listeners:0:ip", "Any" },
                        { "serverOptions:listeners:0:port", "4040" }
                         });
                     })
                     .ConfigureLogging((hostCtx, loggingBuilder) =>
                     {
                         loggingBuilder.AddConsole();
                     }).Build();
            // run host
            await host.RunAsync();
        }
    }

class ADD : IAsyncCommand<WebSocketSession, StringPackageInfo>
{
    public async ValueTask ExecuteAsync(WebSocketSession session, StringPackageInfo package)
    {
        var result = package.Parameters
            .Select(p => int.Parse(p))
            .Sum();

        await session.SendAsync(result.ToString());
    }
}

// Convert WebSocketPackage to OtherPackage
class StringPackageConverter : IPackageMapper<WebSocketPackage, StringPackageInfo>
{
    public StringPackageInfo Map(WebSocketPackage package)
    {
        var pack = new StringPackageInfo();
        var arr = package.Message.Split(' ', 3, StringSplitOptions.RemoveEmptyEntries);
        pack.Key = arr[0];
        pack.Parameters = arr.Skip(1).ToArray();
        return pack;
    }
}

```

Test Client
Chrome Extension Simpe Websocket Client - Catch Exception
![image](https://user-images.githubusercontent.com/7491073/90585331-32041c00-e207-11ea-9e14-905c2387776e.png)

**Comment by kerryjiang** [comment]
Thanks for your finding!
This bug has been fixed in the beta 6.
