### ISSUE TITLE
TcpChannelCreator.Start 异常

### ISSUE THREAD

**Issue by hezhangbo** [kerryjiang/SuperSocket#386]
调用host.RunAsync就会收到下面的错误
Topshelf v4.2.1.215, .NET Framework v3.1.7
info: SuperSocketService[0]
      The listener [Ip=Any, Port=4040, Security=None, Path=, BackLog=0, NoDelay=False] has been started.
fail: TcpChannelCreator[0]
      The listener[Ip=Any, Port=4040, Security=None, Path=, BackLog=0, NoDelay=False] failed to start.
System.Net.Sockets.SocketException (10048): 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at SuperSocket.Server.TcpChannelCreator.Start()
fail: SuperSocketService[0]
      Failed to listen Ip=Any, Port=4040, Security=None, Path=, BackLog=0, NoDelay=False.

但是用工具连接4040又可以连接上，通信也是正常的

下面的是创建Host的方法
        private IHostBuilder CreateSocketServerBuilder()
        {
            return SuperSocketHostBuilder.Create<StringPackageInfo, CommandLinePipelineFilter>()
                   .UseCommand((commandOptions) =>
                   {
                       //注册指令
                       commandOptions.AddCommand<Communication.Command.echo>();
                   })
                   .UseHostedService<Communication.MyServer<StringPackageInfo>>()
                   .ConfigureSuperSocket(options =>
                   {
                       options.Name = "ToDo CommunicationServer";
                       options.AddListener(new ListenOptions { Ip = "Any", Port = 4040 });
                   })
                   .ConfigureLogging((hostCtx, loggingBuilder) =>
                   {

                   });
        }
var socketHost = CreateSocketServerBuilder().Build();
socketHost.RunAsync();

**Comment by kerryjiang** [comment]
According the logs below, there were two listeners with the same port tried to start. The first one succeeded, so the second one failed.

Do you leave a listener in the configuration? So there are two adding the one added by the code.  
-----------------
info: SuperSocketService[0]
The listener [Ip=Any, Port=4040, Security=None, Path=, BackLog=0, NoDelay=False] has been started.
fail: TcpChannelCreator[0]
The listener[Ip=Any, Port=4040, Security=None, Path=, BackLog=0, NoDelay=False] failed to start.

**Comment by hezhangbo** [comment]
我发现
2.0.0-beta6使用options.Listeners = new List<ListenOptions> { new ListenOptions { Ip = "Any", Port = 4040 } };出现上面的错误，
2.0.0-beta5使用options.Listeners = new[] { new ListenOptions { Ip = "Any", Port = 4040 } };不会出现上面的错误

**Comment by kerryjiang** [comment]
What about this line:
```csharp
options.AddListener(new ListenOptions { Ip = "Any", Port = 4040 });
```

**Comment by yxggithub** [comment]
> What about this line:
> 
> ```cs
> options.AddListener(new ListenOptions { Ip = "Any", Port = 4040 });
> ```

也不行

**Comment by MingShanshui** [comment]
应该是在SuperSocketHostBuilder.cs文件里的RegisterDefaultServices(HostBuilderContext builderContext, IServiceCollection servicesInHost, IServiceCollection services)方法，判断是否定义HostedService有问题，注释掉这一行就不会侦听两次
//RegisterDefaultHostedService(servicesInHost);

**Comment by kerryjiang** [comment]
Did a fix just now.
Could you get the nightly build version from the myget?
https://www.myget.org/feed/supersocket/
2.0.0-beta7-gb77c04d71a

**Comment by kerryjiang** [comment]
Close it for now. Reopen it if it has not been fixed please.
