### ISSUE TITLE
FixedHeaderPipelineFilter当解包失败时，如何丢弃当前传输的数据，下一包重新接收

### ISSUE THREAD

**Issue by 491134648** [kerryjiang/SuperSocket#388]
因为我们iot设备开发人员组合数据包或者传输时相关数据包丢失或不完整，导致服务端解析失败，这种包是没法拼凑正常数据包的，只能把所接收到的数据丢弃，在FixedHeaderPipelineFilter中怎么实现这种解包方式呢？

**Comment by kerryjiang** [comment]
那你的协议设计应设计容错，而不是简单的直接使用FixedHeaderPipelineFilter。总之你要告诉SuperSocket如何恢复到正常状态。

**Comment by 491134648** [comment]
有什么方式告诉supersocket如何恢复导致正常状态，调用reset吗？

**Comment by kerryjiang** [comment]
你不告诉SS, 它咋知道怎么恢复？

**Comment by kerryjiang** [comment]
这种恢复逻辑也应定义在你的协议解析里面。

**Comment by kerryjiang** [comment]
TCP是流是数据，前面的数据出错，后面的数据肯定出错，一般情况你不知道如何恢复到正确状态的。如果你知道数据是如何错的，那就应该去解决客户端不能按照协议发送的问题，或者将这部分容错逻辑定义在你的协议之中成为协议的一部分。

**Comment by kerryjiang** [comment]
Did a fix just now.
Could you get the nightly build version from the myget? 
https://www.myget.org/feed/supersocket/
2.0.0-beta7-gb77c04d71a

**Comment by 491134648** [comment]
嗯，我试试！
