### ISSUE TITLE
How to implement the global ServiceLocator pattern?

### ISSUE THREAD

**Issue by 491134648** [kerryjiang/SuperSocket#390]
I registered my instructions through MTCommandAttribute, and when the app launched, I injected the commands into the ioc container via autofac, and I wanted to unpack them in the decodePackage of FitsedSizePipelineFilter, so I needed a global servicelocation, How do I get the global serviceProvider or autofac's IContainer.

`  public void Register(ContainerBuilder builder, ITypeFinder typeFinder, IConfiguration config)
        {
            //find startup tasks provided by other assemblies
            var commands = typeFinder.FindClassesOfType<IPackage>();
            if (commands.Any())
            {
                foreach(var item in commands)
                {
                    MTCommandAttribute commandAttribute = item.GetCustomAttribute<MTCommandAttribute>();
                    if (commandAttribute != null)
                    {
                        builder.RegisterType(item).Keyed<IPackage>(commandAttribute.MsgId);
                    }
                }
            }
        }`

`
 /// <summary>
    /// 注册指令
    /// </summary>
    [MTCommand("0x01")]
    public class RegisterPackage:BasePackage,IPackage
    {
        /// <summary>
        /// 纬度
        /// </summary>
        public float Lat { get; set; }
        /// <summary>
        /// 经度
        /// </summary>
        public float Lng { get; set; }
        /// <summary>
        /// 管理卡号
        /// </summary>
        public long AdminCardNo { get; set; }
        public override void DecodePackage(ref JT808MessagePackReader buffer)
        {
            base.DecodePackage(ref buffer);
            AdminCardNo = buffer.ReadUInt32();
            IMSI = buffer.ReadASCII(15);
            Lat = buffer.ReadFloat();
            Lng = buffer.ReadFloat();
        }
    }
`

`protected override IPackage DecodePackage(ref ReadOnlySequence<byte> buffer)
        {
            string cmdNo ="0x"+HexUtil.DoHexDump(buffer.FirstSpan, 25, 1);
            JT808MessagePackReader jT808MessagePack = new JT808MessagePackReader(buffer.FirstSpan);
            jT808MessagePack.Decode();
            if (jT808MessagePack.CheckXorCodeVali)
            {
                IPackage package = ServiceLocator.GetService<IPackage>(cmdNo);
                package.DecodePackage(ref jT808MessagePack);
                return package;
            }
            else
            {
                return null;
            }
        }`

` public class ServiceLocator
    {
        public static IContainer Current { get; set; }

        public static T GetService<T>()
        {
            return Current.Resolve<T>();
        }
	}`

**Comment by kerryjiang** [comment]
Can you use IServiceProvider instead? I think it can be used in the most places.

**Comment by 491134648** [comment]
用到了autofa的key、name服务，IServiceProvider没有这功能

**Comment by kerryjiang** [comment]
Did you try getting the container from the service provider?

```csharp
var serviceContainer = serviceProvider.GetService<IContainer>();
```
