### ISSUE TITLE
When a Session is closed, how do I know what caused it? Similar to CloseReason of 1.6.

### ISSUE THREAD

**Issue by MingShanshui** [kerryjiang/SuperSocket#393]

**Comment by kerryjiang** [comment]
Yes, I am adding CloseReason back in SuperSocket 2.0

**Comment by kerryjiang** [comment]
Added it back already.
Please check out the nightly build packages:
https://www.myget.org/feed/Packages/supersocket

**Comment by kerryjiang** [comment]
Check out beta 7 please!
