### ISSUE TITLE
It is suggested to add send / receive queue in session

### ISSUE THREAD

**Issue by bxjg1987** [kerryjiang/SuperSocket#394]
Session maintains the session between the client and the server, and the messages sented/received are also part of the session. It is recommended to define queues for sented/received messages in session.

- Memory level thread safe queues, such as BlockingCollection<T> can be used by default
- It also provides integrated message queuing, such as RabbitMQ
- The queue size is limited by default, and you can also configure the queue size at startup.

Since messages are sent and received asynchronously, by default, it is not possible to determine which sent message matches which reply message. If there is queue support, it can be sent in order. When the message is received, it will send a startling message.

session是在客户端和服务端保持会话的，发送/接收的消息也属于会话的一部分。建议在session中分别为发送/接收的消息定义队列。
默认情况下可以使用内存级别的线程安全的队列，如：BlockingCollection<T>
也提供集成消息队列，如：RabbitMQ
队列默认限制大小，也可以在启动时配置队列大小。
由于消息在发送和接收时是异步的，所以默认情况下，无法确定哪条发送的消息与哪条回复的消息是匹配的。若有队列的支持，则可以按顺序发送，当接收到消息时，才发送吓一跳消息。

**Comment by kerryjiang** [comment]
There are queues already. The underlying pipeline is a queue.

**Comment by bxjg1987** [comment]
thanks
