### ISSUE TITLE
如何得到ISessionContainer呢，_serviceProvider.GetSessionContainer 返回是null

### ISSUE THREAD

**Issue by jj91821** [kerryjiang/SuperSocket#395]
运行samples WebSocketServer 项目出错，_serviceProvider.GetSessionContainer()返回是空的。
改为用 IServer.GetSessionContainer() 也是空的。
那么怎么样才能从IServiceProvider中得到全部客户端呢？

**Comment by bxjg1987** [comment]
Program里配置
.UseInProcSessionContainer()//必须使用这个，否则通信过程中获取session容器为空

**Comment by jj91821** [comment]
> 
> 
> Program里配置
> .UseInProcSessionContainer()//必须使用这个，否则通信过程中获取session容器为空

可以了，O(∩_∩)O谢谢

**Comment by kerryjiang** [comment]
Yes, you figured it out by yourself. Sorry for my late response.
