### ISSUE TITLE
nuget版本需要更新，会调用两次 StartListenAsync方法

### ISSUE THREAD

**Issue by dingjianwan** [kerryjiang/SuperSocket#397]
你好，nuget版本2.0.0-beta6 和github源码不一致，什么时候能更新。

源码上SuperSocket.Server  AppSession  方法是这样 protected override ValueTask OnSessionClosedAsync(CloseEventArgs e)

nuget版本是 protected override ValueTask OnSessionClosedAsync(EventArgs e) 

而且nuget版本，是调用两次 StartListenAsync方法。

**Comment by dingjianwan** [comment]
`public class SocketCore
    {
        public static void Init() {
            var host = SuperSocketHostBuilder.Create<StringPackageInfo>()
            .UseHostedService<WcsServer<StringPackageInfo>>()
            .UsePipelineFilter<PipelineFilter>()
            .UsePackageHandler((s, p) => {
                //(s as SocketSession).Handler(p.Key);
                //var result = 0;
                //SessionInstance.Instance.Handler(s, p.Key);
                var bytes = AutofacHelper.Resolve<ISessionManager>().Handler(s, p.Key);
                if (bytes.Count() > 0) {
                    s.SendAsync(bytes);
                    //s.SendAsync(Encoding.UTF8.GetBytes(result.ToString()));
                }
                return new ValueTask();
            }, (s, e) => { return new ValueTask<bool>(true); })

            //host.ConfigureLogging((hostCtx, loggingBuilder) => {
            //    loggingBuilder.AddConsole();
            //});
            .ConfigureSuperSocket(options => {
                //options.Listeners = new List<ListenOptions> { new ListenOptions { Ip = "Any", Port = 4040 } };
            }).UseSession<WcsSession>().StartAsync();

            //host.ConfigureServices((hostContext, services) => {
            //    //services.AddTransient<IProtocolAnalysis, WCSProtocolAnalysis>();//可以注入一些方法
            //});
            //host.StartAsync();

        }
    }

在  public void Configure(IApplicationBuilder app, IWebHostEnvironment env) { 方法调用SocketCore.Init()`

**Comment by kerryjiang** [comment]
You can get the nightly build packages from here:
https://www.myget.org/feed/Packages/supersocket

"调用两次 StartListenAsync方法"
是怎么回事？

**Comment by chucklu** [comment]
How to use `https://www.myget.org/feed/Packages/supersocket`? It's not accessible via browser, also can not be used as a nuget package source. 
The gallery link should be this https://www.myget.org/gallery/hearthstone, and when you click connect feed on web page. It will provide link like https://www.myget.org/F/hearthstone/api/v3/index.json, this link could be used as nuget package source.

I supposed to get a link like  https://www.myget.org/F/supersocket/api/v3/index.json, however it did not work.

**Comment by kerryjiang** [comment]
Try this:

`
dotnet add package SuperSocket.Server --version 2.0.0-beta7-gdb1c0dc2b8 --source https://www.myget.org/F/supersocket/api/v3/index.json
`

**Comment by chucklu** [comment]
https://www.myget.org/F/supersocket/api/v3/index.json works, I forgot to tick `include prerelease`.

**Comment by dingjianwan** [comment]
> You can get the nightly build packages from here:
> https://www.myget.org/feed/Packages/supersocket
> 
> "调用两次 StartListenAsync方法"
> 是怎么回事？
![1](https://user-images.githubusercontent.com/17694635/93982107-6abd8500-fdb3-11ea-8e60-c8dbe29bf257.png)

就是用nuget beta6版本显示这样。如果引用源码项目，没有TcpChannelCreator后面的错误

**Comment by jj91821** [comment]
> 
> 
> https://www.myget.org/feed/supersocket/package/nuget/SuperSocket.Server
> 
> Try this:
> `dotnet add package SuperSocket.Server --version 2.0.0-beta7-g271d806a5e --source https://www.myget.org/F/supersocket/api/v3/index.json`

SuperSocket.WebSocketServer.beta7 一样有问题，只要添加 UseHostedService 注册自己的服务就会启动两次。

**Comment by kerryjiang** [comment]
Check out beta 7 please!
