### ISSUE TITLE
现在已经正在使用此 SocketAsyncEventArgs 实例进行异步套接字操作

### ISSUE THREAD

**Issue by shllove** [kerryjiang/SuperSocket#40]
hi, 用的类库是最新的1.6.5.0， 但是一样出现此问题，运行一段时间后出现

2015-11-10 19:50:12,601 [14712] ERROR PWSS:90_a.b.c.d - Session: 87b5fd71-6844-403f-80e8-3440900b9b1b/a1.b1.c1.d1:8323
Unexpected error
System.InvalidOperationException: "现在已经正在使用此 SocketAsyncEventArgs 实例进行异步套接字操作。";
   在 System.Net.Sockets.SocketAsyncEventArgs.StartOperationCommon(Socket socket)
   在 System.Net.Sockets.Socket.ReceiveAsync(SocketAsyncEventArgs e)
   在 SuperSocket.SocketEngine.AsyncSocketSession.StartReceive(SocketAsyncEventArgs e, Int32 offsetDelta) 位置 d:\WorkShop\SuperSocket\v1.6\SocketEngine\AsyncSocketSession.cs:行号 148

**Comment by kerryjiang** [comment]
Could you send the assembly "SuperSocket.SocketEngine.dll" you current use to my email address?
kerry-jiang@hotmail.com

**Comment by kerryjiang** [comment]
@shllove hello, I commit a fix just now. Could you get the latest source code of branch v1.6 and see if it works?

**Comment by shllove** [comment]
1.6分支中没看见有新的内容，麻烦告诉我下修改了些什么东西或者发我一个patch？ 谢谢。

**Comment by kerryjiang** [comment]
拉1.6分支最新代码。
________________________________

**Comment by kerryjiang** [comment]
There are two commits on Nov 11, 2015.

**Comment by kerryjiang** [comment]
From the other user's feed back, this issue has been fixed in the latest code of SuperSocket branch v1.6.

**Comment by shllove** [comment]
2015年11月11日在supersocket的V1.6分支上没有更新，V1.6的更新历史只有11月6日，麻烦检查下，谢谢。

**Comment by kerryjiang** [comment]
Hello, could you check it from the page of v1.6?
https://github.com/kerryjiang/SuperSocket/tree/v1.6

![Uploading @6X~D[D~ZJJLYQZOTOF0U_G.jpg…]()

**Comment by mmaohq** [comment]
我在.net framework4.7.2上使用1.6.6.1版本，但是仍然出现了这个错误
`System.InvalidOperationException
Message："现在已经正在使用此 SocketAsyncEventArgs 实例进行异步套接字操作。
Stack：   在 System.Net.Sockets.SocketAsyncEventArgs.StartConfiguring()
   在 System.Net.Sockets.SocketAsyncEventArgs.SetBufferInternal(Byte[] buffer, Int32 offset, Int32 count)
   在 SuperSocket.ClientEngine.AsyncTcpSession.SetBuffer(ArraySegment`1 bufferSegment)
   在 SuperSocket.ClientEngine.ClientSession.SuperSocket.ClientEngine.IBufferSetter.SetBuffer(ArraySegment`1 bufferSegment)
   在 SuperSocket.ClientEngine.EasyClientBase.OnSessionDataReceived(Object sender, DataEventArgs e)
   在 SuperSocket.ClientEngine.AsyncTcpSession.ProcessReceive(SocketAsyncEventArgs e)
   在 System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
   在 System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   在 System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)`
