### ISSUE TITLE
UseCommand 报异常

### ISSUE THREAD

**Issue by XIO-OIX** [kerryjiang/SuperSocket#401]
![image](https://user-images.githubusercontent.com/31812077/94357988-280bed80-00d0-11eb-863a-9540852c5b74.png)

**Comment by chucklu** [comment]
https://github.com/kerryjiang/SuperSocket/blob/master/src/SuperSocket.Command/CommandMiddlewareExtensions.cs#L56
```C#
   where TPackageInfo : class, IKeyedPackageInfo<TKey>
```
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/where-generic-type-constraint

The generic parameter `TextPackageInfo` you used  did not match the constraint.

**Comment by chucklu** [comment]
You could try with https://github.com/kerryjiang/SuperSocket/blob/master/src/SuperSocket.ProtoBase/StringPackageInfo.cs
Or write your custom package info which implemented the generic interface https://github.com/kerryjiang/SuperSocket/blob/master/src/SuperSocket.ProtoBase/IKeyedPackageInfo.cs

**Comment by XIO-OIX** [comment]
I see, Thank you
