### ISSUE TITLE
SuperSocketService HandleSession throw  a exception 

### ISSUE THREAD

**Issue by XIO-OIX** [kerryjiang/SuperSocket#402]
![image](https://user-images.githubusercontent.com/31812077/94360530-7aeda100-00e0-11eb-8546-439bf488714d.png)
line 338, _packageHandlingScheduler is null
but when i sent the second time from tcp client ,it's ok

**Comment by chucklu** [comment]
Please check your log file if there is a warning log as `The PackageHandler cannot be found.`, you might need to figure out why packageHandler is null after executing `serviceProvider.GetService<IPackageHandler<TReceivePackageInfo>>()
                ?? _middlewares.OfType<IPackageHandler<TReceivePackageInfo>>().FirstOrDefault();` 
https://github.com/kerryjiang/SuperSocket/blob/master/src/SuperSocket.Server/SuperSocketService.cs#L97
```C#
 var packageHandler = serviceProvider.GetService<IPackageHandler<TReceivePackageInfo>>()
                ?? _middlewares.OfType<IPackageHandler<TReceivePackageInfo>>().FirstOrDefault();

            if (packageHandler == null)
            {
                Logger.LogWarning("The PackageHandler cannot be found.");
            }
            else
            {
                var errorHandler = serviceProvider.GetService<Func<IAppSession, PackageHandlingException<TReceivePackageInfo>, ValueTask<bool>>>()
                ?? OnSessionErrorAsync;

                _packageHandlingScheduler = serviceProvider.GetService<IPackageHandlingScheduler<TReceivePackageInfo>>()
                    ?? new SerialPackageHandlingScheduler<TReceivePackageInfo>();
                _packageHandlingScheduler.Initialize(packageHandler, errorHandler);
            }
```

**Comment by XIO-OIX** [comment]
Thank you, that's work
In HostBuilder, I added the UsePackageDecoder but removed  the UsePackageHandler
