### ISSUE TITLE
FixedHeaderPipelineFilter PipeChannel

### ISSUE THREAD

**Issue by XIO-OIX** [kerryjiang/SuperSocket#403]
![image](https://user-images.githubusercontent.com/31812077/94362104-9dd18280-00eb-11eb-8b66-83ff784bc3d2.png)
1、自定义MyPipelineFilter
2、tcp client 如果发送一次错误数据（如：00 00 01 61 62），再发送正确数据（如：00 00 02 61 62）都无法识别，如果持续发送错误消息，3个字节的消息头会完全错误，必须重新连接才可以
调试后发现：
![image](https://user-images.githubusercontent.com/31812077/94362114-ab870800-00eb-11eb-8575-acc44d01f233.png)
3、在接受到错误消息后，_foundHeader会被置为true，并且返回null
![image](https://user-images.githubusercontent.com/31812077/94362123-b5a90680-00eb-11eb-924d-4f0c9639b910.png)
4、在PipeChannel的468行每次检测packageInfo == null 都为true，导致474行的reset无法执行
请问这种情况该如何处理，希望当我发送满足格式的数据时可以被识别

**Comment by chucklu** [comment]
You'd better upload a sample project to your public git repository, then it would be easier to do the troubleshooting.

**Comment by XIO-OIX** [comment]
https://github.com/XIO-OIX/SuperSocketPractice.git

**Comment by XIO-OIX** [comment]
> You'd better upload a sample project to your public git repository, then it would be easier to do the troubleshooting.

https://github.com/XIO-OIX/SuperSocketPractice.git

**Comment by chucklu** [comment]
How do you define your protocol？

**Comment by XIO-OIX** [comment]
> How do you define your protocol？

implement FixedHeaderPipelineFilter，the header contains 3 bytes，the first byte represent the request's type,the next 2 bytes represent the length of the body, And the body  is a text string

when is sent  00 00 01 61 ,represent 'a'
but if there is any exception that causes more or less bytes that do not match the content length
even if the correct data is sent later，it‘s still unrecognized

**Comment by chucklu** [comment]
Please enable the log feature on server side first.

**Comment by kerryjiang** [comment]
It seems the data client sends doesn't follow the protocol you defined in your server.

https://github.com/XIO-OIX/SuperSocketPractice/blob/785b4e70a17e87a84f41f6e2cd6ee5ec2bd29157/TcpClient/Program.cs#L47-L50

**Comment by chucklu** [comment]
add debug info for GetBodyLengthFromHeader method
https://github.com/XIO-OIX/SuperSocketPractice/blob/dev/SuperSocketPro/PipelineFilters/MyPipelineFilter.cs#L20
```C#
  protected override int GetBodyLengthFromHeader(ref ReadOnlySequence<byte> buffer)
        {
            var array = buffer.ToArray();
            var str = string.Join(" ", array.Select(x => x.ToString("X2")));
            Console.WriteLine(str);

            var reader = new SequenceReader<byte>(buffer);
            reader.Advance(1); // skip the first byte
            reader.TryReadBigEndian(out short len);

            Console.WriteLine($"{nameof(len)} = {len}");

            return len;
        }
```
then you will get the output as following:
00 00 01
len = 1
00 00 01
len = 1
62 00 00
len = 0
01 61 00
len = 24832

The body length you parsed is 24832(0x6100), the server is waiting for your data to complete a package.

**Comment by chucklu** [comment]
You'd better use https://en.wikipedia.org/wiki/Cyclic_redundancy_check to confirm the package integrity.
You can check the example here https://www.lammertbies.nl/comm/info/crc-calculation

**Comment by XIO-OIX** [comment]
> package

Yes，I got the same result，I know I Sent the wrong data
I want to know how to restore the recognition of the correct data after sending the wrong data

**Comment by chucklu** [comment]
You know you send the wrong data, why you decode it successfully? You can just **throw exception** when you decode the wrong data, then it will trigger the following code, and the server will close the connection.
https://github.com/kerryjiang/SuperSocket/blob/master/src/SuperSocket.Channel/PipeChannel.cs#L405

Send wrong data is not allowed, that's why we need the protocol. The client and server should follow the protocol, otherwise it's not allowed to communicate.

**Comment by zhangjingru** [comment]
> 

SuperSocket是否有足够的健壮性处理错误的协议？比如当接收到错误的长度 SuperSocket只能等接收数据达到这个错误的长度，而不是超时报错
