### ISSUE TITLE
WebSocket opening handshake was canceled

### ISSUE THREAD

**Issue by JavierParral** [kerryjiang/SuperSocket#407]
I am trying to configure wss but i get error on handshake was canceled my angular 9 app here its my code

`           var config = new RootConfig();
            var serverConfig = new ServerConfig
            {
                Name = "localhost",
                Ip = "Any",
                Port = 8088,
                Mode = SocketMode.Tcp,
                Security = "tls12",
                Certificate = new CertificateConfig
                {
                    FilePath = SslPath,
                    Password = SslKey,
                    ClientCertificateRequired = true
                },
            };
            `

**Comment by kerryjiang** [comment]
I don't think you need this:
ClientCertificateRequired = true

It is for the scenario where a certificate from client is required by the server side.

**Comment by JavierParral** [comment]
Thks, I get no errors but I got another issue the event NewSessionConnected its not fire-up but SessionClosed do.

Thks.

**Comment by kerryjiang** [comment]
Check the test case in 1.6. I think it is covered.

**Comment by LeMinhTanTMA** [comment]
how about you
