### ISSUE TITLE
TCP health check

### ISSUE THREAD

**Issue by XIO-OIX** [kerryjiang/SuperSocket#408]
Is there any documentation for TCP health checks

**Comment by kerryjiang** [comment]
What do you mean TCP healthy check? If you mean something at the TCP level, this link may help you:
https://en.wikipedia.org/wiki/Keepalive

**Comment by XIO-OIX** [comment]
I mean is there any API for healthy check in the framework or we need to implement it ourselves

**Comment by kerryjiang** [comment]
Which kind of healthy check do you mean?

**Comment by XIO-OIX** [comment]
the session closed event cannot be triggered when client disconnect with an exception

**Comment by kerryjiang** [comment]
Take a look at this piece of code:

https://github.com/kerryjiang/SuperSocket/blob/aaccaf9261f44637e9f77c2a4aa28ec7ff4ee79c/test/SuperSocket.Tests/MainTest.cs#L233-L283

I will add one doc about to configure low level socket options.

**Comment by XIO-OIX** [comment]
It's ok. thank you
Another question. when the session is created. I need to save the client's identification information in the session. I don't know which field is available. How should I do.

**Comment by kerryjiang** [comment]
When a session was created,  you cannot get other client identity information than ip and port because no data had been received from the client.

**Comment by joyswing** [comment]
Has this feature been documented in the latest version?
