### ISSUE TITLE
NuGet missing SocketEngine DLL

### ISSUE THREAD

**Issue by Baccanno** [kerryjiang/SuperSocket#41]
Hi when getting 1.6.5 on NuGet this is what we get in the nupkg : 
```   
      <reference file="SuperSocket.Common.dll" />
      <reference file="SuperSocket.SocketBase.dll" />
      <reference file="SuperSocket.Facility.dll" />
```

When trying to launch the example : 

```if (!appServer.Setup(2012)) //Setup with listening port```

It fails saying that it can't find SuperSocket.SocketEngine.dll, 

Plus you specify on your doc that 
"Add SuperSocket's dll (SuperSocket.Common.dll, SuperSocket.SocketBase.dll, SuperSocket.SocketEngine.dll) in this project's reference"

Why is Facility.dll referenced instead of SocketEngine in NuGet ? It really seems like a simple typo to me :)

Thanks

PS : When adding the DLL manually to the reference it works

**Comment by bigsupersniper** [comment]
just Install-Package SuperSocket.Engine with NuGet

**Comment by Baccanno** [comment]
Did the job.

**Comment by stoffeastrom** [comment]
I have the same problem but it doesn't get solved by adding the `SuperSocket.SocketEngine.dll`

I'm just trying to start it programmatically by

```
var appServer = new AppServer();
//Setup the appServer
if (!appServer.Setup(9000//Setup with listening port
```
it throws on the `appServer.Setup(9000)` line

**Comment by kerryjiang** [comment]
What's the exception?

**Comment by stoffeastrom** [comment]
System.IO.FileNotFoundException: Could not load file or assembly 'SuperSocket.SocketEngine' or one of its dependencies. The system cannot find the file specified.||File name: 'SuperSocket.SocketEngine'||   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)||   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)||   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)||   at System.Type.GetType(String typeName, Boolean throwOnError)||   at SuperSocket.SocketBase.AppServerBase`2.SetupBasic(IRootConfig rootConfig, IServerConfig config, ISocketServerFactory socketServerFactory) in d:\WorkShop\SuperSocket\v1.6\SocketBase\AppServerBase.cs:line 345||   at SuperSocket.SocketBase.AppServerBase`2.Setup(IRootConfig rootConfig, IServerConfig config, ISocketServerFactory socketServerFactory, IReceiveFilterFactory`1 receiveFilterFactory, ILogFactory logFactory, IEnumerable`1 connectionFilters, IEnumerable`1 commandLoaders) in d:\WorkShop\SuperSocket\v1.6\SocketBase\AppServerBase.cs:line 583||   at SuperSocket.SocketBase.AppServerBase`2.Setup(IServerConfig config, ISocketServerFactory socketServerFactory, IReceiveFilterFactory`1 receiveFilterFactory, ILogFactory logFactory, IEnumerable`1 connectionFilters, IEnumerable`1 commandLoaders) in d:\WorkShop\SuperSocket\v1.6\SocketBase\AppServerBase.cs:line 565||   at SuperSocket.SocketBase.AppServerBase`2.Setup(String ip, Int32 port, ISocketServerFactory socketServerFactory, IReceiveFilterFactory`1 receiveFilterFactory, ILogFactory logFactory, IEnumerable`1 connectionFilters, IEnumerable`1 commandLoaders) in d:\WorkShop\SuperSocket\v1.6\SocketBase\AppServerBase.cs:line 619

**Comment by kerryjiang** [comment]
When you debug the exception, please check the inner exception if it has.

**Comment by stoffeastrom** [comment]
`e.InnerException` is null :/

**Comment by kerryjiang** [comment]
Can you find the dll "SuperSocket.SocketEngine.dll" in your application root?

**Comment by stoffeastrom** [comment]
Yes, but there seems to be something weird the output window says it can load 

```
'iService4.exe' (CLR v4.0.30319: iService4.exe): Loaded 'C:\StartupApplication\bin\Debug\SuperSocket.Common.dll'. Cannot find or open the PDB file.
'iService4.exe' (CLR v4.0.30319: iService4.exe): Loaded 'C:\StartupApplication\bin\Debug\SuperSocket.SocketBase.dll'. Cannot find or open the PDB file.
```
but it hasn't tried loading the `SuperSocket.SocketEngine.dll`

**Comment by stoffeastrom** [comment]
No, it's not copied into the `bin` as you suggested.. so something weird.. will keep digging

**Comment by stoffeastrom** [comment]
Manually copying it over to the `bin` fixes it.

**Comment by stoffeastrom** [comment]
I had to add a reference in the code else it doesn't get copied :(

```
//force copy to `bin`
var test = new SuperSocket.SocketEngine.Configuration.SocketServiceConfig();
```
