### ISSUE TITLE
SupperSocket.ClientEngine, FixedHeaderReceiveFilter，接收Body长度为0时。 

### ISSUE THREAD

**Issue by yangzhinong** [kerryjiang/SuperSocket#411]
> Got it， 你是说的body length ＝ 0的场景吧。
> OK， 以前有个用户提过，但是当时忘了改。
> Let me fix it now

我项目是 .net4.7.2 nuget引入SupperSocket.ClientEngine（0.10.0）,和SupperSocket.ProtoBase（1.7.0.17）。

但在接受服务器发过来的包时，如果Body是零长度（只有头时）,会出现无法读取取数据。
能否指出正确的用法？
代码如下
public class MyReceiveFilter : FixedHeaderReceiveFilter<MyPackageInfo>
       {
        public MyReceiveFilter() : base(Consts.PROTOCOL_HEAD_LEN)
        {
        }
        public override MyPackageInfo ResolvePackage(IBufferStream bufferStream)
       {
            try
            {
                var bytes = new byte[bufferStream.Length];
                // bufferStream.Read(bytes, 0, bytes.Length);  //这里困惑 当body长度为0时,无法读出数据， 暂以下两行代替。
                var data = bufferStream.Buffers.Last().Array; 
                Buffer.BlockCopy(data, 0, bytes, 0, bytes.Length); //这样不知道有没有后续问题？ 
                
                MyPackageInfo res = new MyPackageInfo();
                using (var ms = new System.IO.MemoryStream(bytes))
                using (var reader = new System.IO.BinaryReader(ms))
                {
                    res.Key = Encoding.ASCII.GetString(reader.ReadBytes(Consts.PROTOCOL_KEY_LEN))?.TrimEnd();
                    res.BodyEncodeType = (Enums.EnuBodyEncodeType)reader.ReadByte();
                    res.ReqRes = (Enums.EnuReqRes)reader.ReadByte();
                    res.SubCmd = reader.ReadInt32();
                    res.StatusCode = (Enums.EnuResponseCode)reader.ReadInt16();
                    res.NoUse = reader.ReadInt16();
                    res.Length = reader.ReadInt32();
                    if (res.Length > 0)
                        res.Body = reader.ReadBytes(res.Length);
                    else
                        res.Body = new byte[0];
                }

                res.DoResolveFixData();
                return res;
            }
            catch (Exception ex)
            {
                ClsLog.Error(ex);
                return new MyPackageInfo { Key = "Error" };
            }
        }

        protected override int GetBodyLengthFromHeader(IBufferStream bufferStream, int length)
        {
            bufferStream.Skip(length - 4);
            var len = bufferStream.ReadInt32(littleEndian: true);
            if (len > short.MaxValue)
            {
                ClsLog.Warn($"解析数据包超过{short.MaxValue}, 大小为: {len}");
            }
            return len;
        }
    }

_Originally posted by @yangzhinong in https://github.com/kerryjiang/SuperSocket/issues/47#issuecomment-706994283_

**Comment by kerryjiang** [comment]
I have no idea about this problem. And I don't maintain the old version of my libraries right now.
I suggest upgrade everything to SuperSocket 2.0.
