### ISSUE TITLE
supersocket.udp

### ISSUE THREAD

**Issue by billkun** [kerryjiang/SuperSocket#412]
using SuperSocket.Udp 不存在的命名空间 2.0-beta6

**Comment by kerryjiang** [comment]
I haven't released any package which includes this package.
SuperSocket.Udp is still under the way.

**Comment by kerryjiang** [comment]
It is out. Check out beta 7 please.
https://docs.supersocket.net/v2-0/en-US/UDP-Support-in-SuperSocket
