### ISSUE TITLE
如何手动处理粘包？我们协议比较奇葩，PipelineFilter不能满足。

### ISSUE THREAD

**Issue by w405287435** [kerryjiang/SuperSocket#413]
包头：AC AA CC 0D 00 04     （00 04是长度，每条固定10字节）
包尾：CA

这个情况用BeginEndMarkPipelineFilter会有问题，  包体部分可能会包含尾部标识CA，造成数据接收不全。
我该如何处理啊。。。

**Comment by chucklu** [comment]
https://www.cnblogs.com/chucklu/p/6428615.html

**Comment by chucklu** [comment]
@w405287435  Please read the article, and try to implement it first.

**Comment by w405287435** [comment]
@chucklu  你好，文章中提到

0x02+用户数据+0x03，如果出现0x03即被替换为0x1B+0xE8

那帧尾的0x03也会转义成0x1B+0xE7吧。。。。是不是还有可能出现接收不全的现象？

第一次使用supersocket，希望大佬指点一下。。。。卡在这了半天了

**Comment by chucklu** [comment]
@w405287435  Escape character only apply to the **user data**, 0x02+**UserData**+0x03.

**Comment by w405287435** [comment]
谢谢，我目前改成FixedSizePipelineFilter方式解决了，这个转义方式是在是没整明白，希望以后可以搞个DEMO给我们参考下。
