### ISSUE TITLE
Command needs DI

### ISSUE THREAD

**Issue by goldli** [kerryjiang/SuperSocket#414]
Command is a very useful capability. But, it's very hard to use . for example :

   `public class Login : CommandBase<ServiceAppClientContext, RequestInfo>
    {
        public override void ExecuteCommand(ServiceAppClientContext session, RequestInfo requestInfo)
        {
            if (requestInfo.Data is LoginInfo loginInfo)
            {
                var userName = loginInfo.LoginUser;
                session.Logger.Info($"try login from {session.RemoteEndPoint}  with {userName}");
                
                if (!string.IsNullOrEmpty(userName))
                {
                   
                    var psw = ................

                    if (!loginInfo.LoginPsw.Equals(psw))
                    {
                        session.Logger.Info("login failed, wrong password.");
                        return;
                    }
            }
            else
            {
                session.Logger.Info("login failed. unknown request data.");
            }
        }
    }`

as you see, if we write a log , we should get the Logger reference from 'session' ,  why not using a DI to do that ? And DI can extend command much more easier, otherwise, if we want a database operation , what should we do then  ? using a singleton  db object?

**Comment by kerryjiang** [comment]
I thought it is working. Let me add a test case to cover this feature.

https://github.com/kerryjiang/SuperSocket/blob/master/test/SuperSocket.Tests/AutofacTest.cs

**Comment by goldli** [comment]
Itis based on 2.0?

**Comment by kerryjiang** [comment]
Yes.
