### ISSUE TITLE
希望Unity 2017.x 能使用SuperSocket.Client

### ISSUE THREAD

**Issue by SPingels** [kerryjiang/SuperSocket#416]

**Comment by kerryjiang** [comment]
SuperSocket.Client is a netstandard2.1 library. I am not sure if an application developed by Unity 2017.x can use it.

**Comment by kerryjiang** [comment]
Did you hear any commitment from Unity saying when they will support netstandard 2.1 or dotnet 5?

![image](https://user-images.githubusercontent.com/456060/98995118-1e0e4480-24ee-11eb-8b2e-6f83343bfbc5.png)

**Comment by SPingels** [comment]
SuperSocket或者SuperSocket.Client会考虑支持.NetFramework 4.x吗?

**Comment by kerryjiang** [comment]
No, they won't.
