### ISSUE TITLE
[Feature request] Not depend on Microsoft.Extensions.Hosting #155 

### ISSUE THREAD

**Issue by ScarletKuro** [kerryjiang/SuperSocket#418]
I'm using this library for wpf and winform application, this is a good framework, but Microsoft.Extensions.Hosting brings too many references and makes app bootstrapping harder.

**Describe the solution you'd like**
Microsoft.Extensions.Hosting will be optional. I can choose to use it in asp.net core apps, but not use it in wpf/desktop apps.

If you rely on dependency injection, you could use the same mechanism as automapper [does](https://docs.automapper.org/en/stable/Dependency-injection.html#examples).

**Comment by kerryjiang** [comment]
Microsoft.Extensions.Hosting is for service hosting and SuperSocket server depends on it.
I think service is a service which should not be an UI application.

Do you mean you want to use SuperSocket Client?

**Comment by ScarletKuro** [comment]
SuperSocket.Client can't work as a server.

"I think service is a service which should not be an UI application."
I understand where you are coming from, but my situation is an exception I guess. I work with a POS system and we have our internal application that works on top of that POS system with additional UI features, the communication between POS and my application works on TCP level, and we are playing the server role(which is a weird, but not me invented that architecture). So yeah, its a server with an UI... I was using before 1.6 version before and recently switched and found it harder to use it with UI, but yesterday I managed to sync wpf lifetime with the Microsoft.Extensions.Hosting and it works just fine, so i guess you can close the ticket or just consider it for future to depend less on it.

**Comment by kerryjiang** [comment]
Yes, if you want to hosting something as a backend service, Microsoft.Extensions.Hosting should be a good option.
Even if it is an UI application, it also does the hosting role.
