### ISSUE TITLE
Version conflicts with System.Diagnostics.EventLog in SuperSocket 2

### ISSUE THREAD

**Issue by martinmine** [kerryjiang/SuperSocket#419]
How to reproduce:
1. Create a new console application using `dotnet new console`
2. Modify the .csproj file to the following contents (what is special here is `AutoGenerateBindingRedirects`):
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SuperSocket" Version="2.0.0-beta6" />
  </ItemGroup>
</Project>
```
3. Run `dotnet build`, which will result in one warning:
```
C:\Program Files\dotnet\sdk\3.1.403\Microsoft.Common.CurrentVersion.targets(2084,5): warning MSB3277: 
Found conflicts between different versions of "System.Diagnostics.EventLog" that could not be resolved.  
These reference conflicts are listed in the build log when log verbosity is set to detailed.
```

**Comment by martinmine** [comment]
A workaround for this is to explicitly reference an updated package of `Microsoft.Extensions.Hosting`:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.1.9" />
    <PackageReference Include="SuperSocket" Version="2.0.0-beta6" />
  </ItemGroup>
</Project>
```
I expect this to get fixed once 2.0 is out of Preview.

**Comment by kerryjiang** [comment]
OH, I will check this problem.

**Comment by martinmine** [comment]
After I looked in the project configuration for 2.0, it looks like it gets the version to target `Microsoft.Extensions.Hosting` from some build variable (`MSExtensionsVersion`). Currently it targets 3.0.0, but when you build the project again you should be targeting a higher version of those packages. https://github.com/kerryjiang/SuperSocket/blob/master/src/SuperSocket.Server/SuperSocket.Server.csproj#L17

So therefore I think this is something that should fix by itself. Feel free to close this unless you feel there should be done further investigation.

**Comment by kerryjiang** [comment]
Yes, the building should be able to pickup the latest version according the dependencies tree.
