### ISSUE TITLE
Crash when not setting disablePerformanceDataCollector to true

### ISSUE THREAD

**Issue by Baccanno** [kerryjiang/SuperSocket#42]
The program crashes when not setting disablePerformanceDataCollector to true

because of the execution of this in : 

```
   DefaultBootstrap.cs (where the flag is checked)
   m_PerfMonitor = new PerformanceMonitor(m_Config, m_AppServers, serverManager, logFactory);

then in ProcessPerformanceCounterHelper.cs
var runnedInstances = processCategory.GetInstanceNames();

 has exited with code -1073741819 (0xc0000005) 'Access violation'
```

specs : 
VS community 2015
Amd 8320E (8 cores)
Win 8.1 pro

**Comment by kerryjiang** [comment]
Do you host it in IIS?

It should be permission issue.

**Comment by Baccanno** [comment]
I'm Debuging on VS, sorry I'm pretty new to .NET dev, might be IIS underneath
