### ISSUE TITLE
与ASP.Net Core 网站集成部署

### ISSUE THREAD

**Issue by XIO-OIX** [kerryjiang/SuperSocket#420]
1、部署到IIS后，网站必须访问一次才开启socket server监听
2、提示Failed to run socketOptionSetter for the socket.（exception：在 getsockopt 或 setsockopt 调用中指定的一个未知的、无效的或不受支持的选项或层次。）
3、运行一段时间后会自动停止
Application is shutting down...
The listener [Ip=Any, Port=8899, Security=None, Path=, BackLog=0, NoDelay=False] has been stopped.

**Comment by kerryjiang** [comment]
It is the way how IIS application pool runs.

For the error about, could you show me the code? You may got some errors related platform limitation.

**Comment by XIO-OIX** [comment]
https://github.com/XIO-OIX/SuperSocketPractice.git
在服务器运行SuperSocketPro项目会出现异常2

**Comment by kerryjiang** [comment]
1. this test case run correctly on the 3 target platforms, could you check your server environment?

https://github.com/kerryjiang/SuperSocket/blob/cbd087927c58ed0b8dee79c074b16d77005885a4/test/SuperSocket.Tests/MainTest.cs#L263-L314

https://github.com/kerryjiang/SuperSocket/actions/runs/341146725


2. Could you do some research about the lifecycle of the application pool in IIS? It is the default behavior of IIS.
Start the application pool when the first request comes in and shutdown the application when there is no traffic for a while.
