### ISSUE TITLE
help, I can't find any more classes and functions(Version Beta)

### ISSUE THREAD

**Issue by luismk** [kerryjiang/SuperSocket#423]
I can't find it anymore:
**namespace**
SuperSocket.SocketBase.Protocol

**Class**

IReceiveFilter
IRequestInfo
FilterState

the project must have changed the names
but I can't find anything about it, please help me

**Comment by kerryjiang** [comment]
SuperSocket 2.0 is a completely new design. Please follow the documentations.
https://docs.supersocket.net/
