### ISSUE TITLE
Client 2.0.0-beta7 bad nuget package

### ISSUE THREAD

**Issue by AlexDigy** [kerryjiang/SuperSocket#429]
On 2.0.0-beta7 nuget package:
`client.ConnectAsync(IPEndPoint)` failed with exception:
```
Could not load type 'SuperSocket.Channel.CloseEventArgs' from assembly 'SuperSocket.Channel, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.
```
On 2.0.0-beta6 nuget package working fine

**Comment by kerryjiang** [comment]
But the dependencies seems good. Can I see your project file?

![image](https://user-images.githubusercontent.com/456060/99579823-8c8e4f00-2993-11eb-8500-44a2e2592453.png)

**Comment by AlexDigy** [comment]
```
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SuperSocket.Client" Version="2.0.0-beta7" />
  </ItemGroup>

</Project>
```
I just copy code from BasicClient and include beta package SuperSocket.Client beta7.
When I change version to beta6 failed with exception

**Comment by kerryjiang** [comment]
Could you clear your cache of your nuget? I think your building found the SuperSocket.Channel with wrong version.

**Comment by AlexDigy** [comment]
Thanks. It works
