### ISSUE TITLE
WebSocketServer SetupCommands doesn't call base.SetupCommands

### ISSUE THREAD

**Issue by Baccanno** [kerryjiang/SuperSocket#43]
Shouldn't SetupCommands call the base method ? I was trying to add my own command Loader and the code loading the custom commands seems to be in the AppServerBase SetupCommands ( Which is never called )
```
        protected override bool SetupCommands(Dictionary<string, ICommand<TWebSocketSession, IWebSocketFragment>> discoveredCommands)
        {
            var commands = new List<ICommand<TWebSocketSession, IWebSocketFragment>>
                {
                    new HandShake<TWebSocketSession>(),
                    new Text<TWebSocketSession>(),  
                    new Binary<TWebSocketSession>(),
                    new Close<TWebSocketSession>(),
                    new Ping<TWebSocketSession>(),
                    new Pong<TWebSocketSession>(),
                    new Continuation<TWebSocketSession>(),
                    new Plain<TWebSocketSession>()
                };

            commands.ForEach(c => discoveredCommands.Add(c.Name, c));

            if (!SetupSubProtocols(Config))
                return false;

            return true;
        }
```

**Comment by kerryjiang** [comment]
No, you cannot.

They are websocket protocol commands, which should not include your business commands.

Please take at look at the samples about SubCommands.

**Comment by Baccanno** [comment]
Juste managed to do it with subCommands, Thanks again.

2016-01-06 15:51 GMT+01:00 Kerry Jiang <notifications@github.com>:

> No, you cannot.
>
> They are websocket protocol commands, which should not include your
> business commands.
>
> Please take at look at the samples about SubCommands.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kerryjiang/SuperSocket/issues/43#issuecomment-169343490>
> .
>



-- 
Michaël Picovschi, Morphiks
http://www.morphiks.com
