### ISSUE TITLE
Use SemVer 2.0.0

### ISSUE THREAD

**Issue by jzabroski** [kerryjiang/SuperSocket#430]
@kerryjiang 

The package naming should be 2.0.0-beta.9 - by using the dots, you allow yourself to opt in to correct sorting when beta number reaches 10.

**Comment by kerryjiang** [comment]
Yes, I have this problem on MyGet.

I will try my best to release a stable version before the 10th beta version is required.

**Comment by jzabroski** [comment]
The point is, there is no negative consequences to switching now (unless you're saying MyGet sports different than nuget.org).

**Comment by kerryjiang** [comment]
@jzabroski You are correct, I will make it happen.

**Comment by kerryjiang** [comment]
Did the change.
