### ISSUE TITLE
hex data  use [reader.ReadString()] parse error

### ISSUE THREAD

**Issue by McFly2017** [kerryjiang/SuperSocket#431]
When I send hex data to server,use reader.ReadString() get the string data,it's garbled.
Here my code
`public class CustomPipelineFilter : PipelineFilterBase<CdtPackageInfo>
    {
        public override CdtPackageInfo Filter(ref SequenceReader<byte> reader)
        {
			var hexStr= reader.QQReadString(Encoding.UTF8);
			var x = reader.ReadString(); //Useless，but can't delete
			return new CdtPackageInfo {HexBody = hexStr};
        }
}`
So I rewrite the ReadString() method,it works,but the new problem is 'SequenceReader<byte>' read the message time and time again.
How can I solve this problem?
Thanks

**Comment by kerryjiang** [comment]
Do you mean the line of code below doesn't work?

```csharp
using SuperSocket.ProtoBase;
var hexStr = reader.ReadString(Encoding.UTF8);
```

**Comment by McFly2017** [comment]
> Do you mean the line of code below doesn't work?
> 
> ```cs
> using SuperSocket.ProtoBase;
> 
> var hexStr = reader.ReadString(Encoding.UTF8);
> ```

it works,but not my hex data.
for example:
Send data:7B 7B 30 32 30 30 30 30 31 30 32 7D 7D 
Receive data:{{020000102}},
it parse hex to string ,not hex string[7b7b3032303030303130327d7d]

**Comment by kerryjiang** [comment]
Can you show your implementation of QQReadString(...)?

**Comment by kerryjiang** [comment]
Don't forget advance the reader if you consume any bytes from the underlying sequence.

```csharp
reader.Advance(n);
```
