### ISSUE TITLE
Roadmap to Supersocket 2.0 questions

### ISSUE THREAD

**Issue by martinmine** [kerryjiang/SuperSocket#432]
Hi, and thank you for your hard work on moving SuperSocket to .NET Core.
I have started the work on refactoring a server application I maintain which heavily relies on SuperSocket 1.6 in order to minimize the impact when 2.0 gets out. When do you think that SuperSocket will be "production ready" so that we can start moving our application to .NET Core? No need to have any exact date or anything, if it is ready when it is ready, that is alright too :)

**Comment by kerryjiang** [comment]
If I cannot make it in 2020, probably I can wrap it up in the Q1 of 2021.

You can work on the moving right now. The APIs is stable right now and some users already started running SuperSocket 2.0. I will be more confident to release stable version after hear more feedbacks from users.

**Comment by martinmine** [comment]
Cool, I did some investigation a while ago to identify how to upgrade to 2.0, and saw that the biggest change in my case was related to logging and the signatures of the messaging handlers. This application is the backend of a game ([Age of Empires Online - Project Celeste](https://www.projectceleste.com/)) and is entirely relying on SuperSocket for communicating with the game client, launcher, and other components. It is therefore a pretty big application. I have identified equivalent APIs moving from 1.6 to 2.0, or replaced the ones that are being removed with new functionality. So you would argue that the current beta of SuperSocket 2.0 is production ready?

**Comment by kerryjiang** [comment]
Yes, I think the current SuperSocket 2.0 has better quality than SuperSocket 1.6 even it doesn't have a stable release yet. 
I support 2.0 actively and it won't happen to 1.6.

@martinmine Could you shoot me an email or give me your email address? I would ask for a help from you.

**Comment by martinmine** [comment]
@kerryjiang Sure, it is `martin_mine@hotmail.com`
