### ISSUE TITLE
请问一下作者，有没有把WebAPI当作SuperSocket.Server服务器的demo

### ISSUE THREAD

**Issue by GeorGeWzw** [kerryjiang/SuperSocket#433]
请问一下作者，有没有把WebAPI当作SuperSocket.Server服务器的demo

**Comment by kerryjiang** [comment]
和这个类似吧？
https://github.com/kerryjiang/SuperSocket/tree/master/samples/AspNetSample

**Comment by GeorGeWzw** [comment]
@kerryjiang 需要把WebApi当作调度中心，中心和节点之间通信需要用TCP连进行消息接收和发送，请问一下，方便写一下Demo嘛？

**Comment by kerryjiang** [comment]
直接http/https不更简单吗？

**Comment by GeorGeWzw** [comment]
@kerryjiang 想用您这个做一个.Net Core 大数据调度的工具平台，需要用到Node和Master，用http/https的话属于额外开销，现在遇到一个问题，如果使用TCP的话客户端和服务端有连接成功的接口吗？

**Comment by kerryjiang** [comment]
"接成功的接口"? What do you mean?

**Comment by GeorGeWzw** [comment]
@kerryjiang 感谢您的回答，我目前遇到的几个问题已经解决，有其他问题再给您这边提issues.

**Comment by quliting** [comment]
> @kerryjiang 想用您这个做一个.Net Core 大数据调度的工具平台，需要用到Node和Master，用http/https的话属于额外开销，现在遇到一个问题，如果使用TCP的话客户端和服务端有连接成功的接口吗？

请问你如何解决的，我也遇到了这个问题
