### ISSUE TITLE
Can not pulling this repository.

### ISSUE THREAD

**Issue by gouske** [kerryjiang/SuperSocket#434]
throw this error.

error: invalid path 'samples/LiveChat/Commands/CON.cs'
Updating f4e200d2..1b7a41f4

**Comment by chucklu** [comment]
This file exists on git repository https://github.com/kerryjiang/SuperSocket/blob/master/samples/LiveChat/Commands/CON.cs
This error should be a git error, and has nothing to do with SuperSocket

**Comment by kerryjiang** [comment]
I am fixing the strange problem

**Comment by kerryjiang** [comment]
Strange problem. Fixed it by renaming the file.
