### ISSUE TITLE
LinePipelineFilter的用法

### ISSUE THREAD

**Issue by LJBGH** [kerryjiang/SuperSocket#435]
我使用ASP.NetCore在创建主机时报错,代码如下

.public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                })
            .ConfigureAppConfiguration((hostCtx, configApp) =>
            {
                //配置WebSocket服务器的信息,名称和侦听端点并构建主机
                configApp.AddInMemoryCollection(new Dictionary<string, string>
                    {
                        { "serverOptions:name", "TestServer" },//服务器名称
                        { "serverOptions:listeners:0:ip", "Any" },//监听者的监听IP；Any：任何ipv4 ip地址
                        { "serverOptions:listeners:0:backLog", "100" },//挂起的连接队列的最大长度；
                        { "serverOptions:listeners:0:port", DefaultServerPort.ToString() }//侦听器的侦听端口
                    });
            })

            //配置日志记录
            .ConfigureLogging((hostCtx, loggingBuilder) =>
            {
                loggingBuilder.AddConsole();
                loggingBuilder.AddDebug();
            })

            //创建SuperSocket主机
            //.AsSuperSocketHostBuilder<StringPackageInfo, CommandLinePipelineFilter>()
            .AsSuperSocketHostBuilder<TextPackageInfo, LinePipelineFilter>()
            

            //注册连接
            .UseSession<MyAppSession>()

            //注册SuperSocket服务
            .UseHostedService<MySuperSocketService<StringPackageInfo>>()

            ////注册命令
            .UseCommand((opt) =>
            {
                opt.AddCommand<SORT>();
            });

**Comment by kerryjiang** [comment]
Could the error message you got?

The error message is the key to figure out the problem.

**Comment by LJBGH** [comment]
> 可能会收到错误消息吗？
> 
> 错误消息是找出问题的关键。

System.ArgumentException:“The type parameter should be subclass of SuperSocketService ”

**Comment by kerryjiang** [comment]
MySuperSocketService<StringPackageInfo> 这个类型不是继承于 SuperSocketService? 请参考测试用例。
