### ISSUE TITLE
StackOverflowException when using UseUdp()

### ISSUE THREAD

**Issue by martinmine** [kerryjiang/SuperSocket#436]
When I call `UseUdp()` in version 2.0.0-beta7 I get a StackOverflowException. To reproduce this, this was the smallest reproducer I could come up with:
```CSharp
static void Main()
{
    SuperSocketHostBuilder.Create<TextPackageInfo, LinePipelineFilter>()
    .UseUdp();
}
```

This happens because this method calls itself: https://github.com/kerryjiang/SuperSocket/blob/master/src/SuperSocket.Udp/UdpServerHostBuilderExtensions.cs#L15 You need to downcast it to an `ISuperSocketHostBuilder` to make it call the right extension method on it.

**Comment by kerryjiang** [comment]
I did a fix for it:

https://github.com/kerryjiang/SuperSocket/commit/7ec84d8053be291204fc0ede0c4f71692de76496
