### ISSUE TITLE
Version conflict with Microsoft.Extensions.Hosting

### ISSUE THREAD

**Issue by martinmine** [kerryjiang/SuperSocket#437]
In my project (2.0.0-beta7) I am using log4net through `Microsoft.Extensions.Logging.Log4Net.AspNetCore` and this results in the following exception when starting my application on Build() at the server builder: System.MethodAccessException: 'Attempt by method 'Microsoft.Extensions.Logging.Configuration.LoggerProviderConfigurationFactory.GetConfiguration(System.Type)' to access method 'Microsoft.Extensions.Logging.ProviderAliasUtilities.GetAlias(System.Type)' failed.'

The reason I get this is because SuperSocket is referencing 3.0.0 versions of .NET Core components, in my case it is the `Microsoft.Extensions.Hosting` that causes the incompatibilities . To get around this project I will then have to reference `Microsoft.Extensions.Hosting` version `3.1.9` in order to get my application started. This is a problem related to https://github.com/kerryjiang/SuperSocket/issues/419. Just wanted to bring this to your attention since I believe beta7 came out after https://github.com/kerryjiang/SuperSocket/issues/419 was closed.

**Comment by kerryjiang** [comment]
OK, I will upgrade libraries' version.

**Comment by martinmine** [comment]
Confirmed fixed in `2.0.0-beta.8`
