### ISSUE TITLE
发送消息时报错

### ISSUE THREAD

**Issue by LJBGH** [kerryjiang/SuperSocket#439]
System.ThrowHelper.ThrowInvalidOperationException() (位于 [ThrowHelper.cs] 中)(navigate-to-context:0)
    System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore<TResult>.GetResult(short) (位于 [ManualResetValueTaskSourceCore.cs] 中)(navigate-to-context:1)
	SuperSocket.Channel.DefaultObjectPipe<T>.System.Threading.Tasks.Sources.IValueTaskSource<T>.GetResult(short)
    System.Threading.Tasks.ValueTask<TResult>.Result.get() (位于 [ValueTask.cs] 中)(navigate-to-context:3)
    System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<TResult>.ConfiguredValueTaskAwaiter.GetResult() (位于 [ConfiguredValueTaskAwaitable.cs] 中)(navigate-to-context:4)
	SuperSocket.Channel.PipeChannel<TPackageInfo>.<RunAsync>d__28.MoveNext()
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() (位于 [ExceptionDispatchInfo.cs] 中)(navigate-to-context:6)
    System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore<TResult>.GetResult(short) (位于 [ManualResetValueTaskSourceCore.cs] 中)(navigate-to-context:7)
	SuperSocket.Channel.PipeChannel<TPackageInfo>.<RunAsync>d__28.System.Threading.Tasks.Sources.IValueTaskSource<bool>.GetResult(short)
    System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult() (位于 [ValueTaskAwaiter.cs] 中)(navigate-to-context:9)

**Comment by kerryjiang** [comment]
Which version do you use?

**Comment by LJBGH** [comment]
2.0.0-beta7  已经解决了  谢谢

> 您使用哪个版本？
