### ISSUE TITLE
How can I use command with SuperSocket.WebSocket?

### ISSUE THREAD

**Issue by varavut** [kerryjiang/SuperSocket#44]
Hello, I'm new to SuperSocket and SuperSocket.WebSocket. 

I would like to make an server that listen a data from mobile via socket and listen a data from web via websocket. 

Every thing is work fine in the start. but when I see the Usage of Command section on http://docs.supersocket.net/v1-6/en-US/A-Telnet-Example I would like to convert all of my RequestReceived event to commands.

However I can't find a example of using a command with SuperSocket.WebSocket. I try to create a class like a code below but it never called.

```
class ECHO : CommandBase<WebSocketSession, IWebSocketFragment>
{
    public override void ExecuteCommand(WebSocketSession session, IWebSocketFragment requestInfo)
    {
        session.Send("test");
    }
}
```

Could you please suggest me, how can I use command with SuperSocket.WebSocket?

Thank you very much.

**Comment by kerryjiang** [comment]
For websocket protocol, just follow the samples of SuperWebSocket. The usage of them are same.

https://github.com/kerryjiang/SuperWebSocket/tree/master/Samples/CommandAssembly

**Comment by varavut** [comment]
Now my code is work properly.

Thank you very much @kerryjiang

**Comment by b0wter** [comment]
I am facing the same issue yet the samples do not give me any hint on what I am doing wrong. I copied the ADD class from the sample (changing it's namespace so that it matches the one of my project).
Looking in the debug.log only gives the information:

> 2016-07-06 15:29:51,343 [7] DEBUG SuperWebSocket - SubProtocol Basic found the commands: []

`    public class ADD : SubCommandBase
    {
        public override void ExecuteCommand(WebSocketSession session, SubRequestInfo requestInfo)
        {
            var paramArray = requestInfo.Body.Split(' ');

            session.Send((int.Parse(paramArray[0]) + int.Parse(paramArray[1])).ToString());
        }
    }`
