### ISSUE TITLE
AppServer

### ISSUE THREAD

**Issue by LJBGH** [kerryjiang/SuperSocket#442]
SuperSocket(2.0.0-bata7)  这个版本怎么没有AppServer

**Comment by kerryjiang** [comment]
Here it is:

https://github.com/kerryjiang/SuperSocket/blob/7ec84d8053be291204fc0ede0c4f71692de76496/src/SuperSocket.Server/AppSession.cs#L44

**Comment by LJBGH** [comment]
@kerryjiang 使用IserverInfo中的GetSessionContainer获取所有链接显示为null,可以给一下具体的使用方式吗?
![image](https://user-images.githubusercontent.com/45363916/100416140-b264d380-30b8-11eb-82cf-59e65ff7ad2b.png)

**Comment by LJBGH** [comment]
@kerryjiang 
![image](https://user-images.githubusercontent.com/45363916/100430964-776f9980-30d2-11eb-9c6f-889f9d0543ce.png)

**Comment by chucklu** [comment]
Please provide a sample project with git repository

**Comment by kerryjiang** [comment]
https://github.com/kerryjiang/SuperSocket/blob/1ed30887e7ecebcc24d6bd65e22a6484cc0d179e/test/SuperSocket.Tests/SessionContainerTest.cs#L81
