### ISSUE TITLE
请问一下，supperSocket.Server 2.0.0-bata7 的版本如何向指定节点发送消息？

### ISSUE THREAD

**Issue by GeorGeWzw** [kerryjiang/SuperSocket#443]
作者，我这边想请问一下，supperSocket.Server如何向指定节点发送消息？使用的版本是SuperSocket(2.0.0-bata7)

**Comment by kerryjiang** [comment]
Same as v1.6, you just need access the session container.

```csharp
using SuperSocket;

server. GetSessionContainer();
```

**Comment by GeorGeWzw** [comment]
@kerryjiang  也就是说通过注入IAppSession或者IServerInfo获取和使用GetSessionContainer方法向指定节点发送消息

**Comment by kerryjiang** [comment]
https://github.com/kerryjiang/SuperSocket/blob/1ed30887e7ecebcc24d6bd65e22a6484cc0d179e/test/SuperSocket.Tests/SessionContainerTest.cs#L81

**Comment by GeorGeWzw** [comment]
@kerryjiang 好的，一会儿我起来看一下

**Comment by GeorGeWzw** [comment]
@kerryjiang 作者，请问一下有没有长链接的心跳检测，服务端可以拦截的？？

**Comment by kerryjiang** [comment]
Do you mean TCP Keep Alive settings?  Yes, we allow you to set low level socket options:

https://github.com/kerryjiang/SuperSocket/blob/37effd9c0858bf4546eb5a499f4784fe1b90a20a/test/SuperSocket.Tests/MainTest.cs#L263-L315

But if you are talking about application level keep alive, you should design it in your application level protocol.

**Comment by GeorGeWzw** [comment]
@kerryjiang 请问一下，如果是服务端主动断开，会通知这个事件吗？这个事件应该如何传参？？![image](https://user-images.githubusercontent.com/46982191/100950927-6d252380-3548-11eb-81a1-933b3d18e6a3.png)

**Comment by kerryjiang** [comment]
正常断开会有事件的，但就是简单的TCP链接断开，不包含业务逻辑信息。
