### ISSUE TITLE
包内部添加了断线重试机制吗?

### ISSUE THREAD

**Issue by LJBGH** [kerryjiang/SuperSocket#445]
作者,请问一下框架内部有没有集成服务端或者客户端断线重试机制,如果服务端意外宕机,客户端非主动断开是否存在重试机制?

**Comment by LJBGH** [comment]
@kerryjiang服务端突然抛异常 
![image](https://user-images.githubusercontent.com/45363916/100846605-ae222700-34b9-11eb-8fbf-b1a0824fa062.png)

**Comment by kerryjiang** [comment]
重连一般是客户端发起的。请自行在客户端根据业务实现重连机制。

**Comment by kerryjiang** [comment]
你这个异常是你自己代码抛出的异常，貌似是GRPC相关的。

**Comment by LJBGH** [comment]
@kerryjiang 请问一下,如果服务端异常断开,会通知给客户端吗?或者是否有一个事件监听?服务端是否异常宕机???

**Comment by kerryjiang** [comment]
通知客户端是你的业务逻辑，SuperSocket不会内置这些。

处理包异常的捕获有几个扩展点：

1. 注册这个service, 服务器里面是这样获取的:

···csharp
serviceProvider.GetService<Func<IAppSession, PackageHandlingException<TReceivePackageInfo>, ValueTask<bool>>
···

2. override SuperSocketService的方法OnSessionErrorAsync

···csharp
protected virtual ValueTask<bool> OnSessionErrorAsync(IAppSession session, PackageHandlingException<TReceivePackageInfo> exception);
···
