### ISSUE TITLE
运行一段时间后出现Max connection number 5000 was reached!，实际连接数只有数十个

### ISSUE THREAD

**Issue by polar-zhang** [kerryjiang/SuperSocket#446]
运行一段时间后出现“Max connection number xxx was reached!”错误，客户端无法连接；
修改maxConnectionNumber 为5000，过一段时间依然如此，实际连接数远远没有5000，也就几十个。

看了一下代码，AsyncSocketServer里面使用m_SendingQueuePool 一开始分配设定数量的元素，每连接成功一个就Pop出一个，每Close一个就Push回去（默认是可回收的，没看到哪里可以设置不可回收）一个。

但是问题可能出现，用户Close时，由于代码异常或者提前return导致没有Push回去，元素越来越少，最后用户无法继续连接。

为什么m_SendingQueuePool.Push 这么重要的动作不是在try ... finally {}来确保代码执行呢？
另外，为什么要使用m_SendingQueuePool来判断连接数呢，直接判断Sessions.Count不行吗？就算为了性能不对Sessions.Count加锁而导致实际连接数比设定连接数多几个也不是什么大问题。

**Comment by polar-zhang** [comment]
再次看日志，发现有大量错误，有可能是Close()没有被正常调用而导致m_SendingQueuePool元素没有回收的原因：
2020-10-23 01:22:02,585 [114] ERROR QuoteServerSimplified - Session: 56035811-aa09-4ba4-8fa1-dc53f96d1f19/222.139.160.92:1817
Unexpected error
Caller: Negotiate, file path: d:\WorkShop\SuperSocket\v1.6\SocketEngine\AsyncStreamSocketSession.cs, line number: 378
System.ArgumentNullException: 值不能为 null。
参数名: socket
   在 System.Net.Sockets.NetworkStream..ctor(Socket socket)
   在 SuperSocket.SocketEngine.AsyncStreamSocketSession.CreateSslStream(ICertificateConfig certConfig)
   在 SuperSocket.SocketEngine.AsyncStreamSocketSession.BeginInitStream(AsyncCallback asyncCallback)
   在 SuperSocket.SocketEngine.AsyncStreamSocketSession.SuperSocket.SocketEngine.INegotiateSocketSession.Negotiate()

2020-10-23 01:22:38,212 [114] ERROR ManagerServerSimplified - Session: f951bce5-a403-4678-b77e-99a3d34c287b/103.6.176.182:42497
Unexpected error
Caller: OnBeginInitStream, file path: d:\WorkShop\SuperSocket\v1.6\SocketEngine\AsyncStreamSocketSession.cs, line number: 255
System.Security.Authentication.AuthenticationException: 调用 SSPI 失败，请参见内部异常。 ---> System.ComponentModel.Win32Exception: 因为算法不同，客户端和服务器无法通信。
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   在 System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   在 System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   在 SuperSocket.SocketEngine.AsyncStreamSocketSession.OnBeginInitStream(IAsyncResult result, Boolean connect)

**Comment by polar-zhang** [comment]
2020-10-23 01:22:01,101 [65] ERROR QuoteServerSimplified - Session: 511c416e-57e3-46e3-9efe-bb72beefd634/222.139.160.92:1765
Unexpected error
Caller: OnBeginInitStream, file path: d:\WorkShop\SuperSocket\v1.6\SocketEngine\AsyncStreamSocketSession.cs, line number: 255
System.Security.Authentication.AuthenticationException: 调用 SSPI 失败，请参见内部异常。 ---> System.ComponentModel.Win32Exception: 因为算法不同，客户端和服务器无法通信。
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   在 System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   在 System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   在 SuperSocket.SocketEngine.AsyncStreamSocketSession.OnBeginInitStream(IAsyncResult result, Boolean connect)

**Comment by kerryjiang** [comment]
Please upgrade to SuperSocket 2.0.

**Comment by polar-zhang** [comment]
> Please upgrade to SuperSocket 2.0.

Thanks man, you are the best.
I will test it.

**Comment by polar-zhang** [comment]
> Please upgrade to SuperSocket 2.0.

Hi
SuperSocket 2.0 depends on .NETStandard 2.1, which is not supported by any version of .Net Framework. 
Any advice on how to use the new version on .Net Framework?
Thanks

**Comment by kerryjiang** [comment]
Yes, your target must be dotnetcore/dotnet5 app.

**Comment by polar-zhang** [comment]
> Yes, your target must be dotnetcore/dotnet5 app.

I guest I will just download branch 1.6, and fix it right there.
Do you want me to contribute the fix to the branch?

**Comment by kerryjiang** [comment]
Probably no, could you just make your changes and then build it by yourself?

**Comment by kerryjiang** [comment]
Wait, let me check if I can do a quick fix.

**Comment by kerryjiang** [comment]
@polar-zhang No safe fix for me. Please go ahead to fix it by yourself.

**Comment by polar-zhang** [comment]
@kerryjiang Thanks, will do.

**Comment by polar-zhang** [comment]
We figured out that the problem was caused by closing a Session in OnConnected callback.
We redesigned the code, and the problem went away.
Just want you to know. @kerryjiang

**Comment by halogay** [comment]
@paulo-zhang Hi, I'm glad to see that you've resolved the issue. Could you please share the specific details of the code?
