### ISSUE TITLE
SuperWebSocket NewSessionConnected NewMessageReceived can't work 

### ISSUE THREAD

**Issue by Timooooooo** [kerryjiang/SuperSocket#447]
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using SuperWebSocket;
using SuperSocket.SocketBase.Config;

namespace Bigbai.Lib.Websocket
{
    class Server
    {

        public static log4net.ILog Log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        private string IpAddress = "127.0.0.1";

        private ushort Port = 30000;

        private ushort MaxConnectionNumber = 10;

        private string TextEncoding = "gb2312";
        

        public void Start()
        {
            try
            {
                var Wss = new WebSocketServer();

                var WebSocketConfig = new ServerConfig()
                {
                    Port = this.Port,
                    Ip = this.IpAddress,
                    TextEncoding = this.TextEncoding,
                    MaxConnectionNumber = this.MaxConnectionNumber
                };

                if (Wss.Setup(WebSocketConfig))
                {
                    // 新连接
                    Wss.NewSessionConnected += Sockect_NewSessionConnected;
                    // 新消息
                    Wss.NewMessageReceived += Sockect_NewMessageReceived;
                    // 断开连接
                    Wss.SessionClosed += Sockect_SessionClosed;

                    if (!Wss.Start())
                    {
                        Log.Error("创建WebSocket服务失败!");
                    }
                    else 
                    {
                        
                    }

                    while (Console.ReadKey().KeyChar != 'q')
                    {
                        continue;
                    }

                }
                else 
                {
                    Log.Error("IP地址和端口设置失败，请检查是否被占用！");
                }                
            }
            catch (Exception ex)
            {
                Log.Error(ex.Message);
            }
            finally
            {

            }

        }

        /// <summary>
        /// 新的Socket连接事件
        /// </summary>
        /// <param name="session"></param>
        private void Sockect_NewSessionConnected(WebSocketSession session)
        {
            Log.Info("触发新客户连接事件");

            try
            {
                string logMsg = string.Format("{0} 与客户端创建新会话", DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss")) + "\r\n";
                
                Log.Info(logMsg);
            }
            catch (Exception ex)
            {
                Log.Info(ex.Message);
            }
           

            //this.Invoke(new Action(() =>
            //{
            //    txtLogInfo.Text += logMsg;
            //}));
            //loggerManager.Info(logMsg);
            //socketSessionList.Add(session, "");
        }
        /// <summary>
        /// 消息接收事件
        /// </summary>
        /// <param name="session"></param>
        /// <param name="value">接收的消息</param>
        private void Sockect_NewMessageReceived(WebSocketSession session, string message)
        {

            session.Send("Server: " + message);
            Log.Info("触发新消息接收事件");
            try
            {
                string logMsg = string.Format("{0} 从客户端{1}接收新的消息：\r\n{2}", DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"), GetwebSocketSessionName(session), message) + "\r\n";

                Log.Info(logMsg);
            }
            catch (Exception ex) 
            {
                Log.Info(ex.Message);
            }
           

            //this.Invoke(new Action(() =>
            //{
            //    txtLogInfo.Text += logMsg;
            //}));
            //loggerManager.Info(logMsg);
            //ReceiveData receiveData = JsonHelper.ConvertToEntity<ReceiveData>(value);
            ////退出登录
            //if (receiveData.MessageType == "3")
            //{
            //    //调用weiapi接口，更新在线用户的在线状态
            //    socketSessionList.Remove(session);
            //    session.Close(SuperSocket.SocketBase.CloseReason.ClientClosing);//断开连接
            //}
            //else
            //{
            //    if (receiveData.MessageType == "4")//设备故障推送
            //    {
            //        EquipmentFault equipmentFault = JsonHelper.ConvertToEntity<EquipmentFault>(receiveData.MessageContent);
            //    }
            //    else
            //    {
            //        socketSessionList[session] = receiveData.MessageContent;//记录app端的设备id
            //    }
            //}
        }
        /// <summary>
        /// sockect客户端断开连接事件
        /// </summary>
        /// <param name="session"></param>
        /// <param name="value"></param>
        private void Sockect_SessionClosed(WebSocketSession session, SuperSocket.SocketBase.CloseReason value)
        {
            Log.Info("触发客户断开连接事件");

            try
            {
                string logMsg = string.Format("{0} 与客户端{1}的会话被关闭 原因：{2}", DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"), GetwebSocketSessionName(session), value) + "\r\n";

                Log.Info(logMsg);
            }
            catch (Exception ex)
            {
                Log.Info(ex.Message);
            }

            //this.Invoke(new Action(() =>
            //{
            //    txtLogInfo.Text += logMsg;
            //}));
            //loggerManager.Info(logMsg);
            //socketSessionList.Remove(session);
        }

        /// <summary>
        /// 获取连接的客户端的ip地址
        /// </summary>
        /// <param name="webSocketSession"></param>
        private static string GetwebSocketSessionName(WebSocketSession webSocketSession)
        {
            string id = System.Web.HttpUtility.UrlDecode(webSocketSession.SessionID);//获取sessionid
            var remoteClient = webSocketSession.RemoteEndPoint;
            return remoteClient.Address + ":" + remoteClient.Port.ToString();
        }

        /// <summary>
        /// 发送消息
        /// </summary>
        /// <param name="session"></param>
        /// <param name="msg"></param>
        private void SendMessage(WebSocketSession session, string msg)
        {
            //向所有客户端发送消息
            //foreach (var sendSession in session.AppServer.GetAllSessions())
            //{
            //    sendSession.Send(msg);
            //}
            session.Send(msg);//向指定的客户端发送消息
        }
    }
}

![image](https://user-images.githubusercontent.com/22143058/101118932-1a6d6980-3625-11eb-9637-c615f266ec64.png)

2020-12-04 11:35:28,407 [1] INFO  WebSocketServer-3741682 - The server instance WebSocketServer-3741682 has been started!
2020-12-04 11:36:13,539 [5] INFO  Bigbai.Lib.Websocket.Server - 触发客户断开连接事件
2020-12-04 11:36:13,580 [5] INFO  Bigbai.Lib.Websocket.Server - 2020-12-04 11:36:13 与客户端127.0.0.1:54297的会话被关闭 原因：ClientClosing

**Comment by kerryjiang** [comment]
SuperWebSocket or SuperSocket.WebSocket is a websocket server which only accept websocket connections.
You need connect it with a websocket client.
