### ISSUE TITLE
Default settings for MaxPackageLength leading to heavy LOH allocation

### ISSUE THREAD

**Issue by martinmine** [kerryjiang/SuperSocket#452]
The [default value](https://github.com/kerryjiang/SuperSocket/blob/master/src/SuperSocket.Channel/ChannelOptions.cs#L12) for `MaxPackageLength` is 4MB (4194304). Internally, Supersocket is relying on using `ArrayPool<byte>` in order to store buffers. The problem is that the maximum length that this array pool will cache is 1024^2 (1 048 576) (see [this article](https://adamsitnik.com/Array-Pool/) which explains this pretty nicely) and we will instead allocate stuff right into the large object heap and throw that away. In real life, this means that we will not be using the buffer by default unless we explicitly configure the `MaxPackageLength` for the servers to be lower than 1024^2. Given the right circumstances this can blow up pretty badly and lead to poor performance under heavy load. If you for example set up a simple UDP server that will accept packets, you can see in a profiler that it is going to start allocating 4MB chunks:
```CSharp
static async Task Main(string[] args)
{
    var host = SuperSocketHostBuilder.Create<TextPackageInfo, LinePipelineFilter>(args)
    .UsePackageHandler(async (s, p) =>
    {
        Console.WriteLine($"Received {p.Text.Length} bytes");
    })
    .ConfigureSuperSocket(options =>
    {
        options.AddListener(new ListenOptions
        {
            Ip = "Any",
            Port = 4040
        }
        );
    })
    .UseUdp()
    .Build();

    await host.RunAsync();
}
```

![](https://i.imgur.com/3y6sF9X.png)
This allocation will go on until the application performs a full GC. To smooth out this behavior I have set a `MaxPackageLength` for my application that is lower than 1024^2 but I think the default value should take the buffer max value into considerations so that people don't run code that might suddenly blow up under certain circumstances.

**Comment by kerryjiang** [comment]
Thanks for this sharing. It seems I need add at least one test in the benchmark project.

**Comment by martinmine** [comment]
What do you think about reducing the default value? What are the use cases for getting up to 4MB in size? IMO having applications that rely on that large packets would be more an edge case scenario and it would make more sense to optimise towards what most people would rely on.

On 13 Dec 2020, at 23:40, Kerry Jiang <notifications@github.com> wrote:

﻿

Thanks for this sharing. It seems I need add at least one test in the benchmark project.

**Comment by martinmine** [comment]
Forgot to post this yesterday, the allocation issue can be demonstrated with the following code:

```Csharp
const int bufferSize = 1024 * 1024;
var pool = ArrayPool<byte>.Shared;

while (true)
{
    var bytes = pool.Rent(bufferSize);
    Thread.Sleep(300);
    pool.Return(bytes);

    Thread.Sleep(1000);
}
```` 
With bufferSize = 4MB, you will see the following in the memory diagnostics window in Visual Studio:
![](https://i.imgur.com/Icxi0br.png)
While with bufferSize = 1MB:
![](https://i.imgur.com/XcHhAoq.png)

Due to the limitations on what the `ArrayPool<T>` will keep pooled, my suggestion would be that the default value for `MaxPackageLength` is reduced to 1MB.
