### ISSUE TITLE
有计划实现http协议嘛？

### ISSUE THREAD

**Issue by sx212** [kerryjiang/SuperSocket#455]
有计划实现http协议嘛？

**Comment by kerryjiang** [comment]
Why don't you use Kestrel?

I don't want to implement full HTTP protocols. There are already some good web servers can be used.

Probably you can use SuperSocket.Http to implement HTTP like protocol.

https://github.com/kerryjiang/SuperSocket/tree/master/src/SuperSocket.Http

**Comment by sx212** [comment]
Ok, 谢谢；
