### ISSUE TITLE
SuperSocket.ProtoBase Extensions.cs TryReadBigEndian Is incorrect

### ISSUE THREAD

**Issue by leisurelyclouds** [kerryjiang/SuperSocket#457]
uint ulong 的实现是否不正确?

https://github.com/kerryjiang/SuperSocket/blob/53f0caf51a3550cbddb8bdc5d862389fa59dafb5/src/SuperSocket.ProtoBase/Extensions.cs#L63

应该为

```c#
var unit =Math.Pow(256, i-1);
```

可否参考 
https://github.com/neuecc/MessagePack-CSharp/blob/8b558a513d0f5c12d2deaf076d4082f57663db97/src/MessagePack.UnityClient/Assets/Scripts/MessagePack/SequenceReaderExtensions.cs#L148 
修改ushort uint ulong实现

---

Is the implementation of uint ulong incorrect?

https://github.com/kerryjiang/SuperSocket/blob/53f0caf51a3550cbddb8bdc5d862389fa59dafb5/src/SuperSocket.ProtoBase/Extensions.cs#L63

In c# ^ means Is xor 
it shoud be Math.Pow operation?
it is not 2 should it be 256
i should be changed to i-1

could you refer to 
https://github.com/neuecc/MessagePack-CSharp/blob/8b558a513d0f5c12d2deaf076d4082f57663db97/src/MessagePack.UnityClient/Assets/Scripts/MessagePack/SequenceReaderExtensions.cs#L148 

Modify ushort uint ulong implementation

**Comment by kerryjiang** [comment]
Oh, nice finding. That's a stupid bug.

**Comment by kerryjiang** [comment]
Fixed it just now. Thank you!

**Comment by leisurelyclouds** [comment]
ulong的方法好像也是一样的问题 需要修改

**Comment by kerryjiang** [comment]
Oops...  didn't notice that method.
