### ISSUE TITLE
Calling SuperSocketService.StopAsync() does not close existing connections

### ISSUE THREAD

**Issue by martinmine** [kerryjiang/SuperSocket#458]
In v1.6 calling `Stop()` on an `AppServer` instance would close all existing established connections. In v2.0, the equivalent would be calling `StopAsync` on an `SuperSocketService`. The problem is that this does not close existing connections and only the listening socket. In my case, existing connections can stay open even after calling `Dispose()` on an `IHost` that I have gotten from a `MultipleServerHostBuilder`. 

v1.6: https://github.com/kerryjiang/SuperSocket/blob/v1.6/SocketBase/AppServer.cs#L349
v2.0: https://github.com/kerryjiang/SuperSocket/blob/master/src/SuperSocket.Server/SuperSocketService.cs#L399

**Comment by martinmine** [comment]
I am able to drain the servers with the following code:
```CSharp
public async Task DrainAllServers()
{
    foreach (var service in _host.Services.GetServices<IHostedService>())
    {
        if (service is IServer server)
        {
            await DrainServer(server);
        }
    }
}

private async Task DrainServer(IServer server)
{
    var container = server.GetSessionContainer();

    var serverSessions = container.GetSessions();
    foreach (var session in serverSessions)
    {
        try
        {
            await session.CloseAsync(SuperSocket.Channel.CloseReason.ServerShutdown);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, ex.Message);
        }
    }
}
```
Is it by design that they don't close the connections automatically?

**Comment by kerryjiang** [comment]
It is a missing part. One reason I didn't implement it is it requires an optional feature SessionContainer.

**Comment by martinmine** [comment]
Yeah, since in v2 `SessionContainer` is kept outside of the concept of a Server, it gave me the impression that this was by design.
