### ISSUE TITLE
DefaultObjectPipeWithSupplyControl 用法问题

### ISSUE THREAD

**Issue by xilutian** [kerryjiang/SuperSocket#459]
根据我的理解，这个用法对象用法 ，应该是服务端可以控制管道流Pipe读写速度， 我配置中设置了 ReadAsDemand =true ，确实起了作用
问题是 ，客户端每次上传的包大小是 1M，刚开始的时候，传输的字节还不够1M，所以在RunAsyn中就不会得到数据包，这样会导致两边都在等待了 （两边是指：   var package = await _packagePipe.ReadAsync().ConfigureAwait(false);   与     await supplyController.SupplyRequired();）

应该是我的用法不正确，我想请教一下正确的用法是什么
谢谢了！！！

**Comment by kerryjiang** [comment]
I don't think you you use this feature by yourself.

Why do you want to use it? What kind problem did you encounter?

**Comment by xilutian** [comment]
因为服务端写文件比较慢，我想等服务端写完了，客户端再发
现在遇到的问题的   var package = await _packagePipe.ReadAsync().ConfigureAwait(false); 与 await supplyController.SupplyRequired();） 这两个放在 现在都在等待状态了

**Comment by kerryjiang** [comment]
Your server code won't hit the line of "supplyController.SupplyRequired()".

Do you mean your client code?

服务器端写完，发送一个确认包给客户端，客户端收到这个包后继续发送。

**Comment by xilutian** [comment]
这样传输就太慢了，还是想着快速传输文件，请问 您设计的 DefaultObjectPipeWithSupplyControl ，这种主要是做什么的呢？我考虑服务端自己来阻塞或不阻塞，对于客户端来说，服务端阻塞了，客户端自己就阻塞了，您方便说一下  DefaultObjectPipeWithSupplyControl 这个目的是什么呢

**Comment by xilutian** [comment]
我想着基于 DefaultObjectPipeWithSupplyControl 改造实现一下，但是又怕破坏您的思想

**Comment by kerryjiang** [comment]
No, it was not designed for this purpose.

**Comment by kerryjiang** [comment]
@xilutian adjust the buffer sizes, the network speed is good. Just go ahead to adjust the buffer sizes.

1) the buffer size you use to send the data;
2) the receiving buffer size on the server;
3) the buffer size you use to write data to disk.

**Comment by xilutian** [comment]
嗯嗯，明白您的意思，但是我这边数据种类很多，buffer size 不好选择，您方便说一下 DefaultObjectPipeWithSupplyControl 的设计目的吗？

**Comment by kerryjiang** [comment]
客户端事件控制，和服务器端无关。

**Comment by xilutian** [comment]
我想实现 服务端没有处理完成，想阻塞一会管道Pipe 读写的速度，然后服务端处理完成后，触发管道继续读写，您这边有什么好的建议吗？

**Comment by kerryjiang** [comment]
这是我的建议:
服务器端写完，发送一个确认包给客户端，客户端收到这个包后继续发送。

**Comment by xilutian** [comment]
好的，服务端阻塞 ，您感觉这样设计是不太好，是吗？
