### ISSUE TITLE
Why cannot i find the AnyLog.dll in version 1.6?

### ISSUE THREAD

**Issue by catom** [kerryjiang/SuperSocket#46]
I have download the source for version 1.6 several minutes ago. But I just cannot compile the project for SocketBase.Net45? Than i find that this source not include the AnyLog.dll, so what can i do ?

**Comment by catom** [comment]
In addtion, the brench is Master, 3q very much!

**Comment by kerryjiang** [comment]
Please switch to branch v1.6

**Comment by catom** [comment]
Thx very much! I have got it now. And I have found this project includes the sources that describe on official website. That will be very useful to me!
