### ISSUE TITLE
Sited SuperSocket on Quora

### ISSUE THREAD

**Issue by RussellHaley** [kerryjiang/SuperSocket#462]
https://www.quora.com/What-technologies-need-to-be-learned-to-develop-a-communication-software-with-C-I-want-to-develop-a-simple-chat-software-and-plan-to-use-c-do-I-need-to-learn-socket-Or-use-wcf-Or-use-some-open-source-framework/answer/Russell-Haley-4?prompt_topic_bio=1

Cheers,
Russ

**Comment by kerryjiang** [comment]
Really encouraging information for me.

**Comment by RussellHaley** [comment]
In a world of chaos and darkness, you may be confident that you are a force for good. You were one of my first FOSS inspirations because I saw your dedication to helping others. I was successful because of you and I strive to make others successful because of you. I don't do much C# right now, but @kerryjiang influences all other things that I do. 

Be the light of the world! Happy 2021.
Russ
