### ISSUE TITLE
2.0版内存占用问题请教

### ISSUE THREAD

**Issue by chaoyi996** [kerryjiang/SuperSocket#463]
Hi:
我对2.0版内存占用进行了简单测试，使用环境及测试方法如下：
Supersocket版本:2.0b7
服务器端测试代码：master/samples/EchoServer
客户端测试逻辑：循环创建1W个连接，每个连接在1秒后断开，期间不发送数据。
测试结果：服务端程序内存占用只升不降，尝试配置GC为桌面环境，但效果甚微。

烦请指点一下此现象出现原因，谢谢。

**Comment by kerryjiang** [comment]
I will add benchmark for this case.

**Comment by chaoyi996** [comment]
这似乎与.net core 的内存回收机制有关，我尝试在外部开启一个Task循环进行GC，似乎内存得到有效回收，代码类似：
`            Task.Run(async () =>
            {
                while (true)
                {
                    GC.Collect(2, GCCollectionMode.Forced, true);
                    GC.WaitForPendingFinalizers();
                    await Task.Delay(1000);
                }
            });`

**Comment by chaoyi996** [comment]
Task.Run(async () =>
            {
                while (true)
                {
                    GC.Collect(2, GCCollectionMode.Forced, true);
                    GC.WaitForPendingFinalizers();
                    await Task.Delay(1000);
                }
            });

**Comment by DonPangPang** [comment]
这个问题大概是所有Socket Server的通病, 虽然连接断开了, 但是会存在大量僵尸连接, SuperSocket2.0中提供了UseClearIdleSession(), 你可以在构建WebSocketHostBuilder时使用它, 可以复用一些占用的"无用"内存.
一直GC效果其实也不是很明显, 我做过这样的尝试, 大概只能回收很少的一部分.
