### ISSUE TITLE
'Cannot resolve scoped service 'xxx' from root provider' when AsMultipleServerHostBuilder()

### ISSUE THREAD

**Issue by whSwitching** [kerryjiang/SuperSocket#465]
asp.net core 3.1,  razor page website project integrate supersocket service
if use AsMultipleServerHostBuilder(),  exception thrown when create DI instance in AppSession class
> System.InvalidOperationException: 'Cannot resolve scoped service 'xxx' from root provider.'

a sample project can be found on [Google Drive](https://drive.google.com/file/d/1bJuZxwZqa1i4AAswEVkfwxSVuodtg5rt/view?usp=sharing)

to reproduce:
1. run the project ( when AsSuperSocketHostBuilder)
2.  you can see everything is fine
2. in **appsettings.json**, comment out  **single server config**, and uncomment the **multi server config**
3. in **Program.cs**, comment out  **single server config**, and uncomment the **multi server config**
4. now  ( when AsMultipleServerHostBuilder)
4. run the project again, the exception will throw in AppSession constructor

the only difference is how the service registered

**Comment by kerryjiang** [comment]
I will add a test case to cover this scenario.

**Comment by kerryjiang** [comment]
But the test cases seem working?

https://github.com/kerryjiang/SuperSocket/blob/master/test/SuperSocket.Tests/AspNetIntegrationTest.cs

**Comment by whSwitching** [comment]
```
public void ConfigureServices(IServiceCollection services)
 {
    services.AddSingleton<ITestService, TestService>();
}
```
try AddScoped instead of AddSingleton please, this is different from [reproduce sample](https://drive.google.com/file/d/1bJuZxwZqa1i4AAswEVkfwxSVuodtg5rt/view?usp=sharing)

**Comment by kerryjiang** [comment]
Fixed this bug by this commit: https://github.com/kerryjiang/SuperSocket/commit/be56ca2e59e46514c01447b38e043cbd00075223

I will release a new beta version to NuGet ASAP.

**Comment by whSwitching** [comment]
thank you!  expecting the new release

**Comment by kerryjiang** [comment]
Released, but please be aware of the version number:
https://www.nuget.org/packages/SuperSocket/2.0.0-beta.8

**Comment by whSwitching** [comment]
noted,  thanks
