### ISSUE TITLE
[WebSocketServer] SessionCount in 2.0

### ISSUE THREAD

**Issue by a6387534** [kerryjiang/SuperSocket#466]
I'm trying to migrate my websocket server from 1.6 to 2.0,
But how do i retrieve the current sessions count in 2.0?

**Comment by kerryjiang** [comment]
Yes, you can access from server.

https://github.com/kerryjiang/SuperSocket/blob/aedf597bcc06c261517c24ddfe1fffe56e3049f4/test/SuperSocket.Tests/MainTest.cs#L39-L74

**Comment by a6387534** [comment]
I am using this sample to start a websocket server: https://github.com/kerryjiang/SuperSocket/blob/master/samples/WebSocketServer/Program.cs

In this sample, how can i retrieve session count? Thank you

**Comment by kerryjiang** [comment]
.UseWebSocketMessageHandler(async (session, message) =>
                {
                    var sessionCount = session.Server.SessionCount;
                    await session.SendAsync($"The server has {sessionCount} live sessions.");
                })

**Comment by DonPangPang** [comment]
1. everywhere 'session' when you see in supersocket:
`session.Server.SessionCount`

2.you can use like this when you create  SuperSocketHostBuilder as 'server':
`.UseMiddleware<InProcSessionContainerMiddleware>()
.UseInProcSessionContainer()`
and then like use Services in .net core web api:
`var sessionContainer = server.Services.GetService<SessionContainer>()
var count = sessionContainer.Count;`
