### ISSUE TITLE
FixedHeaderReceiveFilter does not work with single message

### ISSUE THREAD

**Issue by askdong** [kerryjiang/SuperSocket#47]
Dear Jiang,

FixedHeaderReceiveFilter在只收到一个消息的情况下CanResolvePackage返回为false，不会调用ResolvePackage； 只有后面继续有消息过来，之前的第一个消息才会被ResolvePackage。

Regards
askdong

**Comment by kerryjiang** [comment]
Thanks for your finding...

I'll fix it ASAP.

**Comment by kerryjiang** [comment]
刚review下了代码，暂时未发现产生这个问题的原因。
请问你有重现这个问题的代码吗？

**Comment by askdong** [comment]
附件为simple example！
message由如下组成LENGTH_BYTES(4字节）+ HEADER_BYTES(10字节） + 真正的message(大部分情况下为空），所以fixed header为14字节。

另外一个非常不解的问题是： 为什么clientengine会connect两次？

感谢！

[Uploading Test.zip…]()

**Comment by kerryjiang** [comment]
Got it， 你是说的body length ＝ 0的场景吧。
OK， 以前有个用户提过，但是当时忘了改。
Let me fix it now

**Comment by kerryjiang** [comment]
Fixed.

你的代码里面bufferStream用得不好。
不能直接bufferStream.ReadUInt32()来读取长度吗？
而且你用bufferStream.ReadByte()一个一个读出来也行啊，不用新建一块buffer copy出来。
设计BufferStream就是为了实现zero copy。

**Comment by kerryjiang** [comment]
另外，你连接的代码有问题，ConnectAsync是异步的，你没等连接操作返回就又循环进行连接。

The code should look like:
var connected = **await** _client.ConnectAsync(new IPEndPoint(IPAddress.Parse("127.0.0.1"), 5000));

**Comment by askdong** [comment]
1.对，正是body length ＝ 0的场景。
2.多谢指点，bufferStream没有注释，没有猜出相关函数的意义。如函数及相关参数都有注释则佳，但势必会耗掉你很多个人时间，supersocket发展到现在，想必Jiang兄很不容易，支持你！！
3.如果用await会污染整个代码链，我下面用了Result来block，我再研究一下asynchronous的用法 :)

**Comment by kerryjiang** [comment]
同步的话task.Wait()

**Comment by askdong** [comment]
好的！

**Comment by yangzhinong** [comment]
> Got it， 你是说的body length ＝ 0的场景吧。
> OK， 以前有个用户提过，但是当时忘了改。
> Let me fix it now

我项止是 .net4.7.2 nuget引入SupperSocket.ClientEngine（0.10.0）,和SupperSocket.ProtoBase（1.7.0.17）引入。

但在接受服务器发过的的包时，如果Body是零长度（只有头时）,会出现无法读取取数据。
能否指出正确的用法？
代码如下
public class MyReceiveFilter : FixedHeaderReceiveFilter<MyPackageInfo>
    {
        public MyReceiveFilter() : base(Consts.PROTOCOL_HEAD_LEN)
        {
        }
        public override MyPackageInfo ResolvePackage(IBufferStream bufferStream)
        {
            try
            {
                var bytes = new byte[bufferStream.Length];
                // bufferStream.Read(bytes, 0, bytes.Length);  //这里困惑 当body长度为0时,无法读出数据， 暂以下两行代替。
                var data = bufferStream.Buffers.Last().Array; 
                Buffer.BlockCopy(data, 0, bytes, 0, bytes.Length); //这样不知道有没有后续问题？ 
                
                MyPackageInfo res = new MyPackageInfo();
                using (var ms = new System.IO.MemoryStream(bytes))
                using (var reader = new System.IO.BinaryReader(ms))
                {
                    res.Key = Encoding.ASCII.GetString(reader.ReadBytes(GxSocketProtocol.Consts.PROTOCOL_KEY_LEN))?.TrimEnd();
                    res.BodyEncodeType = (GxSocketProtocol.Enums.EnuBodyEncodeType)reader.ReadByte();
                    res.ReqRes = (GxSocketProtocol.Enums.EnuReqRes)reader.ReadByte();
                    res.SubCmd = reader.ReadInt32();
                    res.StatusCode = (GxSocketProtocol.Enums.EnuResponseCode)reader.ReadInt16();
                    res.NoUse = reader.ReadInt16();
                    res.Length = reader.ReadInt32();
                    if (res.Length > 0)
                        res.Body = reader.ReadBytes(res.Length);
                    else
                        res.Body = new byte[0];
                }

                res.DoResolveFixData();
                return res;
            }
            catch (Exception ex)
            {
                ClsLog.Error(ex);
                return new MyPackageInfo { Key = "Error" };
            }
        }

        protected override int GetBodyLengthFromHeader(IBufferStream bufferStream, int length)
        {
            bufferStream.Skip(length - 4);
            var len = bufferStream.ReadInt32(littleEndian: true);
            if (len > short.MaxValue)
            {
                ClsLog.Warn($"解析数据包超过{short.MaxValue}, 大小为: {len}");
            }
            return len;
        }
    }
