### ISSUE TITLE
Local TCPIP socket support

### ISSUE THREAD

**Issue by dipenbh** [kerryjiang/SuperSocket#473]
1) Does it support Xamarin forms (android, iOS, wpf)?
2) Does it support local TCP/IP socket? (i.e. need to communicate with devices that are connected under same wifi network without internet connection.)

**Comment by kerryjiang** [comment]
1. It is netstandard2.1 library. According the matrix of framework/netstandard, it can be used in Xamarin but it cannot be used in WPF (.net framework); https://docs.microsoft.com/en-us/dotnet/standard/net-standard
2. Yes.
