### ISSUE TITLE
SuperSocket2.0 Websocket，怎么能够获取服务器的全部连接

### ISSUE THREAD

**Issue by xuyuanhong0902** [kerryjiang/SuperSocket#477]
SuperSocket2.0 Websocket，怎么能够获取服务器的全部连接？
比如：A想B推送消息，服务器收到A的消息后，该如何找到B连接在推送？
谢谢！

**Comment by DonPangPang** [comment]
虽然SuperSocket里内置了SessionContainer，但是建议自己实现一个SessionManager来维护一个Dict管理Session
