### ISSUE TITLE
Protobuf-net

### ISSUE THREAD

**Issue by hoangtrongphuc** [kerryjiang/SuperSocket#48]
How can I serialize/deserialize data with Protobuf ?

**Comment by kerryjiang** [comment]
Of course you can.

Serializing/Deserializing works over the network protocol.

**Comment by hoangtrongphuc** [comment]
So have you planned to implement protobuf in Super Socket ?

**Comment by kerryjiang** [comment]
It's logic of users.

SuperSocket doesn't need have it inside.

**Comment by hoangtrongphuc** [comment]
OK thank you
