### ISSUE TITLE
UsePackageHandler 里怎么做业务处理呢

### ISSUE THREAD

**Issue by CrazyDotNet** [kerryjiang/SuperSocket#480]
使用的是2.0 Beta8；集成在 Abp VNext 4.2.1的 Asp net core 项目中
需要收到出数据包做业务处理，比如注入仓储类和读写缓存等
```cs
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                }).
                AsSuperSocketHostBuilder<TextPackageInfo, LinePipelineFilter>()

                .UsePackageHandler((s, p) =>
                {
                    
                    // echo message back to client
                    Console.WriteLine(p.Text);
                    return ValueTask.CompletedTask;
                })
                .UseSession<MySocketAppSession>()
                .UseInProcSessionContainer()
                .UseAutofac()
                .UseSerilog();
```

**Comment by kerryjiang** [comment]
业务逻辑放在这里面不行吗？
```
.UsePackageHandler((s, p) =>
  {
      // s.Server.ServiceProvider.GetService<Abc>();
      // put your business logics here
  })
```

使用server的service provider访问反转控制容器内定义的服务：
https://github.com/kerryjiang/SuperSocket/blob/17b229dc9b8cf782f5327c9e210c48928d4dc306/src/SuperSocket.Primitives/IServerInfo.cs#L15

**Comment by h0730303779** [comment]
> s.Server.ServiceProvider.GetService<Abc>();

我和题主一样问题... 是的是可以Program.cs这里实现业务逻辑...这也太不优雅了..至少给抽个自定义的
业务逻辑放在这里面不行吗？
`
.UsePackageHandler<MyPackag>(MyHandler) //bilibili之类的吗来处理吧..
`

**Comment by kerryjiang** [comment]
@h0730303779 建议使用命令(Command)来处理复杂的业务逻辑，并不是建议你改成命令行协议。

https://docs.supersocket.net/v2-0/zh-CN/Command-and-Command-Filter
