### ISSUE TITLE
2.0版如何动态创建socket服务通道

### ISSUE THREAD

**Issue by elseif** [kerryjiang/SuperSocket#487]
不用依赖注入，如何用factory动态创建socket通道呢？2.0的例子都是用依赖注入在启动的时候创建了固定的服务通道，如何在运行过程中创建和删除服务通道呢

**Comment by kerryjiang** [comment]
Sorry, SuperSocket 暂不支持此功能，但我会考虑是否支持它。

**Comment by kerryjiang** [comment]
建议通过网关或者负载均衡器来动态管理对外监听IP核端口。
