### ISSUE TITLE
master 版本 数据包过滤后Buffer堆积问题

### ISSUE THREAD

**Issue by ScottFan** [kerryjiang/SuperSocket#488]
开发环境VS2019  .net core 3.1
`static async Task Main(string[] args)
        {
            var host = SuperSocketHostBuilder.Create<StringPackageInfo, CommandLinePipelineFilter>().//创建宿主
                UsePackageHandler(async (session, package) =>//注册用于处理接收到的数据的包处理器
                {
                    try
                    {                      
                        await session.SendAsync(Encoding.UTF8.GetBytes(result.ToString() + "\r\n"));
                    }
                    catch (System.Exception)
                    {
                        System.Console.WriteLine("指令错误");
                    }

                }).ConfigureSuperSocket(options =>//配置服务器如服务器名和监听端口等基本信息
                {
                    options.Name = "Server";
                    options.ReceiveBufferSize = 2048;
                    options.Listeners = new List<ListenOptions>(){
            new ListenOptions{
                Ip="Any",
                Port = 5000
            }
         };
                }).Build();
            await host.RunAsync();
            System.Console.WriteLine("Server started!");
        }
    }`
测试时发现发送“内容“+”\r\n"，服务器工作正常，如果客户端发送数据是“内容“+”\\r\\n"后 ，服务端不会执行try{}中的代码，跟踪调试后发现是SuperSocket\src\SuperSocket.ProtoBase\TerminatorPipelineFilter.cs中
public override TPackageInfo Filter(ref SequenceReader<byte> reader)方法      
           这个地方返回null
           if (!reader.TryReadTo(out ReadOnlySequence<byte> pack, terminatorSpan, advancePastDelimiter: false))
                return null;
这是要求发送数据必须是\r\n结尾吗？
还有出现这种情况后，以后再发送“内容“+”\r\n"，SuperSocket\src\SuperSocket.Channel\PipeChannel.cs这个文件中
protected async Task ReadPipeAsync(PipeReader reader)方法中的result.Buffer会出现堆积，如发送的内容是11个byte,那么后来result.Bufferr的大小就是11byte*发送次数。只有在
private bool ReaderBuffer(ref ReadOnlySequence<byte> buffer, out SequencePosition consumed, out SequencePosition examined)这个方法中这部分代码
if (packageInfo == null)
                {
                    // the current pipeline filter needs more data to process
                    if (!filterSwitched)
                    {
                        // set consumed position and then continue to receive...
                        consumed = buffer.GetPosition(bytesConsumedTotal);
                        return true;
                    }
                    
                    // we should reset the previous pipeline filter after switch
                    currentPipelineFilter.Reset();
                }
在
if (!filterSwitched)
                    {
                        // set consumed position and then continue to receive...
                        consumed = buffer.GetPosition(bytesConsumedTotal);
                        此处添加
                        currentPipelineFilter.Reset();//添加这句后result.Buffer正常
                        return true;
                    }
后来试过出现这个问题后，客户端断开重连result.Buffer就正常了。
请教下.net core 3.1的正确使用方式

**Comment by kerryjiang** [comment]
你呢用一个测试用例描述你的问题吗？

**Comment by ScottFan** [comment]
你好，

附件是我的测试代码，测试用的数据代码中有，当时在git上提issue就是想了解数据包的末尾是不是必须是\r\n才可以。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kerryjiang/SuperSocket"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月11日(星期天) 凌晨3:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kerryjiang/SuperSocket] master 版本 数据包过滤后Buffer堆积问题 (#488)





 
你能用一个测试用例描述你的问题吗？

**Comment by DonPangPang** [comment]
默认的CommandLinePipelineFilter必须添加\r\n，你也可以通过自己重写该PipelineFilter以其他方式获取一包数据

**Comment by kerryjiang** [comment]
必须按照协议发送接收数据。请根据你的协议选择合适协议解析模版实现PipelineFilter。

**Comment by ScottFan** [comment]
嗯，谢谢您的回复，有时间我再研究学习一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kerryjiang/SuperSocket"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月3日(星期一) 上午10:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kerryjiang/SuperSocket] master 版本 数据包过滤后Buffer堆积问题 (#488)





 
必须按照协议发送接收数据。请根据你的协议选择合适协议解析模版实现PipelineFilter。
