### ISSUE TITLE
Multi filter

### ISSUE THREAD

**Issue by masterchen** [kerryjiang/SuperSocket#490]
This is very helupful wheel to develope a socket server, Thank you!
In my usage case , the client devices may send  json strings and fiexed  Begin and End marker  hex data.
How to implement multi filters to support different format packages in netcore ? i know there has pipline , this should be supported !can you give some example ? 

Thanks

**Comment by kerryjiang** [comment]
Please take a look at the property NextFilter of PipelineFilter:

https://github.com/kerryjiang/SuperSocket/blob/6ee95fa1d317bb888b50ecc6ad5b9beb799f9dfd/src/SuperSocket.WebSocket/WebSocketPipelineFilter.cs#L25-L39

**Comment by masterchen** [comment]
well thank you, i will have a try
