### ISSUE TITLE
IPipelineFilter Use DependencyInjection

### ISSUE THREAD

**Issue by qzwzqty** [kerryjiang/SuperSocket#499]
Hello,How do I use constructor dependency injection in IPipelineFilter,thanks!
````
AddServer<xxxxPackage, xxxxxPipelineFilter>
````

**Comment by kerryjiang** [comment]
Unfortunately, you cannot do it directly right now.

But probably you can try UsePipelineFilterFactory() instead:

https://github.com/kerryjiang/SuperSocket/blob/6807d7314521f77f4f01d87bc7aac04c39e219f4/src/SuperSocket.Server/SuperSocketHostBuilder.cs#L168-L184

**Comment by qzwzqty** [comment]
I'll give it a try，thx
