### ISSUE TITLE
Code sample  on How to use tcp server and websocket server 

### ISSUE THREAD

**Issue by masterchen** [kerryjiang/SuperSocket#500]
Hi kerryjiang,
In your example, tcp server use supersockethostbuilder, and websocket server  use websockethostbuilder,
can you show me  the code on  how to setup tcp server and websocket server   which  are hosted in  one net core console application ?  Thank you!

**Comment by kerryjiang** [comment]
Doc:
https://docs.supersocket.net/v2-0/en-US/Multiple-Server-Instances

And one piece of sample code:

https://github.com/kerryjiang/SuperSocket/blob/6807d7314521f77f4f01d87bc7aac04c39e219f4/test/SuperSocket.Tests/MainTest.cs#L541-L585

**Comment by kerryjiang** [comment]
This is a better sample:

https://github.com/kerryjiang/SuperSocket/blob/6807d7314521f77f4f01d87bc7aac04c39e219f4/test/SuperSocket.Tests/WebSocket/WebSocketBasicTest.cs#L876-L911

**Comment by masterchen** [comment]
this is really helpful ,thank you very much!
