### ISSUE TITLE
.net core UseClearIdleSession error

### ISSUE THREAD

**Issue by fengjiannan2010** [kerryjiang/SuperSocket#501]
bool isSuccess = true;
            //配置参数
            host.ConfigureSuperSocket(options =>
            {
                options.Name = "PxIotServer";
                options.MaxPackageLength = 1024 * 1024;
                options.ReceiveBufferSize = 4 * 1024;
                options.SendBufferSize = 4 * 1024;
                options.ReceiveTimeout = 0;
                options.SendTimeout = 5 * 1000;
                options.ClearIdleSessionInterval = 1;
                options.IdleSessionTimeOut = 5;
                options.Listeners = new[] { new ListenOptions { Ip = "Any", Port = 7010, BackLog = 1024 } }.ToList();
            });
            //使用会话的连接和断开事件
            host.UseSessionHandler(OnConnectedAsync, OnClosedAsync);
            //使用会话的数据接收时间
            host.UsePackageHandler(OnPackageAsync);
            //TODO 清理空闲的Session
            host.UseClearIdleSession();
            //启动
            host.RunConsoleAsync();
            PrintSessionAsync();
            return isSuccess;

           error message in ClearIdleSessionMiddleware file:  _sessionContainer  is null

            if (_sessionContainer == null)
                throw new Exception($"{nameof(ClearIdleSessionMiddleware)} needs a middleware of {nameof(ISessionContainer)}");
         
            Please tell me how to solve it, or I forgot what to configure

           thank you very much

**Comment by kerryjiang** [comment]
You need declare the session container when you initialize the host builder:

https://github.com/kerryjiang/SuperSocket/blob/6807d7314521f77f4f01d87bc7aac04c39e219f4/test/SuperSocket.Tests/SessionContainerTest.cs#L81
