### ISSUE TITLE
ReadTimeOut

### ISSUE THREAD

**Issue by Janry** [kerryjiang/SuperSocket#505]
Need to add ReadTimeOut parameter to close session if nothing receive.
Because Idle session check LastActiveTime that update when session send something.

**Comment by chucklu** [comment]
https://docs.supersocket.net/v2-0/en-US/Start-SuperSocket-by-Configuration
receiveTimeout: the timeout for receiving; in milliseconds;

**Comment by Janry** [comment]
@chucklu This is not exactly what I need.
I need to close the connection if the client does not send anything within 10 seconds.

**Comment by kerryjiang** [comment]
Enable ClearIdleSession
