### ISSUE TITLE
How to know the client connect status

### ISSUE THREAD

**Issue by DavidZhiXing** [kerryjiang/SuperSocket#513]
How to know `IEasyClient<T>` client connect state? Shall I use` client.LocalEndPoint == null` as a disconnect status?

**Comment by chucklu** [comment]
What did you mean by `connect status`?
```
public class EasyClient<TReceivePackage> : IEasyClient<TReceivePackage>{
 protected IChannel<TReceivePackage> Channel { get; private set; }
}
```
The Channel has  IsClosed property.

For  interface IEasyClient<TReceivePackage>, you might register Closed event to handle the status manually. Anyway you can implement your own class to maintain the status by yourself.

**Comment by chucklu** [comment]
The status of socket can be checked like this, however you need store the [socket ](https://github.com/kerryjiang/SuperSocket/blob/37effd9c0858bf4546eb5a499f4784fe1b90a20a/src/SuperSocket.Client/EasyClient.cs#L140)by yourself
https://stackoverflow.com/a/2661876/13338936
```C#
bool SocketConnected(Socket s)
{
    bool part1 = s.Poll(1000, SelectMode.SelectRead);
    bool part2 = (s.Available == 0);
    if (part1 && part2)
        return false;
    else
        return true;
}
```

**Comment by askdong** [comment]
I have the same question!

**Comment by askdong** [comment]
@DavidZhiXing， 后来你是如何解决此问题的？ 谢谢

**Comment by askdong** [comment]
@DavidZhiXing， 后来你是如何解决此问题的？ 谢谢

**Comment by DavidZhiXing** [comment]
太久，我有点忘记了，似乎后面解决起来挺简单的...你能再详细描述一下你的问题或者需求吗？
