### ISSUE TITLE
Strong Naming in the 1.6 branch

### ISSUE THREAD

**Issue by etomm** [kerryjiang/SuperSocket#53]
Hello,
Supersocket.Websocket assembly is not strong named. All the others needed are.

This breaks dependencies where projects are strong named.

**Comment by kerryjiang** [comment]
Ok, it seems I should create a new package for signed SuperSocket.WebSocket.

**Comment by etomm** [comment]
Yes, or seeing how the other packages are released I would simply sign the assembly inside SuperSocket.WebSocket too and with the same key.

In theory you shoud not break anything for who uses nugets.

**Comment by kerryjiang** [comment]
OK, the package is updated just now:
https://www.nuget.org/packages/SuperSocket.WebSocket/
