### ISSUE TITLE
SessionID不一致

### ISSUE THREAD

**Issue by hellofengge** [kerryjiang/SuperSocket#533]
作者你好，我在使用supersocet1.6.6.1版本时发现一个问题，我在session创建时将sessionID添加到集合，当关闭连接时将sessionID从集合中移除，我发现能正确移除的sessionID可以找到添加日志，但是存在部分sessionID无法正确移除，添加日志也没有；请问，这是什么原因导致的，sessionID会在创建之后发生改变吗？

**Comment by kerryjiang** [comment]
SessionID不会改变

**Comment by hellofengge** [comment]
好的，谢谢
