### ISSUE TITLE
System.OutOfMemoryException

### ISSUE THREAD

**Issue by hellofengge** [kerryjiang/SuperSocket#534]
Framework 版本: v4.0.30319
说明: 由于未经处理的异常，进程终止。
异常信息: System.OutOfMemoryException
   在 SuperSocket.SocketEngine.AsyncSocketSession.Initialize(SuperSocket.SocketBase.IAppSession)
   在 SuperSocket.SocketBase.AppSession`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Initialize(SuperSocket.SocketBase.IAppServer`2<System.__Canon,System.__Canon>, SuperSocket.SocketBase.ISocketSession)
   在 SuperSocket.SocketBase.AppServerBase`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SuperSocket.SocketBase.IAppServer.CreateAppSession(SuperSocket.SocketBase.ISocketSession)
   在 SuperSocket.SocketEngine.TcpSocketServerBase.CreateSession(System.Net.Sockets.Socket, SuperSocket.SocketBase.ISocketSession)
   在 SuperSocket.SocketEngine.AsyncSocketServer.ProcessNewClient(System.Net.Sockets.Socket, System.Security.Authentication.SslProtocols)
   在 SuperSocket.SocketEngine.AsyncSocketServer.OnNewClientAccepted(SuperSocket.SocketEngine.ISocketListener, System.Net.Sockets.Socket, System.Object)
   在 SuperSocket.SocketEngine.SocketListenerBase.OnNewClientAccepted(System.Net.Sockets.Socket, System.Object)
   在 SuperSocket.SocketEngine.TcpAsyncSocketListener.ProcessAccept(System.Net.Sockets.SocketAsyncEventArgs)
   在 SuperSocket.SocketEngine.TcpAsyncSocketListener.acceptEventArg_Completed(System.Object, System.Net.Sockets.SocketAsyncEventArgs)
   在 System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(System.Net.Sockets.SocketAsyncEventArgs)
   在 System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(System.Object)
   在 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   在 System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(System.Net.Sockets.SocketError, Int32, System.Net.Sockets.SocketFlags)
   在 System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
   在 System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

**Comment by kerryjiang** [comment]
参数问题吧，maxConnectionNumber * receiveBufferSize 过大

**Comment by kerryjiang** [comment]
建议升级到2.0

**Comment by hellofengge** [comment]
好的
