### ISSUE TITLE
Can it works in .net6?

### ISSUE THREAD

**Issue by JerryLiew** [kerryjiang/SuperSocket#538]
When i try to install the supersocket library in my empty .net6 project,Vs prompted warings that it was not Compatible with .net6.  i ignored it,but i found  the config files was not created automatically exist

**Comment by nasir-awan** [comment]
It should be working with .NET 6.0

**Comment by JerryLiew** [comment]
> 

thanks for your answer, but i found the config files did not be created automatically when i install the supersocket lib from nuget.but it could be creadted automaitcally in netframework.

**Comment by ScarletKuro** [comment]
Checked, works for me.
It sounds like you are using 1.6.x version that was for .net framework instead of 2.0.0 for .net core? Because I don't recall any config to be present in 2.0.0.
So yeah if you are using 1.6.x it won't work.

**Comment by JerryLiew** [comment]
> Checked, works for me.
> It sounds like you are using 1.6.x version that was for .net framework instead of 2.0.0 for .net core? Because I don't recall any config to be present in 2.0.0.
> So yeah if you are using 1.6.x it won't work.

thanks a lot,i will check it and try again.

**Comment by xyhere2001** [comment]
supersocket 2.0 work will on net 6
