### ISSUE TITLE
Question about Tests

### ISSUE THREAD

**Issue by Baccanno** [kerryjiang/SuperSocket#54]
Hi kerryjiang,

I didn't find of the documentation statements about the testing procedure. Is there an easy way to mock server and session connections in order to perform command execution tests ? 

It would be great to add some points in the documentation to increase the ease to put in production

Thanks for the lib

**Comment by kerryjiang** [comment]
The Test project of SuperSocket can be used as a sample for unit test.

**Comment by Baccanno** [comment]
I Will investigate in this then. If I come up with a working test I'll make a documentation PR.

**Comment by kerryjiang** [comment]
Great, thanks!

**Comment by kerryjiang** [comment]
Suggest you upgrade to SuperSocket 2.0.
