### ISSUE TITLE
关于IPackageEncoder的问题

### ISSUE THREAD

**Issue by JimReal** [kerryjiang/SuperSocket#553]
在2.0.0-beta.10版本中，我使用自定义协议实现FixedHeaderPipelineFilter。
其中协议的header包含一个key和一个发送消息的用户id（int64）。
我尝试用MemoryStream将整个包组合成byte[]后使用Encoding.UTF8.GetString转码得到一条字符串。
这会导致id所处的位置乱码。
还有别的方案可以写入writer吗？
我使用.net core做服务端\客户端

**Comment by JimReal** [comment]
我目前考虑两种方案：
1、使用string类型的用户id（固定长度）。
2、将id转换为16进制后直接使用stringbuilder拼接整个包体。
想了解有没有转换到二进制而不乱码的方案

**Comment by chucklu** [comment]
show me the code

**Comment by JimReal** [comment]
`public int Encode(IBufferWriter<byte> writer, IMPackage pack)
        {
            byte[] buffer = null;
            var bodyBuffer = Encoding.UTF8.GetBytes(pack.Body);
            using (MemoryStream ms = new MemoryStream())
            {
                ms.WriteByte(pack.Key);//命令字
                ms.Write(BitConverter.GetBytes(pack.SId));//发送者
                ms.Write(BitConverter.GetBytes(pack.RId));//接受者
                ms.Write(BitConverter.GetBytes(bodyBuffer.Length));//包体长度
                ms.Write(bodyBuffer);//包体
                buffer = ms.ToArray();
            }
            var str = Encoding.UTF8.GetString(buffer);
            var num = writer.Write(str, Encoding.UTF8);
            return num; 
        }`

**Comment by chucklu** [comment]
Please provide a [mcve](https://meta.stackoverflow.com/questions/366988/what-does-mcve-mean) example with your own repository

**Comment by JimReal** [comment]
https://github.com/JimReal/SocketDemo
包含了客户端和服务端代码。

**Comment by kerryjiang** [comment]
It's not correct way to encode a package.

**Comment by kerryjiang** [comment]
Encode the package with writer(IBufferWriter) directly instead of encoding/decoding it with MemoryStream.

**Comment by JimReal** [comment]
那就是我的问题 我应该如何转换object到text呢

**Comment by JimReal** [comment]
了解到问题所在了。
因为我一直查看的扩展包是：SuperSocket.ProtoBase.Extensions
而System.Memory包内置了直接写入byte[]类型的方法：System.Buffers.BuffersExtensions
