### ISSUE TITLE
superSocket 1.6版本中重写命令

### ISSUE THREAD

**Issue by bai888888** [kerryjiang/SuperSocket#558]
supersocket是不是异步接收的？
重写命令的时候要不要加上async
public override async void ExecuteCommand(MyAppSession session, MyRequestInfo requestInfo)

因为要频繁的进行数据库存储读取，发现加上async，好像变得快一些，
像这种频繁的进行数据库存储读取，有没有好的处理方式呢

**Comment by kerryjiang** [comment]
1.6 的命令本身不支持异步。但是你可以在命令内用异步实现。
