### ISSUE TITLE
Failure in !bootstrap.Initialize() using SuperSocket.WebSocket.dll

### ISSUE THREAD

**Issue by aliahaider** [kerryjiang/SuperSocket#560]
I just switched to using SuperSocket.WebSocket.dll (1.6..6.1) as SuperWebSocket.dll (0.9.0.2) was not compatible with SuperSocket.SocketBase, SuperSocket.SocketEngine and SuperSocket.Common (1.6.6.1 .NET 4.5).
I also have made some changes to my config file based on your recommendations.
But I am still getting an exception in the bootStrap.Initialize().
I think there is something not correct with some of the config I am using.
With SuperWebSocket I was using:
    <serverTypes>
      <add name="SuperWebSocket" type="SuperWebSocket.WebSocketServer, SuperWebSocket"/>
    </serverTypes>

now with SuperSocket.WebSocket I have changed it to:
    <serverTypes>
      <add name="SuperWebSocket" type="SuperWebSocket.WebSocketServer, SuperSocket.WebSocket"/>
    </serverTypes>

But I am not sure if this is correct. Can you please help.

Thanks,

**Comment by kerryjiang** [comment]
What exception did you get?

**Comment by aliahaider** [comment]
Since bootStrap.Initialize() did not work for me.
I changed the code as follows but it does not seem to ever return from bootStrap.GetServerByName("SuperWebSocket") so now it fails in bootStrap.GetServerName().   

My config for server:
  <superSocket>
    <servers>
      <server name="SuperWebSocket" serverTypeName="SuperSocket.WebSocket" ip="Any" port="XXXX" mode="Tcp" keepAliveTime="1000000000" maxCommandLength="20480" sendingQueueSize="10" receiveBufferSize="16384" sendBufferSize="4096" readTimeout="10" sendTimeout="10" sessionSnapshotInterval="25"></server>
    </servers>
    <serverTypes>
      <add name="SuperWebSocket" type="SuperSocket.WebSocket.WebSocketServer, SuperSocket.WebSocket"/>
    </serverTypes>
  </superSocket>

Here is my code:

        private void StartSuperWebSocketByConfig()
        {
            logger.Debug("Entering StartSuperWebSocketByConfig");
            var serverConfig = ConfigurationManager.GetSection("superSocket") as SocketServiceConfig;
            logger.Debug("Done with GetSection");

            bootStrap = new DefaultBootstrap(serverConfig);

            logger.Debug("Getting GetServerByName");
           var socketServer = bootStrap.GetServerByName("SuperWebSocket") as WebSocketServer;
            logger.Debug("Done getting GetServerByName");

            socketServer.NewMessageReceived += new SessionHandler<WebSocketSession, string>(socketServer_NewMessageReceived);
            socketServer.NewSessionConnected += new SessionHandler<WebSocketSession>(socketServer_NewSessionConnected);
            socketServer.SessionClosed += new SessionHandler<WebSocketSession, CloseReason>(socketServer_SessionClosed);

            if (bootStrap.Start() != StartResult.Success)
            {
                Logger.WriteString("StartSuperWebSocketByConfig", " failed to start " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
                bootStrap.Stop();
            }

Thanks!

**Comment by aliahaider** [comment]
My config for server:
  <superSocket>
    <servers>
      <server name="SuperWebSocket" serverTypeName="SuperSocket.WebSocket" ip="Any" port="XXXX" mode="Tcp" keepAliveTime="1000000000" maxCommandLength="20480" sendingQueueSize="10" receiveBufferSize="16384" sendBufferSize="4096" readTimeout="10" sendTimeout="10" sessionSnapshotInterval="25"></server>
    </servers>
    <serverTypes>
      <add name="SuperWebSocket" type="SuperSocket.WebSocket.WebSocketServer, SuperSocket.WebSocket"/>
    </serverTypes>
  </superSocket>

**Comment by kerryjiang** [comment]
You said you got an exception. Could you tell me the details of the exception?

**Comment by aliahaider** [comment]
That is what I see in the logs
2022-04-22 13:37:37,982 [1] DEBUG AspenONEWebSocket.Program [PID:4476] (C:\Users\haidera\source\Workspaces\aspenONE\main\aspenONEServices\AspenONEWebSocket\AspenONEWebSocket\Program.cs:145) - Entering StartSuperWebSocketByConfig
2022-04-22 13:37:38,285 [1] DEBUG AspenONEWebSocket.Program [PID:4476] (C:\Users\haidera\source\Workspaces\aspenONE\main\aspenONEServices\AspenONEWebSocket\AspenONEWebSocket\Program.cs:147) - Calling bootStrap.Initialize
2022-04-22 13:37:38,669 [1] ERROR Aspen.aspenONE.RabbitMQTransport.RabbitMQTransport [PID:4476] (:0) - unhandled exception caught : Exception has been thrown by the target of an invocation.
2022-04-22 13:37:38,789 [1] ERROR Aspen.aspenONE.RabbitMQTransport.RabbitMQTransport [PID:4476] (:0) - unhandled exception caught : Exception has been thrown by the target of an invocation.

**Comment by aliahaider** [comment]
There is no other information or stack trace.

**Comment by aliahaider** [comment]
These are the logs and exception I see when I use bootStrap.Initialize().

Thanks

**Comment by kerryjiang** [comment]
The exception was thrown from RabbitMQTransport. Is it related to SuperSocket?

**Comment by aliahaider** [comment]
It is used in some communication with another process by Web server application using SuperSocket.  The issue is I do not find it returning or finishing bootStrap.Initialize() or bootStrap.GetServerByName(). I am suspecting that my config is not correct. 
Is there a way of turning any logs to see that bootStrap.Initialize or bootStrap.GetServerByName() failed or succeeded?
I have tried to use debugger and set the break points to isolate the issue but so far no luck with debugger somehow application keeps crashing without hitting any of the break points.

**Comment by kerryjiang** [comment]
Please configure the logging correctly and you may find more information from logs.

**Comment by aliahaider** [comment]
I found after adding some exceptions that it fails in bootStrap Initialize and GetServerByName. I am suspecting something in the config.

**Comment by aliahaider** [comment]
Failed in bootStrap.InitializeSystem.NullReferenceException: Object reference not set to an instance of an object.
Failed in bootStrap.GetServerByNameSystem.NullReferenceException: Object reference not set to an instance of an object.
I am still suspecting my config though I have made all the changes recommended.
Thanks!

**Comment by aliahaider** [comment]
After adding the exception I am seeing this exception when calling bootStrap.Initialize():

- Failed in bootStrap.InitializeSystem.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Could not load file or assembly 'log4net, Version=1.2.13.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at SuperSocket.SocketBase.Logging.Log4NetLogFactory..ctor(String log4netConfig)
   at SuperSocket.SocketBase.Logging.Log4NetLogFactory..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at SuperSocket.SocketBase.Provider.ExportFactory.CreateInstance()
   at SuperSocket.SocketBase.Provider.ExportFactory.CreateExport[T]()
   at SuperSocket.SocketEngine.DefaultBootstrap.Initialize(Func`2 serverConfigResolver, ILogFactory logFactory)
   at SuperSocket.SocketEngine.DefaultBootstrap.Initialize(Func`2 serverConfigResolver)
   at SuperSocket.SocketEngine.DefaultBootstrap.Initialize()

Is it really using log4net v 1.2.13.0? I am using log4net v2.0.4. I thought supersocket 1.6.6.1  requires log4net v2.0.3.

Thanks!

**Comment by kerryjiang** [comment]
Try binding redirection:
https://stackoverflow.com/questions/19372477/how-to-assembly-redirect-log4net-to-newer-version

**Comment by aliahaider** [comment]
<runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="log4net" publicKeyToken="669e0ddf0bb1aa2a" culture="neutral" />
        <bindingRedirect oldVersion="1.2.13.0" newVersion="2.0.14.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>

adding the above to me app.config made it worked. Thanks!

**Comment by aliahaider** [comment]
My config was correct for SuperSocket.WebSocket and everything worked after fixing the exception resulting due to mismatch log4net assembly versions.
Thanks!
