### ISSUE TITLE
在多服务器模式下 能否启用Session容器UseInProcSessionContainer？

### ISSUE THREAD

**Issue by zxy0106** [kerryjiang/SuperSocket#561]

**Comment by kerryjiang** [comment]
Yes, you can.

https://github.com/kerryjiang/SuperSocket/blob/d0e5bcfe363dd0ee3a4bacff3f8bc16a8cf9301e/test/SuperSocket.Tests/MainTest.cs#L541-L580

**Comment by zxy0106** [comment]
thanks.
请问，多服务器启用了UseInProcSessionContainer，ASP.Net Core在Controller中如何获取所有会话呢？

**Comment by kerryjiang** [comment]
Try register ISessionContainer to the global DI context.
