### ISSUE TITLE
Need config  example for SuperSocket.WebSocket

### ISSUE THREAD

**Issue by aliahaider** [kerryjiang/SuperSocket#562]
I have switched from SuperWebSocket to SuperSocket.WebSocket. 
I am a bit confused about the config changes I need if I am using SuperSocket.WebSocket.
I used to have this as config with SuperWebSocket:
  <socketServer>
    <servers>
      <server name="SuperWebSocket" serviceName="SuperWebSocket"></server>
    </servers>
    <services>
      <service name="SuperWebSocket" type="SuperWebSocket.WebSocketServer, SuperWebSocket"/>
    </services>
  </socketServer>

With SuperSocket.WebSocket I have this but I am not sure if it is correct:

<superSocket>
    <servers>
      <server name="SuperWebSocket" serverTypeName="SuperWebSocket"></server>
    </servers>
    <serverTypes>
      <add name="SuperWebSocket"  type="SuperSocket.WebSocket.WebSocketServer, SuperSocket.WebSocket"/>
    </serverTypes>
  </superSocket>

Thanks!

**Comment by kerryjiang** [comment]
Can it help?
https://github.com/kerryjiang/SuperSocket/tree/v1.6/QuickStart/ConfigSample

**Comment by aliahaider** [comment]
The config I had posted was correct and has been working after redirecting  the binding for log4net version per your suggestion that fixed the crash in bootstrap.initialize(). Hence closing this issue. Thanks so much for the sample Configs!
