### ISSUE TITLE
请教下,Asp.Net6 下怎么使用，我曾在Net5使用正常

### ISSUE THREAD

**Issue by NickCc6** [kerryjiang/SuperSocket#563]
![1](https://user-images.githubusercontent.com/42535452/167063252-adde6805-c241-4a28-b953-094fe3fc15da.jpg)
![2](https://user-images.githubusercontent.com/42535452/167063254-6b95bd71-5d50-413e-a880-4a15526f8728.jpg)
![3](https://user-images.githubusercontent.com/42535452/167063256-840ff070-44bc-4584-9d76-24cfc99e715c.jpg)

**Comment by NickCc6** [comment]
使用Net5的写法完成了需求。

**Comment by cyx218** [comment]
请问在.net6中你是用2.0版本还是1.6？

**Comment by cyx218** [comment]
> 使用Net5的写法完成了需要。

请问.NET6中你完成了吗？可以运行并且跨平台吗?

**Comment by NickCc6** [comment]
@cyx218 Net6下可用了，可以看下这个大佬提供的解决方案
#605 
客户服务器是win的，所以我没试过linux,理论上是可行的，因为net6本身就跨平台，你可以测试下

**Comment by cyx218** [comment]
> 

好的，谢谢

**Comment by cyx218** [comment]
> @cyx218 Net6下可用了，可以看下这个大佬提供的解决方案 #605 客户服务器是win的，所以我没试过linux,理论上是可行的，因为net6本身就跨平台，你可以测试下

好的，谢谢
