### ISSUE TITLE
supersocket 2.0 client 接收数据

### ISSUE THREAD

**Issue by easyboot** [kerryjiang/SuperSocket#564]
using SuperSocket.Client;
using SuperSocket.ProtoBase;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Net;
using System.Text;
using System.Threading.Tasks;

namespace aa.Communication
{
    public class TCPSuperSocket
    {
        readonly IEasyClient<MyPackage> client = new EasyClient<MyPackage>(new MyPackageFilter()).AsClient();
        public static TCPSuperSocket instance;

        public static TCPSuperSocket GetInstance()
        {
            if (instance == null)
            {
                instance = new TCPSuperSocket();
            }
            return instance;
        }

        public async void Connect()
        {
            Task.Run(async () =>
            {
               RunClient();
            });
        }

        private async void RunClient()
        {
            string ClassName = System.Reflection.MethodBase.GetCurrentMethod().DeclaringType.Name;
            string FuncName = System.Reflection.MethodBase.GetCurrentMethod().Name;

            string strmsg1 = $"0 { util.GetNow()} connectSUPERSOCKET ";
            App.Log.Info(strmsg1);

            string IP = "127.0.0.1";
            int Port = 9999;

            if (!await client.ConnectAsync(new IPEndPoint(IPAddress.Parse(IP), Port))) ;

            try
            {
                while (true)
                {
                    Debug.WriteLine($"{util.GetNow()} --");

                    var p = await client.ReceiveAsync();

                    if (p != null) 
                    {
                        Debug.WriteLine(p.Body);

                        Debug.WriteLine($"{util.GetNow()} -- 111 {p.Body}");
                    }
                    else
                    {
                        Debug.WriteLine($"{util.GetNow()} -- else");
                    }
                }
            }
            catch (Exception ex)
            {
                App.Log.Error($"{ex.Message}");
            }
        }

        public void Send(string cmd)
        {
            try
            {
                byte[] byteArray = System.Text.Encoding.ASCII.GetBytes(cmd);
                client.SendAsync(byteArray);
            }
            catch (Exception ex)
            {

                App.Log.Error(ex.message);
            }
        }

        public void Dispose()
        {
            client.CloseAsync();
        }
    }
}

我根据[SuperSocket](https://github.com/kerryjiang/SuperSocket)/[samples]的例子写的代码，和网络助手通讯，客户端可以给网络助手服务端发送数据。但是网络助手发送给客户端的数据始终不显示。我哪里弄错了吗？
(https://github.com/kerryjiang/SuperSocket/tree/master/samples)/BasicClient/

**Comment by kerryjiang** [comment]
在网络助手没按照协议发送

**Comment by easyboot** [comment]
using SuperSocket.Client;
using SuperSocket.ProtoBase;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft;
using Newtonsoft.Json;

namespace InfusionBagLabel.Communication
{
    public class TCPSuperSocket
    {  
        public static TCPSuperSocket instance; 
        public IEasyClient<TextPackageInfo> client1 { get; set; } = new EasyClient<TextPackageInfo>(new LinePipelineFilter()).AsClient();
   
        public static TCPSuperSocket GetInstance()
        {
            if (instance == null)
            {
                instance = new TCPSuperSocket();
            }
            return instance;
        }

        public async void Connect()
        {
            //RunClient();
            Task.Run(() =>
           {
               RunClient();
           });
        }

        private async void RunClient()
        {
            string ClassName = System.Reflection.MethodBase.GetCurrentMethod().DeclaringType.Name;
            string FuncName = System.Reflection.MethodBase.GetCurrentMethod().Name;
            string TCPTestIP = Config.GetInstance().GetConfig("TCPTestIP");
            int TCPTestPort = int.Parse(Config.GetInstance().GetConfig("TCPTestPort"));
 
           await client1.ConnectAsync(new IPEndPoint(IPAddress.Parse(TCPTestIP), TCPTestPort));
                while (true)
                {
                    Debug.WriteLine($"{util.GetNow()} -- {client1.LocalEndPoint}");

                    var pp = await client1.ReceiveAsync();
                    if (pp != null)
                    {
                        try
                        {

                        if (pp.Text.Length > 0)
                        {
                            Debug.WriteLine($"{util.GetNow()} -- 222- {pp.Text} ");
                            }
                        }
                        catch (Exception ex)
                        {
                            App.Log.Error($"{ex.Message}");
                        }
                }
            } 
        }

        public void Send(string cmd)
        {
            try
            {
                byte[] byteArray = System.Text.Encoding.ASCII.GetBytes(cmd);
    
                client1.SendAsync(byteArray);
            }
            catch (Exception ex)
            {
                string ClassName = System.Reflection.MethodBase.GetCurrentMethod().DeclaringType.Name;
                string FuncName = System.Reflection.MethodBase.GetCurrentMethod().Name;
                string msg = @$"
                                    Class Name [{ClassName}]
                                    Function   [{FuncName}]
                                    RecvTime   [{util.GetNow()}]
                                    Parameter
                                    Message  视觉通讯出现异常  [{ex.Message}]";
                App.Log.Error(msg);
            }
        }

        public void Dispose()
        {
            client.CloseAsync();
        }
    }
}


我修改了一下我的代码，服务端发送数据要带回车换行才行。
但是我发现一个新的问题，如果服务器将客户端断开后，则supersocket进入死循环一直执行while(true)的内容。好像忽略了  var pp = await client1.ReceiveAsync();这行代码？我该如何修改才好。
