### ISSUE TITLE
Error in sending response to clients

### ISSUE THREAD

**Issue by mdawood1991** [kerryjiang/SuperSocket#57]
Hi,

We have used Super Socket to create a TCPServer for GPS Tracking devices.

For some clients we have issues in sending the response (Acknowledgement) from Super Socket Server.

We enabled the Logging for Super Socket and the error been logged is:

```
Caller: SendSync, file path: d:\WorkShop\SuperSocket\v1.6\SocketEngine\AsyncSocketSession.cs, line number: 183
System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at SuperSocket.SocketEngine.AsyncSocketSession.SendSync(SendingQueue queue)
2016-06-20 19:24:30,063 [47] ERROR MyAppServer-35320229 - Session: 591919ef-adc7-487a-b523-b4ef299398ff/41.189.163.56:57895
Unexpected socket error: 10054
```

Please do you know what the issue here could be? How do we fix it - I have tried increasing Sending Time Out, and the Sending Queue Size etc. But still we are having the same problem.

**Comment by kerryjiang** [comment]
From the error, the situation is the client closed the connection.

**Comment by mdawood1991** [comment]
Is there any setting in super socket to keep the connection alive? Because the devices/clients seem to work when connected to an old version of our TCP Server.

**Comment by kerryjiang** [comment]
What's your old tcp server?

**Comment by mdawood1991** [comment]
The Old Version was a really badly written TCP Server about 5 years ago, and had many issues. 

I am posting the Class dealing with Connections here ( it is based on the Async Socket in .NET) but has many issues: 

https://gist.github.com/mdawood1991/2a5618d69aa97ef7810a7064ef220dcc

The new version developed using Super Socket library is very good - the only problem we are facing is that some clients are been disconnected before receiving the ACK message from the Server. so the connection is been closed. 

Is there a way to keep the connection open from server side?

**Comment by kerryjiang** [comment]
SuperSocket can do nothing about this issue.
It cannot prevent the connection from being dropped by the client and intermedia network.

**Comment by mdawood1991** [comment]
ok thanks
