### ISSUE TITLE
How to find a commit corresponding 2.0.0-preview3-05 version

### ISSUE THREAD

**Issue by kinguru** [kerryjiang/SuperSocket#584]
Dear Kerry,
currently I'm using the SuperSocket version 2.0.0-preview3-05 from NuGet repository.
Is it possible to find newest commits after version 2.0.0-preview3-05? Can't find the point of 2.0.0-preview3-05 in the repository commits to start from.

Thanks in advance, 
Ilya

**Comment by chucklu** [comment]
How did you get this version?
The following command failed ,Package 'Supersocket 2.0.0-preview3-05' is not found in the following primary source(s): 'C:\Program Files (x86)\Microsoft 
SDKs\NuGetPackages\,https://api.nuget.org/v3/index.json. Please verify all your online package sources are available (OR) package 
id, version are specified correctly.
> Update-Package Supersocket -Version 2.0.0-preview3-05

**Comment by chucklu** [comment]
You might check the product version of the .dll file, it should contain the commit id.

**Comment by kinguru** [comment]
Seems there is no commit ID in the dll files.
1st screen is file details.
2nd screen is visual studio NuGet package manager.

![image](https://user-images.githubusercontent.com/54497/177032980-14ac8ec3-3ad0-4669-a426-38474557cf58.png)

![image](https://user-images.githubusercontent.com/54497/177033070-5871fa59-5548-409c-b73c-dcb69944b00c.png)

**Comment by chucklu** [comment]
Please be more  accurate next time, Supersocket.WebSocket is not same as Supersocket

> Update-Package Supersocket.WebSocket -Version 2.0.0-preview3-05

The Date modified of the .dll file is 2020-04-27 06:26 AM GMT+8,

Then review the log of this repository, you will find this commit match  `git show ed0f77520e9`, the date time is 2020-04-27 05:30:08 GMT+8, which means this commit is supposed  release 2.0.0-preview3-05

> commit ed0f77520e9f3f7d8a116a79b9a24124b34288a0
> Author: Kerry Jiang <kerry-jiang@hotmail.com>
> Date:   Sun Apr 26 14:30:08 2020 -0700
>
