### ISSUE TITLE
Json 中文支持问题

### ISSUE THREAD

**Issue by labyte** [kerryjiang/SuperSocket#586]
大佬，在使用JsonAsyncCommand这个的时候，中文不支持啊，在哪里可以设置吗？

**Comment by chucklu** [comment]
How did you implement [IPipelineFilter<TPackageInfo>](https://github.com/kerryjiang/SuperSocket/blob/bc621a515a93ad3d7f47a86650167b620056f703/src/SuperSocket.ProtoBase/IPipelineFilter.cs) or [PipelineFilterBase<TPackageInfo>](https://github.com/kerryjiang/SuperSocket/blob/bc621a515a93ad3d7f47a86650167b620056f703/src/SuperSocket.ProtoBase/PipelineFilterBase.cs)?
Please refer to [TerminatorTextPipelineFilter](https://github.com/kerryjiang/SuperSocket/blob/bc621a515a93ad3d7f47a86650167b620056f703/src/SuperSocket.ProtoBase/TerminatorTextPipelineFilter.cs), you should be able to write your own  [Decoder](https://github.com/kerryjiang/SuperSocket/blob/bc621a515a93ad3d7f47a86650167b620056f703/src/SuperSocket.ProtoBase/PipelineFilterBase.cs#L10)  and [DecodePackage](https://github.com/kerryjiang/SuperSocket/blob/bc621a515a93ad3d7f47a86650167b620056f703/src/SuperSocket.ProtoBase/PipelineFilterBase.cs#L16) method.

**Comment by chucklu** [comment]
I forgot that the protocol and command are alternative things, since you choose to use command, it should be another story.

**Comment by chucklu** [comment]
@kerryjiang , we might need to make property [JsonSerializerOptions](https://github.com/kerryjiang/SuperSocket/blob/bc621a515a93ad3d7f47a86650167b620056f703/src/SuperSocket.Command/JsonCommand.cs#L15) can be set
> commit 05d180048c70e9472508d55b8b610533eee35cc6
> Author: Kerry Jiang <kerry-jiang@hotmail.com>
> Date:   Wed Apr 29 21:20:08 2020 -0700
> 
>     fixed the bug which causes the JsonCommand cannot work

@AByte-L  Then the encoding should be set as mentioned in [How to customize character encoding with System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-character-encoding)

@AByte-L  Maybe you can share a sample repository for me to test

**Comment by AByte-L** [comment]
> @kerryjiang，我们可能需要让属性[JsonSerializerOptions](https://github.com/kerryjiang/SuperSocket/blob/bc621a515a93ad3d7f47a86650167b620056f703/src/SuperSocket.Command/JsonCommand.cs#L15)可以设置
> 
> > 提交[05d1800](https://github.com/kerryjiang/SuperSocket/commit/05d180048c70e9472508d55b8b610533eee35cc6)
> > 作者：[姜凯瑞 kerry-jiang@hotmail.com](mailto:kerry-jiang@hotmail.com)
> > 日期：Wed Apr 29 21:20:08 2020 -0700
> > ```
> > fixed the bug which causes the JsonCommand cannot work
> > ```
> 
> @AByte-L 然后应该按照[如何使用 System.Text.Json 自定义字符编码中所述设置编码](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-character-encoding)
> 
> @AByte-L 也许您可以共享一个示例存储库供我测试

发现问题是我客户端发送的时候没使用UTF-8编码....，改了就好了.
