### ISSUE TITLE
Change in active Session the ReceiveFilterFactory

### ISSUE THREAD

**Issue by tinohager** [kerryjiang/SuperSocket#59]
Hello

I want add a new feature in my mail server project, by default "CommandLineReceiveFilterFactory" is a good protocol. But for "BDAT" i must change in a active session the receiveFilterFactory if this possible?

On the BDAT command i receive a octets count of the next message. I think a good FilterFactory for this part is the "FixedSizeReceiveFilter".

> RFC
> https://tools.ietf.org/html/rfc3030

**Comment by kerryjiang** [comment]
Yes, you need define you own RequestInfo and ReceiveFilter.
Your RequestInfo should be a combination of StringRequestInfo and BinaryRequestInfo.

**Comment by kerryjiang** [comment]
And you need take advantage of NextReceiveFilter property of your receive filter.

**Comment by tinohager** [comment]
How i can make a combination i must set on data type in RequestInfo<T>

```cs
public class TestRequestInfo : RequestInfo<byte[]>
public class TestRequestInfo : RequestInfo<string>
```

**Comment by kerryjiang** [comment]
Yes, you can.

Probably we can inherit from StringRequestInfo directly?

public class TestRequestInfo : StringRequestInfo
{
        public byte[] BinaryData { get; set; }
}
