### ISSUE TITLE
Net6 minimal API 中如何使用？

### ISSUE THREAD

**Issue by loveksmy** [kerryjiang/SuperSocket#592]
Net6 minimal API 中如何使用？
`   var builder = WebApplication.CreateBuilder(args);
builder.Host.AsSuperSocketHostBuilder<TextPackageInfo, LinePipelineFilter>()
      var app = builder.Build();`

这样不会启动

**Comment by kerryjiang** [comment]
Try this
https://github.com/kerryjiang/SuperSocket/blob/master/samples/AspNetSample/Program.cs

https://github.com/kerryjiang/SuperSocket/blob/2858a320d911ecebe1c5656366c10f0bee7aaa79/samples/AspNetSample/Program.cs#L8-L25

**Comment by loveksmy** [comment]
thank you！！
