### ISSUE TITLE
FixedHeaderPipelineFilter 怎么处理不同长度的报文

### ISSUE THREAD

**Issue by panghucui** [kerryjiang/SuperSocket#596]
不知道能不能实现如下场景：
1. 报文头的长度是固定的，比如4个bytes
    short length 报文长度 （假设不包括报文头的长度）
    short messageID 报文的ID，报文的唯一标识
2. 有多个报文， 长度和ID都不同，
2.1 报文1, 报文长度10 + 4 = 14 bytes
    short length         2 bytes
    short messageID  2 bytes
    string name         10 bytes
    int age                 4 bytes
2.2 报文2, 报文长度 5 + 4 = 9 
    short length           2 bytes
    short messageID    2 bytes
    string department  5 bytes
    int num                   4 bytes

报文1和报文2需要定义2个结构，收到报文后，根据messageID来判断是哪个电文。
这种情况应该怎么处理呢？
谢谢！

**Comment by kerryjiang** [comment]
FixedHeaderPipelineFilter 就能直接处理，headSize = 4, 拿到了head就能知道剩下部分的长度和message id.
