### ISSUE TITLE
2.0版本，WebSocketSession怎么重写SessionID

### ISSUE THREAD

**Issue by 18682788952** [kerryjiang/SuperSocket#603]
SessionId想根据业务自定义生成Id，如何实现？

**Comment by chucklu** [comment]
https://github.com/kerryjiang/SuperSocket/blob/master/src/SuperSocket.WebSocket.Server/WebSocketSession.cs#L12
https://github.com/kerryjiang/SuperSocket/blob/master/src/SuperSocket.Server/AppSession.cs#L28
```c#
 void IAppSession.Initialize(IServerInfo server, IChannel channel)
        {
            if (channel is IChannelWithSessionIdentifier channelWithSessionIdentifier)
                SessionID = channelWithSessionIdentifier.SessionIdentifier;
            else                
                SessionID = Guid.NewGuid().ToString();
            
            Server = server;
            StartTime = DateTimeOffset.Now;
            _channel = channel;
            State = SessionState.Initialized;
        }
```


You might implement your own IChannelWithSessionIdentifier like this
https://github.com/kerryjiang/SuperSocket/blob/master/src/SuperSocket.Channel/UdpPipeChannel.cs#L30

**Comment by 18682788952** [comment]
![image](https://user-images.githubusercontent.com/31786261/192932982-5e30113b-58f7-4e75-b23e-b2255f006f2a.png)

应该替换现有的呢，没有找到合适的示例

**Comment by chucklu** [comment]
Find the reference of UdpPipeChannel first
https://github.com/kerryjiang/SuperSocket/blob/master/src/SuperSocket.Udp/UdpChannelCreatorFactory.cs#L33

You will need to write your own channel creator factory which implemented IChannelCreatorFactory, then SuperSocketService will resolve it. You need to know how Microsoft.Extensions.DependencyInjection.GetService method works.


You might check these two files:

src\SuperSocket.Server\TcpChannelCreatorFactory.cs
```c#
 public IChannelCreator CreateChannelCreator<TPackageInfo>(ListenOptions options, ChannelOptions channelOptions, ILoggerFactory loggerFactory, object pipelineFilterFactory)
```
src\SuperSocket.Server\SuperSocketService.cs
```c#
   _channelCreatorFactory = serviceProvider.GetService<IChannelCreatorFactory>() ?? new TcpChannelCreatorFactory(serviceProvider);
```

**Comment by 18682788952** [comment]
thank you very much for your patient guidance. According to your method, the problem has been solved；
