### ISSUE TITLE
1.6.6运行一段时间后就报这个错误，异常信息: System.InvalidOperationException

### ISSUE THREAD

**Issue by flash5665** [kerryjiang/SuperSocket#61]
异常信息: System.InvalidOperationException
堆栈:
   在 System.Net.Sockets.SocketAsyncEventArgs.StartConfiguring()
   在 System.Net.Sockets.SocketAsyncEventArgs.SetBufferInternal(Byte[], Int32, Int32)
   在 SuperSocket.SocketEngine.AsyncSocketServer.SessionClosed(SuperSocket.SocketBase.ISocketSession, SuperSocket.SocketBase.CloseReason)
   在 System.Action`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[SuperSocket.SocketBase.CloseReason, SuperSocket.SocketBase, Version=1.6.6.0, Culture=neutral, PublicKeyToken=null]].Invoke(System.__Canon, SuperSocket.SocketBase.CloseReason)
   在 SuperSocket.SocketEngine.SocketSession.OnSendEnd(Boolean)
   在 SuperSocket.SocketEngine.SocketSession.OnSendingCompleted(SuperSocket.Common.SendingQueue)
   在 SuperSocket.SocketEngine.AsyncSocketSession.OnSendingCompleted(System.Object, System.Net.Sockets.SocketAsyncEventArgs)
   在 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   在 System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(System.Net.Sockets.SocketError, Int32, System.Net.Sockets.SocketFlags)
   在 System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped_)
   在 System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped_)

**Comment by kerryjiang** [comment]
一般需要运行多长时间？多少个链接，喝多少个请求每秒？

**Comment by shenzhigang** [comment]
@flash5665 最近准备用于生产环境，请问出现这个异常后，能自动恢复吗？是否只是影响本次发送？

**Comment by kerryjiang** [comment]
Suggest you upgrade to SuperSocket 2.0.
