### ISSUE TITLE
SuperSocket2.0使用自带的示例代码，测出内存溢出

### ISSUE THREAD

**Issue by shenghao0219** [kerryjiang/SuperSocket#619]
```using System;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using SuperSocket.WebSocket.Server;

namespace WebSocketServer
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var host = WebSocketHostBuilder.Create(args)
                .UseWebSocketMessageHandler(async (session, message) =>
                {
                    // echo message back to the client
                    await session.SendAsync(message.Message);
                })
                 .ConfigureServices((hostCtx, services) =>
                 {
                     services.Configure<HandshakeOptions>(options =>
                     {
                         options.CheckingInterval = 10;
                         options.OpenHandshakeTimeOut = 20;
                         options.CloseHandshakeTimeOut = 20;
                         options.HandshakeValidator = (session, package) => new ValueTask<bool>(false);
                     });
                 })
                .UsePerMessageCompression()
                .ConfigureLogging((hostCtx, loggingBuilder) =>
                {
                    // register your logging library here
                    loggingBuilder.AddConsole();
                }).Build();

            await host.RunAsync();
        }
    }
}

```

WebSocket服务端代码片段如上，只是在官方示例里加了一个 握手校验的选项配置（写死返回false，拒绝所有的握手请求）

客户端使用 WebSocketSharp 随便写个死循环去和上面的服务端建立链接。

将会发现SuperSocket.WebSocket.Server.WebSocketSession 对象的引用计数无限制增加，造成内存泄露。

（线上环境不可能所有握手请求全都拒绝，所以线上要大概跑一个星期，才会出现 SuperSocket.WebSocket.Server.WebSocketSession  有几十万的引用计数）

**Comment by shenghao0219** [comment]
[
![image](https://user-images.githubusercontent.com/16681586/205264162-67239e81-bbe4-4f26-ad16-615c621598a6.png)
](url)

**Comment by shenghao0219** [comment]
WebSocket服务端代码片段如上，只是在官方示例里加了一个 握手校验的选项配置（写死返回false，拒绝所有的握手请求）

客户端使用 WebSocketSharp 随便写个死循环去和上面的服务端建立链接。将会发现SuperSocket.WebSocket.Server.WebSocketSession 对象的引用计数无限制增加，造成内存溢出。（线上环境不可能所有握手请求全都拒绝，所以线上要大概跑一个星期，才会出现 SuperSocket.WebSocket.Server.WebSocketSession  有几十万的引用计数）

**Comment by shenghao0219** [comment]
@kerryjiang 有空的时候，可否帮忙看下呢

**Comment by kerryjiang** [comment]
Will check it this weekend.

**Comment by kerryjiang** [comment]
Just released 2.0.0-beta.13. It may fix this problem.

**Comment by shenghao0219** [comment]
![image](https://user-images.githubusercontent.com/16681586/213059433-81b57662-fa88-4eab-9916-6adb0aa8a0e4.png)

@kerryjiang 用最新版测试，泄漏情况比以前是好了很多，可是如上图，实际上已经不存在任何有效的连接会话了，可他还是有残留17个一直没有被释放。泄漏问题依旧存在

**Comment by shenghao0219** [comment]
用最新版测试，泄漏情况比以前是好了很多，可是如上图，实际上已经不存在任何有效的连接会话了，可他还是有残留17个一直没有被释放。泄漏问题依旧存在




.
***@***.***







                       
原始邮件
                       
                     

发件人："Kerry Jiang"< ***@***.*** &gt;;

发件时间：2023/1/17 10:34

收件人："kerryjiang/SuperSocket"< ***@***.*** &gt;;

抄送人："shenghao0219"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [kerryjiang/SuperSocket] SuperSocket2.0使用自带的示例代码，测出内存溢出 (Issue #619)




 
Just released 2.0.0-beta.13. It may fix this problem.

**Comment by kerryjiang** [comment]
能看出这些连接是在open handshake queue里面还是在close handshake queue里面吗？

**Comment by shenghao0219** [comment]
> 能看出这些连接是在open handshake queue里面还是在close handshake queue里面吗？

调试看了，_openHandshakePendingQueue 和 _closeHandshakePendingQueue 两个队列都是空的。

**Comment by kerryjiang** [comment]
能看出他们在哪里被引用吗？

**Comment by shenghao0219** [comment]
> 能看出他们在哪里被引用吗？

这个看不到

**Comment by shenghao0219** [comment]
> 能看出他们在哪里被引用吗？

![image](https://user-images.githubusercontent.com/16681586/213134629-8173e210-0a9a-490a-88f4-ff345410adf0.png)
打断点调试，上图这个方法没走进来过

**Comment by shenghao0219** [comment]
> 能看出他们在哪里被引用吗？

![image](https://user-images.githubusercontent.com/16681586/213135478-1ba31af3-a6b4-4b1d-9d42-776c92c4d11d.png)
上图这个方法，也没走进去过。

**Comment by shenghao0219** [comment]
![image](https://user-images.githubusercontent.com/16681586/213136321-d22216db-7b30-4b63-a237-29e8373782cd.png)
可是实际情况，是有走进 RegisterSession ，却没走进 OnCloseHandshakeStarted。相当于有注册事件，没删除事件

**Comment by shenghao0219** [comment]
> 能看出他们在哪里被引用吗？

![image](https://user-images.githubusercontent.com/16681586/213141373-8875531e-c0cc-432c-b9c1-f7d9a329b7e6.png)
如上图所示

**Comment by shenghao0219** [comment]
![image](https://user-images.githubusercontent.com/16681586/213142472-79c6c33d-fc24-445c-8c1e-bd15be52a333.png)

**Comment by shenghao0219** [comment]
@kerryjiang 等有新版本之后，麻烦通知下我，到时候我再来测试。

**Comment by kerryjiang** [comment]
> ![image](https://user-images.githubusercontent.com/16681586/213143072-78619890-526b-42f2-8345-7047d939e13d.png)

It is just a reference to WebSocketMiddleware in the session instance.

**Comment by shenghao0219** [comment]
@kerryjiang 我尝试将线上也升级到 released 2.0.0-beta.13 版本之后，内存泄漏问题还是和之前一样。

**Comment by shenghao0219** [comment]
@kerryjiang 测试时明明所有的握手请求，全都是拒绝的，不存在任何有效连接。正常情况下 SuperSocket.WebSocket.Server.WebSocketSession 的计数应该全部释放掉吧。目前是一直残留很多没被释放掉。

**Comment by kerryjiang** [comment]
@shenghao0219 I just released 2.0 beta 14. Could you have a try?

[2.0.0-beta.14](https://www.nuget.org/packages/SuperSocket.WebSocket/2.0.0-beta.14)

**Comment by shenghao0219** [comment]
@kerryjiang 没收到邮件通知，所以刚打开才看见，明天我会测试下。非常感谢

**Comment by shenghao0219** [comment]
![image](https://user-images.githubusercontent.com/16681586/221072084-3868fd23-c9a5-4844-be8b-fecb543e38b7.png)
@kerryjiang 拉取了最新的master代码，测试如上图问题依然存在。

**Comment by shenghao0219** [comment]
using System;
using System.Threading;
using WebSocketSharp;

namespace WebSocketTest
{
    internal class Program
    {
        public class WsClient
        {
            WebSocket _webSocket;
            public WebSocketState State
            {
                get
                {
                    if (_webSocket == null)
                    {
                        return WebSocketState.Closed;
                    }
                    return _webSocket.ReadyState;
                }
            }

            public void InitWebSocket()
            {
                if (_webSocket != null && (_webSocket.ReadyState == WebSocketState.Open || _webSocket.ReadyState == WebSocketState.Connecting))
                {
                    try
                    {
                        _webSocket.Close();
                    }
                    catch { }
                }
                _webSocket = new WebSocket("ws://127.0.0.1:4040/");
                _webSocket.Connect();
            }

            public void Close()
            {
                _webSocket?.Close();
            }

            ~WsClient()
            {

            }
        }
        static void Main(string[] args)
        {
            int totalCount = 0;
            var WebsocketClient = new WsClient();
            WebsocketClient.InitWebSocket();
            for (int i = 0; i < 10000; i++)
            {
                if (WebsocketClient.State == WebSocketState.Closed)
                {
                    totalCount++;
                    WebsocketClient.InitWebSocket();
                    Console.WriteLine("totalCount：" + totalCount);
                }
                else
                {
                    WebsocketClient.Close();
                }
                Thread.Sleep(200);
            }
            Console.ReadKey();
        }
    }
}

**Comment by kerryjiang** [comment]
这个测试用例跑起来没问题。

https://github.com/kerryjiang/SuperSocket/blob/d5a38e629cac56e6cc86ec41dda237d0ebd4b615/test/SuperSocket.Tests/WebSocket/WebSocketBasicTest.cs#L151-L204

**Comment by shenghao0219** [comment]
@kerryjiang 我测试时不是校验这三个参数的值（SessionCount，OpenHandshakePendingQueueLength，CloseHandshakePendingQueueLength），我是直接使用 Visual Studio 2022 自带的诊断工具，进行快照截取，看托管内存的残留计数。

**Comment by shenghao0219** [comment]
> 
![image](https://user-images.githubusercontent.com/16681586/224605304-7b425da5-dd8c-4dce-80e0-86758698a695.png)

上图是我使用您源码里的这个单元测试进行测试的，诊断分析出来的结果也是一样，托管内存里还是有残留16个计数。

**Comment by shenghao0219** [comment]
经过测试发现内存只是涨了一段时间，并没有无限制的一直涨下去，内存泄漏的是其它问题造成，和supersocket2.0源码无关。

**Comment by shenghao0219** [comment]
经过测试发现内存只是涨了一段时间，并没有无限制的一直涨下去，内存泄漏的是其它问题造成，和supersocket2.0源码无关。
