### ISSUE TITLE
Detection of unavailable port

### ISSUE THREAD

**Issue by BOLL7708** [kerryjiang/SuperSocket#620]
Hello! I use SuperSocket in a range of my projects, and I'm converting to 2.0 as we speak, but I've bumped into a slight problem preventing release.

Whenever I try to start the server with a port __that is already in use__ by a different application, it fails silently and I can't seem to be able to detect it. It does show up as an exception in the debug output, but it is not captured by the error handler.
```
System.Net.Sockets.SocketException (10048): Only one usage of each socket address (protocol/network address/port) is normally permitted.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at SuperSocket.Server.TcpChannelCreator.Start()
SuperSocketService: Error: Failed to listen Ip=Any, Port=7788, Security=None, Path=, BackLog=0, NoDelay=False.
```

I'm trying to catch it using the error handler as such, but it does not get any signal when this happens.
```cs
var hostBuilder = WebSocketHostBuilder.Create();
hostBuilder.ConfigureErrorHandler((session, exception) => {
    Debug.WriteLine($"Exception from Error Handler: {exception.Message}");
    return ValueTask.FromResult(false);
});
```
Even if I'm surrounding the building and starting of the server in a try/catch, it doesn't catch the exception. Is there something else I should do to handle this situation?

**Comment by kerryjiang** [comment]
I added a new server state Failed. If no listener was created successfully during the startup, the server goes to state Failed.

I will make a new beta release which includes this change.
