### ISSUE TITLE
客户端断开连接后还会继续执行command bug

### ISSUE THREAD

**Issue by wj8400684** [kerryjiang/SuperSocket#625]
public async override IAsyncEnumerable<TPackageInfo> RunAsync()
        {
            if (_readsTask == null || _sendsTask == null)
                throw new Exception("The channel has not been started yet.");

            while (true)
            {
                var package = await _packagePipe.ReadAsync().ConfigureAwait(false);

                if (package == null)
                {
                    await HandleClosing();
                    yield break;
                }

                yield return package;
            }
        }

**Comment by kerryjiang** [comment]
It is by design. The server side is supposed to process the packages it already has already received even if the client disconnected.

**Comment by kerryjiang** [comment]
Probably I will add an option to stop process packages which are from disconnected client.
