### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by peterpanBest** [kerryjiang/SuperSocket#626]
Hello, Sir
I try to use SuperSocket V2.0 for net core 3.1, but i can not find demo about .net core. can you give me a link about use it net core 3.1. Thank you very much !

**Comment by kerryjiang** [comment]
They are samples:
https://github.com/kerryjiang/SuperSocket/tree/master/samples

Most of them should work for .net core 3.1.

**Comment by kerryjiang** [comment]
BTW, the support of .NET core 3.1 will discontinue soon.

Please upgrade to net5 and net6.
