### ISSUE TITLE
无法触发Closed事件

### ISSUE THREAD

**Issue by fengbozs** [kerryjiang/SuperSocket#628]
你好，我现在使用2.0版遇到一个问题，当使用IEasyClient.CloseAsync()时，无法触发Closed事件，使用代码调试发现PipeChannel的HandleClosing（）函数中await Task.WhenAll(_readsTask, _sendsTask)无法退出，源代码调试发现socket.ReceiveAsync函数在CancellationToken取消时没有退出；另外服务器端调用session.CloseAsync()时，无法触发OnSessionClosedAsync()，ISessionContainer中session也未及时清理。

**Comment by fengbozs** [comment]
测试代码：
internal class Program
    {
        private static bool isConnected;
        private static IEasyClient<PackageInfo> client;
        static void Main(string[] args)
        {
            client = new EasyClient<PackageInfo>(new PrivatePipelineFilter()).AsClient();
            client.Closed += Client_Closed;
            ConnectServer();
            Console.ReadLine();
        }
        private static void ConnectServer()
        {
            isConnected = client.ConnectAsync(new IPEndPoint(IPAddress.Parse("127.0.0.1"), 11885)).GetAwaiter().GetResult();
            if (isConnected)
            {
                Console.WriteLine($"{DateTime.Now}连接成功,5秒后调用Close");
                Thread.Sleep(5000);
                Console.WriteLine($"{DateTime.Now}开始调用CloseAsync（）");
                client.CloseAsync().GetAwaiter().GetResult();
                Console.WriteLine($"{DateTime.Now}CloseAsync（）执行结束");
            }
        }
        private static void Client_Closed(object? sender, EventArgs e)
        {
            Console.WriteLine($"{DateTime.Now}连接断开事件被触发");
        }
    }

**Comment by kerryjiang** [comment]
Thanks for this finding! I already fixed this bug in the latest code and I am make a new beta release ASAP.

**Comment by kerryjiang** [comment]
Just released 2.0.0-beta.13, could you check if it fixed this problem?

**Comment by fengbozs** [comment]
> 

经过测试，beta.13版本SuperSocket.Client该bug仍然存在，Socket.ReceiveAsync()函数任然无法正确退出，测试输出结果：
![image](https://user-images.githubusercontent.com/24955501/212868989-6f68ff94-4b01-4ccf-b6db-b2ed404151fe.png)


TcpPipeChannel控制台输出代码：
 private async ValueTask<int> ReceiveAsync(Socket socket, Memory<byte> memory, SocketFlags socketFlags, CancellationToken cancellationToken)
        {
            Console.WriteLine("开始TcpPipeChannel.ReceiveAsync()");
            try
            {
                var task = await socket
                    .ReceiveAsync(GetArrayByMemory((ReadOnlyMemory<byte>)memory), socketFlags, cancellationToken)
                    .ConfigureAwait(false);
                Console.WriteLine("结束TcpPipeChannel.ReceiveAsync()并返回");
                return task;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"ReceiveAsync()触发异常结束：{ex.Message}");
                throw ex;
            }
        }

PipeChannel控制台输出代码：
 private async ValueTask HandleClosing()
        {
            try
            {
                Console.WriteLine("进入HandleClosing（）");
                await Task.WhenAll(_readsTask, _sendsTask).ConfigureAwait(false);
            }
            catch (OperationCanceledException)
            {
            }
            catch (Exception e)
            {
                OnError("Unhandled exception in the method PipeChannel.Run.", e);
            }
            finally
            {
                Console.WriteLine("进入HandleClosing（）finally{}块");
                if (!_isDetaching && !IsClosed)
                {
                    try
                    {
                        Close();
                        OnClosed();
                    }
                    catch (Exception exc)
                    {
                        if (!IsIgnorableException(exc))
                            OnError("Unhandled exception in the method PipeChannel.Close.", exc);
                    }                    
                }
            }
        }

**Comment by kerryjiang** [comment]
This unit test seems similar to your scenario:

https://github.com/kerryjiang/SuperSocket/blob/c78d7e727288dd87afdce97f4d38f080304310ca/test/SuperSocket.Tests/ClientTest.cs#L44-L108

Could you check it? And it would be great for my further checking if you can add a new test or update an existing test which cannot pass.

**Comment by kerryjiang** [comment]
Close it since it has not been active for a while.
