### ISSUE TITLE
江老师是否考虑SuperSocket兼容新的.NET Core平台

### ISSUE THREAD

**Issue by juzhuanpai** [kerryjiang/SuperSocket#63]

**Comment by kerryjiang** [comment]
当然有考虑

**Comment by juzhuanpai** [comment]
期待您的更新

**Comment by innovak** [comment]
期待您的更新!

**Comment by Supergeek** [comment]
Yes, please consider for .NET Core!

**Comment by kerryjiang** [comment]
Yes, the next major version will be base on .NET Core.

**Comment by Supergeek** [comment]
That is great news! Do you have an estimate of when that might be released?

**Comment by ShockWave2048** [comment]
Hi all!
Is it new .NET Core version will compatible with Mono runtime?

**Comment by GerryWJZhao** [comment]
great news!

**Comment by kerryjiang** [comment]
I have updated the road map in the readme.
SuperSocket 2.0 targets .netstandard 2.1/.netcoreapp3.0.

**Comment by kerryjiang** [comment]
> Hi all!
> Is it new .NET Core version will compatible with Mono runtime?

I think the answer is yes. Mono has the compatibility with .NET Standard.

**Comment by kerryjiang** [comment]
Suggest you upgrade to SuperSocket 2.0.
