### ISSUE TITLE
Supersocket library with Chrome v94 and above

### ISSUE THREAD

**Issue by Vinayak-METSL** [kerryjiang/SuperSocket#634]
Hi,
We are using the supersocket v1.6.6.x in our web application. The web application works fine till Chrome v92.
However with Chrome v94 and above the websockets are unable to make connections.
It give error undefined so we are unable to get the cause of failure.
Any help would be appreciated.

Thank you

With best regards
Vinayak

**Comment by kerryjiang** [comment]
Probably because of TLS version?

**Comment by kerryjiang** [comment]
Please upgrade to SuperSocket 2.0
