### ISSUE TITLE
SuperSocket UsePackageHandler with BackgroundService

### ISSUE THREAD

**Issue by alberk8** [kerryjiang/SuperSocket#635]
Hi,

I am trying to figure out how to I integrate the SuperSocketHostBuilder with a BackgroundService [Queue](https://learn.microsoft.com/en-us/dotnet/core/extensions/queue-service)

What I want to achieve is to Receive TCP messages and pushed it to a background queue.  The queue is non blocking and will execute in the background.   Is that possible? If so, is there any example.  Thank you.

**Comment by kerryjiang** [comment]
Yes, you can. You just need to register your background hosted service.
