### ISSUE TITLE
V2.0 netstandard 2.1 support

### ISSUE THREAD

**Issue by amelkor** [kerryjiang/SuperSocket#636]
Just wondering is version 2 still going to support netstandard 2.1 ? 🤔
With the latest beta release getting:

```
Package SuperSocket.SessionContainer 2.0.0-beta.14 is not compatible with netstandard2.1 (.NETStandard,Version=v2.1).
Package SuperSocket.SessionContainer 2.0.0-beta.14 supports:
  - net5.0 (.NETCoreApp,Version=v5.0)
  - net6.0 (.NETCoreApp,Version=v6.0)
```

**Comment by kerryjiang** [comment]
Added back netstandard 2.1 support. You can find the packages from myget for now.
https://www.myget.org/feed/supersocket/package/nuget/SuperSocket

**Comment by kerryjiang** [comment]
Published SuperSocket 2,0 beta 15 which supports netstandard 2.1.
