### ISSUE TITLE
调用IServer.StopAsync()，ClearIdleSessionMiddleware报错

### ISSUE THREAD

**Issue by loveksmy** [kerryjiang/SuperSocket#643]
调用IServer.StopAsync()后
报错内容如下
SuperSocketService[0]
      The exception was thrown from the middleware ClearIdleSessionMiddleware when it is being shutdown.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at SuperSocket.Server.ClearIdleSessionMiddleware.Shutdown(IServer server)
         at SuperSocket.Server.SuperSocketService`1.ShutdownMiddlewares()

不是每次出现。

**Comment by loveksmy** [comment]
done

**Comment by kerryjiang** [comment]
I will take a look.

**Comment by kerryjiang** [comment]
This bug has been fixed.
