### ISSUE TITLE
websocket服务端无法回复客户端大json，请合并到大版本里修复

### ISSUE THREAD

**Issue by kylinn** [kerryjiang/SuperSocket#645]
WebSocketEncoder类的Encode函数中 的while函数改为如下：

   if (fragmentSize == 0)
            {
                total += EncodeSingleFragment(writer, pack.OpCodeByte, headLen, text);
            }
            else
            {
                var isContinuation = false;
                var encoder = _textEncoding.GetEncoder();

                while (true)
                {
//////////////////////这里新增的////////////////////////////
                    if (text.Length < _size0)
                        headLen = 2;
////////////////////////////////////////////////
                    total += EncodeFragment(writer, isContinuation ? (byte)OpCode.Continuation : pack.OpCodeByte, headLen, fragmentSize, text, encoder, out int charsUsed);

                    if (text.Length <= charsUsed)
                        break;

                    text = text.Slice(charsUsed);
                    
                    if (!isContinuation)
                        isContinuation = true;
                }
            }

**Comment by chucklu** [comment]
You'd better add a test case with the code improvement, then send a pull request

**Comment by kerryjiang** [comment]
This bug has been fixed.
