### ISSUE TITLE
Websocket sends large packets

### ISSUE THREAD

**Issue by thegodboy** [kerryjiang/SuperSocket#646]
Hello, kerry
In version 2.0, when the WebSocket server sends large data packets, during the sharding process, if the last piece is less than or equal to the protocol default size, the header length will continue to be written to 4, causing the client to fail to parse the protocol. Therefore, an additional judgment should be added to modify the header length to 2.
Code line: WebSocketEncoder.Encode，line 180.
你好 kerry
在2.0版本中，WebSocket服务端发送大数据包时，分片过程中当最后一片小于等于协议默认大小，数据头长度继续写入4，导致客户端解析协议失败，应增加判断将数据头长度修改为2.
代码行： WebSocketEncoder.Encode，第180行

**Comment by kerryjiang** [comment]
Understood this bug, but it's not that easy ti fix.

**Comment by thegodboy** [comment]
Yes, I'm just a simple test

**Comment by thegodboy** [comment]
> Understood this bug, but it's not that easy ti fix.

Yes, I'm just a simple test

**Comment by kerryjiang** [comment]
Did a fix and it seems working.
