### ISSUE TITLE
Issue trying to use telnet example

### ISSUE THREAD

**Issue by ray73864** [kerryjiang/SuperSocket#65]
So I am trying to use the telnet example, pretty much copy/pasted it into a new console application in VisualStudio 2015.

If I then use Putty to open a telnet connection to the server (and yes, in Putty I am choosing the type to be 'Telnet') and then do the simple 'echo' command, it doesn't do it the first time but does do it the second time.

If I have the 'NewRequestReceived' function spit out to the console what the 'requestInfo.Key' is, the first time around it is a series of unprintable characters, the second time around (immediately after trying it the first time, exact same session) it shows 'echo'.

Screenshot of the issue: http://puu.sh/qLf5F/9dd99b64b3.png

**Comment by kerryjiang** [comment]
It might because the putty sends extra telnet negotiation bytes which cannot be handled by SuperSocket.

**Comment by ray73864** [comment]
Ahh ok. Yeah, I just tried it in Putty again but this time setting the connection type to 'RAW' instead of 'Telnet' and it worked perfectly without any issues at all.
