### ISSUE TITLE
I want to know how to implement PackageHandler in SuperSocketService class.

### ISSUE THREAD

**Issue by Z5SteveKim** [kerryjiang/SuperSocket#651]
I want to know how to implement PackageHandler in SuperSocketService class.

![image](https://user-images.githubusercontent.com/119577683/237000053-f52c6c32-b654-4d81-8099-0714554c7f8d.png)

In this implementation, I would like to know how to create a PackageHandler in the Game Application.
I'm still a beginner. Thank you.

**Comment by kerryjiang** [comment]
Please take a look at the last part of this doc.
https://docs.supersocket.net/v2-0/en-US/The-Built-in-Command-Line-PipelineFilter
