### ISSUE TITLE
目前客户端连接数在100左右，但程序内存使用量在1G左右，内存占用太高了，有优化方法吗？

### ISSUE THREAD

**Issue by w419894293** [kerryjiang/SuperSocket#656]
每个客户端只要连接后，程序内存占用约增长8M左右，请问是否有默认设置为一个tcp连接使用8M的内存，或有什么其它原因导致这种情况出现？

**Comment by wj8400684** [comment]
万物皆可池化！！！！

**Comment by w419894293** [comment]
> 万物皆可池化！！！！

池化我觉得按照目前的情况，内存占用也不会太少

**Comment by kerryjiang** [comment]
Could you share your configuration?

**Comment by kerryjiang** [comment]
你再持续增加连接数看看。

**Comment by w419894293** [comment]
您的邮件已经收到，稍后会处理.

**Comment by kerryjiang** [comment]
Close it since it has not been active for a while.

**Comment by w419894293** [comment]
您的邮件已经收到，稍后会处理.
