### ISSUE TITLE
Set Sec-WebSocket-Protocol header on websocket server

### ISSUE THREAD

**Issue by optimry** [kerryjiang/SuperSocket#661]
Hi Guys

I can read all the incomming header values from the clients connecting but how can I set the Sec-WebSocket-Protocol header for the server. Basically I would like to tab into the handshake and if a certain criteria is met the Protocol header will be set.

Can anybody please help.
I'm using WebSocketHostBuilder.

**Comment by kerryjiang** [comment]
Why do you want to do it in server side? Do you mean set handshake header from websocket client?

**Comment by optimry** [comment]
The server I am building is communicating with many different clients and each client can have a range of subprotocols.
In the Sec-WebSocket-Protocol header the clients will provide more options, "protocol1 protocol2 protocol3".
During the handshake the server will set the same header with the selected (sub)protocol, "protocol2".
Now the client knows that we are communicating using (sub)protocol, "protocol2".

A good simple discription can be found here:
https://medium.com/@lancers/websocket-api-sec-websocket-protocol-subprotocol-header-support-277e34164537

I'm using the WebSocketHostBuilder and trying to find a way to set the protocol during handshake.

**Comment by optimry** [comment]
Hello again

I have looked at the src code and using the WebSocketHostBuilder.Create() I nedd to set this in WebSocketPackageHandler:
_subProtocolHandlers = serviceProvider.GetServices<ISubProtocolHandler>().ToDictionary(h => h.Name, StringComparer.OrdinalIgnoreCase);

So it is probably just me missing some knowledge on how to do this dependency injection stuff.

How do I set a sub protocol handler when creating a WebSocketHost?

**Comment by kerryjiang** [comment]
Try this:

```
builder.UseWebSocketMessageHandler("subProtoName", handler);
```

**Comment by optimry** [comment]
Thank you!
That did the trick :)
Was already using UseWebSocketMessageHandler but hadn't noticed that I could add the subprotocol.
