### ISSUE TITLE
1.6版本启用TLS 异常 调用 SSPI 失败

### ISSUE THREAD

**Issue by LiLeo** [kerryjiang/SuperSocket#662]
错误信息：System.Security.Authentication.AuthenticationException: 调用 SSPI 失败，请参见内部异常。System.ComponentModel.Win32Exception: 要求的函数不受支持

报错源文件: AsyncStreamSocketSession.cs
报错方法:OnBeginInitStream

有大佬知道原因吗 感谢 - -

**Comment by kerryjiang** [comment]
1.6 版本不再维护，可能是tls版本问题。
