### ISSUE TITLE
clear text private key in configuration for server node of super socket server 

### ISSUE THREAD

**Issue by aliahaider** [kerryjiang/SuperSocket#665]
I am using supersocket 1.6.6.1.
Is it possible to encrypt the private key "password="supersocket""  in the server node config below:
<server name="EchoServer"
        serverTypeName="EchoService"
        ip="Any" port="443"
        security="TLS 12">
    <certificate filePath="localhost.pfx" password="supersocket" />
</server>

If so, what type of encryption should I use?
What will be the format in the config file for encrypted password\encryption it is using?

If I cannot encrypt the private key here what other options do I have to make the private key more secure?

**Comment by kerryjiang** [comment]
You can setup the server with config entity class instance instead of configuration, so you can do whatever you want.
