### ISSUE TITLE
官网怎么打不开了

### ISSUE THREAD

**Issue by qixurulin** [kerryjiang/SuperSocket#669]
rt

**Comment by kerryjiang** [comment]
Moving services...

**Comment by kerryjiang** [comment]
Still working on it

**Comment by kerryjiang** [comment]
It is working right now.

Two problems found:

1) The annotation of Ingress "kubernetes.io/ingress.class" was deprecated. Fixed it by using ingressClassName field.
https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#deprecating-the-ingress-class-annotation

2) The ingress nginx controller was installed incorrectly. I had to use the Azure dedicated install script:
https://kubernetes.github.io/ingress-nginx/deploy/#azure
