### ISSUE TITLE
The Tls protocol issuses

### ISSUE THREAD

**Issue by BoydenYubin** [kerryjiang/SuperSocket#671]
![image](https://github.com/kerryjiang/SuperSocket/assets/50646888/bf8e217d-1fbb-4915-b624-fd5485d513e6)
Just send 6 bytes of data by tsl1.0, but server got the seperated data, why would cause that? 
Thanks for your response in advance.

**Comment by kerryjiang** [comment]
tsl1.0? Which could be deprecated already?

**Comment by kerryjiang** [comment]
https://datatracker.ietf.org/doc/html/rfc8996
