### ISSUE TITLE
ArgumentNullException with ActivatorUtilities.CreateInstance() with upcoming dotnet 8

### ISSUE THREAD

**Issue by trapwired** [kerryjiang/SuperSocket#677]
https://github.com/kerryjiang/SuperSocket/blob/6b919749ce769132336d9ea2ac75e479adde2a2b/src/SuperSocket.Command/CommandMiddleware.cs#L259

In the upcoming dotnet 8 upgrade, Microsoft makes a breaking change at 
```Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)``` See here on microsoft.learn: [The two ActivatorUtilities.CreateInstance methods now throw an ArgumentNullException exception if the provider parameter is null.](https://learn.microsoft.com/en-us/dotnet/core/compatibility/extensions/8.0/activatorutilities-createinstance-null-provider)

Using the preview Version of Microsoft.Extensions.DependencyInjection, the following exception is thrown at CommandMiddleware.cs#L259, because null is passed explicitly. Complete exception: ```System.ArgumentNullException : Value cannot be null. (Parameter 'provider')```

**Comment by kerryjiang** [comment]
Thanks for this information. This should be an easy fix.

**Comment by kerryjiang** [comment]
It has been fixed by this commit:
https://github.com/kerryjiang/SuperSocket/commit/07d5a6f86601cbb7c76b2f18503103b3b232aede

And the beta 18 has this fix.
