### ISSUE TITLE
Published version 2.0.0-beta17 mismatches GitHub source

### ISSUE THREAD

**Issue by Danil0v3s** [kerryjiang/SuperSocket#679]
I'm trying to follow some docs and samples to get something running, however the `FixedSizePipelineFilter` mentioned in the docs has this method `protected abstract int GetBodyLengthFromHeader(ref ReadOnlySequence<byte> buffer);` which is also present at (FixedheaderPipelineFilter.cs)[https://github.com/kerryjiang/SuperSocket/blob/master/src/SuperSocket.ProtoBase/FixedHeaderPipelineFilter.cs#L65C32-L65C55] but when the sources from NuGet don't seem to have that method.

What is happening here?

<img width="1294" alt="Screenshot 2023-08-22 at 22 38 28" src="https://github.com/kerryjiang/SuperSocket/assets/13068064/bab6b843-90fd-4c48-b646-8e2e17f64ffe">

**Comment by chucklu** [comment]
You should use this package source https://www.myget.org/F/supersocket/api/v3/index.json as mentioned in README.md

> Nightly build packages: https://www.myget.org/F/supersocket/api/v3/index.json

**Comment by sky-danilomenezes** [comment]
> You should use this package source https://www.myget.org/F/supersocket/api/v3/index.json as mentioned in README.md
> 
> > Nightly build packages: https://www.myget.org/F/supersocket/api/v3/index.json

I was blindly dumb and after I realised my mistake I closed the issue. I was looking at the docs using the `FixedHeaderPipelineFilter` which indeed have the method to tell the packet size, but was implementing the `FixedSizePipelineFilter`
