### ISSUE TITLE
Telnet socket and strings of text

### ISSUE THREAD

**Issue by ray73864** [kerryjiang/SuperSocket#68]
This is really a 2 parter but both fall under similar things (in this case 'Telnet Socket').

Looking at the example it shows doing things like

```
foreach (var factor in requestInfo.Parameters.Select(p => Convert.ToInt32(p)))
{
  result *= factor;
}
```

However, when I do 'requestinfo.Parameters' I don't get an option for 'Select' at all, the only 'S' related option appears to be 'SetValue', there is however a 'GetValue' and I can do

```
requestInfo.Parameters.GetValue(0).ToString();
```

The other part of this is, is there a way to send a full text message instead of just a 1 word message?

eg. I want to send: echo "This is a test message"
another one might be instead of sending a message, I send a JSON string instead, eg: json { message: "This is a test message" }

Only reason I ask is because I am rewriting my Node.JS+Socket.IO websocket server in c# and the server has 2 parts to it.

Part 1 of my server is a websocket server that web browsers connect to.
Part 2 of my server is a TCP socket server that my production database server uses to communicate messages about batch processes back to the staff members that initiated the batch process.

On linux the batch processes do the following:

```
echo <channel>~<message> > /dev/tcp/<ip address of tcp socket server>/<port of tcp socket server>
```

The TCP Socket server then publishes that message to the redis server which holds all the websocket sessions.

**Comment by kerryjiang** [comment]
1) you should add using "using System.Linq;"
2) you should use requestInfo.Body

**Comment by ray73864** [comment]
Both worked perfectly, thanks for that.

Really enjoying SuperSocket, I think the only thing I found a bit disappointing was the little documentation on the WebSocket side of it.

**Comment by kerryjiang** [comment]
I am glad to hear you like it.
