### ISSUE TITLE
请问SuperSocketHostBuilder在监听多个端口时，如何根据不同端口配置不同的SuperSocketService

### ISSUE THREAD

**Issue by 0FoolishProgrammer** [kerryjiang/SuperSocket#681]
版本 2.0
`
`const string _Ip = "127.0.0.1";
            const int _Port = 8484;
            //创建主机
            var hostBuilder = SuperSocketHostBuilder.Create<StringPackageInfo, CommandLinePipelineFilter>()
                .ConfigureSuperSocket(options =>
                {
                    //服务配置
                    options.Name = "Echo Server";
                    options.Listeners = new List<ListenOptions> { new ListenOptions() { Ip = _Ip, Port = _Port },new ListenOptions() { Ip = _Ip, Port = _Port + 1 }  };
                    Console.WriteLine($"服务启动地址：{_Ip}:{_Port}");
                });
            //添加Session管理
            hostBuilder.UseSession<MapleAppClient>();
            //扩展SuperSocketService 
            hostBuilder.UseHostedService<BaseServer>();
            //添加日志
            hostBuilder.ConfigureLogging((hostCtx, loggingBuilder) =>
            {
                loggingBuilder.AddConsole();
            });
            var host = hostBuilder.Build();
            await host.RunAsync();`
`
在1.6版本中我是通过AppServerBase.Setup去实现

**Comment by kerryjiang** [comment]
Check out this unit test:

https://github.com/kerryjiang/SuperSocket/blob/07d5a6f86601cbb7c76b2f18503103b3b232aede/test/SuperSocket.Tests/MainTest.cs#L541-L585
