### ISSUE TITLE
一个IServer开关几次后，ClearIdleSessionMiddleware报错

### ISSUE THREAD

**Issue by loveksmy** [kerryjiang/SuperSocket#684]
运行结果

`
Hello, World!
info: SuperSocketService[0]
      The listener [Ip=Any, Port=4040, Security=None, Path=, BackLog=0, NoDelay=False] has been started.
关闭了服务Echo Server
info: SuperSocketService[0]
      The listener [Ip=Any, Port=4040, Security=None, Path=, BackLog=0, NoDelay=False] has been stopped.
打开了服务Echo Server
info: SuperSocketService[0]
      The listener [Ip=Any, Port=4040, Security=None, Path=, BackLog=0, NoDelay=False] has been started.
关闭了服务Echo Server
info: SuperSocketService[0]
      The listener [Ip=Any, Port=4040, Security=None, Path=, BackLog=0, NoDelay=False] has been stopped.
fail: SuperSocketService[0]
      The exception was thrown from the middleware ClearIdleSessionMiddleware when it is being shutdown.
System.NullReferenceException: Object reference not set to an instance of an object.
   at SuperSocket.Server.ClearIdleSessionMiddleware.Shutdown(IServer server)
   at SuperSocket.Server.SuperSocketService`1.ShutdownMiddlewares()
打开了服务Echo Server
info: SuperSocketService[0]
      The listener [Ip=Any, Port=4040, Security=None, Path=, BackLog=0, NoDelay=False] has been started.
关闭了服务Echo Server
fail: SuperSocketService[0]
      The exception was thrown from the middleware ClearIdleSessionMiddleware when it is being shutdown.
System.NullReferenceException: Object reference not set to an instance of an object.
   at SuperSocket.Server.ClearIdleSessionMiddleware.Shutdown(IServer server)
   at SuperSocket.Server.SuperSocketService`1.ShutdownMiddlewares()
info: SuperSocketService[0]
      The listener [Ip=Any, Port=4040, Security=None, Path=, BackLog=0, NoDelay=False] has been stopped.
打开了服务Echo Server
info: SuperSocketService[0]
      The listener [Ip=Any, Port=4040, Security=None, Path=, BackLog=0, NoDelay=False] has been started.
关闭了服务Echo Server
fail: SuperSocketService[0]
      The exception was thrown from the middleware ClearIdleSessionMiddleware when it is being shutdown.
System.NullReferenceException: Object reference not set to an instance of an object.
   at SuperSocket.Server.ClearIdleSessionMiddleware.Shutdown(IServer server)
   at SuperSocket.Server.SuperSocketService`1.ShutdownMiddlewares()
info: SuperSocketService[0]
      The listener [Ip=Any, Port=4040, Security=None, Path=, BackLog=0, NoDelay=False] has been stopped.
打开了服务Echo Server
info: SuperSocketService[0]
      The listener [Ip=Any, Port=4040, Security=None, Path=, BackLog=0, NoDelay=False] has been started.
关闭了服务Echo Server
fail: SuperSocketService[0]
      The exception was thrown from the middleware ClearIdleSessionMiddleware when it is being shutdown.
System.NullReferenceException: Object reference not set to an instance of an object.
   at SuperSocket.Server.ClearIdleSessionMiddleware.Shutdown(IServer server)
   at SuperSocket.Server.SuperSocketService`1.ShutdownMiddlewares()
info: SuperSocketService[0]
      The listener [Ip=Any, Port=4040, Security=None, Path=, BackLog=0, NoDelay=False] has been stopped.
打开了服务Echo Server
info: SuperSocketService[0]
      The listener [Ip=Any, Port=4040, Security=None, Path=, BackLog=0, NoDelay=False] has been started.
关闭了服务Echo Server
fail: SuperSocketService[0]
      The exception was thrown from the middleware ClearIdleSessionMiddleware when it is being shutdown.
System.NullReferenceException: Object reference not set to an instance of an object.
   at SuperSocket.Server.ClearIdleSessionMiddleware.Shutdown(IServer server)
   at SuperSocket.Server.SuperSocketService`1.ShutdownMiddlewares()
info: SuperSocketService[0]
      The listener [Ip=Any, Port=4040, Security=None, Path=, BackLog=0, NoDelay=False] has been stopped.
打开了服务Echo Server
info: SuperSocketService[0]
      The listener [Ip=Any, Port=4040, Security=None, Path=, BackLog=0, NoDelay=False] has been started.
关闭了服务Echo Server
fail: SuperSocketService[0]
      The exception was thrown from the middleware ClearIdleSessionMiddleware when it is being shutdown.
System.NullReferenceException: Object reference not set to an instance of an object.
   at SuperSocket.Server.ClearIdleSessionMiddleware.Shutdown(IServer server)
   at SuperSocket.Server.SuperSocketService`1.ShutdownMiddlewares()
info: SuperSocketService[0]
      The listener [Ip=Any, Port=4040, Security=None, Path=, BackLog=0, NoDelay=False] has been stopped.
打开了服务Echo Server
info: SuperSocketService[0]
      The listener [Ip=Any, Port=4040, Security=None, Path=, BackLog=0, NoDelay=False] has been started.
关闭了服务Echo Server
fail: SuperSocketService[0]
`

一个简易演示demo

`
 public class Program
    {
        public static IServer host;
        static async Task Main(string[] args)
        {
            Console.WriteLine("Hello, World!");
            host = SuperSocketHostBuilder.Create<StringPackageInfo, CommandLinePipelineFilter>()
                       .UsePackageHandler(async (s, p) =>
                       {
                           // handle packages
                       })
                       .UseClearIdleSession()//清理过期连接
                      .ConfigureSuperSocket(options =>
                      {
                          options.Name = "Echo Server";
                          options.Listeners = new List<ListenOptions>() {
                                    new ListenOptions
                                    {
                                        Ip = "Any",
                                        Port = 4040
                                    }
                               };
                      })
                      .UseInProcSessionContainer()
                      .BuildAsServer();

            System.Timers.Timer t = new System.Timers.Timer(3000);
            t.Elapsed += new System.Timers.ElapsedEventHandler(Execute);
            t.AutoReset = true;
            t.Enabled = true;
            t.Start();

            await host.StartAsync();

            while (true)
            {

                Thread.Sleep(500);
            }

        }

        public static async void Execute(object source, System.Timers.ElapsedEventArgs e)
        {
            if (host.State == ServerState.Started)
            {
                Console.WriteLine("关闭了服务" + host.Name);
                await host.StopAsync();
            }
            else
            {
                Console.WriteLine("打开了服务" + host.Name);
                await host.StartAsync();
            }

        }

    }
`

**Comment by kerryjiang** [comment]
The problem should be you stop the server before the it succeeds to start.

**Comment by kerryjiang** [comment]
Got the reason, actually we only start middleware one time when the service initializes (not when the service starts), but the middleware stops every time when the service stops.

**Comment by kerryjiang** [comment]
Will have a fix for this problem.

**Comment by kerryjiang** [comment]
Fixed this problem with this change: https://github.com/kerryjiang/SuperSocket/commit/1d399c106f2143d22019af1efd5e7ed5b25cf8e1

It will be included in the next beta release.
