### ISSUE TITLE
WebSocketServer with BasicAuthentification

### ISSUE THREAD

**Issue by optimry** [kerryjiang/SuperSocket#685]
Hi Guys

Using the SuperSocket WebSocketServer is it possible to perform basic authentification on the http request before the upgrade to websocket?
If so, any idea to where I should plugin my BasicAuthentificationHandler?

Thanks

**Comment by kerryjiang** [comment]
You can use HandshakeValidator:

https://github.com/kerryjiang/SuperSocket/blob/07d5a6f86601cbb7c76b2f18503103b3b232aede/test/SuperSocket.Tests/WebSocket/WebSocketBasicTest.cs#L163C103-L163C103
