### ISSUE TITLE
发布的MyGet Version 下载问题

### ISSUE THREAD

**Issue by gdhxt** [kerryjiang/SuperSocket#702]
发布的MyGet Version 下载问题 SuperSocket 19.429
SuperSocket.SessionContainer 找不到19.425版本不能匹配。VS上会报异常

![image](https://github.com/kerryjiang/SuperSocket/assets/3378287/2c10b80d-6fbc-4069-9fd7-1cf2e8d49887)

**Comment by gdhxt** [comment]
![image](https://github.com/kerryjiang/SuperSocket/assets/3378287/b6d08a99-9f13-46dd-bdf0-215b1afc6bdb)
这gmw两个版本匹配不到19.429

**Comment by kerryjiang** [comment]
I did a refactory last week.
Some projects were deleted and some others were renamed.
Lots of classes have been renamed and namespaces also have been adjusted.

Please adjust your code base on the code in samples.
