### ISSUE TITLE
用AsyncTcpSession 来创建客户端连接，有时候会连不上，多久都没有返回结束?

### ISSUE THREAD

**Issue by 810906591** [kerryjiang/SuperSocket#704]
事件 Connected  Error  Closed  DataReceived  都没有事件触发

**Comment by kerryjiang** [comment]
AsyncTcpSession? 这个代码有点老啊

**Comment by AlianBlank** [comment]
我也是使用的这个。但是我并没有发现问题。平台为net8，请问你是怎么使用的呢？
