### ISSUE TITLE
FixedHeaderReceiveFilter 使用问题

### ISSUE THREAD

**Issue by xiaoyaojian** [kerryjiang/SuperSocket#72]
在我自己实现的过滤器使用FixHeaderReceiveFilter协议模板，在发送一下两条命令后，GetBodyLengthFromHeader会被调用三次，前两次是正常，第三次的offset是第二次发送命令的结束位置，length为2.

命令1:ab bc cd d1 01 01 01 01 01 01 01 01.........(共长74位)
命令2:68 03 0e 0e 0e

自定义过滤器的实现:
public class ElecReceiveFilter : FixedHeaderReceiveFilter<ElecRequestInfo>
    {
        public ElecReceiveFilter() : base(2)
        {

        }

        protected override int GetBodyLengthFromHeader(byte[] header, int offset, int length)
        {
            if (header[offset] == 171)
            {
                return 72;
            }
            else if(header[offset]==104)
            {
                return header[offset + 1];
            }
            else
            {
                return length;
            }
        }

        protected override ElecRequestInfo ResolveRequestInfo(ArraySegment<byte> header, byte[] bodyBuffer, int offset, int length)
        {
            ElecRequestInfo info = new ElecRequestInfo();

            return info;
        }
    }

**Comment by chucklu** [comment]
你自己的问题导致的，
https://github.com/xiaoyaojian/supersocket_test/issues/1
