### ISSUE TITLE
无法在ICommand使用依赖注入服务

### ISSUE THREAD

**Issue by loveyeguo** [kerryjiang/SuperSocket#732]
在net7中，我在ConfigureServices中注册了服务：
`services.AddSingleton<IService, MyService>(); `
然后使用服务：
`public class MyCommand : ICommand<StringPackageInfo>
{
    private readonly IService _service;

    public MyCommand(IService service)
    {
        _service = service;
    }

    public async Task ExecuteAsync(IAppSession session, StringPackageInfo package)
    {
        // 在这里可以使用 _service 执行相关操作
    }
}`

但是IService 实例化失败了，显示无法找到。  但是我如果重新定义一个普通的类，在构造函数里面进行IService 注入是可以的，这是什么原因？

**Comment by kerryjiang** [comment]
能写个测试用例重现这个问题吗？

**Comment by kerryjiang** [comment]
I just added a new unit test for this feature:
https://github.com/kerryjiang/SuperSocket/commit/1f179830f736c8de784907af89dc274a85ebd025
