### ISSUE TITLE
是否支持代理协议？

### ISSUE THREAD

**Issue by AsenLins** [kerryjiang/SuperSocket#737]
你好作者，请问SuperSocket 2.0是否支持代理协议？通过Haproxy代理之后，源IP丢失，Haproxy支持send-proxy，我看SuperSocket文档没看到相关的介绍,如果支持，需要通过什么配置去开启吗？

**Comment by kerryjiang** [comment]
Same issue with this one.

**Comment by kerryjiang** [comment]
Close this one, please track this issue instead: https://github.com/kerryjiang/SuperSocket/issues/739
