### ISSUE TITLE
ConfigureSessionHandler配置涉及的Connected事件触发问题

### ISSUE THREAD

**Issue by bart-fan** [kerryjiang/SuperSocket#745]
Socket客户端采用命名空间：System.Net.Sockets的Socket连接时，Connected未能正确触发
 .ConfigureSessionHandler((session) =>
   {
       session.Connected += new AsyncEventHandler(appServer_NewSessionConnected);
       return new ValueTask();
   })
而采用这种方式是可以的
  .ConfigureSessionHandler(
  onConnected: async session =>
  {
      await appServer_NewSessionConnected(session, EventArgs.Empty);
  })

**Comment by kerryjiang** [comment]
You cannot use ConfigureSessionHandler by this way:

```
 .ConfigureSessionHandler((session) =>
{
session.Connected += new AsyncEventHandler(appServer_NewSessionConnected);
return new ValueTask();
})
```
The code should be translated to

```
 .ConfigureSessionHandler(onConnected: (session) =>
  {
      session.Connected += new AsyncEventHandler(appServer_NewSessionConnected);
      return new ValueTask();
  })

```

That means you register the session connected event handler with appServer_NewSessionConnected when the session jsut has been connected. But after that moment, session connect event won't happen again.

**Comment by bart-fan** [comment]
Thank you, I have understood it through the simulation test

**Comment by kerryjiang** [comment]
> .ConfigureSessionHandler((session) => { session.Connected += new AsyncEventHandler(appServer_NewSessionConnected); session.Closed += new AsyncEventHandler(appServer_NewSessionClosed); return new ValueTask(); }) **I have a question here, why is session.Closed triggered when closing? Does it mean that when the client disconnects, will the Closed of the session be triggered once?**

Yes, you registered the close event handler when the connection just connected which is before the connection closes. So when the connection closes, the even handler will be invoked. But if you register the close event handler after the connection closes, the event handler won't be called.
