### ISSUE TITLE
linux环境内存占用持续飙涨

### ISSUE THREAD

**Issue by McEyes** [kerryjiang/SuperSocket#752]
linux环境内存占用持续飙涨，
32G内存服务器，5分钟由16%涨到19%
window本地环境内存占用正常，没有运行稳定的情况没有变化

**Comment by wj8400684** [comment]
咋测试的

**Comment by kerryjiang** [comment]
什么版本？ 怎么测的？

**Comment by McEyes** [comment]
排除SuperSocket的问题了，是其他地方处理不过来导致的

**Comment by kerryjiang** [comment]
Glad to know that!
