### ISSUE TITLE
监听被占用端口怎么判断是否监听成功呢

### ISSUE THREAD

**Issue by 7haihai** [kerryjiang/SuperSocket#754]
![image](https://github.com/user-attachments/assets/8f6700b7-4b3e-41f3-bf8c-71e0fbe3072e)
若端口已经被占用，启动后都是返回成功，怎么判断端口是否监听成功呢？

**Comment by 7haihai** [comment]
![image](https://github.com/user-attachments/assets/ab2bcb09-20de-4923-ac49-1445a276786f)
可以使用这个状态，ServerState? state = Server.State;
namespace SuperSocket.Server.Abstractions;

public enum ServerState
{
    None,
    Starting,
    Started,
    Stopping,
    Stopped,
    Failed
}

bool result = Server.StartAsync().Result; 这个执行都是true。

**Comment by kerryjiang** [comment]
Server state should be Failed if all listeners failed to start.

https://github.com/kerryjiang/SuperSocket/blob/20f32779864674ef2fe81fa438ad3b566685213a/src/SuperSocket.Server/SuperSocketService.cs#L455C1-L460C14

I will add a unit test to cover this case.

**Comment by 7haihai** [comment]
您好，若启动失败后状态为ServerState.Failed，无法再次启动，这个是怎么处理的呢？
            if (state != ServerState.None && state != ServerState.Stopped)
            {
                throw new InvalidOperationException($"The server cannot be started right now, because its state is {state}.");
            }

**Comment by kerryjiang** [comment]
Just made a fix for this issue:
https://github.com/kerryjiang/SuperSocket/commit/22557ccd1164bd0a277a5b5315094bdc73b9ead0
