### ISSUE TITLE
怎么从服务器发送消息

### ISSUE THREAD

**Issue by Leblanc2025** [kerryjiang/SuperSocket#755]
> public class UserSession : SuperSocket.Server.AppSession
> {
> }
我的UserSession类继承了AppSession，但是AppSession无法调用SendAsync()函数，因为AppSession中该函数不是public的

**Comment by Leblanc2025** [comment]
版本2.0.0.beta27

**Comment by 7haihai** [comment]
private IConnection _connection;

        protected internal IConnection Connection
        {
            get { return _connection; }
        }

AppSession有这个，Connection.SendAsync(xxx)

        ValueTask IAppSession.SendAsync(ReadOnlyMemory<byte> data, CancellationToken cancellationToken)
        {
            return _connection.SendAsync(data, cancellationToken);
        }

        ValueTask IAppSession.SendAsync<TPackage>(IPackageEncoder<TPackage> packageEncoder, TPackage package, CancellationToken cancellationToken)
        {
            return _connection.SendAsync(packageEncoder, package, cancellationToken);
        }

我用的这个，
![image](https://github.com/user-attachments/assets/67fdb366-8217-46da-bbb4-446c0947f9ca)

**Comment by Leblanc2025** [comment]
@7haihai 谢谢您，已经解决。
public async Task SendAsync(byte[] data)
{
        await Connection.SendAsync(send);
}
