### ISSUE TITLE
建议CertificateOptions使用SslServerAuthenticationOptions替换

### ISSUE THREAD

**Issue by liuguiyou** [kerryjiang/SuperSocket#756]
不同的.net版本里，SslServerAuthenticationOptions增加了不同的属性，CertificateOptions用SslServerAuthenticationOptions替换，用户可以更灵活的配置相关选项

**Comment by kerryjiang** [comment]
Push a commit about it just now.
https://github.com/kerryjiang/SuperSocket/commit/e3f650c05da5c1d722504ea2222deb8991d4cb4e

I will make some adjustments this weekend. Please leave what you think if you have.
