### ISSUE TITLE
SuperSocket.WebSocket.Server 如何创建自定义appserver，按照文档过程创建appsession是通过的appserver 无法创建提示异常

### ISSUE THREAD

**Issue by freefer** [kerryjiang/SuperSocket#757]
![image](https://github.com/user-attachments/assets/f4459c8e-b3bb-442b-992a-1d929e0980b4)
![image](https://github.com/user-attachments/assets/354a9d91-c979-40f8-bbd7-5443eb1ec259)
![image](https://github.com/user-attachments/assets/2aa08a6e-ab6e-4dcb-818f-cbe84c405415)

**Comment by wj8400684** [comment]
<img width="1082" alt="image" src="https://github.com/user-attachments/assets/e0548142-6879-4375-b90c-cbc99a219304">
<img width="1193" alt="image" src="https://github.com/user-attachments/assets/a029cf21-9d17-47ca-aa41-559e7e82a1e4">
<img width="983" alt="image" src="https://github.com/user-attachments/assets/ba189300-ea25-4957-b430-e067d45adb3e">
