### ISSUE TITLE
Max request length: 1024, current processed length: 4096

### ISSUE THREAD

**Issue by qiankunpig** [kerryjiang/SuperSocket#81]
2000+连接 不停的发数据，会报Max request length: 1024, current processed length: 4096这个错误，怎么清理DefaultReceiveBufferSize和DefaultMaxRequestLength呢？

**Comment by kerryjiang** [comment]
You can find configuration about that in the document:
http://docs.supersocket.net/v1-6/en-US/SuperSocket-Basic-Configuration

**Comment by qiankunpig** [comment]
How to get the client mac address? AppSession.RemoteEndPoint can not found the property of mac

**Comment by qiankunpig** [comment]
SuperSocket接收不到来自客户端发送的消息，但是在telnet中是可以的。下面这样就不行，这是什么原因啊？
` IPEndPoint point=new IPEndPoint(IPAddress.Parse("192.168.2.122"),2223);
            Socket socket=new Socket(AddressFamily.InterNetwork,SocketType.Stream, ProtocolType.Tcp);
            socket.Connect(point);
            while (true)
            {
                socket.Send(Encoding.UTF8.GetBytes("AllSession"));
                Thread.Sleep(1000);
            }`
项目中有AllSession类 继承自CommandBase
