### ISSUE TITLE
NewSessionConnected以后SessionCount更新但是GetAllSessions不更新

### ISSUE THREAD

**Issue by whSwitching** [kerryjiang/SuperSocket#94]
TelnetServer.Program.cs
static void appServer_NewSessionConnected(AppSession session)
        {
            session.Send("Welcome to SuperSocket Telnet Server");
            Console.WriteLine("all sessions : "+ session.AppServer.SessionCount);
            //  "all sessions : 1"
            foreach (var s in session.AppServer.GetAllSessions())
                Console.WriteLine("    " + s.SessionID);  // nothing prints here
        }

start a new client ,
            //  "all sessions : 2"
            //      only the first SessionID prints

same issue for  SessionClosed  event

**Comment by jinqi166** [comment]
把session快照功能关了，看文档有介绍


发自网易邮箱大师
在2017年03月21日 21:30，whSwitching 写道：

TelnetServer.Program.cs
static void appServer_NewSessionConnected(AppSession session)
{
session.Send("Welcome to SuperSocket Telnet Server");
Console.WriteLine("all sessions : "+ session.AppServer.SessionCount);
// "all sessions : 1"
foreach (var s in session.AppServer.GetAllSessions())
Console.WriteLine(" " + s.SessionID); // nothing prints here
}

start a new client ,
// "all sessions : 2"
// only the first SessionID prints

same issue for SessionClosed event

**Comment by whSwitching** [comment]
it works,  thank you!
