### ISSUE TITLE
Custom protocol with encrypted and compressed TCP/IP data stream

### ISSUE THREAD

**Issue by FYGonzalo** [kerryjiang/SuperSocket#95]
I am trying to implement a game server based on a custom protocol. 

In this protocol, the entire body of a packet may be encrypted (simple secret-key encryption, where the key is different for each session) nor compressed. A packet may contain one or more requests.

Here is a brief representation of body of a TCP/IP packet.
```xml
<Packet>
    <field type="ushort" name="BodyLength" /> <!-- Length of encrypted/compressed body -->
    <field type="short" name="NumberOfRequests" /> <!-- Number of requests in body -->
    <field type="byte" name="BodyStatus" /> <!-- Indicates whether body is encrypted nor compressed -->
    <field type="byte" name="Checksum" />
    <field type="byte[]" name="Body"/> <!-- May contain many requests -->
</Packet>
```

My problem here is that I don't know how to implement the decryption/decompression process.

First I thought that would be simple as implementing IReceiveFilter but as requests may be more than one in the same packet, and are all encrypted nor compressed together, I can not decrypt nor decompress one at a time (unless I add an alternative buffer inside my IReceiveFilter implementation but I don't think this is the way to go).

**Comment by kerryjiang** [comment]
Try FixedHeaderReceiveFilter, place your decode code in the filter.

**Comment by FYGonzalo** [comment]
This is the protocol I am working with.

![packet](https://cloud.githubusercontent.com/assets/8304703/24245174/8b50921c-0fa0-11e7-87af-3a28a9b4b6b1.png)

I am not sure if FixedHeaderReceiveFilter is properly to use in this case, that header is for the entire Body and not for a individual request.

I am still confused about implementing the decoder and decompressor inside the filter, the biggest issue is the decompressor, which comes after the decoder.
If I do this way, I must decode and decompress the entire readBuffer (because the compression method doesn't allow dynamic decompression) then the result (that may contain many request info) would be needed be stored on a auxiliar byte array in the scope of MyReceiveFilter to handle the case when there are more than one request info in the same body.
After processing the first request info, which value will I assign to rest? I have already processed the entire buffer (remember the compression doesn't allow dynamic decompression) but still need another call to return the second request info. I could do something tricky and return any int > 0 so it process the next request info, but is that what you are meaning?

**Comment by FYGonzalo** [comment]
Yep, I think I got it. 

After the full packet is in the read buffer, I decrypt and decompress it, and store those bytes in an auxiliar buffer in the scope of RequestFilter.
Then I return the first Request and delete it from that auxiliar buffer, and if there are more request in the same packet, Filter would be called many times because of LeftBufferSize property.
